### ISSUE TITLE
Use HTTP range requests to stream large files.

### ISSUE THREAD

**Issue by davidsoergel** [tensorflow/tfjs#1029]
This is similar to sharded_url_data_source except that the sharding happens on demand and need not be prepared by the file host.

**Comment by gaikwadrahul8** [comment]
Hi, @davidsoergel 

Thank you for opening this issue for tracking purposes. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFJs team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TFJs [version](https://github.com/tensorflow/tfjs/releases/tag/tfjs-v4.11.0) with the latest compatible hardware configuration which could potentially resolve the issue. We can keep the issue open if it is still relevant. Please confirm if we need to keep the issue open.

Thank you for your support and cooperation.
