### ISSUE TITLE
Model.fit(): More aggressively push data() await calls to the end to keep GPU busy

### ISSUE THREAD

**Issue by caisq** [tensorflow/tfjs#1066]

**Comment by caisq** [comment]
cc @dsmilkov

**Comment by dsmilkov** [comment]
Thanks! Few notes:

- When `yieldEvery: 'never'`, no await should happen at both batch and epoch level. The fit() should freeze until everything is done.
- When `yieldEvery: 'batch'`, no await should happen at every epoch since it leads to double yielding when a new epoch starts.
- When `yieldEvery: 'epoch'`, no await happens on batch.
- When `yieldEvery: 'auto'`, make sure no double yielding happens.
