### ISSUE TITLE
Add `trimWhitespace` option to `CSVConfig`

### ISSUE THREAD

**Issue by bileschi** [tensorflow/tfjs#1113]
To get help from the community, we encourage using Stack Overflow and the [`tesnorflow.js`](https://stackoverflow.com/questions/tagged/tensorflow.js) tag.

#### TensorFlow.js version
tfjs: "0.14.2"
tfjs-converter: "0.7.2"
tfjs-core: "0.14.5"
tfjs-data: "0.1.7"
tfjs-layers: "0.9.2"

#### Browser version
Google Chrome | 72.0.3626.28 (Official Build) beta (64-bit

#### Describe the problem or feature request

Given the first lines of Auto-MPG, 
```
18.0   8   307.0      130.0      3504.      12.0   70  1	"chevrolet chevelle malibu"
15.0   8   350.0      165.0      3693.      11.5   70  1	"buick skylark 320"
18.0   8   318.0      150.0      3436.      11.0   70  1	"plymouth satellite"
```
We would expect these to parse into 9 columns, and this is exactly how pandas dataframe works.  Instead, in tfjs-data, each space is considered a delimiter, and there are many more (empty) columns.

Pandas code:
```
column_names = ['MPG','Cylinders','Displacement','Horsepower','Weight',
                'Acceleration', 'Model Year', 'Origin'] 
raw_dataset = pd.read_csv(dataset_path, names=column_names,
                      na_values = "?", comment='\t',
                      sep=" ", skipinitialspace=True)
```
From Tensorflow tutorial:
https://www.tensorflow.org/tutorials/keras/basic_regression

#### Code to reproduce the bug / link to feature request
```
 const myData = tf.data.csv(url, {
    hasHeader: false,
    delimiter: ' ',
    columnNames: [
      'MPG', 'Cylinders', 'Displacement', 'Horsepower', 'Weight',
      'Acceleration', 'Model Year', 'Origin'
    ]
  });
```

**Comment by kangyizhang** [comment]
This is a sub-task of https://github.com/tensorflow/tfjs/issues/1012

**Comment by davidsoergel** [comment]
This is not a CSV file at all, so it's not part of #1012.

Instead, this is a 'fixed width record' format, so this is precisely #1021.  Closing this as a dup of that.

Aside: such a file should be read in pandas using [pandas.read_fwf()](https://pandas.pydata.org/pandas-docs/version/0.22/generated/pandas.read_fwf.html).  It only works with [pandas.read_csv()](https://pandas.pydata.org/pandas-docs/version/0.22/generated/pandas.read_csv.html) here because you set `skipinitialspace=true`.  So what is happening is that the *first* space after each field is considered the delimiter.  All the spaces after that are considered the prefix of the next field, and are trimmed.  That would work the same if the columns were not vertically aligned, i.e. having an arbitrary number of spaces between each pair of fields.  So that's a bit of a hack :)

**Comment by davidsoergel** [comment]
Actually, reopening and renaming.  Much as I find the described usage very hacky,

 * having a 'trim whitespace' option may be generally useful, and
 * it is actually a convenient way to deal with fixed-width files without having to specify the widths up front.
