### ISSUE TITLE
tf.gather() returns nonsensical result when given negative integer indices

### ISSUE THREAD

**Issue by caisq** [tensorflow/tfjs#1147]
To get help from the community, we encourage using Stack Overflow and the [`tensorflow.js`](https://stackoverflow.com/questions/tagged/tensorflow.js) tag.

#### TensorFlow.js version
0.14.2

const x = tf.tensor2d([1, 2, 3, 4], [2, 2]);
x.gather([-1]).print();

==>  Tensor
     [[0, 0],]

To be consistent with the behavior of tf.gather() in Python TF, negative indices ought to lead to an error.

**Comment by caisq** [comment]
I'm not sure how to fix this without slowing down tf.gather().  

The indices can either be a Tensor or a TensorLike. In the former case, we can use `.min()` and `.max()` to check the range of the indices. In the latter, we can just iterate through the elements. But I'm not sure how much slow down will be caused as a result.

@nsthorat @dsmilkov

**Comment by nsthorat** [comment]
How critical is this error message? It's going to be pretty complicated to do this efficiently without slowing down gather for everyone. One idea is to generate a NaN and have debug mode catch this.

**Comment by gaikwadrahul8** [comment]
Hi, @caisq 

Apologize for the delayed response and I tried to replicate the same issue with latest version of `@tensorflow/tfjs@4.10.0` by using above code snippet from issue template still I'm getting the same output. Thank you!

CC :@mattsoulanille

Here screenshot for your reference :

![image](https://github.com/tensorflow/tfjs/assets/115997457/c3b11fcd-d78e-4613-9f6a-4a16838f349e)

**Comment by gaikwadrahul8** [comment]
Hi, @caisq 

Thank you for opening this issue for tracking purposes. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFJs team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TFJs [version](https://github.com/tensorflow/tfjs/releases/tag/tfjs-v4.11.0) with the latest compatible hardware configuration which could potentially resolve the issue. We can keep the issue open if it is still relevant. Please confirm if we need to keep the issue open.

Thank you for your support and cooperation.

**Comment by mattsoulanille** [comment]
Some more info on this behavior: When running on the GPU, there's not an easy way to throw an error if an index is negative, since that would require downloading the result of that check to CPU in order to throw the error. For performance reasons, we avoid that. If you switch to the CPU backend, you'll see errors when passing tf.gather negative indices. You can try this out [on our API website](https://js.tensorflow.org/api/latest/#gather).
