### ISSUE TITLE
Load model changes in 1.0

### ISSUE THREAD

**Issue by dsmilkov** [tensorflow/tfjs#1175]
This issue will track all changes related to loading models in TensorFlow.js 1.0.

### Renames of methods and args
- `tf.loadModel()` is renamed to:
```ts
loadLayersModel(pathOrIOHandlerOrJSON: string|io.IOHandler|LayersModelJSON,
    options: LoadOptions): Promise<tf.LayersModel>;
```
	
- `tf.loadFrozenModel()` is renamed to:
```ts
loadGraphModel(pathOrIOHandlerOrJSON: string|io.IOHandler|GraphModelJSON,
    options: LoadOptions): Promise<tf.GraphModel>;
```

- Both share the same options:
```ts
export interface LoadOptions {
  onProgress?: Function;
  fetchFunc?: Function;
  strict?: boolean;
  requestInit?: {...},
  fromTFHub: boolean
}
```
	
- `loadTFHubModule(): Promise<tf.GraphModel>` is removed to keep the API simple. It’s a simple wrapper around `tf.loadGraphModel()`, so users will be able to load new TF Hub modules via `tf.loadGraphModel()` by passing `{fromTFHub:true}` to the load options.

- `tf.model.modelFromJSON()` is removed. `loadLayersModel()` above will be able to take a JSON Object.

### Renames of interfaces/classes
- `tf.Model` gets renamed to `tf.LayersModel`
- `tf.FrozenModel` gets renamed to `tf.GraphModel`

### Reserved for future use
- `tf.loadModel(): tf.Model` is removed but will be reserved for future use for a generic model loader agnostic to the format.
- `tf.Model` is reserved for future use. Will contain the intersection of all tfjs models.
- `tf.node.loadSavedModel(): SavedModel` is planned for `tfjs-node`, for directly loading a SavedModel without conversion.

### Alignment of model.json
The model.json file associated with both LayersModel and GraphModel will have the following top-level attributes:
- `format: string`. Currently, can be `layers-model` or `graph-model`.
- `generatedBy: string`. Will be used for debugging purposes when the (de)serialization fails.
  - the name+version of the tfjs-layers npm package if the model originated from layers
  - the name+version of tfjs-converter pip package if the model originated from the converter
- `modelTopology: {...}` Contains the model topology
- `weightsManifest: {...}` Contains info about the weights

### Remaining the same
- `tf.model()` and `tf.sequential()` will remain since it is the only way to programmatically create a model from TensorFlow.js. They will return a `LayersModel`.

### Changes in tfjs-converter
The `--output_format` flag will remain optional, but the possible values will be `‘tfjs_layers_model’|’tfjs_graph_model’` when going from python to js, and `‘keras’` when going from js to python. The inferred value of `output_format` will depend on the `input_format`:

input_format | output_format (inferred)
-- | --
keras | tfjs_layers_model
tf_frozen_model | tfjs_graph_model
tf_hub | tfjs_graph_model
tf_saved_model | tfjs_graph_model
tf_session_bundle | tfjs_graph_model
tfjs_layers_model | keras

Note that `tensorflowjs` is not a valid `input_format` anymore.

**Comment by caisq** [comment]
@dsmilkov Here are my thoughts: 

1. Unifying the signature and putting all the optional config is great and has my full support.
2. As for the name `tf.loadLayersModel()`, I don't like it because it is 
  - Long, somewhat a mouthful, and inconsistent with Keras or tf.keras.
  - Potentially confusing. It can be misunderstood as "load layer's model" or "load layers' model"
  How about changing `tf.loadModel()` to **`tf.models.loadModel()`**? That way it is completely 
  consistent with `keras.model.load_model()` and `tf.keras.model.load_model()` in Python,
  and addresses point 2, too.
3. For `loadWebSavedModel`, I'm not sure I'm 100% with it, either. I see the point that 
    we need to reflect that fact that such models will no longer be frozen (i.e., it can be
    trained further). So I'm happy with that. But what's the implication of this name for tfjs-node?

**Comment by nsthorat** [comment]
FYI: tfjs-core@0.15.2 and tfjs-core@1.0.0-alpha3 have been released with the `LoadOptions` interface.

The next step is to have tfjs-converter and tfjs-layers add the methods `tf.loadGraphModel` and `tf.loadLayersModel` which have the new API and route to the old methods at master. In that PR, don't delete the old methods since they both need to exist on the minor version.

After those changes are cherry picked, we can delete the old methods at master.

**Comment by nsthorat** [comment]
FYI the converter doesn’t yet take a JSON object as the first argument. I think it also doesn’t support an IOHandler.

**Comment by dsmilkov** [comment]
Nice catch. @pyu10055 last remaining item:

loadGraphModel() should take an `IOHandler` and a `GraphModelJSON`

**Comment by dsmilkov** [comment]
Closing this mega issue since the leftover changes are tracked in separate issues.
