### ISSUE TITLE
Support for PaddedBatchDatasetV2, MapDataset, TensorSliceDataset, DatasetToSingleElement

### ISSUE THREAD

**Issue by cwbeitel** [tensorflow/tfjs#1176]
#### TensorFlow.js version

0.6.7

#### Browser version

non-browser (tfjs converter) issue

#### Describe the problem or feature request

Attempting to convert a SavedModel exported from a [tensor2tensor](https://github.com/tensorflow/tensor2tensor) Model (i.e. with relevance to conversion of other models implemented and trained in that paradigm), found various ops not yet supported.

These ops include:
* PrintV2
* StringFormat
* convert_gradient_to_tensor_HBc3xYw22Mw
* PaddedBatchDatasetV2
* MapDataset
* TensorSliceDataset
* DatasetToSingleElement

#### Code to reproduce the bug / link to feature request

You would need this particular SavedModel to precisely reproduce this which I can share via GCS if needed, the commands were as follows:

```bash
!python -m tensorflow.python.tools.saved_model_cli show \
--dir /tmp/tmpfllcatvx/export/1548868889 --all
```

```bash
MetaGraphDef with tag-set: 'serve' contains the following SignatureDefs:

signature_def['serving_default']:
  The given SavedModel SignatureDef contains the following input(s):
    inputs['input'] tensor_info:
        dtype: DT_STRING
        shape: (-1)
        name: serialized_example:0
  The given SavedModel SignatureDef contains the following output(s):
    outputs['outputs'] tensor_info:
        dtype: DT_FLOAT
        shape: (-1, 12, 1, 1)
        name: multi_modal_dev_model/concat:0
  Method name is: tensorflow/serving/predict
```

```bash
!tensorflowjs_converter \
    --input_format=tf_saved_model \
    --output_node_names="multi_modal_dev_model/concat" \
    --saved_model_tags=serve \
    /tmp/tmpdrgz3xqn/export/1548900462 \
    /tmp/tmpfllcatvx/export/converted3
```

```bash
Using TensorFlow backend.
Traceback (most recent call last):
  File "/usr/local/bin/tensorflowjs_converter", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/tensorflowjs/converters/converter.py", line 317, in main
    strip_debug_ops=FLAGS.strip_debug_ops)
  File "/usr/local/lib/python3.6/dist-packages/tensorflowjs/converters/tf_saved_model_conversion.py", line 294, in convert_tf_saved_model
    skip_op_check=skip_op_check, strip_debug_ops=strip_debug_ops)
  File "/usr/local/lib/python3.6/dist-packages/tensorflowjs/converters/tf_saved_model_conversion.py", line 117, in optimize_graph
    ', '.join(unsupported))
ValueError: Unsupported Ops in the model before optimization
PrintV2, StringFormat, convert_gradient_to_tensor_HBc3xYw22Mw, PaddedBatchDatasetV2, MapDataset, TensorSliceDataset, DatasetToSingleElement
```

Thank you!! TF.js is awesome!! 👏

**Comment by cwbeitel** [comment]
@rthadur @pyu10055 Hey there just wanted to offer my help getting these implemented; this is not my area of expertise but if you could lay out the steps required I could give it a try (if that would be helpful)!

**Comment by rthadur** [comment]
Here are the steps https://github.com/tensorflow/tfjs/blob/master/CONTRIBUTING_MISSING_OP.md which will help in contributing to new ops , thank you

**Comment by gaikwadrahul8** [comment]
Hi, @cwbeitel

Just to confirm, May I know are you still working on this feature request to implement `PaddedBatchDatasetV2`, `MapDataset`, `TensorSliceDataset`, `DatasetToSingleElement` Ops ? 

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFJs team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TFJs [version](https://github.com/tensorflow/tfjs/releases/tag/tfjs-v4.10.0) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tfjs/blob/master/README.md) to stay up to date with the latest developments which are happening in the Tensorflow.js space.

Thank you for your support and cooperation.
