### ISSUE TITLE
Possible memory leak in executeAsync.

### ISSUE THREAD

**Issue by annxingyuan** [tensorflow/tfjs#1186]
I'm using the latest tfjs (0.14.1) and calling `executeAsync` on the converted universal sentence encoder lite model. When I log `tf.memory().numTensors` before and after `executeAsync`, I see that 11 new tensors are created. We can't wrap `executeAsync` in a `tidy` because it's asynchronous. Would you mind looking into the possibility that there is a memory leak in `executeAsync`? 

I created a codepen that demonstrates the issue: https://codepen.io/annxingyuan/pen/LqyGzM

Thanks!

**Comment by nsthorat** [comment]
Also confirmed this is happening in 0.15.0.

**Comment by tafsiri** [comment]
Re-opening as I am experiencing a very similar issue on version 1.0.4 of tfjs.

Here is a reproduction with universal sentence encoder. https://codepen.io/tafsiri/pen/BEOENm?editors=0012 Digging into the code a little bit on my local machine suggests that it is the executeAsync call. I also get the same number of tensors leaked as the original issue.

**Comment by tafsiri** [comment]
cc @pyu10055

**Comment by nsthorat** [comment]
cc @pyu10055

**Comment by alvinsunyixiao** [comment]
I observed potential memory leak in executeAsync in the latest release. Can we consider re-open this issue?

Since my model is more of a differential equation simulation step, there are a lot of control flow ops in the model. It is hard to create a minimal reproducible code snippet, but my code repo, https://github.com/alvinsunyixiao/itp-websim/tree/alvin/mem,can be easily tested by running `yarn && yarn start` in the root.

The python code for the TF model is defined [here](https://github.com/alvinsunyixiao/itp-websim/blob/alvin/mem/model/spresso_tf.py). This script also conveniently saves the model into TFSavedModel format. The inference where the memory leak was observed is in [this function](https://github.com/alvinsunyixiao/itp-websim/blob/alvin/mem/src/Spresso.js#L160-L188). I have tried to log the number of tensor used through `tf.memory().numTensors` in a variety of locations, and it seems like the number of tensors in the memory grows (nondeterministically) every time `executeAsync` is called.

**Comment by Nk911** [comment]
@alvinsunyixiao meanwhile they check and provide fix. Please try using following.
The way to clean any unused tensors in async code is to wrap the code that creates them between a startScope() and an endScope() call.

tf.engine().startScope()
// do your thing
tf.engine().endScope()

Hope it helps

**Comment by gravestar** [comment]
> 
> 
> @alvinsunyixiao meanwhile they check and provide fix. Please try using following.
> The way to clean any unused tensors in async code is to wrap the code that creates them between a startScope() and an endScope() call.
> 
> tf.engine().startScope()
> // do your thing
> tf.engine().endScope()
> 
> Hope it helps

im facing a problem with this startScpoe and endScpoe,

so in my code, 
i need to set this first before anything else,
`async componentDidMount() {`
`await tf.ready();`
`this.model = await mobilenet.load()`
`this.knnClass = await knnClassifier.create()`
`}`

and for the other things, already wrapped inside startScope and endScope,
and return 0 or 1 numTensor,

the problem is, everytime i refresh the page, or go to another page and come back to TF page,
numTensor increase by 72, everytime i opened the page,

am i doing it wrong ? or its a bug ?
