### ISSUE TITLE
tfjs-core tensor dispose failure for WebGL backend with custom gl rendering context

### ISSUE THREAD

**Issue by pyu10055** [tensorflow/tfjs#1194]
To get help from the community, we encourage using Stack Overflow and the [`tensorflow.js`](https://stackoverflow.com/questions/tagged/tensorflow.js) tag.

#### TensorFlow.js version
0.15.0
#### Browser version
WeChat mini app
#### Describe the problem or feature request
```
    tf.tidy(() => {
      const start = Date.now();
      let result = '';
      const pixels = tf.tensor3d(new Uint8Array(ab), [size.height, size.width, 4], 'float32')
          .transpose([1, 0, 2]).slice([0,0,0], [-1, -1, 3]).resizeNearestNeighbor([224,224]);

      const tensor = this.mobileNet.predict(pixels) as tf.Tensor;
      const topK = this.mobileNet.getTopKClasses(tensor, 5);
      result += `prediction: ${Date.now() - start}ms\n`;
      result += topK.map((x, i) => `${x.value.toFixed(3)}: ${x.label}`).join('\n');
      return result;
    });
```

Above code causing the numTensors continues to decrease by 1 and eventually generate the following exception:
'Cannot release a texture that was never provided by this texture manager'
from texure_manager.ts:98

#### Code to reproduce the bug / link to feature request

**Comment by nsthorat** [comment]
This code doesn't run on it's own -- this could be a bug at many different layers of the stack. I tried to run this in a codepen with a loaded MobileNet, but I get shape mismatch errors.

Could you post a codepen with minimal reproducible code? Thanks.

**Comment by nsthorat** [comment]
Okay will look into this when I get some time

**Comment by nsthorat** [comment]
Okay this has to do with what @annxingyuan was seeing in her change (when we switch backend the download tensor gets parented to the wrong backend).

Can you check if this happens in 1.0.0-alpha1?

**Comment by pyu10055** [comment]
@nsthorat with the latest on master, the failure becomes 
`undefined is not an object (Evaluating texList.indexOf) `
on this [line](https://github.com/tensorflow/tfjs-core/blob/master/src/kernels/webgl/texture_manager.ts#L96)

**Comment by nsthorat** [comment]
I think the texShape is correct (2x2 packing) -- Ann can you look at the texList.indexOf problem? I think it's related to the original issue you fixed.

**Comment by annxingyuan** [comment]
Hey @pyu10055,

One of the issues is that you're passing `false` into the `MathBackendWebGL` constructor as the value of `delayedStorage`, which means when you read data from tensors registered to your backend, we keep them on the GPU (https://github.com/tensorflow/tfjs-core/blob/master/src/kernels/backend_webgl.ts#L2339). After reading from a texture we change its `TextureUsage` property to `UPLOAD`, but this does not necessarily translate to its physical texture type: https://github.com/tensorflow/tfjs-core/blob/master/src/kernels/webgl/texture_manager.ts#L146. Note if the usage is `UPLOAD`, we don't branch on 'WEBGL_RENDER_FLOAT32_ENABLED'. So If 'WEBGL_RENDER_FLOAT32_ENABLED' is false, and we later try to dispose that texture we read from, the texture manager thinks it's never seen that texture because it was created with a different `TextureUsage`, and hence different shape key.

Anyway this means you can get your demo to work by not passing `false` into the backend constructor, but maybe that's not possible for your use case. I'm working on addressing the underlying problem in this [PR](https://github.com/tensorflow/tfjs-core/pull/1543)

cc @nsthorat

**Comment by nsthorat** [comment]
Ping, as far as I understand, you shouldn't need delayedStorage=false for the `MathBackendWebGL` constructor, it's really an internal detail about when we upload CPU values to the GPU. Once you confirm that we can just go ahead and remove the bit altogether.
