### ISSUE TITLE
Update Layer models_tests to stub core API instead of fetch

### ISSUE THREAD

**Issue by pyu10055** [tensorflow/tfjs#1230]
To get help from the community, we encourage using Stack Overflow and the [`tensorflow.js`](https://stackoverflow.com/questions/tagged/tensorflow.js) tag.

#### TensorFlow.js version
1.0.0.alpha2
#### Describe the problem or feature request
Currently model loading tests in [src](https://github.com/tensorflow/tfjs-layers/blob/master/src/models_test.ts) is stubbing window fetch API, which made the tests coupling with the core implementation, instead it should stub the core APIs.

**Comment by gaikwadrahul8** [comment]
Hi, @pyu10055 

Thank you for opening this issue for tracking purposes. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFJs team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TFJs [version](https://github.com/tensorflow/tfjs/releases/tag/tfjs-v4.11.0) with the latest compatible hardware configuration which could potentially resolve the issue. We can keep the issue open if it is still relevant. Please confirm if we need to keep the issue open.

Thank you for your support and cooperation.
