### ISSUE TITLE
Add integration tests with <script> tags

### ISSUE THREAD

**Issue by dsmilkov** [tensorflow/tfjs#1251]
Add an integration test for the union package (and possibly for the smaller packages) that loads the library in a <script> tag and calls a few commands and make sure no warning or error messages show up.

This will prevent issues like https://github.com/tensorflow/tfjs-converter/pull/306

For example:

```html
<script src="tf.js"></script>
<script>
  tf.add(4, 5).print()
  ...
</script>
```

**Comment by gaikwadrahul8** [comment]
Hi, @dsmilkov 

Apologize for the delayed response and I was able to replicate the same issue with minimum above code and it's not showing any error messages or warning messages may be this issue has been taken care by this PR [#306](https://github.com/tensorflow/tfjs-converter/pull/306) which got merged . For your reference I have added screenshot below, If have I missed something here please let me know or Could you please confirm if this issue is resolved for you ? Please feel free to close the issue if it is resolved ? Thank you!

![image](https://user-images.githubusercontent.com/115997457/233959712-f2ba21d8-a613-4bdd-9024-6fddc055cdcb.png)
