### ISSUE TITLE
Missing call to tf.shuffle() in tfjs-examples/iris-fitDataset

### ISSUE THREAD

**Issue by irealva** [tensorflow/tfjs#1287]
#### Describe the problem or feature request

The [iris dataset](https://github.com/tensorflow/tfjs-examples/tree/master/iris-fitDataset) example in tfjs-examples is potentially [missing a tf.shuffle() call](https://github.com/tensorflow/tfjs-examples/blob/master/iris-fitDataset/data.js#L135) when using the new fitDataset API.

**Comment by bileschi** [comment]
Shuffling appears on [line 115](https://github.com/tensorflow/tfjs-examples/blob/master/iris-fitDataset/data.js#L115).  It is an operation on the array itself, rather than the dataset.  This is a rather unusual case, as the entire dataset is so small.  See the TODO comment for a discussion of a better way to handle this, once dataset.cache() is implemented.

If this answer is insufficient, please feel free to reopen.
