### ISSUE TITLE
MobileNet models: why are only v1_${alpha}_224 are being stored on public storage bucket?

### ISSUE THREAD

**Issue by randomarchive101** [tensorflow/tfjs#1310]
To get help from the community, we encourage using Stack Overflow and the [`tensorflow.js`](https://stackoverflow.com/questions/tagged/tensorflow.js) tag.

#### Describe the problem or feature request
from what i understand, you can in retrieve mobilenet models urls that are:
https://storage.googleapis.com/tfjs-models/tfjs/mobilenet_v${version}_${alpha}_${size}/

However, only those which size is 224 are being stored there.

I would be very interested in being able to access smaller size (96 or 124) models, as i constantly run into problems trying to access/load/use them otherwise.

**Comment by dsmilkov** [comment]
We only host the 224 version since that was the only version that we ported using the TF.js Converter tool at that time (this was before TF Hub).

If you find the version you want on TF Hub, (e.g. [v2_050_160](https://tfhub.dev/google/imagenet/mobilenet_v2_050_160/classification/2)), you can load it like this:
```ts
const modelUrl =
    'https://tfhub.dev/google/imagenet/mobilenet_v2_050_160/classification/2';
const model = await tf.loadGraphModel(modelUrl, {fromTFHub: true});
const zeros = tf.zeros([1, 224, 224, 3]);
model.predict(zeros).print();
```
