### ISSUE TITLE
Should be able to specify the Input layer with a shape [null, 1]

### ISSUE THREAD

**Issue by huan** [tensorflow/tfjs#1341]
#### Describe the problem or feature request

In Python, we have the following PY code:

```py
  decoder_inputs = Input(shape=(None, num_decoder_tokens))
```

In order to translate it to Javascript, we need to write this JS code:

```js
  const decoder_inputs = tf.layers.input({
    shape: [null, num_decoder_tokens],
  })
```

However, according to the current code, our `tf.layers.input()` accepts an argument with type `InputConfig` with a `shape?: Shape` property and the `Shape` had been defined as `number[]`, which I believe it should be changed as the following: 

```diff
- export declare type Shape = number[];
+ export declare type Shape = (number | null)[];
```

Currently, as a workaround, what I have to do is to force a type cast, which can make the TFJS typing system happy temporary.

```ts
  const decoder_inputs = tf.layers.input({
    shape: [null, num_decoder_tokens] as number[],
  })
```

cc @wangtz

**Comment by davidsoergel** [comment]
I suspect this is only as issue because you have `strictNullChecks` turned on. We don't use `strictNullChecks` in TFJS, so `[null, 1]` is already a valid `Shape` as far as the type system is concerned.  Also, I'm not sure that we actually interpret `null` shape components correctly, even though the type system allows them.

Of course, we also don't want to cause errors in dependent projects that do use `strictNullChecks`. 
 I'll continue trying to find the best fix for this kind of thing in general.  In the meantime, you can use the `skipLibCheck` compiler option to turn off the strict checking for dependencies, while leaving it on for your own code. (See https://stackoverflow.com/questions/40164034/typescript-strictnullchecks-with-limited-scope).

**Comment by nsthorat** [comment]
It would be good to add a unit test for a [null, 1] shape here if we support this.

**Comment by huan** [comment]
@nsthorat I had just added a very simple unit test for checking this, please let me know if there are more checks needed, thanks.

**Comment by huan** [comment]
Today I also have to use this to allow a dynamic input length:

> `shape: [null] as any as number[]`

https://github.com/huan/javascript-concise-chitchat/blob/ec37fcadee0f081c9d65bebbaace9e5c808164e9/src/model/encoder-model.ts#L17-L22

**Comment by huan** [comment]
Close this issue because The PR had been merged.
