### ISSUE TITLE
Implement gradient for dl.gather

### ISSUE THREAD

**Issue by nsthorat** [tensorflow/tfjs#135]
_From @tafsiri on March 5, 2018 15:35_

_Copied from original issue: tensorflow/tfjs-core#813_

**Comment by BusbyActual** [comment]
This issue link is broken or internal? I'm open to taking this just want to read about it more : ^)

**Comment by ManrajGrover** [comment]
Hi @BusbyActual :)

All of the issues and discussions have been moved to this repository to centralize management of issues, hence the link is not working. Feel free to discuss the issue here and take this one up.

**Comment by BusbyActual** [comment]
Would this feature be similar to [gradients](https://www.tensorflow.org/versions/master/api_docs/python/tf/gradients)? I checked the docs for [gather](https://www.tensorflow.org/versions/master/api_docs/python/tf/gather) && [gatherrd](https://www.tensorflow.org/versions/master/api_docs/python/tf/gather_nd) and they don't reference gradients. I'm trying to scope out the issue and map it out before i dive in : ^)

**Comment by jgartman** [comment]
@BusbyActual Just to give a little background (sorry if you knew this already), you can see [here](https://github.com/tensorflow/tfjs-core/blob/v0.6.0/src/ops/array_ops.ts#L753-L759) that `tf.gather` in TensorflowJS doesn't have it's gradient defined.  The gradient for `gather` in Tensorflow is [here](https://github.com/tensorflow/tensorflow/blob/r1.7/tensorflow/python/ops/array_grad.py#L388) so you could use that as a guide if you wanted to implement it.  One difficulty that I've noticed is that in Tensorflow the gradient  uses IndexedSlices which are used to represent sparse tensors.  Since sparse tensors don't yet exist in TensorflowJS I think you would need to find a way to convert that sparse representation to a dense tensor.  Hope that helps you out a little bit.

**Comment by jgartman** [comment]
@nsthorat I'll give it a try.

**Comment by zaidalyafeai** [comment]
thanks for your efforts. Any alternative for the time being? I can't use embedding layers.

**Comment by BusbyActual** [comment]
About to be on holiday for a few days. Happy to take another issue when I return

**Comment by nsthorat** [comment]
@zaidalyafeai I'd rather not rush on this since it's a tricky gradient and we want to get it right. Will ping you when it's done :)

**Comment by tafsiri** [comment]
closed by https://github.com/tensorflow/tfjs-core/pull/981
