### ISSUE TITLE
tf.data does not work in Edge Browser

### ISSUE THREAD

**Issue by DJCordhose** [tensorflow/tfjs#1395]
#### TensorFlow.js version

1.0.1

#### Browser version

Windows 10, Edge 44.17763.1.0

#### Describe the problem or feature request

loading data using tf.data does not work, since 

https://github.com/tensorflow/tfjs-data/blob/master/src/iterators/byte_chunk_iterator.ts#L96

uses 

https://developer.mozilla.org/en-US/docs/Web/API/TextDecoder

which is not supported in Edge. 

#### Code to reproduce the bug / link to feature request

https://djcordhose.github.io/crash-risk-calculator/

**Comment by Kriyszig** [comment]
Can we add a polyfill for TextDecoder? We are using it decode UTF-8 encoded entities so a polyfill specific to UTF-8 should be enough.
Maybe we can just use <https://gist.github.com/Yaffle/5458286> [comes with the license attached]

**Comment by kangyizhang** [comment]
[tfjs-core](https://github.com/tensorflow/tfjs/blob/81225adc2fcf6fcf633b4119e4b89a3bf55be824/tfjs-core/src/platforms/platform_browser.ts#L45) is also using TextDecoder.

@dsmilkov what do you think?

**Comment by dsmilkov** [comment]
Hi @Kriyszig,

Since Edge is moving to Chromium, it will have built-in `TextDecoder`. We won't be baking polyfill into tf.data to keep the library size small and avoid extra code for browsers/platforms that do have it built-in.

You have two options:
1) (Recommended) Provide your own polyfill. E.g. see [`text-encoding`](https://github.com/inexorabletash/text-encoding) library
2) Provide your own platform which is an object that implements our [`Platform`](https://github.com/tensorflow/tfjs/blob/master/tfjs-core/src/platforms/platform.ts) interface and provide your own `encode()` and `decode()` implementations. See [`PlatformReactNative()`](https://github.com/tensorflow/tfjs/blob/6e6bd195b48e3504e28c36aae4e9d61239c226e4/tfjs-react-native/src/platform_react_native.ts#L232) as an example.
