### ISSUE TITLE
Support tf.node.decodeImage.

### ISSUE THREAD

**Issue by nsthorat** [tensorflow/tfjs#1416]
This should be a binding to https://www.tensorflow.org/api_docs/python/tf/io/decode_image

We've had many issues talking about lack of support for reading images in Node.js, we should prioritize this.

https://github.com/tensorflow/tfjs/issues/1414
https://github.com/tensorflow/tfjs/issues/594

**Comment by chenqing** [comment]
this great.  
node-canvas has many dependences ，and in China install it very slowly.
so very looking forward to implementing this feature.
thank you.

**Comment by JacopoMangiavacchi** [comment]
I'm successfully using jpeg-js to decode the image and then transform the pixel buffer to get the 3d tensor instead of using node-canvas.

Anyway I'm having performance issues on inferencing this way a tf.Tensor3D to a mobilenet coco-ssd model.  On the browser the same model, just passing an HTMLImageElement instead, is much faster.

Technically I'm not really running just on node.js as I'm on a Electron app but I suppose it should be the same.

Any advice here please ?

**Comment by tafsiri** [comment]
@JacopoMangiavacchi Could you make a new issue for what you are experiencing, since you are already past the point of reading the images into memory. That way you could also give us more detailed information about your execution environment (e.g. which Electron process are you running inference in, what size tensors are you passing in etc).

**Comment by chenqing** [comment]
any progress? @nsthorat

**Comment by nsthorat** [comment]
No progress yet but @caisq will be taking this work on in the near future. There is still a workaround with tf.browser.fromPixels and using a canvas in the meantime.
