### ISSUE TITLE
Keras spec identifier (value-list / Type) {camelCase/snake_case} pattern consistency

### ISSUE THREAD

**Issue by bileschi** [tensorflow/tfjs#1463]
This bug is about, for lack of clearer vocabulary, the 'Keras-identifiers', by which I mean things like FanModes (see initializer_config.ts), Distributions (intiializer_config.ts), Constraints (constraint_config.ts), and Activations.  Objects which are known string sets belonging to the Keras spec.

For objects like these, we often need access to the enumerated list of values.  We use these for input validation at run-time, enumeration over values for testing & creation of drop-down menus.  We also need access to these objects as a typescript type.

Furthermore, we sometimes need these identifiers in camelCase mode, and sometimes need them in snake case mode.

This describes a four cell pattern: {valueList, Type} x {camelCase, snake_case}.  In keras_format currently, several patterns are used.

For instance, compare:
```
export type FanMode = 'fanIn'|'fanOut'|'fanAvg';
export const VALID_FAN_MODE_VALUES = ['fanIn', 'fanOut', 'fanAvg'];
// These constants have a snake vs. camel distinction.
export type FanModeSerialization = 'fan_in'|'fan_out'|'fan_avg';
```
with:
```
export const activationOptions = stringLiteralArray([
  'elu', 'hard_sigmoid', 'linear', 'relu', 'relu6', 'selu', 'sigmoid',
  'softmax', 'softplus', 'softsign', 'tanh'
]);

/**
 * A type representing the strings that are valid loss names.
 */
export type ActivationSerialization = typeof activationOptions[number];

// Sad that we have to do all this just for hard_sigmoid vs. hardSigmoid.
// TODO(soergel): Move the CamelCase versions back out of keras_format
// e.g. to src/common.ts.  Maybe even duplicate *all* of these to be pedantic?
/** @docinline */
export type ActivationIdentifier = 'elu'|'hardSigmoid'|'linear'|'relu'|'relu6'|
    'selu'|'sigmoid'|'softmax'|'softplus'|'softsign'|'tanh';
```

For FanMode we have:
*  camelCaseType
*  camelCaseList
*  snakeCaseType

For Activation we have:
*  camelCaseType
*  snakeCaseType
*  snakeCaseList

Also, we have a confluence of terms referring to the individual cells, i.e., `XXXIdentifier` vs `XXXSerialization` vs. `XXXOptions` vs. `XXX`

We should make the pattern consistent across the Keras-identifiers.

**Comment by bileschi** [comment]
One proposal is to make all four cells available for each Keras-identifier.  One proposed name scheme:

```
FanMode_CamelCase_Type
FanMode_CamelCase_ValueList
FanMode_SnakeCase_Type
FanMode_SnakeCase_ValueList
```

Another option could be to only explicitly reference one or the other capitalization:
```
FanMode_Type
FanMode_ValueList
FanMode_SnakeCase_Type
FanMode_SnakeCase_ValueList
```

Another naming decision is be to only explicitly reference the type or the value list.  We should see which is needed more often in user-facing code and make that one implicit:
```
FanMode_CamelCase
FanMode_CamelCase_ValueList
FanMode_SnakeCase
FanMode_SnakeCase_ValueList
```

Of course, we could combine.
```
FanMode
FanMode_ValueList
FanMode_SnakeCase
FanMode_SnakeCase_ValueList
```

Other options are also possible
```
FanMode
FanModeValues
FanModeSerializaiton
FanModeSerializationValues
```

etc.

**Comment by davidsoergel** [comment]
Totally agree in principle with all of this-- it's just down to the naming discussion imho.

Since these are all TypeScript symbols (even if they *describe* python-style snake_case things), the names should all be pure CamelCase.  Also, the type symbols should start with a capital, and the list symbols should start with lowercase (again just JS/TS convention for types vs variables).

That leaves the fully-explicit names something like

    FanModeCamelCaseType
    fanModeCamelCaseValues
    FanModeSnakeCaseType
    fanModeSnakeCaseValues

I think I like `*Options` instead of `*Values`.

Re `*CamelCase*`/`*SnakeCase*` vs. `**`/`*Serialization*`, I can see arguments both ways.

In combination I think my current favorite is

    FanMode
    fanModeOptions
    FanModeSerialization
    fanModeSerializationOptions

but I feel much less strongly about the particulars than about the idea of establishing some consistent pattern :)

**Comment by bileschi** [comment]
```
FanMode
fanModeOptions
FanModeSerialization
fanModeSerializationOptions
```

Works for me.

**Comment by gaikwadrahul8** [comment]
Hi, @bileschi 

Thank you for opening this issue for tracking purposes. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFJs team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TFJs [version](https://github.com/tensorflow/tfjs/releases/tag/tfjs-v4.11.0) with the latest compatible hardware configuration which could potentially resolve the issue. We can keep the issue open if it is still relevant. Please confirm if we need to keep the issue open.

Thank you for your support and cooperation.
