### ISSUE TITLE
Blob and Base64 images to Tensor 

### ISSUE THREAD

**Issue by Jonarod** [tensorflow/tfjs#1485]
Given the same `.jpg` image, HTML5 commonly accepts these types of `<img />` tags:
```html
<img src="https://domain.com/path/to/my/image.jpg" />
<img src="data:image/jpg;base64,/dh7hfhwehfw9hfw...wh9fh8w9hf" />
<img src="blob:https://domain.com/b3872f9f-acb7-49d9-a26d-4854d72c9939" />
```
If I am correct, `tfjs` will only load images using `tf.fromPixels(input)` which, as its name implies, loads from pixels (= the first type of `src`).
However, I could not find anything like `tf.fromBase64(input)` nor `tf.fromBlob(input)` to convert other formats to tensors.
More generally, is there any way to process Blobs and/or base64 images through tfjs ?
Thanks !

**Comment by jessetrana** [comment]
Yes, but it is a bit roundabout and not probably what you want. I currently do Blob -> URL.createObjectURL(blob) -> Image() load using URL -> tf.browser.fromPixels(img) in a Firefox plugin. I do base64 as well but only as a fallback; I recommend sticking with Blob if you can.

**Comment by jessetrana** [comment]
Can someone familiar with the internals comment on the overall strategy around this? My hunch is that this has not been implemented for the same reason that tf.fromPixels moved to tf.browser.fromPixels - the browser is the one that is responsible for managing image parsing via whatever codec support it has rather than trying to reimplement (perhaps awkwardly) in JS. If that's the case, it seems like this may be a candidate for closure as the convenience may not outweigh the disadvantages (even though I too would love such a convenient API).

**Comment by tafsiri** [comment]
@jessetrana I would say you're strategy is correct (assuming you already have a blob loaded). Since blob and base64 are pretty generic in terms of what they can represent it would probably be best for user code to convert it to an image using the format they know the data is in. We probably won't be implementing functionality to take blobs or base64 strings directly.

@Jonarod To you first question, have you tried `tf.browser.fromPixels` with second and third image tags? It should work assuming the image is done loading (I tried it with something similar to what you have in your second example). Let us know if it doesn't.

**Comment by 0x00b1** [comment]
fromPixels accepting a base64 string would be super useful since the HTMLImageElement (or similar) dance is especially cumbersome in our application where images are stored in an IndexedDB database and rarely outputted to the DOM.

**Comment by dsmilkov** [comment]
Since you have your own custom serialization/deserialization, you should use [`tf.tensor (values, shape?, dtype?)`](https://js.tensorflow.org/api/latest/#tensor) . For `values`, you can pass a regular (or nested) array of values, or a TypedArray. Then all you have to do is convert from IndexedDB to pixel values.

**Comment by rthadur** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
