### ISSUE TITLE
[tfjs-node] tf.loadLayersModel support cache 

### ISSUE THREAD

**Issue by chenqing** [tensorflow/tfjs#1514]
when we load a model from remote url, tf should add an option to support cache in local.

**Comment by rthadur** [comment]
cc @dsmilkov

**Comment by tafsiri** [comment]
I'm not sure if this is something we would want to bake into the library since caching/cache busting might be something end users want a fair amount of control over. Two alternatives I can think of include:

1. Downloading the model and weights to the local filesystem and loading them from there (we may need to some work to make it clearer how to do that).
2. Using libraries like https://www.npmjs.com/package/make-fetch-happen that support customizing fetch on node to support caching in a configurable way. This would be used in the same way that node-fetch is used currently.

**Comment by chenqing** [comment]
@tafsiri  thanks for your replay.
Yes,  maybe we lack best practices to tell the user handle this.  for example, write in docs.

**Comment by rthadur** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
