### ISSUE TITLE
When I used tensorflow-convert to convert Python model to js, an error was reported and no add_to_collection was found.

### ISSUE THREAD

**Issue by XdyGoGo** [tensorflow/tfjs#1520]
To get help from the community, we encourage using Stack Overflow and the [`tensorflow.js`](https://stackoverflow.com/questions/tagged/tensorflow.js) tag.

**Comment by tafsiri** [comment]
@XdyGoGo Could you please fill out the template to let us know what version of the converter you are using? Could you also paste the error message you get in this thread. Anything more you can tell us about the model itself would be helpful.

cc @pyu10055

**Comment by rthadur** [comment]
It looks like you haven't used a template to create this issue. Please resubmit your issue using a template from [here](https://github.com/tensorflow/tfjs/issues/new). We ask users to use the template because it reduces overall time to resolve a new issue by avoiding extra communication to get to the root of the issue. We will close this issue in lieu of the new one you will create from the template. Thank you for your cooperation.
