### ISSUE TITLE
[tfjs-core]: Add bicubic resize

### ISSUE THREAD

**Issue by aptlin** [tensorflow/tfjs#1668]
#### TensorFlow.js version

1.1.2

#### Describe the problem or feature request

EfficientNet requires the support for a bicubic resize for the optimal performance, yet it is not yet in the `tfjs-core` toolkit. Using a bilinear resize [does](https://github.com/lukemelas/EfficientNet-PyTorch/issues/12) deteriorate the performance.

#### Code

As far as I understand, we need to add the corresponding op to the [image ops](https://github.com/tensorflow/tfjs-core/blob/master/src/ops/image_ops.ts) after implementing them in all of the backends and adjust the [tensor interface](https://github.com/tensorflow/tfjs-core/blob/a538a801d430e67acab077f424855ca6662c06bf/src/tensor.ts). Am I correct?

**Comment by nsthorat** [comment]
The general approach we take for deciding whether it should be implemented as a backend interface method is if it shows up in [ops.pbtxt](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/ops/ops.pbtxt).

In this case, the ops.pbtxt entry looks like this:
```
op {
  name: "ResizeBicubic"
  input_arg {
    name: "images"
    type_attr: "T"
  }
  input_arg {
    name: "size"
    type: DT_INT32
  }
  output_arg {
    name: "resized_images"
    type: DT_FLOAT
  }
  attr {
    name: "T"
    type: "type"
    allowed_values {
      list {
        type: DT_INT8
        type: DT_UINT8
        type: DT_INT16
        type: DT_UINT16
        type: DT_INT32
        type: DT_INT64
        type: DT_HALF
        type: DT_FLOAT
        type: DT_DOUBLE
      }
    }
  }
  attr {
    name: "align_corners"
    type: "bool"
    default_value {
      b: false
    }
  }
  attr {
    name: "half_pixel_centers"
    type: "bool"
    default_value {
      b: false
    }
  }
}
```

Since this appears here, you are exactly right this should be implemented as a kernel and also as an op!

High level question for you @sdll -- is there a place where you've outlined the models you want to add to tfjs-models? I think we should probably review this and make sure we'll accept them before you do all the required work. Maybe we can discuss and track on a separate issue?

**Comment by sdll** [comment]
@nsthorat, thank you for illuminating the workflow! For sure, I will create a separate issue tracking the current progress and outlining the future work, moving away from the Google Sheet I sent you a while ago. There is also a Notion board to which you have access, but gh issues do seem more robust.

**Comment by sdll** [comment]
The bicubic resize is not a major issue, EfficientNet does seem to perform quite well without it, judging from the pytorch implementation, but it would be nice to have it in the long-term.

**Comment by rthadur** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by sdll** [comment]
@rthadur, not sure if the issue should be closed until the bicubic resize is implemented. Is this tracked anywhere else?

**Comment by nsthorat** [comment]
Let's keep this open since it's a feature request.

**Comment by susmeet-jain** [comment]
Hey @nsthorat 
Any update on this feature request?

**Comment by gaikwadrahul8** [comment]
Hi, @aptlin 

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFJs team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TFJs [version](https://github.com/tensorflow/tfjs/releases/tag/tfjs-v4.10.0) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tfjs/blob/master/README.md) to stay up to date with the latest developments which are happening in the Tensorflow.js space.

Thank you for your support and cooperation.

**Comment by kevinz8866** [comment]
So do we plan to have **bicubic resize** or not? Thanks!
