### ISSUE TITLE
tf.unstack() code example in documentation is broken (0.11.2)

### ISSUE THREAD

**Issue by generic-github-user** [tensorflow/tfjs#1672]
In the API documentation for [version 0.11.2](https://js.tensorflow.org/api/0.11.2) of TensorFlow.js, the given code example for `tf.unstack()` throws an error when run: `tf.unstack(...).print is not a function`.

![image](https://user-images.githubusercontent.com/40661852/59635908-4985d780-9120-11e9-8455-ac4144f4e1c2.png)

I found [another issue](https://github.com/tensorflow/tfjs/issues/412) about this, but it is closed and appears to have been resolved. The problem still occurs in all three links provided in that issue. It works fine in the latest version of the docs.

No error is logged if I replace `tf.unstack(a).print();` with `console.log(tf.unstack(a));`, but the output seems unfamiliar.

![image](https://user-images.githubusercontent.com/40661852/59636308-2e679780-9121-11e9-9cec-b85335a648da.png)

**Comment by tafsiri** [comment]
Looks like this got fixed in version 0.11.7 so feel free to refer to those docs https://js.tensorflow.org/api/0.11.7/#unstack. Note that unstack returns an array of tensors. 

The code snippets are extracted from the code based at the time the version was released so we won't typically go back to change them.

**Comment by generic-github-user** [comment]
This makes sense - thanks for the quick response.
