### ISSUE TITLE
tfvis.show.fitCallbacks provides no support for  xAxisDomain and yAxisDomain for Accuracy chart

### ISSUE THREAD

**Issue by ToonTalk** [tensorflow/tfjs#1698]
The documentation for https://js.tensorflow.org/api_vis/latest/#show.fitCallbacks shows how one can specify the x and y domain of the loss chart but why is there nothing like it for the accuracy chart?

**Comment by tafsiri** [comment]
Hi I realize this is an older bug, but thought I'd chime in anyway. This is by design, generally we expect users will want to see accuracy on the full 0-1 scale that the metric is reported over (and that this provides the most accurate view of overall performance). We do provide a `zoomToFitAccuracy` option to allow tighter zooming, but didn't see as much benefit to allowing arbitrary setting of the domains.
