### ISSUE TITLE
Feature request - ability to save a tf.GraphModel to a local file system.

### ISSUE THREAD

**Issue by oveddan** [tensorflow/tfjs#1701]
Currently you can load a `tf.GraphModel` with `tf.loadGraphModel`.  Is there an easy way to save the files for the graph model locally?  For my use case, I want to be able to load the files from the google cloud, save them locally, then serve off of a local file server.  If there is no easy way, it would be nice if there was an api method to do this, something like:

```typescript
const model = await tf.loadGraphModel( 'www.someurl.com/somecheckpoint')
await model.saveToFileSystem('/pathToSaveTo')
```

 It would be fine if this only worked in node.js

**Comment by ozican** [comment]
I am gonna be crazy.. 1 week I didn't sleep because of that.. How nobody needs that? I want to create an api in my server via node.js. I have a trained vision model (autoML), and when I load it from local file, it gives me error!!!!! F***k yeah f***king G****l* bot.... Love you!!! Have a nice day, bay bay.

(Finally feel better)

**Comment by caisq** [comment]
@pyu10055 do you have cycles to take a look at this feature request?

**Comment by pyu10055** [comment]
@oveddan The graph model has added save() method, you can store them in any of the storage option now.
