### ISSUE TITLE
Unknown op 'ExtractImagePatches'

### ISSUE THREAD

**Issue by Kompalk** [tensorflow/tfjs#1714]
Hi,

While I run the below command, I get an error "ValueError: Unsupported Op in the model before optimization ExtractImagePatches".

tensorflowjs_converter --input_format=tf_frozen_model --output_node_names='output' --saved_model_tags=serve --output_json=true yolov2/yolov2.pb web_model/

Even though I use '--skip_op_check' to skip the ops during conversion, these ops error come up again when I call the model for prediction in frontend.
Can this op "ExtractImagePatches" be added for supported operations by [Tensorflow.js]

TensorFlow.js :0.8.6
Tensorflow: 1.14.0
Browser version - Google Chrome: 74.0.3729.131

Thanks.

**Comment by gaikwadrahul8** [comment]
Hi, @Kompalk 

Apologize for the delayed response and this issue is too old so now we're using `Tensorflow version 2.x `so could you please try with latest stable version of `tensorflow 2.12.0` and check whether this issue still exist or not ? if issue still exist please help me with model folder to replicate the same issue from our end ?

@doiko Could you please give it try with latest version of `tensorflow 2.12.0` and `tensorflowjs 4.4.0` ? if issue still exist please help me with model folder and exact command you're using for` tensorflowjs_converter` ? Thank you!
