### ISSUE TITLE
Feature Request: Speech to Text (STT) via DeepSpeech

### ISSUE THREAD

**Issue by beriberikix** [tensorflow/tfjs#1725]
During the jsconfeu talk the team mentioned more audio models are on the roadmap. Are you considering Speech to Text (STT) models? I have a use case that would benefit transcribing long-form audio from a file in the browser using tfjs. [DeepSpeech](https://github.com/mozilla/DeepSpeech) from Mozilla is the most popular open source Speech-To-Text engine, based on research from Baidu and uses TensorFlow. They provide pre-trained models in their [releases](https://github.com/mozilla/DeepSpeech/releases) and models can be exported for [TFLite](https://github.com/mozilla/DeepSpeech#exporting-a-model-for-tflite). They also provide an example transcribing long-form audio written in [Python](https://github.com/mozilla/DeepSpeech/blob/master/examples/vad_transcriber/wavTranscription.md).

Many thanks!

**Comment by vadimkantorov** [comment]
I managed to run NVidia openseq2seq wav2letter checkpoint in TFJS: https://github.com/vadimkantorov/inferspeech

Unfortunately, lack of native stft makes it super-slow, and the model OOM Chrome quite regularly: https://github.com/tensorflow/tfjs/issues/1657#issuecomment-506458895

**Comment by tafsiri** [comment]
cc @nsthorat @nkreeger

**Comment by gaikwadrahul8** [comment]
Hi, @beriberikix 

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFJs team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TFJs [version](https://github.com/tensorflow/tfjs/releases/tag/tfjs-v4.10.0) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tfjs/blob/master/README.md) to stay up to date with the latest developments which are happening in the Tensorflow.js space.

Thank you for your support and cooperation.
