### ISSUE TITLE
[Codelab]: Making Predictions from 2D Data

### ISSUE THREAD

**Issue by rsaeta** [tensorflow/tfjs#1798]
To get help from the community, we encourage using Stack Overflow and the [`tensorflow.js`](https://stackoverflow.com/questions/tagged/tensorflow.js) tag.

#### Describe the problem or feature request
On step 4. Define the model architecture of the [tensorflow.js codelabs](https://codelabs.developers.google.com/codelabs/tfjs-training-regression/index.html#3), the code block for `createModel` has a different output layer than the line-by-line walkthrough. The code-block will actually not produce any visualization when trying to train the model in the next pages. However, the line-by-line (omitting `useBias` field) fixed the problem.

**Comment by rthadur** [comment]
@rsaeta thanks for reporting the issue , i was able to reproduce the issue.Will fix it.

**Comment by tafsiri** [comment]
Hi. useBias is true by default for dense layers, we have a note about that on the [model definition page](https://codelabs.developers.google.com/codelabs/tfjs-training-regression/index.html#3), so after explaining it we no longer include it in the calls. Note that omitting it is not the same as changing it to false (which we do not do).

@rthadur it looks like unlike @rsaeta, in both cases (useBias being present and being omitted) you were able to train the model and get a visualization?

Does the output in each case stay consistent? (because of random initialization you can get different results on different runs). I was not able to get a consistent difference between using useBias and not using it.

**Comment by rsaeta** [comment]
I honestly tried to do this again and could not reproduce the same error. The actual behavior I saw was that it was not showing a visualization for MSE/loss when going through iterations of training. It would adjust the x-axis but no line was showing up.

**Comment by rthadur** [comment]
@tafsiri yes i was able to train the model and get a visualization in both cases, but output is not consistent.

**Comment by rthadur** [comment]
@rsaeta let us know if you were able to get resolve this ?

**Comment by rsaeta** [comment]
Yes I was able to resolve this, but still not quite sure of root cause. Can close if cannot reproduce as I cannot either.

**Comment by tafsiri** [comment]
Thanks for the update. I'm going to close this for now as the original issue cannot be reproduced.
