### ISSUE TITLE
tfjs-react-native alpha release

### ISSUE THREAD

**Issue by tafsiri** [tensorflow/tfjs#1948]
Hello TensorFlow.js community,

We are very excited to announce something we have been working on and invite you to try it out and give us feedback!

We have just released an **alpha version of TensorFlow.js for React Native**. This brings all tensorflow.js capabilities to native apps writing in react native. You can install the [package from npm](https://www.npmjs.com/package/@tensorflow/tfjs-react-native) and setup instructions are [available on github](https://github.com/tensorflow/tfjs/tree/master/tfjs-react-native).

This platform package:
 - Supports both inference and training.
 - Has GPU support with WebGL via [expo-gl](https://github.com/expo/expo/tree/master/packages/expo-gl).
 - Has support for loading models from the web, asyncStorage as well as models that are included in the app bundle.
 - Has support for saving models to asyncStorage.

It will be in _alpha_ while we get feedback from the community. Our team is not primarily a React Native team so there is plenty of opportunity to jump in, get involved and shape the future of this package! The kind of feedback we are looking for includes: 
 - **Usability** of the package.
 - **Use cases**: what kinds of ML powered mobile applications are you looking to build? 
 - **Performance**: how quickly do your models run on this platform. So far our testing has shown this platform to be comparable in performance to the WebGL backend in mobile browsers.
 - **Compatibility**: we’ve tested on a wide range of Android and iOS devices, but could always get more feedback here. Note that we can only support devices that support OpenGL ES 3.0 and higher. 

Your feedback will help shape priorities for the general launch of this package!

We also welcome people interested in getting involved in future development. In creating this package we have learned of a few things that we are used to being built into the web platform by default that aren’t present by default in a React Native. Experienced react native developers will have a good sense of how to best integrate with other parts of the RN ecosystem. Places we have identified for further investigation (and welcome your comments) include:
 - Best practices for efficiently working with binary data in react native
 - Integrating with sensors in RN. Eg. Camera, including streaming access (no built in canvas!) etc.
 - Compatibility with the recently released RN 0.60.

Links: 
 - NPM: https://www.npmjs.com/package/@tensorflow/tfjs-react-native 
 - GitHub: https://github.com/tensorflow/tfjs/tree/master/tfjs-react-native.

Feel free to discuss this on the [community mailing list](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or on this tracking issue  on GitHub. We’ll use one mega-issue (this one) to collect initial feedback. Also feel free to forward this to others interested in React Native and Machine Learning!

Looking forward to what you build!

**Comment by curiousily** [comment]
Awesome to see this project going! What is the status of supporting the latest RN 0.60/0.61versions? Where do you guys need help?

**Comment by tafsiri** [comment]
@curiousily, Thanks for checking it out! I think the biggest blocker to RN 0.60 support is expo/expo-gl supporting RN 0.60. I believe expo is planning on supporting it in future releases so I imagine that will smooth out eventually. In terms of help, testing it out and seeing if there are any weaknesses/holes in terms of functionality would be great. 

One thing I've been wondering about is how folks handle image processing in react native, currently I've been doing decoding and encoding in the JS process but I wonder if there are best practices for doing this on the native side.

**Comment by mgroeneweg** [comment]
Hi,

We're looking into a use case to  use TensorFlow.js in a Mendix native mobile app, which is actually a React Native app. The user will walk around a museum. pointing the mobile phone at items on display. The app recognizes the items and provides information, on the display and/or through text-to-speech.
So recognizing objects using the camera stream from a pre-trained model is key here. For other use cases we would like to train the model in React Native too. However, that could be done on a laptop or tablet too.

**Comment by ben-xD** [comment]
Is there a possibility of using a different way to get GPU support? Expo is a **very** painful experience, and I've decided that its not worth it for my projects. I'm going to find a long way around to get neural networks on react native, probably tensorflow lite.

A few of my reasons (many others have said the same, btw):
- Lots of open issues (670), and the issues that I'm affected by (many of them), are not handled. This includes random bugs with the camera module. I would prefer if I can use react-native-camera instead of expo-camera. 
- heavy?: unimodules and the expo related stuff added ~10Mb to my app, and a lot of complexity, and dependency hell. 
- (my opinion/ feeling) Most developers don't use expo (even their so called 'bare workflow') for projects
- I'm cloning their repository and its almost 2GB. Do they expect people to clone that to create PRs on small modules like camera?
- Expo actually gets 70k weekly downloads on [npm](https://www.npmjs.com/package/expo), but react-native-camera gets 75k. This is a library that is an alternative to using expo-camera. I wonder how many downloads expo-camera would get if it were a separate library and expo wasn't the first thing on react-native's page.
- One nice thing about expo, are the snacks. But then most of them are outdated anyway...

Sorry Expo, i've actually tried so many times to use you over the past few months. I **cannot** believe how react native code snippets actually defaults to expo. **What** a **trap** for beginners. 

Other opinions/ anecdotes: 
https://www.reddit.com/r/reactnative/comments/9z5zdj/im_sorry_but_expo_sucks/
https://www.reddit.com/r/reactnative/comments/7hpwrb/i_hate_expo/

**Comment by tafsiri** [comment]
Closing this because its somewhat old/out of date. 

@ben-xD If you have any suggestions on a different way to get WebGL support outside of a webview, I'd be open to hearing them (feel free to make a new issue). But it does look like expo is a path endorsed by the react-native team.
