### ISSUE TITLE
Support for Rank 5 Tensors in model prediction and related functions

### ISSUE THREAD

**Issue by prouast** [tensorflow/tfjs#1985]
#### TensorFlow.js version
1.2.8
#### Browser version
Chrome 76.0.3809.132 (64-bit)
#### Describe the problem or feature request
Following up on [this comment](https://github.com/tensorflow/tfjs/issues/767#issuecomment-528166717), I ran into the same issue originally reported in issue #767 when trying to input a rank 5 tensor into model.predict():
```
Error: sliceAlongFirstAxis() received an unsupported tensor rank: 5
```
The error occurs in [tfjs_backend.ts](https://github.com/tensorflow/tfjs/blob/master/tfjs-layers/src/backend/tfjs_backend.ts), where [`sliceAlongFirstAxis()`](https://github.com/tensorflow/tfjs/blob/master/tfjs-layers/src/backend/tfjs_backend.ts#L217) still does not support tensor rank 5. Would it now be possible to create a `tfc.slice5d` method?

**Comment by OVERSTANDING683** [comment]
Needs update... type:bug

**Comment by PhillipMerritt** [comment]
I'm also dealing with this when attempting to predict on a stack of frames from a game with a shape of [4,172,95,1].

I'm not really sure how to work around this besides going back to predicting on single frames.

**Comment by net2cn** [comment]
Hi,
According to my experience, rank 5 tensors work perfectly fine with CPU backend since I've run into a similar situation and found a temporary solution by switching to CPU backend.
However, this solution works unbearably slow since you'll lose all hardware acceleration. So I'm wondering whether an automatic fallback on the methods that don't support high rank tensors is possible.
Best regards.
