### ISSUE TITLE
Optimize fromPixels for WebGPU backend

### ISSUE THREAD

**Issue by qjia7** [tensorflow/tfjs#1988]
This is blocked by WebGPU to provide a texImage2D like API which ingesting HTMLVideoElement.

**Comment by qjia7** [comment]
@annxingyuan FYI

**Comment by gaikwadrahul8** [comment]
Hi, @qjia7 

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFJs team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TFJs [version](https://github.com/tensorflow/tfjs/releases/tag/tfjs-v4.10.0) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tfjs/blob/master/README.md) to stay up to date with the latest developments which are happening in the Tensorflow.js space.

Thank you for your support and cooperation.

**Comment by qjia7** [comment]
It has been supported in webgpu backend.
