### ISSUE TITLE
coco-ssd custom training

### ISSUE THREAD

**Issue by ghafran** [tensorflow/tfjs#2049]
@pyu10055 

https://github.com/tensorflow/tfjs-models/tree/master/coco-ssd

Where can we find a step-by-step documentation on how tfjs-models coco-ssd model.json was built? The readme file does not provide sufficient information. 

We are trying to use the coco-ssd model with a custom model using transfer learning from https://github.com/tensorflow/models/tree/master/research/object_detection. Can you please provide the exact conversion process for model.json?

Thanks.

**Comment by pyu10055** [comment]
Hi @ghafran 

As described in end of the coco-ssd README, we add some optimization by removing the post-processing sub-graph from the original python saved model.
But this process cannot be done with the latest converter, since it requires you to specify the output nodes. There are two ways to achieve this:
1. use a older version of the converter.
2. add a SignatureDef to the python model that has the intermediate nodes as output.

The following instruction is for the option 1:

You can install a previous version of TensorFlow.js in a virtual environment to convert the model to the JSON format. Here is how you can achieve this.

Set up the virtual environment:

```
virtualenv --no-site-packages venv
. venv/bin/activate
pip install tensorflowjs==0.8.6
```
venv is the name of the virtual environment.

Convert the coco ssd saved model:
```
tensorflowjs_converter --input_format=tf_saved_model \
                       --output_node_names='Postprocessor/ExpandDims_1,Postprocessor/Slice' \
                       --saved_model_tags=serve \
                       --output_json=true \
                       ./saved_model \
                       ./web_model
```

**Comment by ghafran** [comment]
@pyu10055 

I created a colab based on your instructions and seems to work using tensorflowjs 0.8.6.

https://colab.research.google.com/drive/1wbbFo6RmUslM2pXNjeYNj7capbo-gljG

Would be great to see this work with latest version.

Thanks!

**Comment by rthadur** [comment]
thank you , glad it worked for you, there is no plan as of now.
