### ISSUE TITLE
[react native] implement custom decodeJpeg

### ISSUE THREAD

**Issue by tafsiri** [tensorflow/tfjs#2071]
#### Describe the problem or feature request

To make handling images in react native easier we should implement a [decodeJpeg](https://www.tensorflow.org/api_docs/python/tf/io/decode_jpeg) utility (similar to [tf.node.decodeJpeg](http://localhost:8080/api_node/1.2.8/#node.decodeJpeg)). One difference from the regular decodeJpeg signature is that we should allow a `ImageResolvedAssetSource` to be passed in as the first parameter. This enables flexibility of doing the byte reading and decoding on the native thread without going across the bridge (though this would be an internal implementation detail). It would also take a byte array if the bytes for the image are already in the js process.

Proposed signature (just the first 3 arguments)

```ts
decodeJpeg(contents: ImageResolvedAssetSource|Uint8Array|ArrayBuffer, channels?:0|1|3, ratio?: 1|2|4|8)
```

**Comment by dsmilkov** [comment]
sgtm

**Comment by jessetrana** [comment]
What is the long term strategy on image handling across the different backends? Is a unified approach likely? At one point (over on #1485 ) it seemed as though image decoding was not going to be pulled into the core. However, to make the node case better [tf.node.decodeJpeg](https://www.tensorflow.org/api_docs/python/tf/io/decode_jpeg) came into being. I found this intriguing, but looking into how it was implemented, it appears as though it is actually [being forwarded to Tensorflow itself via a binding](https://github.com/tensorflow/tfjs/blob/6d3a9a994bfd67fc721a6a4f699bedb060045a8f/tfjs-node/src/nodejs_kernel_backend.ts#L1772). I'm assuming that's why it wasn't implemented as a more generic tf.image.decodeJpeg.

The Node implementation piqued my interest however, and further looking at what Tensorflow supports showed what appears to be an [ops-based image decoder](https://github.com/tensorflow/tensorflow/blob/r1.14/tensorflow/python/ops/image_ops_impl.py#L2137-L2250).

Now perhaps that's too much code to try to port/support, but I was wondering if pulling over the ops-based code would provide a generic solution that could work across the backends somehow and enable bypassing the DOM for image decoding as in #1485. (Full disclosure: my current use of TF.js would definitely use this feature assuming it was faster than the DOM!)

Is my understanding correct on how that is working? Is that something that would make sense in the context of how this project handles backend implementations?

**Comment by tafsiri** [comment]
@jessetrana I was thinking about this as well and it seemed that it would be advantageous to have the unified op, however at lease in the context of RN, the assumption that reading the file into memory and decoding it as two separate steps doesn't have extra overhead isn't necessarily true (in this case being able to do it in one step is likely more performant).

So far it looks like there is enough nuance per platform (browser, node, and newer ones like RN) that having separate implementations seems to be better performance wise. If doing inference from a pre-trained model it give a clear indication that one should more likely skip the nodes that do image decoding and do that in a way that best suits the platform. As we actually implement more of these we will have a better handle on performance and may eventually unify it. But at the moment that doesn't seem to be the case.

Are you in a situation where you are trying to reuse code across the difference platforms and this is causing issues? To your comment about performance, in the current scheme we let the browser itself to the decoding, that is pretty much always going to be faster than doing decoding in JS.

**Comment by jessetrana** [comment]
Thanks @tafsiri for taking the time to talk through the issues.

Regarding my use case, I have been developing a Firefox plugin that does NSFW content filtering fully client-side. In fact, I just made a dedicated GitHub account as @wingman-jr-addon so you may see me posting under that moniker more often now.

So with respect to that use case, I do target different at least different desktop OS's. I have not yet seen OS-dependent issues arise. In my case I view all of the work from "I have a byte array" to "I can predict on the right size image" as essentially one holistic step (you can see related comments over #294 for this recently). This step occurs hundreds or thousands of times on say, a typical Pinterest viewing session, so I care about performance quite a bit.

Consider the different options I might have:

1. Load raw bytes into tensor (medium size transfer to GPU?), decompress/decode using decode_image directly to a tensor (relatively fast?), resizeBilinear (fast, remains on GPU, consistent across platforms), predict.
2. Load raw bytes into Blob/Object URL (medium size), decode using JS Image() (fast, native, probably transfer to GPU), fromPixels (large size transfer to GPU?, particular since this routes via a Canvas as described in #294), resizeBilinear (fast, remains on GPU, consistent across platforms)
3. Load raw bytes into Blob/Object URL (medium size), decode using JS Image() (fast, native, probably transfer to GPU), drawImage with resize to Canvas (fast, possible platform-inconsistent resize strategy), fromPixels (fast, smaller transfer to GPU because ImageData is bounded)

Until recently I used option 2. This is likely the most accurate method currently available; I've seen what even small image resizing differences can do to reproducibility for e.g. OpenNSFW. However, I've augmented my model enough that I'm willing to go with option 3 (as described in #294)  despite possible issues with reproducibility because the performance is just that much better.

However, I began to realize that option 1 might be a possibility. I'd worry that GPU memory usage might bloat as images initially get loaded, but I have to imagine that the transfer of the image *while compressed* to the GPU and then decompressing it there straight into a tensor might work out reasonably well. I'm assuming that if the decoding is done as primarily GPU work via ops that JS simply doesn't play into the performance of this step that much? Then it keeps from having to draw onto a Canvas yet again, and the resize now happens in the more strictly reproducible world of resizeBilinear.

I detail this out because it seems that while decode_image may be slower as a single part, it is possible that in aggregate it is faster when taking the use case as a whole, and it helps promote usage of resizeBilinear for more consistent results.

Now I realize that my use case is not the same as everybody else's, nor is perhaps even typical. However, it does seem likely to me that a general path of image loading and preprocessing for inference on a finetuned Mobilenet, etc. is going to be a recurring use of this library. What usage patterns are you seeing around this path right now? Are most cases starting with a byte array or an already loaded HTMLImageElement?

Thanks for your time and for thinking about this feature.
