### ISSUE TITLE
how to pruning model with tfjs?

### ISSUE THREAD

**Issue by aohan237** [tensorflow/tfjs#2080]
for example. if i use tensorflow object detection api, and transfer python models to tfjs.
tfjs-conveter can quantize the model with extreme 4 times smaller. but it compressed version is still about 15m size, which is too large for js model, and requires more time.

so, i wonder if there is any thing like keras_prunning(https://www.tensorflow.org/model_optimization/guide/pruning/train_sparse_models)  tools , so we can make the model compressed size smaller ,like 2m size or  4m size.

**Comment by pyu10055** [comment]
@aohan237 You are right about the keras prunning API, it has the potential to reduce the model size up to 6 times, and in combination with quantization it can achieve 24x size reduction.
But here what you can do:
1. use the keras prunning API to retrain your model and set the matrix sparsity to 85-90%, this would make many weight to 0.
2. and quantize the model to 8 bit. (reduce the model size to 1/4)
3. when you serving your model on your http server, make sure to use compression (i.e. gzip). Since 85-90% of the model is zero, it can be compressed very well. (close to 6x) Browse support unzip directly, this should be transparent to your javascript code.

**Comment by aohan237** [comment]
@pyu10055  thanks for your response.
here is the problem.i use the tensorflow object detection api `https://github.com/tensorflow/models/tree/master/research/object_detection` ,which i can use my own dataset for training. the model seems to be written without keras api, so if i want to do step 1, i maybe will have to implement the model again.

so is there any solution about this?

**Comment by pyu10055** [comment]
I believe the model is being migrated to keras implementation, but meanwhile there are several external object detection models that is implemented using keras, maybe you can give those and pruning API a try. It would be great if you can share your experiences with us. Thanks.

**Comment by pyu10055** [comment]
actually the object detection has keras implementation now, here is the link
https://github.com/tensorflow/models/blob/fe748d4a4a1576b57c279014ac0ceb47344399c4/research/object_detection/models/ssd_mobilenet_v2_keras_feature_extractor.py

**Comment by aohan237** [comment]
@pyu10055  thank you very much.  i did not find it before.

i will check the model if the model will be effective ,if with keras prunning.

i will share more infomation if any thing i think important.
