### ISSUE TITLE
add `meshgrid` function

### ISSUE THREAD

**Issue by silky** [tensorflow/tfjs#2111]
would be nice to have an equiv of `tf.meshgrid` in python tensorflow.

**Comment by rthadur** [comment]
@silky  can you please tell us your use case ?

**Comment by silky** [comment]
```
  x = tf.linspace(-1, 1, w);
  y = tf.linspace(-1, 1, h);

  const xx = tf.matMul( tf.ones  ([h, 1]), x.reshape([1, w]) )
  const yy = tf.matMul( y.reshape([h, 1]), tf.ones  ([1, w]) );
```

vs. `xx, yy = tf.meshgrid(x, y)`

**Comment by hoechenberger** [comment]
Hello @rthadur, I see you closed this issue. Does this mean the feature was implemented? Or that it is *not* going to be implemented, after all? Or that there is a good alternative to achieve the desired behavior? Thank you very much!

**Comment by hoechenberger** [comment]
Friendly ping @rthadur :)

**Comment by DCtheTall** [comment]
@rthadur I am interested in trying to implement this, if you're still accepting contributions 😄

**Comment by rthadur** [comment]
@DCtheTall please go ahead , thank you.

**Comment by DCtheTall** [comment]
@rthadur I handled the 2D case since JS doesn't let you have kwargs after variable-length argument parameters like Python and to keep the scope of the PR simple at first.

I added unit tests based on [NumPy's unit tests](https://github.com/numpy/numpy/blob/cb557b79fa0ce467c881830f8e8e042c484ccfaa/numpy/lib/tests/test_function_base.py#L2222) since the Python TensorFlow tests just compare the output to NumPy's implementation.
