### ISSUE TITLE
Remove tf.ENV

### ISSUE THREAD

**Issue by nsthorat** [tensorflow/tfjs#2124]
tf.ENV is a global mutable object that is exported from the module. This isn't allowed in ES2015 semantics and thus closure has problems with it.

Let's remove this in favor of tf.environment().

**Comment by rthadur** [comment]
@nsthorat i see the PR got merged , can we close this issue or is there more request coming through ?

**Comment by nsthorat** [comment]
The PR that got merged is just introducing tf.env(), we won't be able to remove tf.ENV until we want to make a breaking change for TensorFlow.js 2.0 so let's keep this open.

**Comment by rthadur** [comment]
sure , thanks for confirming

**Comment by gaikwadrahul8** [comment]
Hi, @nsthorat 

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFJs team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TFJs [version](https://github.com/tensorflow/tfjs/releases/tag/tfjs-v4.10.0) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tfjs/blob/master/README.md) to stay up to date with the latest developments which are happening in the Tensorflow.js space.

Thank you for your support and cooperation.
