### ISSUE TITLE
In Node, the number of shards change after saving.

### ISSUE THREAD

**Issue by Neuroforge** [tensorflow/tfjs#2127]
To get help from the community, we encourage using Stack Overflow and the [`tensorflow.js`](https://stackoverflow.com/questions/tagged/tensorflow.js) tag.

#### TensorFlow.js version

The latest version from npm.
    "@tensorflow/tfjs-node": "^1.2.9"

#### Browser version
N/A

#### Describe the problem or feature request

When loading a model (loadLayersModel) takes a model config.json and weight.bin files.  Initially, the model has 9 shards.  When i load this same tensorflowjs model in nodejs and then save to disk, there is only 1 shard file.  Is there a way to maintain the number of shards?

#### Code to reproduce the bug / link to feature request
If you would like to get help from the community, we encourage using Stack Overflow and the [`tensorflow.js`](https://stackoverflow.com/questions/tagged/tensorflow.js) tag.

Using a multi-shard file, it would be possible to see this result using the following code snippet.

```
const tf = require("@tensorflow/tfjs-node");

let modelDir = "./test/img/model_0/";
tf.loadLayersModel("http://localhost:4200/assets/modeljs/model_0/model.json").then(newModel =>{
	const saveResults = newModel.save("file://" + modelDir).then(()=>{
		console.log("This has been saved.");
	}).catch(err =>{
		console.log(err);
	});
}).catch(err =>{
	console.log(err);
});

```

<img width="906" alt="Screen Shot 2019-10-02 at 2 55 38 PM" src="https://user-images.githubusercontent.com/1474186/66019113-3e1ab880-e525-11e9-8637-f3f3026d0f4f.png">

GitHub issues for this repository are tracked in the [tfjs union repository](https://github.com/tensorflow/tfjs/issues).

Please file your issue there, following the guidance in [that issue template](https://github.com/tensorflow/tfjs/blob/master/ISSUE_TEMPLATE.md).

**Comment by Neuroforge** [comment]
Any update on this issue?

**Comment by wingman-jr-addon** [comment]
Well, `tensorflowjs_converter` seems to call this out as expected behavior and indicates that might be one reason to use tfjs_layers_model-to-tfjs_layers_model conversion.

> The tfjs_layers_model-to-tfjs_layer_model conversion option serves the following purposes:
>
>    It allows you to shard the binary weight file into multiple small shards to facilitate browser caching.
> This step is necessary for models with large-sized weights saved from TensorFlow.js (either browser  or Node.js), _because TensorFlow.js puts all weights in a single weight file ('group1-shard1of1.bin')_

See [https://github.com/tensorflow/tfjs/tree/master/tfjs-converter](https://github.com/tensorflow/tfjs/tree/master/tfjs-converter). I'm not sure it preserves the original shard sizes, though, as it seems to split based on size.

I suppose you could possibly round trip back to .h5...

**Comment by wingman-jr-addon** [comment]
@Neuroforge Any luck? My reading leads me to believe that this is expected behavior. This issue has been tagged as support, so perhaps if you feel strongly about it you can enter an issue wording this as a new feature request and it can be addressed that way. If you go that route, it might also be good to list your use case too so others can see why you are wanting it to work this way.
