### ISSUE TITLE
Feature request: `tf.spectral.fft2d`

### ISSUE THREAD

**Issue by bourdakos1** [tensorflow/tfjs#2130]
A 2-dimensional fft would be helpful for some image processing use-cases. One example would be for object tracking. I can work on adding this op.

**Comment by gaikwadrahul8** [comment]
Hi, @bourdakos1 

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFJs team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TFJs [version](https://github.com/tensorflow/tfjs/releases/tag/tfjs-v4.10.0) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tfjs/blob/master/README.md) to stay up to date with the latest developments which are happening in the Tensorflow.js space.

Thank you for your support and cooperation.
