### ISSUE TITLE
tf.io.serialization.register() should warn or throw on duplicate registration of classes under the same name

### ISSUE THREAD

**Issue by caisq** [tensorflow/tfjs#2175]
To get help from the community, we encourage using Stack Overflow and the [`tensorflow.js`](https://stackoverflow.com/questions/tagged/tensorflow.js) tag.

#### TensorFlow.js version
1.2.11

#### Describe the problem or feature request
Context: see https://github.com/tensorflow/tfjs/issues/2170. Two classes got registered under the same name, causing trouble.

The register() method should at least print a warning when this happens. The reason why we are hesitant to let this throw an error is that some users may accidentally depend on two different versions of tfjs-layers in the same app. But there can be a flag that gets turned on in tests, which causes duplicate registrations to throw an error.

**Comment by gaikwadrahul8** [comment]
Hi, @caisq 

Apologize for the delayed response and we are re-visiting our older issue and checking whether have we resolved this issue or not so May I know have we resolved this issue or still are we working on this issue please ?

Could you please confirm if this issue is resolved for you ? Please feel free to close the issue if it is resolved ? Thank you!
