### ISSUE TITLE
how to clean up memory? aka "what does tf.tidy do?"

### ISSUE THREAD

**Issue by silky** [tensorflow/tfjs#2204]
using tfjs 1.0.0, here's my code:

```
<html>
<head>
  <meta charset="utf-8">
  <script type="text/javascript" src="js/tf.min.js"></script>
</head>
<body>
<h1> tfjs Memory Test </h1>
<script type="text/javascript">
  function buildModel () {
    var m = tf.linspace(-1, 1, 200);
    return m;
  }

  function go () {
    tf.tidy( () => buildModel() );

    console.table( tf.memory() );
  }

</script>
<button onclick="javascript:go()">Test</button>
</body>
</html>
```

and here's the result of clicking the button twice:

![image](https://user-images.githubusercontent.com/129525/66813251-29580f00-ef80-11e9-808a-d4d39312ee6d.png)

note that the memory is increasing. 

why?

how can i dispose this memory? 

i'm asking because i've got a more complicated model, and none of the dispose methods i'm trying really works. i think i'm missing something fundamental?

**Comment by DirkToewe** [comment]
Hi @silky,
this question would be better suited for the [Stackoverflow support page](https://stackoverflow.com/questions/tagged/tensorflow.js?tab=Newest). The behavior, You describe, is actually a feature not a bug.

`tf.tidy` is very similar to the local variable scope of a standard JS function. When a JS function returns, all local objects are garbage collected unless references to those local objects were passed to it's environment, e.g. by returning the object as return value of the function. Unlike usual JS objects, the resources behind TFJS tensor objects are not garbage collected automatically. The reason for that is that garbage collection did/does not work that well with WebGL.

In order to release the resources you could just manually call [`Tensor.dispose`](https://js.tensorflow.org/api/0.11.2/#tf.Tensor.dispose) for every single tensor that You create. That is however incredibly tedious and prone to error. That's where [`tf.tidy`](https://js.tensorflow.org/api/0.11.2/#tidy) comes into play. If You execute `tf.tidy(f)` for some function `f`, said function is executed exactly once. Every tensor that was created during the call to f is automatically disposed of by `tf.tidy` *with the exception* of the tensors returned by f, which are returned by `tf.tidy` as well, i.e. passed on to the caller of `tf.tidy`. So looking at Your example:

```js
function go () {
  const myModel = tf.tidy( () => buildModel() );
  console.table( tf.memory() );
}
```

What's happening is that the value returned by buildModel() has not been disposed by `tf.tidy` but returned instead. To fix this several different things can be done:

  * Make the function inside of `tf.tidy` not return any Tensor:
    ```js
    tf.tidy( () => { buildModel(); return undefined; } )
    ```
  * Use another nesting/encapsulating call to `tf.tidy`:
    ```js
    tf.tidy( () => {
       const myModel = tf.tidy( () => buildModel() );
       // ... do something with myModel ...
    })
    ```
  * Dispose of `myModel` manually (not recommended):
    ```js
    const myModel = tf.tidy( () => buildModel() );
    try {
      // ... do something with myModel ...
    }
    finally {
      myModel.dispose()
    }
    ```

You can read more about memory management in TFJS [here](https://www.tensorflow.org/js/guide/tensors_operations#memory).

**Comment by silky** [comment]
i like it

thanks for the thoughtful response @DirkToewe !

**Comment by EddieOne** [comment]
I also found this useful.
https://stackoverflow.com/a/59934467/654499
