### ISSUE TITLE
BodyPix 2.0 - change internalResolution to use a percentage instead of hardcoded resolutions

### ISSUE THREAD

**Issue by oveddan** [tensorflow/tfjs#2245]
With PR [#321](https://github.com/tensorflow/tfjs-models/pull/321) - the new internalResolution parameter is passed at inference time, which is great.  However, the fact that `low` `medium` `high` are tied to corresponding values of `257`, `513`, and `1025` is problematic for a few reasons:

* It will force the image to be resized to a square, causing black pixels to be added in the smaller dimension, which means those pixels will be fed through the network causing an uncessary slowdown in performance.  Similar to this issue from before #1844 
* If a user is new to the api, and they lets say pass a webcam video of 640x480, and they want a "high" resolution - the image will then be resized up to 1025, making inference super slow.  They no longer have an option of using the image in its original resolution of 640x480.   A new user would not realize, without looking at the code, that internally its resized up to that resolution.
* if a user want to do inference on 1080p images, this is no longer an option.  It will be resized down to 1025.

A much better approach would be to map low/medium/high to percentages, let's say 25/50/100 %.  And internally the image is resized while maintaining the original aspect ratio.

**Comment by nsthorat** [comment]
I think we can solve the issues above but keep the current API (which I like better because 'low', 'medium', 'high' are much easier to understand than a fixed number):

- We can find an aspect ratio for the model that is nearest to the requested resolution.
- That's a good point. We shouldn't use an internal resolution larger than the image provided.
- `internalResolution` also allows passing a number, not just 'low', 'medium', 'high'.

**Comment by oveddan** [comment]
Yeah I think the concept of `high` `middle` `low` is great.  Just internally if we map to percentages would be the best way.

**Comment by oveddan** [comment]
I didn't realize that this also takes a number.  Closing!  Will open a separate issue around the aspect ratio
