### ISSUE TITLE
Document saving / loading Keras models with custom layers.

### ISSUE THREAD

**Issue by bileschi** [tensorflow/tfjs#254]
To get help from the community, check out our [Google group](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs).

#### TensorFlow.js version
0.10.2

#### Browser version
any

#### Describe the problem or feature request
If a user creates a custom layer, such as the one in [this example](https://github.com/tensorflow/tfjs-examples/pull/61#issuecomment-382043495), then any model which includes this layer is no longer serializable.

**Comment by oeway** [comment]
Hi, I am looking for this feature too. 

Just checked the code, how about do the following to allow pass a `customObjects` dict to loadModel?
What we need to do is:
1. add a parameter `customObjects` to `loadModel` [src/models.ts#L187](https://github.com/tensorflow/tfjs-layers/blob/367c353454eeb651d8d8f5b64a68178fb77f7d4c/src/models.ts#L187) and `loadModelInternal` [src/exports.ts#L158](https://github.com/tensorflow/tfjs-layers/blob/367c353454eeb651d8d8f5b64a68178fb77f7d4c/src/exports.ts#L158)

2. pass `customObjects` to [src/models.ts#L202](https://github.com/tensorflow/tfjs-layers/blob/367c353454eeb651d8d8f5b64a68178fb77f7d4c/src/models.ts#L202)

**Comment by caisq** [comment]
@tafsiri Will look into incorporating an example such as https://codepen.io/caisq/pen/jdBgwB in the new documentation.

**Comment by chenqing** [comment]
> @tafsiri Will look into incorporating an example such as https://codepen.io/caisq/pen/jdBgwB in the new documentation.

```
Uncaught (in promise) TypeError: tf.loadModel is not a function
    at main (pen.js:93)
```
just update tf.loadModel -> tf.loadLayersModel.

**Comment by sdll** [comment]
@tafsiri, could you please tell me whether writing a custom layer implementation still does not work with the converted keras model? What will it take to make it work?

**Comment by sdll** [comment]
In other words, is the [comment](https://github.com/tensorflow/tfjs-examples/blob/fc8646fa87de990a2fc0bab9d1268731186d9f04/custom-layer/custom_layer.js#L31) still valid for something like EfficientNet converted from the Keras implementation with [custom layers](https://github.com/qubvel/efficientnet/blob/master/efficientnet/layers.py)?

**Comment by tafsiri** [comment]
@sdll By converted keras model, do you mean converting a model with a (pytnon) lambda layer? If so there is an issue related to that [here](https://github.com/tensorflow/tfjs/issues/283). I'm not sure how possible it will be to do that but pinging the folks assigned on that issue might be a good way to get an update.

This issue was for saving a model written in JavaScript with a custom layer. Is that what you were thinking of?

**Comment by sdll** [comment]
@tafsiri, sorry for the confusion. In my case, custom layers subclassed from python `keras.layers` did not convert to a working model, which seems obvious in retrospect, since the converter does not translate layer specifications. I was thinking of writing the missing infra in `tf.js`, but the solution turned out to be simpler: porting the Keras implementation to tf.keras and converting to tf.SavedModel instead of keras hdf5. Thanks for your support!

**Comment by bionicles** [comment]
Hi, we use custom layers and “add loss” extensively and would like to switch from python to JavaScript. Can we save JavaScript models with custom layers?

**Comment by rthadur** [comment]
@bionicles yes you can use and also there is a detailed explanation from @caisq [here](https://github.com/tensorflow/tfjs/issues/674)  , will be closing this and track the same in #674.
