### ISSUE TITLE
Adding live demo for MobileNet

### ISSUE THREAD

**Issue by toncic** [tensorflow/tfjs#2699]
#### TensorFlow.js version
    "@tensorflow-models/mobilenet": "^2.0.4",

#### Browser version
NA
#### Describe the problem or feature request
Hello everyone, I tried to find an easy way to test how  [MobileNet](https://github.com/tensorflow/tfjs-models/tree/master/mobilenet)  will classify my image, but I couldn't find any live demo or something similar that can help me.

#### Code to reproduce the bug / link to feature request

I have created a simple demo with React for this purpose which can be found [here](https://github.com/toncic/Image-Classification)
If this makes sense and if it can be helpful for the community I can deploy it somewhere and add more features to make it even more helpful.

Hope someone will find time to take a look at this simple demo and give me some feedback.

**Comment by tafsiri** [comment]
Hi @toncic, Since this is not a bug, this is not the best place to post this. Please post this to the [community mailing list](https://groups.google.com/a/tensorflow.org/g/tfjs) if you are interested in wider community feedback. Personally I would also suggest you just deploy the demo somewhere to make it easier for people to see without needing to do any setup. You could try setting it up on [glitch.com](https://glitch.com/) or a similar platform.
