### ISSUE TITLE
[tfjs-react-native] and managed Expo workflows

### ISSUE THREAD

**Issue by robsco-git** [tensorflow/tfjs#2729]
With, `@tensorflow/tfjs-react-native@0.2.1`, `tfjs-react-native` is using `react-native-fs` for the [bundleResourceIO](https://github.com/tensorflow/tfjs/blob/90f52ddb341d5079925af81000edfe845e40774a/tfjs-react-native/src/bundle_resource_io.ts#L21) function. To the best of my knowledge, managed `Expo` workflows do not work with `react-native-fs`, instead, the recommended path is to use [expo-file-system](https://docs.expo.io/versions/latest/sdk/filesystem/). Attempting to run a managed Expo app results in this error at runtime: `TypeError: null is not an object (evaluating 'RNFSManager.RNFSFileTypeRegular')`.

To work around this, I [forked the repo](https://github.com/robsco-git/tfjs/tree/expo-react-native),  and changed the bundle loading code into a stub. I [published this code to NPM](https://www.npmjs.com/package/tfjs-react-native-expo-fix), installed it and ran it successfully in the context of a managed Expo workflow. I managed to get the [example realtime demo](https://github.com/tensorflow/tfjs/blob/master/tfjs-react-native/integration_rn59/components/webcam/realtime_demo.tsx) working.

Based on the [README](https://github.com/tensorflow/tfjs/blob/master/tfjs-react-native/README.md), it appears that managed Expo workflows are within the set of project types supported by `tfjs-react-native`, hence this issue.

**Comment by tafsiri** [comment]
Yep will be looking into an alternative that will work with the managed workflow. Thanks for reporting.

**Comment by jgough99** [comment]
@robsco-git I am having exactly the same issue so I am excited to see you have published a work around. However I am struggling to get tfjs-react-native-expo-fix to work with my project since I am getting many errors. Could you give some advice on how to use this fix please? Does it need to be imported? Do you still need to install the non-fixed tensoflow? Many thanks.

**Comment by MichaelMcNeil** [comment]
@jgough99  same. @robsco-git what's the workflow to run with your fix rn?

**Comment by tafsiri** [comment]
This was autoclosed by a PR, but the release including it should come out shortly.

**Comment by MichaelMcNeil** [comment]
@tafsiri thank you! I was a little mixed up after re-testing when I saw this closed. Looking forward to it!

**Comment by tafsiri** [comment]
0.2.2 is out on NPM https://www.npmjs.com/package/@tensorflow/tfjs-react-native @robsco-git @jgough99 @MichaelMcNeil, give it a whirl and let me know if it doesn't solve the issue.

**Comment by robsco-git** [comment]
@tafsiri I've just had a chance to try it out and it appears to be working well on both Android and iOS in our managed Expo workflow! Thanks a million.

**Comment by tafsiri** [comment]
Yes, once the component is unmounted the generator will be exhausted and this is expected behaviour. Another way to not have the null check is to cancel the requestAnimationFrame of this parent component. This is how i handled it in the updated demo https://github.com/tensorflow/tfjs/blob/master/tfjs-react-native/integration_rn59/components/webcam/realtime_demo.tsx#L126
