### ISSUE TITLE
Add tf.enablePackedDepthwiseConv()

### ISSUE THREAD

**Issue by annxingyuan** [tensorflow/tfjs#2821]
We need to add a global function `tf.enablePackedDepthwiseConv`, analogous to `tf.enableDebugMode`, that flips the value of `WEBGL_PACK_DEPTHWISECONV`.

This will be useful for models that use depthwiseConv and could benefit from the speedup of packed depthwiseConv and do not trigger numerical issues reported in https://github.com/tensorflow/tfjs/issues/1679

**Comment by Sahil-Sayyed** [comment]
tf.enablePackedDepthwiseConv(); i added this but its stuck at evaluateFlag

**Comment by annxingyuan** [comment]
Hey @mattsoulanille ! For context, this would be used in places like https://github.com/tensorflow/tfjs-models/blob/master/face-landmarks-detection/src/mediapipe-facemesh/index.ts#L320

**Comment by gaikwadrahul8** [comment]
Hi, @annxingyuan 

Thank you for opening this issue for tracking purposes. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFJs team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TFJs [version](https://github.com/tensorflow/tfjs/releases/tag/tfjs-v4.12.0) with the latest compatible hardware configuration which could potentially resolve the issue.

Based on our internal discussion, we are closing this issue at this time. If you still feel that this feature request is relevant, please feel free to create a new issue.

Thank you for your support and cooperation.
