### ISSUE TITLE
tfjs-node should avoid DOM types

### ISSUE THREAD

**Issue by amitport** [tensorflow/tfjs#2835]
To get help from the community, we encourage using Stack Overflow and the [`tensorflow.js`](https://stackoverflow.com/questions/tagged/tensorflow.js) tag.

#### TensorFlow.js version
`tfjs-node@1.6`
#### Browser version
NA `node@12.16` `typescript@3.8`
#### Describe the problem or feature request
without including dom libraries, running typecript on nodejs
(only using lib: ['ES2020'] and `@types/node`) we get:

```
packages/example/node_modules/@types/node-fetch/index.d.ts:18:27 - error TS2307: Cannot find module 'form-data'.

18 import FormData = require('form-data');
                             ~~~~~~~~~~~

packages/example/node_modules/@types/offscreencanvas/index.d.ts:10:22 - error TS2304: Cannot find name 'CanvasImageSource'.

10     drawImage(image: CanvasImageSource | OffscreenCanvas, dx: number, dy: number): void;
```
etc

**Comment by gaikwadrahul8** [comment]
Hi, @amitport 

Apologize for the delayed response and I found similar issue on stack-overflow so I would request you to please refer those [answers](https://stackoverflow.com/questions/37548734/tsc-throws-ts2307-cannot-find-module-for-a-local-file) and check whether this issue is resolving for you or not ? If not please let us know with error log and please make sure that try with latest version of `@tensorflow/tfjs-node@4.4.0`. Thank you!

**Comment by amitport** [comment]
The answers in the links are unrelated. 

It's been 3 years.

There is an obvious workaround (just include dom types) and beyond that, no need to fix the issue as far as I'm concerned.
