### ISSUE TITLE
Activation serialization in production mode minified

### ISSUE THREAD

**Issue by atanasster** [tensorflow/tfjs#288]
When I have 6.0.1 installed, the model.getConfig() serializes the activation function as a single letter character.
ie: 
```
"className": "LSTM",
      "config": {
        "units": 4,
        "activation": "p", <- this is sigmoid
        "useBias": true,
        "kernelInitializer": {
          "className": "VarianceScaling",
```

the same code on 5.6.0:
```
className": "LSTM",
      "config": {
        "units": 4,
        "activation": "sigmoid",
        "useBias": true,
        "kernelInitializer": {
          "className": "VarianceScaling",
```

similar for other activation functions. `"activation": "linear",` -> `"activation": "f",`

**Comment by davidsoergel** [comment]
Which package are these version numbers referring to?

**Comment by atanasster** [comment]
thanks @davidsoergel for looking into this:
`npm -v @tensorflow/tfjs`

**Comment by atanasster** [comment]
oops, you are right, haven't been sleeping much the last couple of days. Actually I have the same version @tensorflow/tfjs@0.10.3 both on the server and client. No idea what other lib could be the reason, I am mostly synced with my heroku server.

It might help to try it out yourself for this and the issue for WebGL, here is a link to the site:
https://crypto-grommet.com/models/playground
I have removed the check for Safari, so it should fail running the default model with LSTM
If you do run a model (ie on Chrome) and go to history, and then click on expand button, it gives the getConfig of the full model.

**Comment by atanasster** [comment]
another difference I can think of is that the heroku server does not have a GPU, while my dev is a MacBook Pro with a GPU. no idea why this could affect getConfig

**Comment by davidsoergel** [comment]
Let's back up a couple of steps.  What are these two environments?  On your local dev machine, I imagine you build your app with webpack and then load up the resulting html+js in a browser, so TF.js is part of the bundle and runs in the browser.  On the Heroku side, you're rebuilding the app on the server, as opposed to just statically hosting the webpacked app?  Is there some magic happening whereby the TF.js part runs on the Heroku server under Node, not in the browser?

Since there seems to be a mysterious difference, let's a) consider whether you really need two different build environments at all, and b) wipe out node_modules and rebuild from scratch to be sure everything is in sync and up to date.  You can diff the two package_lock.json files (or yarn.lock, if using yarn instead of npm) to be sure there's no discrepancy.

**Comment by ericdnielsen** [comment]
Activations use a different code path for serialization than just about anything else, and this sounds like a minification problem.

**Comment by atanasster** [comment]
Sorry, I didnt give enough background.
I am building with nextjs(webpack is under the covers) and on my local machine in dev mode and with nextjs with hot reloading
On the server, I am using a production build and then serving from a nodejs 10.0 server
@ericdnielsen might be onto something with the minification

**Comment by atanasster** [comment]
and the shortened names seem consistent - always 'p' for sigmoid, 'f' for linear etc.

**Comment by ericdnielsen** [comment]
Working on a fix, but probably won't have it until next week.

**Comment by atanasster** [comment]
Thanks, since we are just reporting issues here, wanted to tell evveryone what a fantastic job you have done. Its a game changer and is very much appreciated

**Comment by ericdnielsen** [comment]
Fix has been merged:
https://github.com/tensorflow/tfjs-layers/pull/176
