### ISSUE TITLE
Using the video frames as a texture in tf.fromPixels without canvas element

### ISSUE THREAD

**Issue by chaosmail** [tensorflow/tfjs#294]
#### TensorFlow.js version

master

#### Describe the feature request

I was looking for a way to feed video frames into tfjs without sampling from the video element manually through canvas. According to this [MDN Tutorial Animating_textures_in_WebGL](https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API/Tutorial/Animating_textures_in_WebGL#Using_the_video_frames_as_a_texture) it should be possible by binding the HTMLVideoElement to the `gl.texImage2D` directly.

Here is a shortened snippet from the linked MDN page:

```
const video = document.createElement('video');
...
gl.texImage2D(gl.TEXTURE_2D, level, internalFormat, srcFormat, srcType, video)
```

I am not sure if this is implemented or if you have discussed this internally already. However, when looking at the `tf.fromPixels` GPU implementation in the [current master branch](https://github.com/tensorflow/tfjs-core/blob/2c9b9a0c09053b09dd04c098ea8179d06dddc06f/src/kernels/backend_webgl.ts#L109)  it seems that you read the HTMLVideoElement data via canvas.

Would be really great to have this feature in tfjs ;)

Best, Christoph

**Comment by nsthorat** [comment]
You can pass an HTMLVideoElement directly to tf.fromPixels!

**Comment by davidsoergel** [comment]
Whoops I had misunderstood the question.  Looks like all is well then!  @chaosmail, please reopen if this doesn't solve your problem.  Thanks!

**Comment by davidsoergel** [comment]
No wait, @chaosmail is right-- the implementation copies the video frame to a canvas in order to then read it into a texture, and it looks like that extra step my be avoidable (at least in some browsers?).

**Comment by nsthorat** [comment]
Oh great point. I don't remember why we did this, this changed recently when we added a FromPixelsProgram. Daniel wrote this code so we should ask him when he gets back unfortunately, I'm sure there was a good reason since it was added explicitly.

@dsmilkov for your pile of email when you get back from vacation ;)

**Comment by wingman-jr-addon** [comment]
Thanks for prioritizing and working on this - I just discovered today that HTMLImageElement takes the same path and was drawing onto a canvas. Prior to today, my code would load into an Image() and then rely on tf.resizeBilinear before feeding into a MobileNetV2 based network. However, after seeing the code I decided to instead take the Image and do a drawImage with resize and pass in an ImageData instead. The performance difference was dramatic. (Yes, I'm aware that I may run into issues around not as strictly handling preprocessing - this is not the right choice for everyone, but is working ok for me.)

I'm excited to see how this ends up being fixed/extended! Thanks!

**Comment by wingman-jr-addon** [comment]
Sure! Thanks for looking into this. Please note that I am also @jessetrana and have just started posting under this account for my plugin.

I used to have something like this where I pulled in the Image element and then did a resizeBilinear:
https://github.com/wingman-jr-addon/wingman_jr/blob/e68048de958c143398ffb8a9f050b9b96a065a92/background.js#L119

However, after observing that an Image gets drawn to a Canvas I now draw it myself with the resize overload like this:
https://github.com/wingman-jr-addon/wingman_jr/blob/7906906ddb2c775b8ecea45e8a344cb05e55a045/background.js#L125

Over on #2071 I am noting that, in my specific case, it may or may not actually be better to skip creating an `<img>` element and do something like image_decode -> resizeBilinear since I'm starting with a byte stream. I also don't particularly trust the browser implementation of Canvas resize to be bilinear.

Let me know if you need anything else and thanks for taking a peek at this. My use case involves regularly loading hundreds of images in one session so I care about this performance story a lot!

**Comment by wingman-jr-addon** [comment]
@dsmilkov Did you need any further clarification on the code samples etc?

**Comment by dsmilkov** [comment]
Sorry for the long delay on this one. We used to feed `VideoElement` directly to `texImage2D` but we had a problem that the actual pixel values are slightly different then when you read from a canvas.

This means that we get numerically different results when running webgl vs cpu vs wasm. For these reasons we decided to always feed into intermediate canvas which leads to consistent pixel values, at the cost of speed.

I'm going to close this issue since we don't have plans to address this in the near future, but feel free to comment with use-cases where you find `fromPixels` being a bottleneck, which will help revisit this in the future
