### ISSUE TITLE
Support tf.fromPixels in Node.

### ISSUE THREAD

**Issue by nsthorat** [tensorflow/tfjs#298]
Right now we fail when checking the instance of pixels because ImageData is not defined.

See https://groups.google.com/a/tensorflow.org/d/msgid/tfjs/ef1bfe7f-128c-4c6c-bfa2-f462ebe2ffa5%40tensorflow.org

**Comment by dsmilkov** [comment]
I can take this on! (tomorrow)

**Comment by dijs** [comment]
This would be a big win!

**Comment by roieki-maana** [comment]
Would love to help @dsmilkov!

**Comment by roieki** [comment]
Would love to help @dsmilkov !

**Comment by alienatorZ** [comment]
I would love this!

**Comment by roieki** [comment]
The implementation looks great, I tested it out with ‘canvas’ and it seems to work, meaning I can create a valid looking tensor from an image. Using node canvas for this purpose seems straightforward and reasonable. Thank you for getting this done!

On another note, I’ve been seeing a different issue that might be related to this. I mentioned it another thread where the issue was already mentioned, albeit in a different context: 

https://groups.google.com/a/tensorflow.org/d/msg/tfjs/wsTuFcSVLfQ/U-UXrwTzAwAJ

Again - thanks for the blazing fast response.

**Comment by roieki-maana** [comment]
Hi Daniel,

The implementation looks great, I tested it out with ‘canvas’ and it seems to work, meaning I can create a valid looking tensor from an image. Using node canvas for this purpose seems straightforward and reasonable. Thank you for getting this done!
On another note, I’ve been seeing a different issue that might be related to this. I mentioned it another thread where the issue was already mentioned, albeit in a different context: https://groups.google.com/a/tensorflow.org/d/msg/tfjs/wsTuFcSVLfQ/U-UXrwTzAwAJ

Roie Schwaber-Cohen
Senior Open Source Engineer • Technology Evangelist • Maana, Inc.

On Jun 28, 2018 at 7:23 AM, Daniel Smilkov <notifications@github.com> wrote:


Hi guys,

I just added support for tf.fromPixels() in Node which will be available for use in the next release of TF.js (within a week).

Since HTMLCanvasElement/ImageData/HTMLImageElement don't exist in node, the workflow I focused on is to make sure fromPixels() can take a canvas element as the one returned by the canvas<https://www.npmjs.com/package/canvas> npm package. Let me know if you had a different workflow in mind.

Also, I made to make sure that when in node, people are using our tfjs-node<https://github.com/tensorflow/tfjs-node> backend which calls into TF C, instead of our vanilla cpu backend, which is plain JS and therefore very slow.

**Comment by Rutulpatel7077** [comment]
@dsmilkov Did you find any solution for this?
<img width="1142" alt="screen shot 2018-07-13 at 9 07 01 pm" src="https://user-images.githubusercontent.com/22271244/42719272-db7f04c2-86e0-11e8-84f3-587bfaf5bd63.png">

**Comment by lastmjs** [comment]
Yes, question here, if I have a data url, how to I get the canvas from npm to draw it? Is there a recommended image element from npm?

**Comment by dsmilkov** [comment]
```js
const {Image} = require('canvas');
const img = new Image()
img.src = ...
```

You can use the Image.src property to point to a URL. See [this section](https://github.com/Automattic/node-canvas#imagesrc) for details.

Then you can pass the image to `tf.fromPixels(img)` to make a tensor.

**Comment by Rutulpatel7077** [comment]
@dsmilkov  Thanks! I already figured out by using `node-canvas`

**Comment by samuelgoto** [comment]
Some of the TF hub's model take a [4d image](https://www.tensorflow.org/hub/common_signatures/images#input) as input ([batch_size, width, height, 3]) whereas fromPixels creates a [3d image](https://js.tensorflow.org/api/0.6.1/#fromPixels).

Would anyone know if there is a handy/easy way to transform the fromPixel to the 4d tensor?

For example, in [this](https://github.com/tensorflow/tfjs-converter#step-2-loading-and-running-in-the-browser) example:

```javascript
const model = await loadFrozenModel(MODEL_URL, WEIGHTS_URL);
const cat = // does node-canvas-ing
model.execute({input: tf.fromPixels(cat)});
```

On nodejs, this needs to be turned into a 4d tensor:

```console
Error: The shape of dict['images'] provided in model.execute(dict) must be [-1,224,224,3], but was [224,224,3]
      at Object.assert (node_modules/@tensorflow/tfjs-core/dist/util.js:35:15)
      at node_modules/@tensorflow/tfjs-converter/dist/src/executor/graph_executor.js:274:34
```

Ideas?

**Comment by dsmilkov** [comment]
Call `tf.fromPixels(cat).expandDims(0)`. See [tf.expandDims](https://js.tensorflow.org/api/0.12.5/#tf.Tensor.expandDims) API doc for details.

**Comment by DavidGOrtega** [comment]
Ideal solution would be an Image pollyfill. Have you ever watched the [instructions](https://github.com/Automattic/node-canvas/wiki/Installation---Windows) to install Canvas on Windows? I Have!

![image](https://user-images.githubusercontent.com/414967/46489693-5ff43900-c806-11e8-8bdd-01c0b45ad099.png)

**Comment by bobmoff** [comment]
Relying on canvas for this is an issue when wanting to run it on AWS Lambda. Lambdas node version is 8.10 and that specific version has a bug in it that makes canvas break :(

**Comment by nkreeger** [comment]
Stay tuned - we're working on auto-generated code which will provide a Node-specific version of `tf.image.decode_image`: https://www.tensorflow.org/api_docs/python/tf/image/decode_image

**Comment by piercus** [comment]
I was able to make it work without canvas by using [opencv4nodejs](https://github.com/justadudewhohacks/opencv4nodejs) 

```javascript
const cv = require('opencv4nodejs');
const tf = require('@tensorflow/tfjs');
require('@tensorflow/tfjs-node');

const image = 'your image path here';
const mat = cv.imread(image);
// By default opencv is working with BGR color space
// before doing getData, we need to reorganize pixel to RGB
const mat2 = mat.cvtColorAsync(cv.COLOR_BGR2RGB);
const tensor = tf.tensor3d(new Uint8Array(mat2.getData()), [width, height, 3], 'int32').expandDims(0);

net.execute(tensor);
```

**Comment by Porizm** [comment]
does this work? https://www.npmjs.com/package/image-pixels

**Comment by ydp** [comment]
Searching workaround for wasm backend, FYI, after long time experiments, I used below code to pass image into mobilenet v2 model:
```
import { get, getSync } from '@andreekeberg/imagedata'

  let img = getSync(image_name)
  const tensor = tf.browser.fromPixels({data: new Uint8Array(img.data), width: img.width, height: img.height})
    .resizeBilinear([224, 224])
    .cast('float32')
    .div(255)
    .expandDims(0)
    .toFloat();
  let model = await tf.loadGraphModel(
    'https://tfhub.dev/google/imagenet/mobilenet_v2_100_224/classification/2',
    {fromTFHub: true});

  const logits = model.predict(tensor);
```
Complete code: https://github.com/ydp/tfjs-wasm-examples/tree/main/mobilenet
