### ISSUE TITLE
Installing tensorflowjs for python disables gpu support

### ISSUE THREAD

**Issue by davodesign84** [tensorflow/tfjs#3051]
To get help from the community, we encourage using Stack Overflow and the [`tensorflow.js`](https://stackoverflow.com/questions/tagged/tensorflow.js) tag.

#### TensorFlow.js version
tensorflowjs 1.7.2 

#### Browser version
Backend only

#### Describe the problem or feature request
Using the official gpu docker container `tensorflow/tensorflow:latest-gpu-py3-jupyter`

Before installing `tensorflowjs` gpu are accessible in python
```
print("Num GPUs Available: ", len(tf.config.experimental.list_physical_devices('GPU')))
> Num GPUs Available:  1
```

After installing `tensorflowjs`
```
print("Num GPUs Available: ", len(tf.config.experimental.list_physical_devices('GPU')))
> Num GPUs Available:  0
```

#### Code to reproduce the bug / link to feature request
Ensure docker is installed and nvidia-docker is installed and running correctly.

```bash
docker pull tensorflow/tensorflow:latest-gpu-py3
docker run --gpus all -it tensorflow/tensorflow:latest-gpu-py3 bash
python
```

```python
import tensorflow as tf
tf.config.list_physical_devices('GPU')
>> [PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]
exit()
```

```bash
pip install tensorflowjs
python
```
```python
import tensorflow as tf
tf.config.list_physical_devices('GPU')
>> [ ] # The array should still contain the gpu devices

**Comment by rthadur** [comment]
@davodesign84 did you try installing tfjs-node-gpu ?

**Comment by kangyizhang** [comment]
The issue seems to be related with tfjs converter pip package. While installing tensorflowjs pip package, it will install its corresponding dependent version of tensorflow python. As listed in step 0 in the documentation (https://github.com/tensorflow/tfjs/tree/master/tfjs-converter#step-1-converting-a-tensorflow-savedmodel-tensorflow-hub-module-keras-hdf5-or-tfkeras-savedmodel-to-a-web-friendly-format), while using tensorflowjs converter pip, it should happen in its own virtual environment or docker, so that it does not cause conflict with the original tensorflow python package.

**Comment by davodesign84** [comment]
I guess this should be then mentioned on here https://www.tensorflow.org/js/tutorials/conversion/import_keras or at the very least importing the getting started guide on the main website.

Is there any specific reason why the script pulls its own tensorflow rather than using what's already on the machine?

**Comment by kangyizhang** [comment]
It is mentioned in the requirement section.

The reason is that each version of the tensorflowjs pip package depends on a specific version of tensorflow.
