### ISSUE TITLE
React Native BodyPix

### ISSUE THREAD

**Issue by QuevedoIB** [tensorflow/tfjs#3134]
Hello, I'm trying to do a BodyPix implementation with tfjs-react-native but I'm having problems with the outputs. 

The method to detect people returns https://www.npmjs.com/package/@tensorflow-models/body-pix#returns

BodyPix has another method to convert that output into ImageData https://www.npmjs.com/package/@tensorflow-models/body-pix#returns-4

I didn't find any way yet to use that ImageData in React Native environment because is browser canvas oriented output.

I'm now trying with https://www.npmjs.com/package/react-native-canvas. And draw the ImageData output into react-native-canvas with the method https://www.npmjs.com/package/@tensorflow-models/body-pix#bodypixdrawmask

```
 const handleCanvas = canvas => {
    const opacity = 0.7;
    const flipHorizontal = false;
    const maskBlurAmount = 0;

    const uri = initialImage.slice('file://'.length);

    bodyPix.drawMask(
      canvas, //canvas ref from react-native-canvas
      uri, //second argument expects html image
      imageData, //toMask output
      opacity,
      maskBlurAmount,
      flipHorizontal,
    );
  };
```
But that method expects an html img second argument I don't know how to pass it since React Native Image component/jsx doesn't seem to work.

Does anyone know how to handle BodyPix outputs in a React Native environment? I followed implementation for mobilenet of @tafsiri in https://blog.tensorflow.org/2020/02/tensorflowjs-for-react-native-is-here.html maybe can help about BodyPix implementation, thanks.

**Comment by tafsiri** [comment]
You can see what drawMask is doing [here](https://github.com/tensorflow/tfjs-models/blob/4a81af309322e356173e24b6c047bf289f1663d5/body-pix/src/output_rendering_util.ts#L353), that will give a sense of what its going to use the image for. I also saw that it takes the [following types](https://github.com/tensorflow/tfjs-models/blob/4a81af309322e356173e24b6c047bf289f1663d5/body-pix/src/output_rendering_util.ts#L25) as valid for that image. In particular since it takes canvas elements you could try rendering your original image to a canvas and pass that as the second param.

You would otherwise need to construct an Image object (not the Image component), similar to [this snippet](https://www.npmjs.com/package/react-native-canvas#image) in the react native canvas docs.

Since these rendering functions are built on browser standards, you need some kind of polyfill, or you would need to recreate the drawMask logic directly applied to the appropriate react native rendering target you want to use.

**Comment by QuevedoIB** [comment]
Thanks a lot for your reply and guidance, I've now a workaround polyfill setup that will do the trick for now based on canvas rendering.

**Comment by tafsiri** [comment]
@QuevedoIB Great to hear! What polyfill did you end up using?

**Comment by anishone** [comment]
I'm stuck with the same question now. How does your polyfill look like? Thanks both of you for pointers.

**Comment by bigdong89** [comment]
@QuevedoIB  how did you use bodypix with react native? i can't load model ....
never saw 'load end'

const bpModel = await bodyPix.load({                     
 24     ┊   architecture: 'MobileNetV1',                         
 25     ┊   outputStride: 16,                                    
 26     ┊   multiplier: 0.50,                                    
 27     ┊   quantBytes: 2                                        
 28     });    
console.error('----load end');

**Comment by StPov** [comment]
@bigdong89 try this
https://heartbeat.fritz.ai/image-classification-on-react-native-with-tensorflow-js-and-mobilenet-48a39185717c

**Comment by bigdong89** [comment]
@StPov thanks!!!!!!!!

**Comment by JakeJustLearning** [comment]
I am trying to do this as well. and I am stuck at trying to get an image in the correct format to hand to `segmentPersonParts`. How are you creating an HTML image element or imageData to hand to that bodyPix function?

**Comment by BigZ** [comment]
hello @QuevedoIB @tafsiri @JakeJustLearning @bigdong89 
did you manage to have a working react-native bodypix implementation ?
i successfully modified toMask to work with react-native-canvas and return it's implementation of imageData, but i can't do anything with this mask
cheers !
