### ISSUE TITLE
Feature request: Support of saving weights and loading weights

### ISSUE THREAD

**Issue by utkobe** [tensorflow/tfjs#3295]
####  feature request

Common frameworks will provide the api to just save weights and load weights. It seems that tfjs currently only provide model.save and tf.loadModel to save both weights and architecture.

**Comment by pyu10055** [comment]
@utkobe Thank you for the suggestions, can you explain your use case for saving/loading weight without the model topology?

**Comment by utkobe** [comment]
@pyu10055 Thanks for the reply. I have some use cases where i wish to save weights of one weights of one model and apply the weights to part of another model. These two models share part of architecture so in theory they could have same weights of this part. (Like model A is a backbone of model B)

**Comment by utkobe** [comment]
@pyu10055 Thanks for the reply. Actually i do not have use cases that must just save weights. Just would like to save less information for checkpoints or transfer if I can reconstruct topology using codes manually. :)

**Comment by pyu10055** [comment]
Since our weights require the topology file to work properly, we would like to keep them consistent. The topology file are rather small comparing to the weight file, it is usually just several kilobytes. The weight only load/save API does not provide enough benefits but might be harder for users to debug problem. Sorry, I would not recommend that API.
