### ISSUE TITLE
inconsistent results of tf.Conv2D on WebGL in PC browser and mobile browser

### ISSUE THREAD

**Issue by ducanh841988** [tensorflow/tfjs#3299]
To get help from the community, we encourage using Stack Overflow and the [`tensorflow.js`](https://stackoverflow.com/questions/tagged/tensorflow.js) tag.

#### TensorFlow.js version
1.0.0
#### Browser version
Mac browser: Version 81.0.4044.138 (Official Build) (64-bit)
Android phone: Chrome 81.0.4044.138
#### Describe the problem or feature request
the densenet like model provides different results on Mac and Android browsers.
The result on the Mac browser is correct but the result on the Android browser is incorrect.
When I add tf.ENV.set('WEBGL_CONV_IM2COL', false); the result on the Android browser is correct but the speed is very slow. It seems that it is correct on cpu but incorect on WEBGL.
I need the tf.Conv2D runs correctly and fastly on WebGL for mobile devices.
Could you help me to solve this problem.

#### Code to reproduce the bug / link to feature request
This is the model that I used. [M1](https://drive.google.com/file/d/13VFQn1Gr6O9XDRFlG2a7lwW65VMojY_a/view?usp=sharing)
The tmp_out node is where the model provides different results on Mac and Android devices.

If you would like to get help from the community, we encourage using Stack Overflow and the [`tensorflow.js`](https://stackoverflow.com/questions/tagged/tensorflow.js) tag.

GitHub issues for this repository are tracked in the [tfjs union repository](https://github.com/tensorflow/tfjs/issues).

Please file your issue there, following the guidance in [that issue template](https://github.com/tensorflow/tfjs/blob/master/ISSUE_TEMPLATE.md).

**Comment by rthadur** [comment]
@ducanh841988 I see you are using 1.0 , is there a reason why you are not using latest version. If not can you please try

**Comment by ducanh841988** [comment]
I tested with version 1.7.2. The result is same as 1.0.0

**Comment by ducanh841988** [comment]
@axinging  @rthadur Have you reproduce the error?

**Comment by ducanh841988** [comment]
@annxingyuan  @rthadur I have check the detail of our model.
The first two conv2d layers give correct result. the input sizes are [200x500x1] and [50x125x48].
The inconsistent result occurs from the third conv2d layer. the input size is [50x125x128].
I think this problem had report on [tf.Conv2D on WebGL unreliable for large inputs](https://github.com/tensorflow/tfjs/issues/1936).
but there is no solution for webgl.

**Comment by annxingyuan** [comment]
@mattsoulanille for additional context, the `WEBGL_CONV_IM2COL` flag determines whether we use the im2col algorithm to speed up convolution. If we do, then convolution goes through matrix multiplication rather than the conv2d shader in 2 steps: first we run a shader to remap the input tensor to fit im2col, then we run im2col.

**Comment by murphycj** [comment]
I can confirm that I am observing a similar issue with the `webgl` backend while running with a model that has Conv1D layers. The model runs as expected on my macbook pro, iPhone, and iPad. However, when running on an Android phone the predicted values from the model are way off. I found that the only way to fix the issue is to switch the backend to `wasm` or `cpu`.
