### ISSUE TITLE
Posenet miss positioning of points

### ISSUE THREAD

**Issue by fhenri42** [tensorflow/tfjs#3307]
Hey thank's for your amazing work with TFJS, it's really impressive.
We are using "PoseNet" and we are having a small issue with the position of the points, depending on the aspect ratio of the camera and the size of the image

#### TensorFlow.js version
```json 
"tensorflow/tfjs": "1.7.4",
"tensorflow/tfjs-react-native": "0.2.3"
```
#### Browser version
react-native expo-sdk-37
#### Describe the problem or feature request
With PoseNet the points are not aline with the frame of the video, we tested on Android and on iOS.
We find a solution for android if we stay in 16:9 but the 4:3 and 1:1 does not work.  
On iOS we were not able to make it work at all.

#### Code to reproduce the bug

```javascript
const INPUT_TENSOR_WIDTH = Platform.OS === 'ios' ? 360 : 360
const INPUT_TENSOR_HEIGHT = Platform.OS === 'ios' ? 360 : 203
```
```javascript
  getCameraTextureDimensions() {
    const isIOS = Platform.OS === 'ios'
    return {
      height: isIOS ? 1080 : 1080,
      width: isIOS ? 1080 : 1920,
    }
  }
```
```javascript

  <TensorCamera
          style={styles.camera}
          type={Camera.Constants.Type.front}
          zoom={0}
          ratio={Platform.OS === 'ios' ? '1:1' : '16:9'}
          cameraTextureHeight={textureDims.height}
          cameraTextureWidth={textureDims.width}
          resizeHeight={INPUT_TENSOR_HEIGHT}
          resizeWidth={INPUT_TENSOR_WIDTH}
          resizeDepth={3}
          onReady={this.handleImageTensorReady}
          autorender={true}
        />
```
example (IOS): 
![person](https://user-images.githubusercontent.com/16137548/82682327-60497e00-9c4f-11ea-8da4-5d768ff98e77.png)

Thank's for your help :)

**Comment by tafsiri** [comment]
You need to scale your rendering of the output from posenet to match the scaling done by TensorCamera. The input tensor that is passed to posenet is shrunk according to resizeHeight and resizeWidth, you need to reverse this transformation when rendering the output.

As for aspect ratio, i believe the texture from the camera on android is always 16:9, this could vary by device though.

**Comment by coukou** [comment]
Hey !
Thanks for your answer, we finally resolved our issue and it seems to come from our side :cry: 

The issue was the texture dimensions given to TensorCamera component mismatch Expo Camera preview texture dimensions, that make texture being send to tensorflow cropped

After couple hours of searching where issue could come from, we noticed that Expo Camera preview texture scale depending the style width and height of the Camera component.
This behavior is explained here: https://docs.expo.io/versions/latest/sdk/camera/#takepictureasync

So, we solved it by passing those texture params:
```
const textureDims = {
  height: PixelRatio.getPixelSizeForLayoutSize(isIOS ? width : height),
  width: PixelRatio.getPixelSizeForLayoutSize(isIOS ? height : width)
}
```

I think realtime example lead us to the wrong direction about textures that we need to pass to the TensorCamera component, maybe example need to be more documented about this :books: :student: 

Again thanks for your work, you rock! :rocket:
