### ISSUE TITLE
Custom GPU kernel in NodeJS environment (guide/documentation)

### ISSUE THREAD

**Issue by TheNewSound** [tensorflow/tfjs#3312]
#### Describe the problem or feature request

Can someone create a guide on how to create custom GPU kernels in TFJS on NodeJS? There is/was a guide for creating a custom GPU kernel when using TFJS in the browser (using GLSL).

**Comment by tafsiri** [comment]
What is your use case/kernel you are trying to get running? There is no direct path to this and since on node we bind to libtensorflow the process would involve  the flow for a [custom op in tensorflow](https://www.tensorflow.org/guide/create_op). You would then have to bind to that in node (either with a custom tf build or some other mechanism).

Depending on your need for server side custom GPU kernels it not clear to me if it would be worthwhile to call them via node. But you can take a look at the guide linked above if this is something you want to explore further.

**Comment by TheNewSound** [comment]
@tafsiri 

The following kernel (written in GLSL):

```javascript
const intersectionKernel = inputShape => {
    const variableNames = ['X'];
    const outputShape = [inputShape[0], inputShape[0]];
    const userWidth = inputShape[1];
    const userCode = `
        void main() {
            ivec2 coords = getOutputCoords();
            float sum = 0.0;
            for(int i=0; i<${userWidth}; i++) {
                sum += min(getX(coords.y, i),getX(coords.x, i));
            }
            setOutput(sum);
        }`;
    return {variableNames, outputShape, userCode};
};
```

**Comment by tafsiri** [comment]
We now have [registerKernel](https://github.com/tensorflow/tfjs/blob/1e16ae77905a38fe0994f295648ef64aed542664/tfjs-core/src/kernel_registry.ts#L138) and will be writing up some more documentation on how to use it when we release 3.x, though probably not specific to node.js (or custom GPU code in node). You can see an example of a kernel specification that goes with that function here https://github.com/tensorflow/tfjs/blob/master/tfjs-node/src/kernels/Dilation2D.ts.

The nodegl backend is not usable/supported at this time.

I'm going to close this now since its not something we will likely do, but if in the meantime you figured out how to do it, publishing a blog post or something would be great!
