### ISSUE TITLE
Feature Request: Progress event for model download

### ISSUE THREAD

**Issue by EddieOne** [tensorflow/tfjs#336]
I hardly notice myself. However, on slow 3G it takes about 5 minutes to download 0.75 MobileNet model. Having a progress bar for web based apps would be helpful to overcome the large downloads on slow connections.

**Comment by timotheebernard** [comment]
👍  loadModel is based on fetch and it is possible to get the progress of a download with fetch, example:

- https://fetch-progress.anthum.com/fetch-basic/
- https://fetch-progress.anthum.com/fetch-basic/supported-browser.js

Maybe loadModel could work with a callback function:

```javascript
let mobilenet = await tf.loadModel('http://...json', {
  progressFunction: progressData => {
    console.log(progressData.numberOfBytesRead + '/' progressData.numberOfBytesTotal);
  }
});
```

Or, in order to not mix callbacks and promises, use a bluebird-like approach:

```javascript
tf.loadModel('http://...json')
  .progressed(progressData => {
    console.log(progressData.numberOfBytesRead + '/' progressData.numberOfBytesTotal);
  })
  .then(model => {
    console.log('loaded!');
  });
```
But this would imply using different promises than ES6 Promises so not sure this is the best option.

**Comment by EddieOne** [comment]
Alright, that's cool. We need more examples, thanks for sharing that code.

**Comment by caisq** [comment]
This is coming in v1.0

**Comment by ToonTalk** [comment]
Great to hear v1.0 is coming soon. I wonder if there is a roadmap anywhere. And when I went to https://github.com/tensorflow/tfjs/releases I see documentation about 0.14.1 but https://js.tensorflow.org/api/latest/ is at 0.15.1

**Comment by caisq** [comment]
@ToonTalk Yeah, we are currently a little sloppy in terms of making release notes. We'll make a note to improve that. As for roadmap, we are currently heads-down working on v1.0 release. We'll visit releasing a roadmap after it settles. Thank you for your feedback.

**Comment by EddieOne** [comment]
Awesome work, a lot of inspiring things happening around tfjs. Thanks!🙇
