### ISSUE TITLE
Benchmark tool on Chrome Android falsely says "Skipping kernel time, use Chrome +70"

### ISSUE THREAD

**Issue by ToonTalk** [tensorflow/tfjs#3654]
https://tensorflow.github.io/tfjs/e2e/benchmarks/ on Chrome 84 Android 8.1 when I select WebGL (and leave it on mobilenet_v2) seems to behave as if I have a version of Chrome 70 or earlier.

**Comment by rthadur** [comment]
@ToonTalk its working fine on my MAC OS , what device you are using ?

**Comment by ToonTalk** [comment]
Nexus 5 Android phone -- yes, it works fine on my Windows laptop too.

**Comment by rthadur** [comment]
Chrome android doesn't have the query timer aPI, but that's ok, we use a fallback in order to time kernels, So you can ignore above message.

**Comment by Linchenn** [comment]
The message here is misleading. The reason of skipping kernel times is because the browser does not supports `EXT_disjoint_timer_query` or `EXT_disjoint_timer_query_webgl2` extensions, which is not necessarily related to the browser version. I sent a fix here: https://github.com/tensorflow/tfjs/pull/3725
