### ISSUE TITLE
[WASM] The tfjs-backend-wasm module try to find simd binary when I specify a  wasm file

### ISSUE THREAD

**Issue by akineeic** [tensorflow/tfjs#3771]
#### TensorFlow.js version
2.0.1

#### Browser version
84.0.4147.105 (Official Build) (64-bit)

#### Describe the problem or feature request
I use `setWasmPath` to set path to wasm binary(tfjs-backend-wasm.wasm), but the module seem to find tfjs-backend-wasm-simd.wasm in the same path instead and cause the error `file not found`. Why the module try to import simd binary file since I specified a wasm file?

**Comment by annxingyuan** [comment]
Hi @akineeic - thank you for reporting this. This behavior will be fixed in our next release: https://github.com/tensorflow/tfjs/pull/3627

Our next release will deprecate `setWasmPath` and include a new function `setWasmPaths` (notice the 's' at the end) which will accept either a string indicating the folder where all your WASM binaries can be found, or a map specifying the location of each binary: https://github.com/tensorflow/tfjs/blob/master/tfjs-backend-wasm/src/backend_wasm.ts#L403
