### ISSUE TITLE
Threaded build of WASM backend should support Node.

### ISSUE THREAD

**Issue by annxingyuan** [tensorflow/tfjs#3830]
Currently we exclude Node from the threaded build of the WASM backend (https://github.com/tensorflow/tfjs/pull/3829). The threaded build fails in Node for several reasons:

- In Emscripten SDK v.1.39.15 (this is what we're using), the web worker code includes the line `Worker = nodeWorkerThreads.Worker`, which is problematic because `Worker` is undefined. Emscripten v.1.39.16 contains a fix for this: https://github.com/emscripten-core/emscripten/commit/cccf9bf53671a4d6e865420922295b556b292b59. We need to update to 1.39.16 (which means addressing several compile errors). 
- We are currently using the `Blob` API for the threaded build in order to narrow down the `wasm.mainScript` to just the Emscripten-generated WASM module, rather than our entire `tf-backend-wasm.js` bundle (which contains the Emscripten-generated WASM module). We need to narrow it down because the worker ingests `wasm.mainScript` through `importScripts`, and the worker can't ingest our whole bundle because it contains TFJS code that the worker doesn't know anything about (hence it immediately throws an error if attempting to ingest the whole bundle because `runKernel` is undefined). We need to polyfill `Blob` for Node, the way we do for `fetch`. 
- Launching a simple node program with the necessary experimental flags to ask for the threaded + SIMD build (e.g. `node index.js --experimental-wasm-simd --experimental-wasm-threads --experimental-wasm-bulk-memory`) fails with the following message: 

> requested a shared WebAssembly.Memory but the returned buffer is not a SharedArrayBuffer, indicating that while the browser has SharedArrayBuffer it does not have WebAssembly threads support - you may need to set a flag (on node you may need: --experimental-wasm-threads --experimental-wasm-bulk-memory and also use a recent version)` (from Emscripten).

**Comment by tigercosmos** [comment]
Do you have a plan to upgrade the emscripten to the latest v2.11?

**Comment by mightyplow** [comment]
I would also like to know, if there is some progress on the multi threading issue.

**Comment by gaikwadrahul8** [comment]
Hi, @annxingyuan 

Thank you for opening this issue for tracking purposes. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFJs team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TFJs [version](https://github.com/tensorflow/tfjs/releases/tag/tfjs-v4.12.0) with the latest compatible hardware configuration which could potentially resolve the issue.

Based on our internal discussion, we are closing this issue at this time. If you still feel that this feature request is relevant, please feel free to create a new issue.

Thank you for your support and cooperation.

**Comment by koush** [comment]
I think I got this working: https://github.com/tensorflow/tfjs/pull/8059
