### ISSUE TITLE
tfjs-examples out of date

### ISSUE THREAD

**Issue by Download** [tensorflow/tfjs#3856]
*Posted here because tfjs-examples does not have an issues tab.*

Current TFJS version is 2.3.0, released 13 days ago.
tfjs-examples are using tfjs 1.x.
For example, tfjs-examples/simple-object-detection is using [`"@tensorflow/tfjs": "^1.3.2"`](https://github.com/tensorflow/tfjs-examples/blob/master/simple-object-detection/package.json#L12)

Some examples were updated in [this commit](https://github.com/tensorflow/tfjs-examples/commit/046a2a18f00bf5c24d8f5fc766127d2b217a1a45):

* [x] cart-pole
* [x] iris-fitDataset
* [x] mnist
* [x] mnist-core
* [x] mnist-node
* [x] mnist-transfer-cnn

The other examples still need to be updated:

* [ ] addition-rnn-webworker
* [x] addition-rnn
* [ ] baseball-node
* [x] boston-housing
* [ ] chrome-extension
* [ ] custom-layer
* [ ] data-csv
* [ ] data-generator
* [x] date-conversion-attention
* [ ] electron
* [x] fashion-mnist-vae
* [ ] firebase-object-detection-node
* [ ] getting-started
* [ ] intent-classifier
* [x] iris-fitDataset
* [x] iris
* [x] jena-weather
* [x] lstm-text-generation
* [x] mnist-acgan
* [ ] mobilenet
* [ ] polynomial-regression-core
* [ ] polynomial-regression
* [ ] quantization
* [x] sentiment
* [ ] shared
* [ ] simple-object-detection
* [x] snake-dqn
* [ ] translation
* [ ] tsne-mnist-canvas
* [x] visualize-convnet
* [ ] webcam-transfer-learning
* [ ] website-phishing

**Comment by rthadur** [comment]
@Download feel free to submit a PR , thank you

**Comment by Download** [comment]
Send a pay-check and I will.

I mean this is what Google Cloud is using behind the Machine Learning surface, no? Google Cloud is not cheap. My clients pay through the nose to have their model labeled and trained. Then when it comes to deploying the model, we get send here. It's great that it's Open Source, but does that mean 'unmaintained' or something??

I have been working on Google Cloud projects for a while now, but I am pretty upset about your attitude.
I have seen multiple repos with serious issues. In this one, your WebGL backend is basically broken and unusable in production. #3858 . Your examples are out of date and your docs and versions are not in sync. Your Material Design Icons NPM package has been [out-of-date for years](https://github.com/google/material-design-icons/issues/1050) but you still tell us to `npm install` it, giving us outdated icons and hours of pain before we figure this out. Your schema.org project has lots of issues... I try to be a good Open Source spirited developer, so I report these issues. In a detailed fashion, minimizing the amount of work for you to recognize that indeed, there is an issue. I know how to write an issue report because I used to do engineering support work for years so I know that 'it doesn't work' is not helpful. So I give detailed reports. And what do you do? Do you respond timely? No. And when finally, after a month goes by, you do respond, your response is please do our work for us, thank you?? I mean you get paid to work at Google no? Because I am currently typing this in my spare time. Yes, for free. My clients won't pay me for updating your examples, I hope you can understand.

I have seen this attitude in many, many Google repos:
* Don't respond to issues or PRs, at all
* When a response comes, it is something like a counter question or ask for PR
* Seems you invest ZERO time yourself in actually investigating or fixing something
* Literally say you don't have resources, when Alphabet Inc rakes in 30 BILLION per year...

I get very pissed at Google and will not make any contributions to any of your code anymore thanks to this very hard sucking attitude.

**Comment by rthadur** [comment]
We understand your frustration ,we have limited resource on this project, and really appreciated community support . Thank you for your contribution and let us work together to make this library better.

**Comment by Download** [comment]
@rthadur With all due respect. I have seen you in other issues and I know you do good work. But who is this 'we' you are referring to when you say 'we have limited resources'? Google?

I will assume it is Google and when I say 'you' below, I am talking to Google, not to @rthadur who is a good person. But Google is displaying really bad behavior here. Because when I attend a Google Cloud conference it does not feel to me, at all, that Google has limited resources. It feels like they have money pouring out of the ceiling! Frankly, to say that one of the richest and most profitable companies in the world does not have enough resources to update their example code when they make a new release is laughable. 

@Google Why did you release 2.x? I mean it's your project right? You decide the timeline? It simply wasn't READY. That has NOTHING to do with resources. Your examples have not yet been updated THUS your project is not release-worthy yet. Period. It is a simple engineering thing and has NOTHING to do with money. You have a bunch of code and a bunch of examples and docs. Either those examples and docs are important, in which case they should be keept in sync with the code. That means updating your docs and examples to 2.x BEFORE you release 2.x. Or they are not important, in which case you should probably just remove them. What you don't do is let everything go out of sync so no one understands anything anymore and then say we, poor Google, don't have the time or money to manage our project correctly. Boohoo we only made 30 BILLION last year. 

The docs and examples being out-of-sync with the codebase affects me as a developer. I write my code following the docs and examples and then get code that does NOT work. My client ends up paying for me spending time to figure out that YOU winged it when you made your release. Do you understand this? Do you understand that it is frustrating when you spend thousands of dollars on extra development time because the richest company in the world tells you they don't have the resources to update the docs and examples when they release a new version?

**Comment by tafsiri** [comment]
The examples are being updated. We'll update this issue as they get completed.

On incompatibilities upgrading to 2.x do feel free to @ mention me on any issues you run into between 2.x and 1.x. I try and keep an eye out for these on the issues but may occasionally miss some. For users of the [tfjs](https://www.npmjs.com/package/@tensorflow/tfjs) package (which we sometimes refer to as our union package), there should be no breaking api changes between 1.x and 2.x so if you ran into a breakage that would be a bug. I think we also anticipated the time between 2.x and 3.x being shorter than it turned out to be so that was part of decision to hold off on upgrading all the examples.

My apologies for the frustration you experienced with using/referring to the examples.

**Comment by Download** [comment]
@tafsiri Thanks and sorry for getting upset

**Comment by gaikwadrahul8** [comment]
Hi, @Download 

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFJs team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TFJs [version](https://github.com/tensorflow/tfjs/releases/tag/tfjs-v4.10.0) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tfjs/blob/master/README.md) to stay up to date with the latest developments which are happening in the Tensorflow.js space.

Thank you for your support and cooperation.
