### ISSUE TITLE
Does TF.js have support for models that require a 5D Tensor as input from a webcam?

### ISSUE THREAD

**Issue by yudhiesh1997** [tensorflow/tfjs#3876]
I am using Transfer learning with MobileNetV2 + LSTM for awareness detection on Tensorflow and this model takes as input a 5D Tensor. So how would I get it to work on TF.js with react-native expos camera?

**Comment by tafsiri** [comment]
To answer the question in your title, Tf.js does support 5d tensors. However the rest of the question is too vague and open ended, and since it isn't related to a bug or feature request is also better suited for a [stack overflow](https://stackoverflow.com/questions/tagged/tfjs).

I would however also encourage you to make sure you understand in general how to create tensors/reshape and what your 5d tensor actually represents. You can see our [tutorials here](https://www.tensorflow.org/js) and some pointers to [other resources here](https://www.tensorflow.org/resources/learn-ml).
