### ISSUE TITLE
Cannot use addWeight with constraint in CustomLayer

### ISSUE THREAD

**Issue by piercus** [tensorflow/tfjs#3979]
**System information**
- TensorFlow.js 2.4.0
- This issue occurs both on Node.js and in the browser

Thanks for this wonderful library :-)

**Scenario**

See fiddle https://jsfiddle.net/fj2d6Luw/8/ (inspired from [this gist](https://gist.github.com/caisq/33ed021e0c7b9d0e728cb1dce399527d))

* Creating a custom layer
* Adding a constraint in the build method, while using `getWeight` function
```js
    this.x = this.addWeight('x', shape, 'float32', tf.initializers.ones(), null, true, tf.constraints.minMaxNorm({minValue: 0.95, maxValue: 1.05}) );
```
* Logging the value of the variable in `call`

```js
 call(input) {
    return tf.tidy(() => {
    	const xRead = this.x.read();
      const k = tf.pow(xRead, this.alpha);
      xRead.print();
      return tf.add(input[0], k);
    });
  }
```

**Describe the current behavior**

The variable is not impacted by the constrained during training : 

```
"Tensor
    1"
"Epoch 0: loss = 3.0572354793548584"
"Tensor
    0.947640061378479"
"Epoch 1: loss = 2.5550408363342285"
"Tensor
    0.9010470509529114"
"Epoch 2: loss = 2.146026611328125"
"Tensor
    0.8594121932983398"
"Epoch 3: loss = 1.8105026483535767"
"Tensor
    0.8220672011375427"
"Epoch 4: loss = 1.5334960222244263"
"Model saved."
```

**Conclusion** :  the variable is going under the constraint of minValue: 0.95

**Describe the expected behavior**

The variable should be impacted by the constraint and stay in the minValue-maxValue range

### Other consideration

* By looking in the code, it seems that the [LayerVariable.write](https://github.com/tensorflow/tfjs/blob/master/tfjs-layers/src/variables.ts#L95) method is never called
* I faced this issue with different constraint and i'm just using `tf.constraints.minMaxNorm`for the example
* Might be related to #3345

**Comment by zaleslaw** [comment]
Hi, guys; I could not find the place in the code when constraints are applied, not here, not in the Keras framework. How does it work under the hood in Keras? How are you going to change weights after its update by the optimizer?

**Comment by shmishra99** [comment]
Hi @piercus ,
Apology for the late response. I have replicated this issue with latest version of `@tensorflow/tfjs@4.4.0` and Issue is still persist. 
CC: @lina128 Do you have any update on this ? 
Thank You !

**Comment by gaikwadrahul8** [comment]
Hi, @piercus 

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFJs team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TFJs [version](https://github.com/tensorflow/tfjs/releases/tag/tfjs-v4.10.0) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tfjs/blob/master/README.md) to stay up to date with the latest developments which are happening in the Tensorflow.js space.

Thank you for your support and cooperation.

**Comment by vmukhachev** [comment]
A workaround is something like (i have not tested well):
```
function contraintCallback(model) {
  return {
    onBatchEnd: function () {
      for (const w of model.collectedTrainableWeights) {
        if (w.constraint != null) {
          w.val.assign(w.constraint.apply(w.val));
        }
      }
    }
  };
}
```
To use modify callbacks you are using for fitDataset:
```
model.fitDataset(..., {
     ...
    callbacks: [{contraintCallback(model)]
  })
```
