### ISSUE TITLE
TensorCamera does not render children as Expo camera does

### ISSUE THREAD

**Issue by ClementWalter** [tensorflow/tfjs#3986]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow.js version (you are using): 

```
    "@tensorflow/tfjs": "2.0.0",
    "@tensorflow/tfjs-backend-webgl": "2.0.0",
    "@tensorflow/tfjs-core": "2.0.0",
    "@tensorflow/tfjs-react-native": "^0.3.0",
```

- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**

Using raw expo-camera, one can superimpose components atop the Camera doing:

```
import { Camera } from 'expo-camera';

...

<Camera>
   <Text>This is atop the camera screen</Text>
</Camera>
```

Changing `Camera` to `TensorCamera = cameraWithTensor(Camera)` the `<Text>` is not rendered anymore.

**Will this change the current api? How?**

It will not

**Who will benefit with this feature?**

Developpers, people updating from `<Camera>`  to `<TensorCamera>`

**Any Other info.**

**Comment by ClementWalter** [comment]
Ok I will try to push something in the next coming days

**Comment by gaikwadrahul8** [comment]
Hi, @ClementWalter 

Apologize for the delayed response and just to confirm, May I know have you submitted the PR for this feature or still you're working on it ? Thank you!

**Comment by ClementWalter** [comment]
@gaikwadrahul8 well I've not worked on this since then so short answer is no!

**Comment by gaikwadrahul8** [comment]
Hi, @ClementWalter 

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFJs team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TFJs [version](https://github.com/tensorflow/tfjs/releases/tag/tfjs-v4.10.0) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tfjs/blob/master/README.md) to stay up to date with the latest developments which are happening in the Tensorflow.js space.

As I see your previous comment you're not working on this feature request so do you want to keep this issue open or want close this issue ?

Thank you for your support and cooperation.
