### ISSUE TITLE
Screen goes blank on embedding large data with USE model in a browser

### ISSUE THREAD

**Issue by fawazahmed0** [tensorflow/tfjs#4015]
**System information**
- Windows 7 Service Pack 1 Build 7601
- TensorFlow.js Version: 2.4.0 (Latest)
- USE Model: 1.3.2 (Latest)
- Browser version: Chrome 85.0.4183.121 (Latest)
- GPU: RX550 2GB (Radeon Software 20.2.2 )

**Describe the current behavior**
The Screen seems to go blank when embedding large data using [USE model](https://www.npmjs.com/package/@tensorflow-models/universal-sentence-encoder) in browser, the only way to recover is by hard rebooting the pc

**Standalone code to reproduce the issue**
[CodePen](https://codepen.io/fawazahmed0/pen/bGpXxbw?editors=1111)

**Comment by tafsiri** [comment]
This may be a driver issue, assuming you are using webgl it generally shouldn't be able to bring your machine regardless of what is going on in the tab.

To help us understand more about this:
 - How large is large data?
 - Which tfjs backend are you using?
 - Could you post a screenshot of what you see here https://js.tensorflow.org/debug/

To help resolve your ability to use USE:
 - Can you split your data into smaller groups to pass to the model rather than trying to embed it all at once? You may already be hitting the max texture size for webgl on your browser so you may have to do this anyway.

**Comment by fawazahmed0** [comment]
Thanks @tafsiri for replying, I did tried the [CodePen](https://codepen.io/fawazahmed0/pen/bGpXxbw?editors=1111) in a laptop having integrated Intel HD 5500 Graphics and in that the screen goes blank and then driver restarts with the screen coming alive with a Driver failed notification. But in my pc, the screen never comes back alive, have to hard reboot.

> How large is large data?
6000+ text lines
> Which tfjs backend are you using?
I did not set any backend, so probably the default one.
> Could you post a screenshot of what you see here https://js.tensorflow.org/debug/
![-2020-oct-5-005](https://user-images.githubusercontent.com/20347013/95129889-51d0ae80-0779-11eb-904a-b9be9d6af63a.jpg)

> Can you split your data into smaller groups
I tried embedding 50 lines at a time, but even that causes this issue, see [codepen Batch Mode](https://codepen.io/fawazahmed0/pen/JjKPEzZ?editors=1111)

Thanks

**Comment by tafsiri** [comment]
I couldn't understand your use of splice in your codepen. But I forked it so that I could try batching, here is a [link to my codepen](https://codepen.io/tafsiri/pen/zYBOwVB?editors=1111), you can adjust the batch size used. It will still take a while to process all your data. You may want to consider doing it once (possibly on node) and saving the embeddings so that you can re-use them.

**Comment by fawazahmed0** [comment]
The [splice](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/splice) takes slice of array each time it's called, so similar to batching.
> here is a link to my codepen, 

I tried your [codepen](https://codepen.io/tafsiri/pen/zYBOwVB?editors=1111), even that has the same issue, I will share a gif and that would probably explain the issue, it seems to be a memory leakage issue, observe the GPU memory used.
![Mem Leak](https://user-images.githubusercontent.com/20347013/95144050-4db28a00-0795-11eb-8373-9e88138eacd9.gif)

I had to close the browser tab, otherwise the screen would have gone blank and I couldn't have recorded it.

> You may want to consider doing it once (possibly on node) and saving the embeddings so that you can re-use them.

I want to use this model on frontend side, so that might not be possible. I actually raised a similar [issue](https://github.com/tensorflow/tfjs/issues/3471) but it was a slowness issue at node side. I am not sure if it has something to do with this one.

Thanks

**Comment by tafsiri** [comment]
Thanks for the GIF, that is very helpful. In terms of controlling memory usage there are a few things you would need to do.

1. Disposing the output tensor for each batch of embedded text: You would download the final values from the GPU to CPU and then dispose the tensor that is resident on GPU.
2. Setting `tf.env().set("WEBGL_DELETE_TEXTURE_THRESHOLD", 0);` at the top of the program. Disposing the tensors above may not solve the memory issue if many differently sized textures are being allocated to process the different sentence lengths in the input. Setting this flag to zero means that when you dispose the tensor it will actually delete the backing texture as well rather than trying to save it to reuse later.
3. With the two steps above you should save a bunch of GPU memory. You may still run into this [issue with the binary cache](https://github.com/tensorflow/tfjs/issues/3061) and we don't have an escape hatch for that but are discussing options. Try the two steps above and let us know if that helps.

I've [updated the codepen](https://codepen.io/tafsiri/pen/zYBOwVB?editors=1011) to include the steps above.

cc @annxingyuan who suggested using the flag mentioned in step 2.

**Comment by fawazahmed0** [comment]
Thanks @tafsiri @annxingyuan ,the key was `tf.env().set("WEBGL_DELETE_TEXTURE_THRESHOLD", 0)` to solve the issue for me, dispose() function rather slows down the whole embedding process for me, so I removed it.

Thanks
