### ISSUE TITLE
[webgl] Investigate how to reduce memory usage from texture allocation with minimal performance impact.

### ISSUE THREAD

**Issue by talolard** [tensorflow/tfjs#4129]
Hi,
I've been using the Universal Sentence Encoders model and had a hard to track memory leak. I eventually found [this comment](https://github.com/tensorflow/tfjs/issues/4015#issuecomment-704335135)  which suggested setting 
```js
tf.env().set("WEBGL_DELETE_TEXTURE_THRESHOLD", 0);
```
Which solved the issue. 
I don't know what it did but it worked and I suggest documenting it more prominently. 
I'd volunteer to do so myself but don't understand what this does so leaving it as a suggestion
Thanks !

**Comment by rthadur** [comment]
```
// set this flag so that textures are deleted when tensors are disposed.
tf.env().set("WEBGL_DELETE_TEXTURE_THRESHOLD", 0);
```

**Comment by talolard** [comment]
> ```
> // set this flag so that textures are deleted when tensors are disposed.
> tf.env().set("WEBGL_DELETE_TEXTURE_THRESHOLD", 0);
> ```

I'm not sure of that was for my sake, but if it was I (and similar users) don't understand it. 

I'm just a simple NLP guy, I know some tensorflow and am fighting my way in the JS world to make things works. 
I (and people like me), want to use this lib, but have no idea what a texture is.

More practically, it would be cool if it said somewhere: 
"Hey, if you see your script using 10G of ram, you might have a memory leak. Try this because WebGL allocates textures but doesn't release them by default ... " 

Hope that's helpful

**Comment by tafsiri** [comment]
I think a goo place to do this would be in the README for Universal Sentence Encoder. @talolard if you were interested in making a PR for that that would be great. Else we can do that.

**Comment by tafsiri** [comment]
cc @annxingyuan

**Comment by talolard** [comment]
> I think a goo place to do this would be in the README for Universal Sentence Encoder. @talolard if you were interested in making a PR for that that would be great. Else we can do that.

I'd be happy to. To make the thing compelte, can you point me to why it's a universal encoders thing and a general tf.js issue ? 
e.g. If I was building my own model it wouldn't be an issue ?

**Comment by annxingyuan** [comment]
@talolard Changing the default behavior of `WEBGL_DELETE_TEXTURE_THRESHOLD` is hopefully more of a last resort for our users, so I think that's why we'd want to document this closer to the specific use cases.

**Comment by talolard** [comment]
Thanks @annxingyuan 
Can you shed some light on what it does and why it's specifc to Universal Sentence Encoders. 
I'd love to submit a PR with the relevant information but don't feel like I know what I'm talking about yet. 

Tnx

**Comment by vladmandic** [comment]
not intending to hijack this thread, but `WEBGL_DELETE_TEXTURE_THRESHOLD` is pretty much required for execution of any complex model due to TFJS extremely high WebGL memory usage. On the other hand, it has a really bad performance impact - it slows down subsequent inferences by 2-3x.

The goal should be to optimize TFJS not to use 10x memory with `backend-webgl` compared to other backends.

See this one for more details: <https://github.com/tensorflow/tfjs/issues/4166>

**Comment by annxingyuan** [comment]
@vladmandic Yes you're right - adjusting `WEBGL_DELETE_TEXTURE_THRESHOLD` does not address the underlying issue, which is why I'm hesitant to encourage people to rely on it, although I understand that it can improve performance in certain cases. We need to figure out how to reduce the memory footprint while minimizing the cost of aggressive texture deletion.

I've changed the title of this issue to reflect.

**Comment by gaikwadrahul8** [comment]
Hi, @talolard 

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFJs team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TFJs [version](https://github.com/tensorflow/tfjs/releases/tag/tfjs-v4.10.0) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tfjs/blob/master/README.md) to stay up to date with the latest developments which are happening in the Tensorflow.js space.

Thank you for your support and cooperation.
