### ISSUE TITLE
UnsortedSegmentSum fails in node.

### ISSUE THREAD

**Issue by nsthorat** [tensorflow/tfjs#417]
When running the unit tests for WebGL in node, we get the following error:

`Message: data.shape = [2,4] does not start with segment_ids.shape = [4]`

The tests are not yet checked in, once they are I will ping this thread.

@jgartman

**Comment by jgartman** [comment]
What's happening is that in the frontend function axis 0 on the input tensor is being transposed so that it's the innermost axis and then the WebGL and CPU backends are assuming that this has already been done by the time the tensor is passed to them.  Since the C API doesn't know anything about this, it's assuming the sum is being taken along axis 0 of the tensor it's being passed (which was already permuted on the frontend) and throwing an error.  The solution would be to move the transpose operation into both `backend_cpu.ts` and `backend_webgl.ts` and have the frontend function pass the tensor to the backend as is.

**Comment by nsthorat** [comment]
Thanks for debugging! Would you be willing to send a PR?

**Comment by jgartman** [comment]
The node tests passed locally for me with the changes from that PR.

**Comment by yanyou426** [comment]
Hello, I have met the problem recently when I am training my model using tf 1.14.0. It confused me that I have many feature vector as the input of my model, but the problem occurs just for some inputs. I also check the shape of these vectors which are all the same. Therefore, I wonder why the error just occurs sometimes.

`tensorflow.python.framework.errors_impl.InvalidArgumentError: data.shape = [772,128] does not start with segment_ids.shape = [648]
         [[{{node graph-embedding-net/graph-aggregator/UnsortedSegmentSum}}]]`

**Comment by yanyou426** [comment]
> What's happening is that in the frontend function axis 0 on the input tensor is being transposed so that it's the innermost axis and then the WebGL and CPU backends are assuming that this has already been done by the time the tensor is passed to them. Since the C API doesn't know anything about this, it's assuming the sum is being taken along axis 0 of the tensor it's being passed (which was already permuted on the frontend) and throwing an error. The solution would be to move the transpose operation into both `backend_cpu.ts` and `backend_webgl.ts` and have the frontend function pass the tensor to the backend as is. I can open a PR to fix this.

Hello, I have met the problem recently when I am training my model using tf 1.14.0. It confused me that I have many feature vector as the input of my model, but the problem occurs just for some inputs. I also check the shape of these vectors which are all the same. Therefore, I wonder why the error just occurs sometimes.
`tensorflow.python.framework.errors_impl.InvalidArgumentError: data.shape = [772,128] does not start with segment_ids.shape = [648]
         [[{{node graph-embedding-net/graph-aggregator/UnsortedSegmentSum}}]]`
