### ISSUE TITLE
FaceMesh memory Leak when covering the face partially

### ISSUE THREAD

**Issue by gerritsanetra** [tensorflow/tfjs#4173]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow.js installed from (npm or script link): npm
- TensorFlow.js version (use command below): 2.1
- Browser version: Chrome 86.0.4240.111
- Tensorflow.js Converter Version: 2.1

**Describe the current behavior**
When I run the demo of the FaceMesh model and I cover my face partially, the gpu memory demand is steadily increasing with each frame. When the whole face is visible or the face isn't visible at all, the allocated memory remains the same. All this is only an issue with the webgl backend.
**Describe the expected behavior**
The memory demand should not increase in any case.
**Code to reproduce the issue**
The line following line can be added to the renderPrediction function to monitor gpu demand:
`console.log(tf.backend().memory())`

![facemesh](https://user-images.githubusercontent.com/69153609/97991946-5a50ef00-1de2-11eb-9406-aaab6d54ddf8.gif)

**Comment by annxingyuan** [comment]
For context: the facemesh pipeline includes two models:
1) Bounding box detection model
2) Geometry detection model

If the face remains in view, we only run (2). If there is no face in view, we only run (1). if the face moves in and out of view, we run (1) followed by (2) over and over. So there is more opportunity for leaks in this case. I'm not sure where the leak occurs exactly, but this is the most likely scenario for creating a leak.

For additional context, we are dataSyncing the bounding box detection model output to the CPU because we are doing many small postprocessing transformations on the output of the bounding box detection model that are slower to carry out on the GPU according to our experiments.

**Comment by rthadur** [comment]
Please check the latest face-landmark-detection with mediapipe here https://github.com/tensorflow/tfjs-models/tree/master/face-landmarks-detection/ , the above demo was deprecated.
