### ISSUE TITLE
Add back camera Blazeface tfjs model

### ISSUE THREAD

**Issue by simon-lanf** [tensorflow/tfjs#4185]
Hi, I'm trying to use Blazeface in TFJS and see that the only version for tfjs available is the front camera version.

The model card states that two versions exist: https://drive.google.com/file/d/1f39lSzU5Oq-j_OXgS67KfN5wNsoeAZ4V/view

Here are the two .tflite version of the model:
https://github.com/google/mediapipe/blob/master/mediapipe/models/face_detection_front.tflite
https://github.com/google/mediapipe/blob/master/mediapipe/models/face_detection_back.tflite

The first one (front) accepts images of 128x128 and can detect up to 2 meters. The second one (back) accepts images of 256x256 and can detect up to 5 meters.

The only version avaliable online on TFHub is the front one, is there some way that you could publish the back one too ? that would be very helpful.

Otherwise if there are any way to convert the tflite to tfjs, directly or indirectly, please let me know.

Thank you.

edit: this also means that https://github.com/tensorflow/tfjs-models/tree/master/blazeface does not work if you configure it to use image larger than 128x128: "The shape of dict['input'] provided in model.execute(dict) must be [-1,128,128,3], but was [1,256,256,3]"

**Comment by simon-lanf** [comment]
I'm asking for the same thing as https://github.com/google/mediapipe/issues/61 , for TFJS.

**Comment by rthadur** [comment]
cc @annxingyuan

**Comment by vladmandic** [comment]
ported both back and front models: <https://github.com/vladmandic/human/tree/main/models>

**Comment by simon-lanf** [comment]
@vladmandic I tried using your demo for front and back camera, selecting only face detection and it performs significantly worse than the Blazeface TFJS demo here: https://storage.googleapis.com/tfjs-models/demos/blazeface/index.html
I used your demo with these options: #
![vladmandic github io_human_demo_index html](https://user-images.githubusercontent.com/58534677/98566951-62df7480-227d-11eb-91d5-cb59aa7ea83b.png)

the performance I get is far from useable for our use case. nice project nonetheless.

**Comment by vladmandic** [comment]
key difference is that original uses: 
```
  minConfidence: 0.9
  iouThreshold: 0.3,
  scoreThreshold: 0.75
```
while i use far more aggressive values as default:
```
  minConfidence: 0.1,
  iouThreshold: 0.1,
  scoreThreshold: 0.2,
```
which means there are more hits and more things to process  
(reason for more aggressive values is that i use it to find large number of small faces in photos as well)  

and that is all tunable.

if there are any other performance issues due to code itself, i'd be more than interested in analyzing/fixing  

also, feel free to re-use models and do your implementation  
like i said, only difference to original models are additional `concat` operations to get to the final output node

**Comment by simon-lanf** [comment]
the settings I sent you are an example, I tried many combinations of settings.

at minConfidence: 0.9 I see my face one in like 10 frames. It misses everything. I truly mean it, it just does not perform the same. Try for yourself to recreate the demo with just this model and isolate and you'll see that the demo from TFJS performs better.

**Comment by vladmandic** [comment]
ahh, i think i know what the issue with that is - had the same problem with handdetect - bug in cache invalidation. need to do the same fix for blazeface.

**Comment by simon-lanf** [comment]
let me know when you fix this I'll create a demo comparison page.

Also on my chrome the wasm version crashes most of the time. The error is:

Error: Backend name 'wasm' not found in registry

**Comment by vladmandic** [comment]
@simon-lanf done, pushed new update

keep in mind that default parameters still differ from google's demo  
also, webcam input resolution makes a big difference, especially with wasm backend  
(resolution can be tuned in my demo as well)

performance wise, with webgl both back and front model variations are running within margin of error  
with wasm, performance difference starts to show - back is about 1/2 - 1/3 of performance of front which makes sense given the much larger model input resolution  

regarding your error, you can't run wasm from demo on git pages as it doesn't load wasm backend by default (my choice due to extra size). you need to it enable script loading in index.html (it's documented in there).

**Comment by simon-lanf** [comment]
@vladmandic I continued the discussion in your project's issues: https://github.com/vladmandic/human/issues/26

**Comment by simon-lanf** [comment]
@vladmandic could you please tell me where did you find the saved model or keras model to generate your versions ? For example blazeface back camera is not on tfhub and I could not find it online.

**Comment by vladmandic** [comment]
@simon-lanf <https://github.com/PINTO0309/PINTO_model_zoo>

**Comment by ahsenkh** [comment]
@vladmandic when I try to use the back-facing model, downloaded from [here](https://github.com/PINTO0309/PINTO_model_zoo/blob/main/030_BlazeFace/09_tfjs/download_new.sh), it gives me the following error upon calling `estimateFaces` method.

![image](https://user-images.githubusercontent.com/18351371/153241671-043f8ccd-f174-4d09-b6d6-15e9abf7a4b2.png)

**Comment by ahsenkh** [comment]
This would require changes in the `blazeface.esm.js`, or is there a simpler way to resolve this?

**Comment by vladmandic** [comment]
@ahsenkh i use my own decoding routine, see <https://github.com/vladmandic/human/blob/main/src/face/blazeface.ts>
