### ISSUE TITLE
How to make sense of TFHub TFjS model outputs (handdetector)

### ISSUE THREAD

**Issue by djthegr8** [tensorflow/tfjs#4200]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js):No, [from TFHub](https://tfhub.dev/mediapipe/tfjs-model/handdetector/1/default/1)
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Linux Ubuntu 20.04 LTS
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:N/A
- TensorFlow.js installed from (npm or script link):script link
- TensorFlow.js version (use command below):2.7.0
- Browser version:N/A
- Tensorflow.js Converter Version:N/A

**Describe the current behavior**
No models on TFHub with tfjs models are well-documented, for example the hand-detector model gives outputs that aren't parseable for me. They are of shape `(1,2944,19)`..
**Describe the expected behavior**
Well-written documentation regarding official model outputs on TFjS.
**Standalone code to reproduce the issue**
Any code for importing a TFHub model as GraphModel
**Other info / logs**      
N/A

**Comment by rthadur** [comment]
cc @pyu10055

**Comment by annxingyuan** [comment]
Hi @djthegr8 - the handdetector model is designed to be used as part of the TF.js handpose package: https://github.com/tensorflow/tfjs-models/tree/master/handpose - rather than as a standalone model.

Our handpose package will parse the [1, 2944, 19] output tensor into an array of keypoints.

Apologies for the confusion - in the long term we intend to unify the API across the tfjs models repo and TFHub.
