### ISSUE TITLE
Will TF.JS survive WebAssembly? Is TF.JS going to die?

### ISSUE THREAD

**Issue by aelich** [tensorflow/tfjs#4283]
If we have [WebAssembly](https://webassembly.org/) tool that enables us to run C/C++,RUST, Python, Go... code in Browser at **native speed**  what is reason of using TF.JS in future?

WebAssembly(supports WebGL) and guarantee consistent performance across a spectrum of browsers while JS must be optimized per se. 

Also as there is no need for multiple run of JS as interpreter and code can be complied which would save time.. (WebAssembly and JavaScript both have the same peak performance. But… JavaScript can easily fall off the “fast path” while WebAssembly will not.)

--------------------------------------------
**| .js         -> Ignition  ->/<-    TubroFan |**
 
- _js input_
  Ignition: Interprets the JS text and runs it. While running, collects analytics data about how the code is behaving before 
  TurboFan kicks in.
  TurboFan: The optimizing compiler.

**| .wasm ->  LiftOff       ->       TubroFan |**

- _wasm input_
  Liftoff: The streaming WebAssembly compiler which generates machine code.
  TurboFan: The optimizing compiler which generates optimized code.                                                             |

--------------------------------------------
[IMAGE https://itenium.be/assets/blog-images/webassembly-v8-js-vs-wasm.png]

Will this means future decline of TFJS in next years as overlapping is so huge? (as ML dev don't prefer JS and would rather use Python)

P.S.
I'm aware it's early days of WebAssembly but as its supported by https://www.w3.org/ it's here to stay.

**Comment by pyu10055** [comment]
@aelich You have raised a good point, WASM has been on a rise recently. TensorFlow.js being an ML platform for the web/javascript developers, we are tech stack neutral. Our goal is to utilized all web technologies to provide our users the best performance, that includes WASM, webGL, webGPU, and the future WebNN standard. WASM has already been used in our tfjs-backend-wasm package. We are also actively investing more into WASM, you will see more news coming out in the near future.

**Comment by wingman-jr-addon** [comment]
As an anecdote, I'm probably one of those "ML devs" who "don't prefer JS". However, for me the big story with any ML model is to make it useful by deploying it - deploying an ML model in any meaningful way often means a different language, model optimization, potentially learning new frameworks etc. For me - and I suspect many others - Tensorflow.js usage is focused primarily on the use case of inference of pretrained models.
In most deployments, there are (at least) two parts: glue code and performance-critical code. Glue code has business logic and performance-critical code does the heavy lifting for the model. As such, the performance for glue code often doesn't matter that much as long as the interfacing is done well to the performance-critical code. In this way, Tensorflow.js using JS with optimized backends (including WASM) is not really that different from say Python with Tensorflow bindings to a GPU backend.

So what am I getting at? For the glue code, I think the requirements tend to be "fast enough", "as fast as possible to write", and "easy to maintain". JS checks all those boxes for me; right now WASM does not. I'm not saying tooling won't get better in the future, etc., but I do think that in many cases you still have to either 1) interface with HTML/CSS or 2) something else that wants JS at some point. JS has utility precisely because it provides a tradeoff in simplicity and tooling without sacrificing (much) speed where it counts. I suspect WASM without any JS will definitely have a certain use case too, but so far we also haven't seen (for example) C# apps converted to WASM magically displace JS - quite the opposite. So I think that essentially we have "JS bindings" for "WASM backend" and I'd be surprised if either one went away just based on the patterns that seem to pop up on other systems. 

However, web tech is not my primary focus, so maybe I'm missing something here; it'd be interesting to see what others think on this front.
