### ISSUE TITLE
tfjs-node: bundled libtensorflow.so doesn't work on Ubuntu 14.04

### ISSUE THREAD

**Issue by d4l3k** [tensorflow/tfjs#431]
#### TensorFlow.js version
@tensorflow/tfjs-node@0.1.7

The bundled version of libtensorflow.so doesn't work on Ubuntu 14.04. It gets a libc linking error. This makes it very hard to test tfjs-node projects on Travis CI.

https://travis-ci.org/luk-ai/lukai/jobs/392378382

Manually downloading https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-cpu-linux-x86_64-1.8.0.tar.gz and extracting it into node_modules/@tensorflow/tfjs-node/deps/tensorflow/lib/ fixes the problem.

The download script sources tensorflow from a different location. Might consider updating it to use the https://storage.googleapis.com/tensorflow/libtensorflow binaries instead? https://github.com/tensorflow/tfjs-node/blob/master/scripts/download-libtensorflow.sh#L7

I'm not sure why there's a difference between them.

**Comment by MongoExpUser** [comment]
I am having **the same problem**. I extracted the **tar.gz** file to the specified directory using the command below:
curl -L "https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-cpu-linux-x86_64-1.8.0.tar.gz" | sudo tar -C "/path_to_directory/node_modules/@tensorflow/tfjs-node/deps/tensorflow/" -xz

The bundled version of **libtensorflow.so** is still not working on my system (**Ubuntu 16.04.4 LTS**)

**Any solution to this problem?**

**Comment by nkreeger** [comment]
@d4l3k I was not aware of those pre-built binaries. I'll ask around to see where they come from. The current binaries that we build are from a 16.04 machine that targets the current minimum system requirements of TensorFlow (16.04 essentially):

https://www.tensorflow.org/install/

I hear you on the Travis integration problem - we have that as well on our setup so we default to Mac OS only. Travis recommended setting up a Docker image since 16.04 support is still a long ways out.

Do you mind sharing a stack trace? I'll double check what libc our build machine is using.

@MongoExpUser You're not CP'ing the files into the correct directory - you need to append ensure that the *.so files end up in /lib:

```
"/path_to_directory/node_modules/@tensorflow/tfjs-node/deps/tensorflow/lib"
```

**Comment by nkreeger** [comment]
CPU-Linux builds should now support 14.04 - the tfjs-node repo is using Travis for linux testing. I'll update the docs shortly.

**Comment by nkreeger** [comment]
@d4l3k bundled CPU build should work on Node.js bindings now - see our Travis setup: https://travis-ci.org/tensorflow/tfjs-node/jobs/398273568

**Comment by d4l3k** [comment]
@nkreeger Nice, thanks!
