### ISSUE TITLE
TensorFlowJS Unsupported Ops needed for Yahoo's Open NSFW Model

### ISSUE THREAD

**Issue by tomslick** [tensorflow/tfjs#433]
To get help from the community, check out our [Google group](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs).

#### TensorFlow.js version
tensorflowjs 0.4.1
(installed via pip install tensorflowjs on June 13, 2018)

#### Browser version
N/A

#### Describe the problem or feature request
I attempted to convert the TensorFlow model of Yahoo's Open NSFW model found [here](https://github.com/mdietrichstein/tensorflow-open_nsfw) with `tensorflowjs-convert`. (First, I exported the TensorFlow .npy file into a Frozen Model and also a Saved Model.)

For the Frozen Model, I ran:
```
tensorflowjs_converter --input_format=tf_frozen_model --output_node_names='fc_nsfw/BiasAdd' --saved_model_tags=serve frozen_open_nsfw.pb web_model
```
and received the following message:
```
Unsupported Ops in the model
TensorArrayWriteV3, TensorArrayV3, DecodeBase64, TensorArrayScatterV3, TensorArrayReadV3, EncodeJpeg, Assert, All, TensorArraySizeV3, DecodeJpeg, Unpack, TensorArrayGatherV3
```

Running on the Saved Model also results in the same Unsupported Ops list.

Request: Please add my vote to support these Ops
- TensorArrayWriteV3
- TensorArrayV3
- DecodeBase64
- TensorArrayScatterV3
- TensorArrayReadV3
- EncodeJpeg
- Assert
- All
- TensorArraySizeV3
- DecodeJpeg
- Unpack (I noticed this was added earlier today but not yet in the latest pip installed version)
- TensorArrayGatherV3

Thanks!

**Comment by pyu10055** [comment]
The TensorArray related ops are almost ready, see https://github.com/tensorflow/tfjs-converter/pull/170
All op has been added. The ops left are: 
DecodedBase64, EncodeJpeg, Assert
We will add those to our priority list.

**Comment by rstml** [comment]
Same issue here. The only outstanding ops are: `DecodeBase64`, `DecodeJpeg`, `EncodeJpeg`

**Comment by xue160709** [comment]
Same issue here. The only outstanding ops are: DecodeBase64, DecodeJpeg, EncodeJpeg

**Comment by SSaishruthi** [comment]
Working on it.

**Comment by rstml** [comment]
@SSaishruthi Frankly, if OpenNSFW is the only reason for supporting those operations, you may reconsider it. 

For everyone else requesting this:

OpenNSFW has not been updated since its announcement in 2016. There are now alternative models which you can use.

We trained our alternative, MobileNetV2 based model which you can find here: https://github.com/purify-ai/geacc-models 
TFJS example using this model is available here: https://github.com/purify-ai/geacc-tfjs-demo
Chrome extension which uses TFJS and our model: https://github.com/purify-ai/geacc-crx
We plan to release updated dataset and model soon (potentially 100K images).

There's also NsfwJS which is based on InceptionV3: https://github.com/infinitered/nsfwjs

**Comment by pyu10055** [comment]
DecodeJpeg op has been added in tfjs-node.
