### ISSUE TITLE
UpSampling2D(interpolation=bilinear) gives significant difference when converted using tensorflowjs_converter

### ISSUE THREAD

**Issue by beingtmk** [tensorflow/tfjs#4340]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js): close to stock example
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- TensorFlow.js version (use command below): "@tensorflow/tfjs-node": "^2.1.0"
- Tensorflow.js Converter Version: tensorflowjs 2.7.0

**Describe the current behavior**
1. Added a layer`UpSampling2D` with interpolation as `bilinear` (tensorflow python model).

`model.add(tf.keras.layers.UpSampling2D(size=(2,2), interpolation='bilinear'))`

2. Converted the model (to be used in js) using tensorflowjs_converter

`tensorflowjs_converter --control_flow_v2=True --input_format=tf_saved_model --saved_model_tags=serve --signature_name=serving_default --skip_op_check --strip_debug_ops=True --weight_shard_size_bytes=4194304 model_path output_path`

3. Now, the output in tensorflow js (converted model) is significantly different than tensorflow python.

**Note:** The outputs are same when we use `interpolation=nearest` (js vs python)

**Describe the expected behavior**
There should not be significant difference when a model with a particular layer is converted from python to js.

**Comment by rohanmuplara** [comment]
As a followup, the problem seems to be https://js.tensorflow.org/api/0.12.5/#layers.upSampling2d. In tensorflow python, you can define this layer with both bilinear and nearest neighbor but in https://github.com/tensorflow/tfjs/blob/5f1991a993b0f6cbed708599eac084717d0a7f5a/tfjs-layers/src/layers/convolutional.ts#L1253 it is clear is is just implemented in nearest neighbor.

1. Will there be support for this (bilinear resizing in upsamplign2d in the future?
2. In the interim, what would we need to change to support bilinear conversion We would need to change lines 1253 and 258 to use image.resizeBilinear instead of nearest neighbor but what else would we have to change.  Would we have to rebuild tfjs? Are there any files we have to change? Do we have change the converter?

**Comment by Shawn-Chahal** [comment]
I am having the same issue.

I am using an `UpSampling2D` layer to generate images using a Generative Adversarial Network. In Python I set `tf.keras.layers.UpSampling2D(size=2, interpolation='bilinear')`, but the resulting generated image in TensorFlow.js looks as though it was switched to `interpolation='nearest'`.
