### ISSUE TITLE
Unable to install 'node-red-contrib-tf-model' on Node-RED

### ISSUE THREAD

**Issue by devittok** [tensorflow/tfjs#4384]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution: Windows 10 Home x64
- Node version: 14.15.1
- NPM version: 6.14.9

I followed the tutorials below for the installation of the tensorflow model:

- https://flows.nodered.org/node/node-red-contrib-tf-model
- https://github.com/tensorflow/tfjs/blob/master/tfjs-node/WINDOWS_TROUBLESHOOTING.md

1. I first installed the '@tensorflow/tfjs-node' inside Node-RED directly by running the following code
_C:\Users\username.node-red\node_modules> **npm install @tensorflow/tfjs-node@1.4.0**_

2. Ran npm install under C:\Users\username.node-red\node_modules@tensorflow\tfjs-node:
_C:\Users\username.node-red\node_modules@tensorflow\tfjs-node> **npm install**_

3. Finally ran npm install node-red-contrib-tf-model on the same directory:
_C:\Users\username.node-red\node_modules@tensorflow\tfjs-node> **npm install node-red-contrib-tf-model**_

Error that occured:

**npm WARN node-red-contrib-tf-model@0.1.11 requires a peer of @tensorflow/tfjs-node@^1.4.0 but none is installed. You must install peer dependencies yourself. npm WARN @tensorflow/tfjs-node@1.4.0 No license field.**

I have installed the correct tfjs-node version, and so why does this error occur?

**Comment by tafsiri** [comment]
Hi I don't think we'd be able to help with node-red debugging, I think this would be better asked on the https://github.com/yhwang/node-red-contrib-tf-model repositories (or the main node-red one).  

Other than that my only suggestions would be to:  1) check your lock files to see what actually got installed. 2) While npm is giving a _warning_ that it can't see the peerDep, you might not necessarily get an _error_ at require time if node-red-contrib-tf-model is otherwise able to resolve tfjs-node. 

I'm going to close this for now but if you do find an error that is more tfjs/tfjs-node specific feel free to comment/elaborate.
