### ISSUE TITLE
cocoSSD with wasm backen doesnt work

### ISSUE THREAD

**Issue by pallavikhtri25** [tensorflow/tfjs#4398]
even though mentioned that tfjs-backend-wasm has support to run cocoSSD..but can't get this working getting error 

Slice.ts:72 Uncaught (in promise) TypeError: Cannot perform Construct on a detached ArrayBuffer

**Comment by rthadur** [comment]
It looks like you haven't used a template to create this issue. Please resubmit your issue using a template from [here](https://github.com/tensorflow/tfjs/issues/new/choose). We ask users to use the template because it reduces overall time to resolve a new issue by avoiding extra communication to get to the root of the issue. We will close this issue in lieu of the new one you will create from the template. Thank you for your cooperation.
