### ISSUE TITLE
Determinant of a matrix

### ISSUE THREAD

**Issue by henrmota** [tensorflow/tfjs#4477]
I just want to make a question, I developed an algorithm to calculate the determinant of a square matrix, If I open a pull request will the community help me to put this code in the required way? What are my chances to see my code merged? 

A version of this can be seen at, (open the console to see the output):

https://codepen.io/henrmota/pen/MWjjoJB

**System information**
- TensorFlow.js version (you are using):
- Are you willing to contribute it (Yes):

**Describe the feature and the current behavior/state.**

**Will this change the current api? How?**

**Who will benefit with this feature?**

**Any Other info.**

**Comment by rthadur** [comment]
It looks like you haven't used a template to create this issue. Please resubmit your issue using a template from [here](https://github.com/tensorflow/tfjs/issues/new/choose). We ask users to use the template because it reduces overall time to resolve a new issue by avoiding extra communication to get to the root of the issue. We will close this issue in lieu of the new one you will create from the template. Thank you for your cooperation.
