### ISSUE TITLE
Model zoo for TensorFlow.js visualizer

### ISSUE THREAD

**Issue by lutzroeder** [tensorflow/tfjs#45]
The [Netron](https://www.github.com/lutzroeder/Netron) visualizer now supports **TensorFlow.js** (`model.json`, `.pb`) files. 

Is there a model zoo or set of models to test this with?

<img width="1385" alt="netron" src="https://user-images.githubusercontent.com/438516/38168618-6399cedc-3506-11e8-85c8-0c405215bb39.png">

**Comment by caisq** [comment]
@lutzroeder Thanks for this question. TensorFlow.js can currently load models from keras (hence model.json) and tensorflow (hence .pb). Are there any existing model zoos for (python) keras and tensorflow models? If so, I guess I don't fully understand why we need a separate zoo for TensorFlow.js. 

On the flip side, it is currently possible to export the topology of TensorFlow.js models in the keras model.json format, but since those models are essentially keras models, they can just use whatever existing keras model zoo there is. Another question I have: does Netron load keras HDF5 files?

**Comment by davidsoergel** [comment]
Yep, the question of standardizing the serialization format is under active discussion.  The current model.json should be considered a TF.js implementation detail for now.  Good point about the file extension, thanks!

**Comment by nsthorat** [comment]
Closing this out -- any discussions can move over to the community discussion mailing list.
