### ISSUE TITLE
Is it possible to recognize facial expressions through face-landmark-detection

### ISSUE THREAD

**Issue by Sunyingbin** [tensorflow/tfjs#4520]
hello:
       I would like to ask whether it is possible to judge facial expressions through the face net

**Comment by rthadur** [comment]
cc @annxingyuan @pyu10055 @lina128

**Comment by rthadur** [comment]
@Sunyingbin it is not possible through face-landmark-detection model , you need to write custom code in order to implement this. Sorry, we do not have bandwidth to support this in near future.Please refer face-api which uses tfjs-node to recognize facial expressions https://github.com/justadudewhohacks/face-api.js/ . Thank you .
