### ISSUE TITLE
Why can not convert tfjs-graph-model to keras?

### ISSUE THREAD

**Issue by qiankunxienb** [tensorflow/tfjs#4531]
I have a tfjs graph model, it can only be loaded by tfjs. and can not convert to h5 or even tfjs-layer-model. How can I use it in keras?

**Comment by pyu10055** [comment]
@qiankunxienb unfortunately graph model cannot be converted to h5 or tfjs layers model, the reason is graph model is inference only model, which h5 and layers model support training.
If you have the original TensorFlow TF saved model that graph model is converted from, you can try to convert that to layers or h5 models.

**Comment by qiankunxienb** [comment]
@pyu10055 the problem is that, I want to use your model in https://nsfwjs.com/quant_mid/* , however, it can only be loaded by tfjs. How can I use it in keras?

**Comment by pyu10055** [comment]
@qiankunxienb This model is not created by us, you can ask the author of the model to share the original TensorFlow model, it could be built from Keras.

**Comment by qiankunxienb** [comment]
Thanks for your reply.
