### ISSUE TITLE
Error: The dict provided in model.execute(dict) has keys: [ToFloat] that are not part of graph

### ISSUE THREAD

**Issue by startonggithub** [tensorflow/tfjs#4540]
hi all, I have got the captioned error when running the following scripts for Google AutoML multiple object detection. Is there any clue ? 

<script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs"></script>
<script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-automl"></script>
<img id="mahjong" src="tiles2.jpg">
<script>
async function run() {
  //const model = await tf.automl.loadImageClassification('model.json');
  const model = await tf.automl.loadObjectDetection('model.json');
  const image = document.getElementById('mahjong');
  const options = {score: 0.5, iou: 0.5, topk: 20};
  //const predictions = await model.classify(image);
  const predictions = await model.detect(image, options);
  console.log(predictions);
  // Show the resulting object on the page.
  const pre = document.createElement('pre');
  pre.textContent = JSON.stringify(predictions, null, 2);
  document.body.append(pre);
}
run();
</script>

**Comment by rthadur** [comment]
It looks like you haven't used a template to create this issue. Please resubmit your issue using a template from [here](https://github.com/tensorflow/tfjs/issues/new/choose). We ask users to use the template because it reduces overall time to resolve a new issue by avoiding extra communication to get to the root of the issue. We will close this issue in lieu of the new one you will create from the template. Thank you for your cooperation.
