### ISSUE TITLE
Error: The dict provided in model.execute(dict) has keys: [ToFloat] that are not part of graph

### ISSUE THREAD

**Issue by startonggithub** [tensorflow/tfjs#4542]
This template is for miscellaneous issues not covered by the other issue categories.

For questions on how to work with TensorFlow.js, or support for problems that are not verified bugs in TensorFlow.js, please go to [StackOverflow](https://stackoverflow.com/tags/tensorflow.js).

hi all, I have got the captioned error when running the following scripts for Google AutoML multiple object detection. Is there any clue ?

[index.txt](https://github.com/tensorflow/tfjs/files/5822253/index.txt)

tfjs:17 Uncaught (in promise) Error: The dict provided in model.execute(dict) has keys: [ToFloat] that are not part of graph
    at e.t.checkInputs (tfjs:17)
    at e.<anonymous> (tfjs:17)
    at u (tfjs:17)
    at Generator._invoke (tfjs:17)
    at Generator.forEach.e.<computed> [as next] (tfjs:17)
    at Um (tfjs:17)
    at o (tfjs:17)
    at tfjs:17
    at new Promise (<anonymous>)
    at e.<anonymous> (tfjs:17)

**Comment by rthadur** [comment]
@startonggithub is it possible to share the model which you are using ?

**Comment by startonggithub** [comment]
hi rthadur, here is the model. Thanks. 

[model.zip](https://github.com/tensorflow/tfjs/files/5845242/model.zip)

**Comment by gaikwadrahul8** [comment]
Hi, @startonggithub 

Apologize for the delayed response and we're re-visiting our older issues and checking whether those issues got resolved or not as of now so May I know are you still looking for the solution or your issue got resolved ?

If issue still persists after trying with latest version of TFJs please let us know with error log and code snippet to replicate the same issue from our end ?

Could you please confirm if this issue is resolved for you ? Please feel free to close the issue if it is resolved ? Thank you!

**Comment by Akinleyejoshua** [comment]
Thanks for reaching out to me - the issue has been resolved.

**Comment by Akinleyejoshua** [comment]
Yes, everything is fine.

**Comment by sherbeee** [comment]
hello @startonggithub @Akinleyejoshua, im currently facing the same error when i am trying to run a model using the tfjs library. we are using v4.11.0. may i know how did you resolve your issue?
