### ISSUE TITLE
tf.nonmaxsuppression() in webgl locks the ui thread. call tf.nonmaxsuppressionasync() instead

### ISSUE THREAD

**Issue by gaurav8809** [tensorflow/tfjs#4680]
Getting this warning when using Cocossd in tfjs/react-native

- TensorCamera preview looks laggy for real-time object detection
- Getting only one object in prediction array all time

Please give any solution for smooth camera view and fast object detection through Cocossd

**Comment by rthadur** [comment]
It looks like you haven't used a template to create this issue. Please resubmit your issue using a template from [here](https://github.com/tensorflow/tfjs/issues/new/choose). We ask users to use the template because it reduces overall time to resolve a new issue by avoiding extra communication to get to the root of the issue. We will close this issue in lieu of the new one you will create from the template. Thank you for your cooperation.

**Comment by AdarshJais** [comment]
> Getting this warning when using Cocossd in tfjs/react-native
> 
> * TensorCamera preview looks laggy for real-time object detection
> * Getting only one object in prediction array all time
> 
> Please give any solution for smooth camera view and fast object detection through Cocossd


Did you got the solution ??

**Comment by julianklumpers** [comment]
Any update on this?

**Comment by uffoltzl** [comment]
> 
> 
> Getting this warning when using Cocossd in tfjs/react-native
> 
>     * TensorCamera preview looks laggy for real-time object detection
> 
>     * Getting only one object in prediction array all time
> 
> 
> Please give any solution for smooth camera view and fast object detection through Cocossd

Did you find a solution?

**Comment by spector32** [comment]
This is still a problem.

**Comment by xiibrightside** [comment]
any updates on this ?

**Comment by fatihatac** [comment]
Same problem.

**Comment by JunekCZ** [comment]
Same problem.

**Comment by micbaumr** [comment]
same problem

**Comment by AmitHBhagat** [comment]
Same problem

**Comment by akhilkrishnan1268** [comment]
Have any one solved it.?

**Comment by kevinroleke** [comment]
same problem
