### ISSUE TITLE
Not getting anything as result from facemesh..estimateFaces({input: nextImageTensor}) function in React Native

### ISSUE THREAD

**Issue by gaurav8809** [tensorflow/tfjs#4683]
Getting 0 length array value from facemesh..estimateFaces({input: nextImageTensor})

- Passing Tensor3D Image as input into the function
- Using TensorCamera as camera and tensor3D type of image

**Comment by rthadur** [comment]
It looks like you haven't used a template to create this issue. Please resubmit your issue using a template from [here](https://github.com/tensorflow/tfjs/issues/new/choose). We ask users to use the template because it reduces overall time to resolve a new issue by avoiding extra communication to get to the root of the issue. We will close this issue in lieu of the new one you will create from the template. Thank you for your cooperation.
