### ISSUE TITLE
Lint with gts

### ISSUE THREAD

**Issue by mattsoulanille** [tensorflow/tfjs#4706]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow.js version (you are using): N/A
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**
Code linting is currently done by vscode, but we should probably lint with something like [gts](https://github.com/google/gts).
**Will this change the current api? How?**
It may change how code is formatted, but I think the current vscode formatting is similar to gts.
**Who will benefit with this feature?**
Everyone.
**Any Other info.**

**Comment by gaikwadrahul8** [comment]
Hi, @mattsoulanille 

Thank you for opening this issue for tracking purposes. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFJs team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TFJs [version](https://github.com/tensorflow/tfjs/releases/tag/tfjs-v4.12.0) with the latest compatible hardware configuration which could potentially resolve the issue.

Based on our internal discussion, we are closing this issue at this time. If you still feel that this feature request is relevant, please feel free to create a new issue.

Thank you for your support and cooperation.
