### ISSUE TITLE
prices data model

### ISSUE THREAD

**Issue by js08** [tensorflow/tfjs#4721]
Hi,

I am trying to apply AI and ML algorithms in my data, there are hundred thousand stores with competitors, where gas prices changes 15 minutes once. 
Assume in each city if I have my own gas station and how should I give my prices so that more customers come to my store.

Can we apply AI for my above logic. If so can we do a poc in codesandbox using tensor flow and react native

https://codesandbox.io/s/ktncm

sample json

[
    {
        c: false
        i: 4540
        ic: "41418"
        ico: "walamart.png"
        l: "41418 - walamrt"
        la: "35.18903"
        lo: "-97.45071"
        r: "1.699"
    },
    {
        c: false
    i: 4635
    ic: "41649"
    ico: "711.png"
    l: "32323- walmart - HOUSTON, TX"
    la: "29.8504"
    lo: "-95.49"
    r: "1.719"
    }
]

**Comment by rthadur** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow.js) since it is not a bug or feature request. There is also a larger community that reads questions there.
You can try  checking https://github.com/tensorflow/tfjs-examples to see if any examples is relevant to your requirement. Thank you
