### ISSUE TITLE
object_detection训练的模型转换为tfjs速度很慢

### ISSUE THREAD

**Issue by zhanghu11** [tensorflow/tfjs#4814]
转换后速度很慢，tf2.2 ,tfjs3.2,请问如何优化，如何转换

**Comment by zhanghu11** [comment]
可以的话加我微信请教13033547336

**Comment by rthadur** [comment]
It looks like you haven't used a template to create this issue. Please resubmit your issue using a template from [here](https://github.com/tensorflow/tfjs/issues/new/choose). We ask users to use the template because it reduces overall time to resolve a new issue by avoiding extra communication to get to the root of the issue. We will close this issue in lieu of the new one you will create from the template. Thank you for your cooperation.

Note : If possible please translate.
