### ISSUE TITLE
[react-native] Tensorcamera is not properly working with expo-camera method recordAsync

### ISSUE THREAD

**Issue by dhiogocorrea** [tensorflow/tfjs#4829]
**Describe the current behavior**
After cameraRef.current.camera.recordAsync() resolves (using stopRecording, for example), it returns the URI of the video as excepted, but the video is blank (0 seconds).

**Describe the expected behavior**
The final video, from the moment that recordAsync was called to the moment that it stopped.

Testing the same code using expo-camera directly returns the video as expected.

**Code snippet to test**

```
import React, {useEffect, useState, useRef} from 'react';
import * as Permissions from 'expo-permissions';
import {Camera} from 'expo-camera';
import {cameraWithTensors} from '@tensorflow/tfjs-react-native';
import {ScrollView, Button, Text} from 'react-native';

import Video from 'react-native-video';

export const TFCameraRecordingTest = () => {
  const cameraRef = useRef();

  const TensorCamera = cameraWithTensors(Camera);

  const [hasPermission, setHasPermission] = useState(false);
  const [videoUrl, setVideoUrl] = useState(null);
  const [recording, setRecording] = useState(false);

  useEffect(() => {
    handlePermission();
  }, []);

  const handlePermission = async () => {
    const {status} = await Permissions.askAsync(Permissions.CAMERA, Permissions.AUDIO_RECORDING);
    setHasPermission(status === 'granted');
  };

  const startRecording = async () => {
    cameraRef.current.camera.recordAsync().then(result => {
      setVideoUrl(result.uri);
    });

    setRecording(true);

    setTimeout(() => {
      stopRecording();
    }, 5000);
  };

  const stopRecording = () => {
    cameraRef.current.camera.stopRecording();
    setRecording(false);
  };

  return (
    <ScrollView>
      <TensorCamera
        ref={cameraRef}
        // Standard Camera props
        style={{
          width: 600,
          height: 600,
        }}
        type={Camera.Constants.Type.front}
        zoom={0}
        // tensor related props
        cameraTextureHeight={1200}
        cameraTextureWidth={1600}
        resizeHeight={200}
        resizeWidth={200}
        resizeDepth={3}
        autorender={true}
      />
      <Button onPress={() => startRecording()} disabled={hasPermission === false && recording === true}>
        Start
      </Button>
      {videoUrl !== null && (
        <React.Fragment>
          <Text>{videoUrl}</Text>
          <Video source={{uri: videoUrl}} />
        </React.Fragment>
      )}
    </ScrollView>
  );
};
```

**Comment by rthadur** [comment]
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by dhiogocorrea** [comment]
> In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

Added code snippet.

**Comment by dhiogocorrea** [comment]
any suggestions?

**Comment by jinjingforever** [comment]
Hi Dhiogo, sorry for the delay.. I am currently a little bit busy with some other projects, but will take a look at this issue some time this week (thanks for the code snippet btw). Thank you for your patience!

**Comment by dhiogocorrea** [comment]
> Hi Dhiogo, sorry for the delay.. I am currently a little bit busy with some other projects, but will take a look at this issue some time this week (thanks for the code snippet btw). Thank you for your patience!

Hey Jin! All good, I understand! Thank you for the reply!

Looking forward to solve this issue. I have tried some workarounds, but none of them worked :(

**Comment by jinjingforever** [comment]
Hi Dhiogo,

I think the issue is caused by this line:

`const TensorCamera = cameraWithTensors(Camera);`

If I move it to outside of `TFCameraRecordingTest` (e.g. right after the `import Video from 'react-native-video'` line), your could would work. 

I am not a react-native expert, but I am guessing that the `setRecording(true)` call when the recording is started will trigger the component to re-render which will create a new TensorCamera component instance (since it is not a "state" variable I guess). This will make things messy. If you want to leave it inside `TFCameraRecordingTest`, you can try the following which seems to work as well:

`const TensorCamera = useRef(cameraWithTensors(Camera)).current;`

One unfortunate thing is that, even this can record a video, the TensorCamera view would freeze during the recording:) This is probably caused by how the TensorCamera renders stuff on the screen (through expo-gl I think). If you couldn't find a solution to this, please feel free to file a new issue (but it might be low priority for now:))

Thank you!
