### ISSUE TITLE
Too many duplicated code in all backends

### ISSUE THREAD

**Issue by qjia7** [tensorflow/tfjs#5054]
There are too many duplicated codes in all backends. For example:
1. Validation code. For the parameter validation, we can do it in the front end instead of doing it in all backends. 
2. For some ops, they are using *ImplCPU for all backends. 
3.  For some ops, they don't need a backend specific kernel. For example, `Identity`, `ExpandDims`.
4. For some common optimizations, for example, in some situations, this operation is just return an Identity of itself or reshape. 

All of above situations, maybe we can put them in the front end (`fjs-core/src/ops/`) instead of making a copy in all backends.

Take #5025 as an example,  it seems that `SparseSegmentMean` is using a cpu implementation. I suppose it will be same for all backends although only cpu/webgl was covered in that PR.

**Comment by qjia7** [comment]
@pyu10055 @lina128 Any thoughts on this?

**Comment by pyu10055** [comment]
@qjia7 Thank you for raising this issue. The backend kernel is designed this way to allow tree shaking and custom bundle. We can discuss more in our weekly sync.

**Comment by gaikwadrahul8** [comment]
Hi, @qjia7 

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFJs team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TFJs [version](https://github.com/tensorflow/tfjs/releases/tag/tfjs-v4.10.0) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tfjs/blob/master/README.md) to stay up to date with the latest developments which are happening in the Tensorflow.js space.

Thank you for your support and cooperation.

**Comment by qjia7** [comment]
No further actions on this.
