### ISSUE TITLE
TFJS executeAsync gives warning/any penalty;

### ISSUE THREAD

**Issue by rohanmuplara** [tensorflow/tfjs#5219]
When I am running with executeAsync, it gives a warning. 
"This model execution did not contain any nodes with control flow or dynamic output shapes. You can use model.execute()" 
This seems to apply executeAsync has some disadvantage. Is there any performance penalty when using executeAsync or any other disadvantages .  I think decent number of people would want to use async and not block while model is running.

**Comment by pyu10055** [comment]
@rohanmuplara This might be a miss naming of the methods. The `model.executeAsync()` is catered to models that contains control flow (ie. branch, loops) in the model topology. It cannot pre-compile and cache the execution plan (serialize the model execution) as `model.execute()` would do.  
Both of the methods will be execution the kernels asynchronously with WebGL backend, meaning the javascript portion of the model execution usually are minimal (UI blocking), and mostly of the work is queued up and done on the GPU. You call `data()` method to retrieve the output asynchronously. 
For models without control flow or dynamic output shapes, `model.executeAsync()` would not give you any performance gain, since javascript execution will still be serialized.

**Comment by rohanmuplara** [comment]
Thanks for you help. I think I am still a little unclear why executeAsync then needs to return a promise. Is it because it takes some time setting up stuff for the gpu compared to the regular model.execute. I think also in documentation it would be great if you guys could add a few lines on differences between predict, execute, executeAsync and what is recommended/when to use what

**Comment by pyu10055** [comment]
@rohanmuplara The reason executeAsync need to return promise is that the model execution needs to read intermediate data from GPU and that is an async process. For execute or predict method, there is no need to read intermediate GPU data.

**Comment by rohanmuplara** [comment]
Ok makes sense. My where's right now are at the end of the model graph.  Is there any performance advantage of separating them out into their own graph, or putting them in the beginning of the graph. (I have a pipeline of mobilnet models so I can theorethically put the wheres at the beginning of the model(

**Comment by rohanmuplara** [comment]
@pyu10055 Also, I notice when running my models even though they are being called in an async function, when the models are running the ui is very slow and not responsive. Is that expected and due to models running in webgl? Any tricks to optimize this?

**Comment by rohanmuplara** [comment]
@pyu10055 I looked into more and when I call console.log before and after the model, it takes the whole model prediction time. This is the first I call it and I believe this is in webgl when it is setting everything up.
