### ISSUE TITLE
Problems when running tflite demo

### ISSUE THREAD

**Issue by Zengyf-CVer** [tensorflow/tfjs#5266]
##### I run [the demo in tflite](https://github.com/tensorflow/tfjs/tree/master/tfjs-tflite/demo), the chrome console has such a problem：
![ksnip_20210630-195510](https://user-images.githubusercontent.com/41098760/123956647-80647880-d9dd-11eb-9d57-75896c38bcb0.png)

**Comment by jinjingforever** [comment]
Looks like there is a typo in the README file which will cause the `download-tflite-web-api.sh` script to fail (it should be `./scripts` instead of `./script`). I have a PR to update the README file to make things more clear.

Note that you do need to successfully build the tfjs-tflite package locally before running the demo. I tested the steps (after the typo fix) on my machine and they seem to work. Here is the [screenshot](https://drive.google.com/file/d/1PjJAY1bl4XCFEqBoYn7NYO8SsNxku0ur/view?usp=sharing) of all the commands I ran and their outputs.

After my PR is merged please give it another try. Thanks!

**Comment by Zengyf-CVer** [comment]
@jinjingforever 
I followed your method to the step of `yarn watch`, and the error in the picture occurred:
![ksnip_20210701-100202](https://user-images.githubusercontent.com/41098760/124053926-b0e6f980-da53-11eb-9ac2-8d60bb908b4d.png)
I only installed `@tensorflow/tfjs-core` with yarn. I don't know what else needs to be installed for the code to work, or what caused the error in the picture above?
![ksnip_20210701-100520](https://user-images.githubusercontent.com/41098760/124054206-2357d980-da54-11eb-9eb2-94df69c426b9.png)

**Comment by Zengyf-CVer** [comment]
The problem is solved, the location of `yarn add` is wrong, I should execute it in the demo directory. thank you.
