### ISSUE TITLE
How to use execute instead of executeAsync for object detection model?

### ISSUE THREAD

**Issue by Jove125** [tensorflow/tfjs#5377]
Good day!

I have integrated Unity WebGL with TensorflowJS.
When calling the JavaScript script from Unity, I need to return the search result for objects detection.
The result must be obtained synchronously, since it is used in Unity for post-processing (realtime, in the same frame).

How can I use execute instead of executeAsync for object detection (mobilenet v3)?

Now, when I try to call executeAsync, I get the error:
Uncaught (in promise) Error: This execution contains the node 'Postprocessor/BatchMultiClassNonMaxSuppression/map/while/Exit_2', which has the dynamic op 'Exit'. Please use model.executeAsync() instead. Alternatively, to avoid the dynamic ops, specify the inputs [Postprocessor/BatchMultiClassNonMaxSuppression/map/TensorArrayStack/TensorArrayGatherV3]

**Comment by rthadur** [comment]
Please provide a codepen example or git repo for us to reproduce the same , meanwhile can you please check below related issue https://github.com/tensorflow/tfjs/issues/4579 , thank you

**Comment by Jove125** [comment]
**rthadur**,
You can see my sample code and model here:
https://github.com/tensorflow/tfjs/issues/5259

It work with version 3.3.0 when using the execute function and doesn't work with executeAsync function.

**Comment by gaikwadrahul8** [comment]
Hi, @Jove125 

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFJs team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TFJs [version](https://github.com/tensorflow/tfjs/releases/tag/tfjs-v4.10.0) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tfjs/blob/master/README.md) to stay up to date with the latest developments which are happening in the Tensorflow.js space.

Thank you for your support and cooperation.
