### ISSUE TITLE
[e2e] Failed to catch failure caused by tint change

### ISSUE THREAD

**Issue by axinging** [tensorflow/tfjs#5397]
Recently due to tint changed the shared memory size policy, all webgpu conformance should fail. However, e2e failed to catch this error. There are two reasons for this:
1. The predict results of most models are objects, instead of arrays. Current implementation assumes that the predict results are arrays, which results in some fake pass. This can be fixed by https://github.com/tensorflow/tfjs/pull/5384.
2. Models with tensor input still got passed with https://github.com/tensorflow/tfjs/pull/5384 applied, though they are indeed failed due to tint change. This is because the input for tensor are some special values(such as zeros), and so does the predict results. We should change those tensor values to guarantee the test is valid.

**Comment by rthadur** [comment]
@axinging can we close this issue ?

**Comment by axinging** [comment]
@rthadur, Below issue is still not resolved:

2. Models with tensor input still got passed with [e2e] Fix object compare #5384 applied, though they are indeed failed due to tint change. This is because the input for tensor are some special values(such as zeros), and so does the predict results. We should change those tensor values to guarantee the test is valid.

**Comment by gaikwadrahul8** [comment]
Hi, @axinging 

Apologize for the delayed response and we're re-visiting our older issues and checking whether those issues got resolved or not as of now so May I know are you still looking for the solution or your issue got resolved ?

If issue still persists after trying with latest version of TFJs please let us know with error log and code snippet to replicate the same issue from our end ?

Could you please confirm if this issue is resolved for you ? Please feel free to close the issue if it is resolved ? Thank you!
