### ISSUE TITLE
(ranged) Sigmoid layer in advanced activation function

### ISSUE THREAD

**Issue by bibs2091** [tensorflow/tfjs#5452]
- Are you willing to contribute it (Yes I am willing to):

In tfjs, there is a lot of activation functions as a layer, but what is weirdly missing is layers.sigmoid.

This day I was making a dot product matrix factorization recommender system and the output of the dot layer should be in between 0 and 1, for this layers.sigmoid is needed.

FastAI also offer ranged sigmoid which is very interesting, it squeeze the value into a range ]a,b[ instead of ]1,0[, this can be also used in my case when i need to predict ratings in a certain range (let's say ratings from 1 star to 5 stars).

I can contribute to add this feature.

**Comment by sourabh112** [comment]
@rthadur Thanks for the opportunity and sorry for the late reply. I was making myself comfortable with the code of the advanced activation layer. In order to accommodate the sigmoid layer in advanced activation layers. I just need to make some changes to the` exports_layers.ts` and `advanced_activations.ts` files. I will make a PR hopefully by tomorrow. with these changes with a working example. After that, I will add test in `advanced_activations.ts` and make any changes if needed.

**Comment by sourabh112** [comment]
@rthadur As for the ranged sigmoid function suggested by @bibs2091 might be a difficult task because (As per my knowledge) there is no file related to the ranged sigmoid activation function and I have to implement that from scratch. In doing so, I would need some (Actually a lot in the tfjs-core part where actually these functions start) help. If you allow doing that, then I will do that in the same PR after implementing stuff included in the above comment. 

If you think I'm wrong somewhere please correct me.

**Comment by bibs2091** [comment]
@rthadur the implementation of SigmoidRange is in this pull request https://github.com/tensorflow/tfjs/pull/5548 ,
 kindly review it it and tell me what do you think.

@sourabh112  I am sorry I did not notice that you have been assigned, I already started working on the issue days ago and I wrote in my issue that I am ready to contribute to the idea.

**Comment by sourabh112** [comment]
@bibs2091 No problem, I was just starting to work on it. And after going through your PR. I got to know that I was on quite a bit wrong path. And sorry for not reading the last line of the issue.

**Comment by gaikwadrahul8** [comment]
Hi, @bibs2091 

Apologize for the delayed response and we are re-visiting our older feature requests and checking whether those feature requests implemented or not as of now and I see you've submitted PR https://github.com/tensorflow/tfjs/pull/5548 for this feature request and you're facing some issue w.r.t test and was waiting to merge this PR https://github.com/tensorflow/tfjs/pull/6424 and now that PR got merged so May I know are you still working on this feature request in TFJs ? 

If someone wants to contribute for this feature then you're always welcome and please feel free to do and please refer these links [Ref-1](https://github.com/tensorflow/tfjs/blob/master/CONTRIBUTING.md), [Ref-2](https://github.com/tensorflow/tfjs/blob/master/CONTRIBUTING_MISSING_OP.md) . Thank you!
