### ISSUE TITLE
How to use existing tensorflow.js model in keras

### ISSUE THREAD

**Issue by wirlsawyer** [tensorflow/tfjs#5481]
I have tensorflow.js model which I have converted to keras but could not got same predict in keras, what wrong?

**Comment by rthadur** [comment]
It looks like you haven't used a template to create this issue. Please resubmit your issue using a template from [here](https://github.com/tensorflow/tfjs/issues/new/choose). We ask users to use the template because it reduces overall time to resolve a new issue by avoiding extra communication to get to the root of the issue. We will close this issue in lieu of the new one you will create from the template. Thank you for your cooperation.
