### ISSUE TITLE
fromPixels results are inconsistent for image input

### ISSUE THREAD

**Issue by axinging** [tensorflow/tfjs#5482]
Reproduce steps:
  1. Build and run e2e(yarn build-deps, npx-http-server), then load bodypix or posenet, select input type image. 
  2. Click “Test correctness”, when the test is done,  click it again. 
  3. Check the results from console, ypu will see the results mismatch.

Problem investigation:
  This problem is caused by chromium's canvas implementation. It can be workaround with recreate canvas context every time, or turn on chrome://flags/#new-canvas-2d-api. I have filed a bug for chromium here: https://bugs.chromium.org/p/chromium/issues/detail?id=1239467, and WIP fix here: https://chromium-review.googlesource.com/c/chromium/src/+/3092523.

Test case:
     Besides above reproduce steps, you can also use below single page case to reproduce this issue:
```
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1.0, user-scalable=no">

<body>
    <div id="info" style='display:none'></div>
    <div id="predictions"></div>

    <video id="video" playsinline style="
    -webkit-transform: scaleX(-1);
    transform: scaleX(-1);
    display: none;
    width: auto;
    height: auto;
    ">
    </video>
    <canvas id="output" style=""></canvas>
    <canvas id="hand_cut" style=""></canvas>
    <div id="status"></div>
    <script src="https://unpkg.com/@tensorflow/tfjs-core@latest/dist/tf-core.js" crossorigin></script>
    <script>

        function getURLState(url) {
            let params = new URLSearchParams(url);
            const keys = [...params.keys()];
            if (keys.length === 0) return 0;
            if (params.has('recreate')) {
                return true;
            }
            return false;
        }
        async function loadImage(imagePath) {
            const imageBucket =
                'https://storage.googleapis.com/tfjs-models/assets/posenet/';
            const image = new Image();
            const promise = new Promise((resolve, reject) => {
                image.crossOrigin = '';
                image.onload = () => {
                    resolve(image);
                };
            });

            image.src = `${imageBucket}${imagePath}`;
            return promise;
        }

        function consoleLogArray(array, printLen = 3, comment = '') {
            if (printLen > array.length) {
                throw new Error("Print len is bigger than array.length");
            }

            console.log(comment + array.slice(0, printLen).toString());
        }

        async function fromPixelWrap(recreateContext = false) {
            const image = await loadImage('tennis_standing.jpg');
            const fpImage = tf.browser.fromPixels(image);;
            return fpImage;
        }

        async function testFromPixel() {
            const recreateContext = getURLState(window.location.search);
            console.log(recreateContext);
            const fpImage1 = await fromPixelWrap(recreateContext);

            const fpImage2 = await fromPixelWrap(recreateContext);
            consoleLogArray(await fpImage1.data());
            consoleLogArray(await fpImage2.data());
            tf.test_util.expectArraysClose(await fpImage1.data(), await fpImage2.data());
        }

        const bindPage = async () => {
            await testFromPixel();
        }
        bindPage();

    </script>
</body>

```

<html>
<body>

Google Chrome | 94.0.4605.0 (Official Build) canary (64-bit) (cohort: Clang-64)
-- | --
Revision | a03befa72fc2a3d296e323116474694029ca21aa-refs/branch-heads/4605@{#1}
OS | Windows 10 OS Version 2004 (Build 19041.1110)
JavaScript | V8 9.4.146

</body>
</html>

**Comment by lina128** [comment]
Hi @axinging, will clearRect() before drawing another image help?

**Comment by axinging** [comment]
@lina128 , indeed I have tried the clearRect, not work. Currently the workarounds are : recreate canvas context every time, or turn on chrome://flags/#new-canvas-2d-api.

**Comment by shaoboyan** [comment]
@axinging Will adopt the recreate canvas context every time for now and mitigate to new API when it is released based on https://bugs.chromium.org/p/chromium/issues/detail?id=1239467#c5

**Comment by lina128** [comment]
Hi, we tested this behavior on three browsers. Safari and Firefox don't have this issue, the first draw are both on GPU. Only Chrome has this issue. For Chrome, we explored three methods, all of them have some caveats. Method 1 is the most promising, but the problem is that it is still not very reliable. In some circumstances, the first few drawImage calls happen in CPU (e.g. if they are in the same scope in JS), so drawing one more time still doesn't work in these cases. Also this approach will incur duplicate fromPixel call to draw, download and upload data. We think what you observed most likely only happens in test, and in reality it's likely someone wants to call fromPixels on the same image twice. But it's a nice finding, we can add a warning in this method's doccomment, so that people are aware of this, and if they really want the two calls to yield exactly same result, they can call fromPixels three times and only use the last two results. The same applies to your test. 

Given that we have a workaround, we prefer not to modify the original behavior, as stated above the fix would add unnecessary computation and is not reliable.
