### ISSUE TITLE
[webgpu]Remove tfjs-backend-webgpu/src/kernels/pool_webgpu_test.ts

### ISSUE THREAD

**Issue by axinging** [tensorflow/tfjs#5506]
This case is specially for For PoolWithFilterSizeEqualsOneProgram. 
And this case will fail wasm, Wasm bug: https://github.com/tensorflow/tfjs/issues/5471.
When wasm bug got fixed, removed it.

(And Xing will follow up this)

**Comment by gaikwadrahul8** [comment]
Hi, @axinging 

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFJs team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TFJs [version](https://github.com/tensorflow/tfjs/releases/tag/tfjs-v4.10.0) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tfjs/blob/master/README.md) to stay up to date with the latest developments which are happening in the Tensorflow.js space.

Thank you for your support and cooperation.
