### ISSUE TITLE
Latest released @tensorflow/tfjs-core 3.9.0 missed some files.

### ISSUE THREAD

**Issue by BruceDai** [tensorflow/tfjs#5566]
Current @tensorflow/tfjs-core 3.9.0 only have following 
```sh
node_modules/@tensorflow/tfjs-core$ ls
dist  package.json  README.md
```

while @tensorflow/tfjs-core 3.8.0 had
```sh
node_modules/@tensorflow/tfjs-core$ ls
BUILD.bazel  cloudbuild.yml  development  dist  package.json  README.md  scripts  setup_test_bazel.ts  src  test.html  tsconfig.test.json
```

**Comment by BruceDai** [comment]
Link https://github.com/webmachinelearning/webnn-polyfill/issues/114

**Comment by mattsoulanille** [comment]
Thanks for the bug report! This is actually intentional as part of the Bazel build migration. We omitted TS source files (along with other files) in the most recent release because they are not used by downstream packages (although it seems like your package is an exception).

In the issue you linked, I noticed you're using `@tensorflow/tfjs-core/src/ops/conv_util`. Could you instead import `@tensorflow/tfjs-core/dist/ops/conv_util`, or does this not work for your use case?

**Comment by BruceDai** [comment]
Thanks much @mattsoulanille. It works for my case.
