### ISSUE TITLE
Enhance benchmark result

### ISSUE THREAD

**Issue by lina128** [tensorflow/tfjs#5634]
Refactor the database schema to include failure cases as well. Revise the addResultToFirestore function to also store failure results to Firebase. https://github.com/tensorflow/tfjs/blob/master/e2e/benchmarks/browserstack-benchmark/firestore.js#L73-L81

**Comment by gaikwadrahul8** [comment]
Hi, @lina128 

Thank you for opening this issue for tracking purposes. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFJs team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TFJs [version](https://github.com/tensorflow/tfjs/releases/tag/tfjs-v4.12.0) with the latest compatible hardware configuration which could potentially resolve the issue.

Based on our internal discussion, we are closing this issue at this time. If you still feel that this feature request is relevant, please feel free to create a new issue.

Thank you for your support and cooperation.
