### ISSUE TITLE
Export function "nameScope" in "tfjs-layers" module

### ISSUE THREAD

**Issue by JanKaul** [tensorflow/tfjs#5661]
**System information**
- TensorFlow.js version: 3.9.0
- Are you willing to contribute it: Yes

Feature: Expose the function "nameScope" from "tfjs-layers/src/common.ts" to the tfjs-layers module. This enables the serialization/deserialization of custom layers that contain other layers with weights.

It will add the function "nameScope" to the publicly visible API of tfjs-layers.

This will benefit anybody who want the serialize/deserialize more complex custom layers.

**Comment by rthadur** [comment]
@JanKaul thank you , do you wish to contribute for this ?

**Comment by JanKaul** [comment]
Yes, I will try to prepare a PR.

**Comment by gaikwadrahul8** [comment]
Hi, @JanKaul 

Apologize for the delayed response and we are re-visiting our older feature requests and checking whether those feature requests implemented or not as of now and as you mentioned in your previous comment you'll submit PR for this feature request so May I know are you still working on it or have you already submitted PR for this please ?

If someone wants to contribute for this feature then you're always welcome and please feel free to do and please refer these links [Ref-1](https://github.com/tensorflow/tfjs/blob/master/CONTRIBUTING.md), [Ref-2](https://github.com/tensorflow/tfjs/blob/master/CONTRIBUTING_MISSING_OP.md) . Thank you!

**Comment by JanKaul** [comment]
Hi, @gaikwadrahul8 

thanks for the follow up. I didn't get around to implementing the feature. Since I won't need it anymore I will not be working on this. Should I therefore close the issue?

**Comment by gaikwadrahul8** [comment]
Hi, @JanKaul 

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFJs team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TFJs [version](https://github.com/tensorflow/tfjs/releases/tag/tfjs-v4.10.0) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tfjs/blob/master/README.md) to stay up to date with the latest developments which are happening in the Tensorflow.js space.

I see your previous comment, you won't need this feature and not working on this feature request so please feel free to close this issue.

Thank you for your support and cooperation.
