### ISSUE TITLE
tfjs-react-native RangeError when loading model in release variant

### ISSUE THREAD

**Issue by kudlav** [tensorflow/tfjs#5717]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js):
   `custom code`
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
   `MacOS 11.6 (20G165)`
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
   `Samsung Galaxy A40`
- TensorFlow.js installed from (npm or script link):
   `npm`
- TensorFlow.js version (use command below):
   `"@tensorflow/tfjs": "3.9.0"`, `"@tensorflow/tfjs-react-native": "0.7.0",`
- Browser version:
   `"react-native": "0.66.4", ejected from expo`
- Tensorflow.js Converter Version:
   `TensorFlow.js Converter v3.9.0`

**Describe the current behavior**
When building with `npx react-native run-android --variant=release` I am unable to load model. But it works fine when building with `npx react-native run-android`
Invoking `tf.loadGraphModel(bundleResourceIO(modelJson, modelWeights))` causes:

```
    ArrayBuffer length minus the byteOffset is not a multiple of the element size
```

Same when releasing APK. But the model assets are included in APK.

**Standalone code to reproduce the issue**
```
 import React, {Component} from 'react';
 import { Text, View, Button, ScrollView } from 'react-native';
 
 import * as tf from '@tensorflow/tfjs';
 import { bundleResourceIO } from '@tensorflow/tfjs-react-native';
 
 export default class MainScreen extends Component {
   constructor(props) {
	 super(props);
	 this.tfReady = false;
	 this.model = null;
   }

   componentDidMount() {
	 tf.ready().then(() => {
	   this.tfReady = true;
	   this.onStatus({ status: `TF loaded, backend: ${tf.getBackend()}` });
	 });
   }
 
   loadComponentConfig = async () => {
	 if (this.tfReady) {
	   const modelJson = require('./assets/model.json');
	   const modelWeights = require('./assets/group1-shard1of1.bin');
	   tf.loadGraphModel(bundleResourceIO(modelJson, modelWeights)).then(model => {
		 this.model = model;
		 this.onStatus({ status: `TF Model loaded` });
	   }).catch(e => {
		 this.onError({ error: `TF Model failed to load: ${e}` });
	   });
	 }
   };
...
```

**Other info / logs**
Provided code produces following output:
```
 Status: TF loaded, backend: rn-webgl
 Error: TF Model failed to load: RangeError: ArrayBuffer length minus the byteOffset is not a multiple of the element size
```

from package.json
```
"dependencies": {
    "@react-native-async-storage/async-storage": "~1.15.0",
    "@tensorflow/tfjs": "^3.9.0",
    "@tensorflow/tfjs-backend-wasm": "^3.9.0",
    "@tensorflow/tfjs-react-native": "^0.7.0",
    "expo": "~42.0.1",
    "expo-camera": "~11.2.2",
    "expo-gl": "~10.4.2",
    "expo-gl-cpp": "~10.4.1",
    "expo-splash-screen": "~0.11.2",
    "expo-status-bar": "~1.0.4",
    "expo-updates": "~0.8.1",
    "next-frame": "^0.2.3",
    "react": "16.13.1",
    "react-dom": "^17.0.2",
    "react-native": "~0.63.4",
    "react-native-async-storage": "^0.0.1",
    "react-native-fs": "^2.18.0",
    "react-native-gesture-handler": "~1.10.2",
    "react-native-progress": "^5.0.0",
    "react-native-reanimated": "~2.2.0",
    "react-native-screens": "~3.4.0",
    "react-native-threads": "^0.0.19",
    "react-native-unimodules": "0.14.10",
    "react-native-web": "^0.17.5"
  },
```

**Comment by tomashornak** [comment]
Hi. Are there any updates on this or did you come to any workaround?
We came to similar issue, only with APK for release and only with YOLOv5 tfjs model: https://github.com/ultralytics/yolov5/issues/7853

**Comment by gaikwadrahul8** [comment]
Hi, @kudlav 

Apologize for the delayed response and we're re-visiting our older issues and checking whether those issues got resolved or not as of now so May I know are you still looking for the solution or your issue got resolved ?

If issue still persists after trying with latest version of TFJs and I would request you to please give it try with mentioned packages version in as per this [official documentation](https://github.com/tensorflow/tfjs-examples/tree/master/react-native) and please let us know whether your issue is resolving or not ? if issue still persists please help us with error log and code snippet to replicate the same issue from our end ?

Could you please confirm if this issue is resolved for you ? Please feel free to close the issue if it is resolved ? Thank you!

**Comment by kudlav** [comment]
I'm not working with tfjs anymore, maybe @tomashornak will assist you.

**Comment by gaikwadrahul8** [comment]
Hi, @kudlav 

Thank you for the confirmation and @tomashornak Do you any help on this issue or your issue got resolved most probably there may be package dependancies compatible issue so please try to use above mentioned package dependancies and check whether your issue is resolving or not ? 

If issue still persists after trying with above mentioned package dependancies please let us know with error log ? Thank you!
