### ISSUE TITLE
tf.data.Dataset.size returns null

### ISSUE THREAD

**Issue by bibs2091** [tensorflow/tfjs#5845]
**System information**
- TensorFlow.js version: 3.10.0

**Describe the current behavior**
I created a tf.data.Dataset called validationDataset :
```
 let csvDataset: tf.data.Dataset<any> = (tf.data.csv(
            myPath, {
            configuredColumnsOnly: true,
            delimiter: options.delimiter,
            columnConfigs: {
                [options.userColumn]: {
                    required: true,
                    // dtype: "float32"
                },
                [options.itemColumn]: {
                    required: true,
                    // dtype: "float32"
                },
                [options.ratingColumn]: {
                    isLabel: true,
                    // dtype: "float32"
                }
            }
        })).shuffle( 100 ).map((x: any) => (
            { xs: { user: this.datasetInfo.userToModelMap.get(`${x.xs[options.userColumn]}`), item: this.datasetInfo.itemToModelMap.get(`${x.xs[options.itemColumn]}`) }, ys: { rating: Number(x.ys[options.ratingColumn]) } }
        ))

let validationPercentage = 0.1;
this.validationDataset = csvDataset.skip(trainSize).batch(this.batchSize);
this.validationDataset = this.validationDataset.map((x: Idataset) => ({ xs: { user: x.xs.user.reshape([-1, 1]), item: x.xs.item.reshape([-1, 1]) }, ys: { rating: x.ys.rating.reshape([-1, 1]) } }))
```
But when I try to get the size of the validationDataset i get null:
```
console.log(this.validationDataset.size)
```
I know for a fact when I log the validationDataset that there are many elements in it yet it returns null.

Thank you

**Comment by shmishra99** [comment]
Hi @bibs2091 ,
Apology for the late response. I have replicated the issue and i am getting the same `{ size: null }`. 
Code : 
<img width="918" alt="image" src="https://user-images.githubusercontent.com/124146945/236292342-2b399373-5c2b-411e-904a-b274919f8b04.png">
As per TFJS [Documentation](https://js.tensorflow.org/api/latest/#class:data.CSVDataset:~:text=A%20Dataset%20represents,recapitulates%20the%20transformations.) `Data loading and transformation is done in a lazy, streaming fashion`. 
In your case, it seems that the size of the `validationDataset` dataset is not yet known because it has not been enumerated yet. You can try calling the `.forEachAsync` method on the dataset before accessing the size property.

Let me know if have I missed something here. Thank You !
