### ISSUE TITLE
TFLite support does not work in safari on iOS

### ISSUE THREAD

**Issue by SIY1121** [tensorflow/tfjs#5846]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js): `yes`
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): `iOS 15.0.2`
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: `iPad 7th gen`
- TensorFlow.js installed from (npm or script link): `npm`
- TensorFlow.js version (use command below): tfjs: `3.11.0` , tfjs-tflite: `0.0.1-alpha.7`
- Browser version: `Safari 15.0`
- Tensorflow.js Converter Version: `None`

**Describe the current behavior**
`tflite.loadTFLiteModel()` report the error on the console.

```
[Warning] INFO: Created TensorFlow Lite XNNPACK delegate for CPU. (tflite_web_api_cc.js, line 9)
[Warning] ERROR: failed to create XNNPACK runtime (tflite_web_api_cc.js, line 9, x50)
[Warning] ERROR: failed to delegate ADD node #2234 (tflite_web_api_cc.js, line 9)
[Warning] ERROR: failed to create XNNPACK runtime (tflite_web_api_cc.js, line 9)
[Warning] ERROR: failed to delegate ADD node #2247 (tflite_web_api_cc.js, line 9)
[Warning] ERROR: failed to create XNNPACK runtime (tflite_web_api_cc.js, line 9)
[Warning] ERROR: failed to delegate ADD node #2260 (tflite_web_api_cc.js, line 9)
[Warning] ERROR: failed to delegate MUL node #2269 (tflite_web_api_cc.js, line 9)
[Warning] ERROR: failed to create XNNPACK runtime (tflite_web_api_cc.js, line 9)
[Warning] ERROR: failed to delegate ADD node #2273 (tflite_web_api_cc.js, line 9)
[Warning] ERROR: failed to delegate FULLY_CONNECTED node #2728 (tflite_web_api_cc.js, line 9)
[Warning] ERROR: Node number 2762 (TfLiteXNNPackDelegate) failed to prepare. (tflite_web_api_cc.js, line 9)
[Warning] ERROR: Restored original execution plan after delegate application failure. (tflite_web_api_cc.js, line 9)
```

Then `model.predict()` failed. 

```
RuntimeError: abort(undefined). Build with -s ASSERTIONS=1 for more info.
```

I used pretrained `Onsets and Frames` model from magenta project.
https://github.com/magenta/magenta/tree/main/magenta/models/onsets_frames_transcription/realtime 

**Standalone code to reproduce the issue**
see https://github.com/SIY1121/tflite-worker-bug-test

**Comment by gaikwadrahul8** [comment]
Hi, @SIY1121 

Apologize for the delayed response and we're re-visiting our older issues and checking whether those issues got resolved or not as of now and I tried to reproduce the same issue on my Mac M1 system with safari browser and I am getting below output and I see worker model loaded message and also worker predict result so May I know is it working as expected or not ? If have I missed something here please let me know ?

Here is output screenshot on Mac M1 system with safari browser :

![image](https://github.com/tensorflow/tfjs/assets/115997457/1bb09874-bcfa-43af-a852-6ff3a530a91b)

Could you please confirm if this issue is resolved for you ? Please feel free to close the issue if it is resolved ? if issue still persists please let us know ? Thank you!
