### ISSUE TITLE
tf.ready() throwing JSON Parse error with react-native 0.66.3

### ISSUE THREAD

**Issue by kateinkim** [tensorflow/tfjs#5866]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS 11.6
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: iOS Simulator
- TensorFlow.js installed from (npm or script link): npm
- TensorFlow.js version: 3.11.0
- CUDA/cuDNN version:

**Describe the problem**
After spinning up a fresh react-native app and installing tfjs [per the instructions](https://www.npmjs.com/package/@tensorflow/tfjs-react-native) I'm getting the following error:

<img width="300" alt="CleanShot 2021-11-17 at 20 24 13@2x" src="https://user-images.githubusercontent.com/53795920/142347037-29340711-81c6-4afd-b182-e2d2fdb2f893.png">

**Provide the exact sequence of commands / steps that you executed before running into the problem**
1. Spin up a brand new react native app
2.  Follow tfjs react native instructions

**Any other info / logs**
Minimal reproduction: https://github.com/kateinkim/tfjs-rn-example

**Comment by efremovartem792** [comment]
Sometimes we experience the same issue when just calling tf.ready() after starting react native app (iOS 15 device).

@tensorflow/tfjs: 3.11.0
react-native: 0.65.1

**Comment by raienko** [comment]
same for me:
```
    "@react-native-async-storage/async-storage": "^1.15.14",
    "@tensorflow/tfjs": "^3.11.0",
    "@tensorflow/tfjs-react-native": "^0.8.0",
    "expo": "^43.0.3",
    "expo-camera": "~12.0.3",
    "expo-gl": "~11.0.3",
    "expo-gl-cpp": "~11.0.1",
    "react": "17.0.2",
    "react-native": "0.66.3",
    "react-native-fs": "^2.18.0",
```

**Comment by GantMan** [comment]
@tafsiri  or @lina128   any insight here?  This seems to be a blocker for our dev to make progress on a React Native component library.

**Comment by jinjingforever** [comment]
Sorry for the delay.. I plan to take a look at this issue today or early next week. Thanks for the patience!

**Comment by jinjingforever** [comment]
Hi folks,

I took a closer look and it looks like the error happens right after the tfjs-react-native backend creates the GLView context ([here](https://github.com/tensorflow/tfjs/blob/master/tfjs-react-native/src/platform_react_native.ts#L171)). We actually found this problem before, and that's why we mentioned the working version combination [here](https://github.com/tensorflow/tfjs-examples/tree/master/react-native). I will move this paragraph to the main tfjs repo so people can easily see it. I also found a [similar issue](https://github.com/expo/expo/issues/15390) reported in the expo repo.  

As @raienko mentioned, the solution is to downgrade. Sorry I don't have any better solutions for now. I will keep an eye on the expo repo and test the newer versions again when the problems on their side are fixed.

@kateinkim just FYI that due to the usage of GLView (expo-gl), tfjs-react-native can only be tested on real devices, not simulators. 

Thanks!

**Comment by kateinkim** [comment]
Thanks @jinjingforever! I tested it on a real device before but didn’t work so downgrade it is!

**Comment by gaikwadrahul8** [comment]
Hi, @kateinkim 

Apologize for the delayed response and Just confirm, After downgrading the react-native version as per below package dependancies whether your issue got resolved or not ? please refer this [official documentation ](https://github.com/tensorflow/tfjs-examples/tree/master/react-native) and also refer this [comment](https://github.com/tensorflow/tfjs/issues/7454#issuecomment-1478743753)

If issue still exists please let us know with error log for further investigation to find out root cause for your issue ? Thank you!

```
"expo": "~44.0.2",
"expo-camera": "^12.1.0",
"expo-file-system": "^13.2.0",
"expo-gl": "^11.1.1",
"expo-gl-cpp": "^11.1.0",
"react": "17.0.1",
"react-native": "~0.64.3"
```
