### ISSUE TITLE
Disruption of video frame order related to tf.browser.fromPixels(HTMLVideoElement) in recent Firefox

### ISSUE THREAD

**Issue by eyaler** [tensorflow/tfjs#5947]
**System information**
- I written custom code
- Windows 10 and 11, issue on Firefox 94-105 compared to older versions of FF + chorme/edge)
- PC (tried on a few different machines)
- TensorFlow.js from jsdelivr.net/npm tried versions from 2.4.0 to 3.20.0

**Describe the current behavior**
Running mediapipe facemesh estimateFaces on videoElement in Firefox 94/95 causes the video to be extremely jerky with frames jumping back and forth in time. I think this is related to tf.browser.fromPixels(HTMLVideoElement). It was OK in previous versions of FF (not sure which but it was OK a few months ago), and it is OK on chorme/edge and it is also OK if I use a camera stream instead of video. Link to demo showing the issue below (wait for the model loading to complete + you can hide/remove the mask to see that the issue is with the underlying video itself)

**Describe the expected behavior**
the video frames should be displayed in order without jumping back and forth.

**Standalone code to reproduce the issue**
demo: https://eyaler.github.io/tfjs_webgl_app/face_landmark/ 
this is the line causing the issue: https://github.com/eyaler/tfjs_webgl_app/blob/master/face_landmark/webgl_main.js#L650

thanks!

**Comment by rthadur** [comment]
Looks like issue is not reproducible in latest version of Mozilla , can you please check. Thank you

**Comment by eyaler** [comment]
@google-ml-butler, this issue is open since december 2021, so i do not appreciate the pressure to mark this as stale/closed after just a few days from last call to action.

@rthadur, thanks. i just checked on firefox 105.0.1 (64-bit) on windows, with tfjs 3.12.0 and i see the same issue. i did not try with later tfjs versions. did you test with a later version? is there a commit addressing the issue?

**Comment by rthadur** [comment]
We do not have windows machine , I am not sure if there is a fix , please try with latest version and update the issue , thank you

**Comment by eyaler** [comment]
I updated both tfjs and tf-backend-wasm to the latest 3.20.0 and seeing the exact same issue :(

**Comment by eyaler** [comment]
any news please? @rthadur @lina128

**Comment by gaikwadrahul8** [comment]
Hi, @eyaler 

Apologize for the delayed response and we're re-visiting our older issues and checking whether those issues got resolved or not as of now so May I know are you still looking for the solution or your issue got resolved ?

If issue still persists after trying with latest version of `@tensorflow-tfjs@4.6.0` and `@tensorflow/tfjs-backend-wasm@4.6.0 ` please let us know and I tried on my `Mac M1 system` and it's working as expected and I don't have windows system to test it from my end now so I would request you to please try it from your end with latest versions and  let us know whether are you still facing the same issue or not ?

Could you please confirm if this issue is resolved for you ? Please feel free to close the issue if it is resolved ? Thank you!

**Comment by eyaler** [comment]
@gaikwadrahul8 thanks for your kind followup.
i can confirm that the issue was solved when going from firefox 107.0.1 (broken) to 108.0 (fixed; dec 2022)
i tested with both tfjs 3.20.0 and 4.6.0
i believe the next step should be to figure out what was the relevant changeset and understand any other possible implications. i hope you will not blindly close this bug as this was a breaking issue with video playback that prevented using tfjs for video on firefox for ~1.5 years. bugs that magically disappear always call for a deeper investigation, important lessons can be learned.

**Comment by gaikwadrahul8** [comment]
Hi, @eyaler 

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFJs team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TFJs [version](https://github.com/tensorflow/tfjs/releases/tag/tfjs-v4.10.0) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tfjs/blob/master/README.md) to stay up to date with the latest developments which are happening in the Tensorflow.js space.

Thank you for your support and cooperation.
