### ISSUE TITLE
Scalar multiplication gives a wrong answer

### ISSUE THREAD

**Issue by hodovani** [tensorflow/tfjs#5960]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS Big Sur 11.6
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow.js installed from (npm or script link): script link
- TensorFlow.js version (use command below): 3.11.0
- Browser version: Safari Version 15.0 (16612.1.29.41.4, 16612)
- Tensorflow.js Converter Version:

**Describe the current behavior**

Scalar 0.1 * Scalar 0.2 = 0.020000001415610313 

**Describe the expected behavior**

Scalar 0.1 * Scalar 0.2 = 0.02

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/CodePen/any notebook.

https://codepen.io/matvii_hodovaniuk/pen/vYeJPdN

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by lina128** [comment]
Hi @hodovani, this is expected for floating numbers. See some explanations here: https://www.quora.com/Why-is-0-1+0-2-not-equal-to-0-3-in-most-programming-languages

**Comment by hodovani** [comment]
@lina128 yes, but when I use tensor instead of scalar I receive right result. The uoutput from this codepen https://codepen.io/matvii_hodovaniuk/pen/vYeJPdN

![image](https://user-images.githubusercontent.com/12833067/201134828-df663cfa-4694-49d4-a847-18e569e608a2.png)

**Comment by shmishra99** [comment]
Hi @hodovani,
Apologies for the delay in my response. As @lina128 mentioned this behaviour is expected for floating numbers in computer. 
`0.02` cannot be represented exactly in binary format and is instead approximated as `0.020000000298023224`. Thank You!!

**Comment by hodovani** [comment]
@shmishra99 thanks. But why do we have the correct answer for the Tensor type?

**Comment by shmishra99** [comment]
Hi @hodovani ,
I apologize for the delay in my response. The rounding error may be due to the way data is stored in TensorFlow.js. Tensors are stored in the form of multi-dimensional arrays, while scalars are stored in the form of primitives. I am not sure why this difference is occurring, but I will investigate further and get back to you. Thank You!

**Comment by gaikwadrahul8** [comment]
Hi, @hodovani 

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFJs team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TFJs [version](https://github.com/tensorflow/tfjs/releases/tag/tfjs-v4.10.0) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tfjs/blob/master/README.md) to stay up to date with the latest developments which are happening in the Tensorflow.js space.

Thank you for your support and cooperation.
