### ISSUE TITLE
package @tensorflow/tfjs-react-native on function decodeJpeg(contents: Uint8Array, channels?: 0 | 1 | 3), we need to support 1 channel  for grayscale color.

### ISSUE THREAD

**Issue by AhmadBadah** [tensorflow/tfjs#5966]
<em>console print : [Error: Only 3 channels is supported at this time]</em>

When use  "1 channel or zero channel" in decodeJpeg(contents: Uint8Array, channels?: 0 | 1 | 3) function then catch error "Error: Only 3 channels is supported at this time".
But when using "3 channels" on function decodeJpeg(), my code worked well.

We want from @tensorflow/tfjs-react-native {decodeJpeg(Uint8Array,1)} to be supported.

I used these packages versions:
-"@tensorflow/tfjs": "^3.12.0",
-"@tensorflow/tfjs-react-native": "^0.8.0",
-"expo": "~43.0.2",
-"expo-gl": "^11.0.3",
-"expo-camera": "^12.0.3",

![Screen Shot 2021-12-27 at 11 17 20 AM](https://user-images.githubusercontent.com/38249806/147456486-d4cf08a9-efa5-4d5b-9834-2752b6aadd06.png)

**Comment by AhmadBadah** [comment]
Any update?!

**Comment by gaikwadrahul8** [comment]
Hi, @AhmadBadah 

Apologize for the delayed response and we're re-visiting our older issues and checking whether those issues got resolved or not as of now so May I know are you still looking for the solution or your issue got resolved ?

It seems like we have updated official documentation w.r.t [decodeJpeg](https://js.tensorflow.org/api_react_native/0.8.0/#decodeJpeg) so I would request you to please try to use below package dependancies and check whether your issue is resolving or not ? please refer this [official documentation ](https://github.com/tensorflow/tfjs-examples/tree/master/react-native)

```
"expo": "~44.0.2",
"expo-camera": "^12.1.0",
"expo-file-system": "^13.2.0",
"expo-gl": "^11.1.1",
"expo-gl-cpp": "^11.1.0",
"react": "17.0.1",
"react-native": "~0.64.3",

```


If issue still persists after trying with above mentioned package dependancies please let us know with error log and code snippet to replicate the same issue from our end ?

Could you please confirm if this issue is resolved for you ? Please feel free to close the issue if it is resolved ? Thank you!
