### ISSUE TITLE
[Question] What's the right way to support cross-platform (browser + Node) TFJS libraries?

### ISSUE THREAD

**Issue by thekevinscott** [tensorflow/tfjs#6036]
Hi, I searched but couldn't find anything.

[I maintain an open source library leveraging TFJS](https://github.com/thekevinscott/UpscalerJS/). Officially, it's browser-only, but the community has asked for Node support.

**What is the right way for a package built on TFJS to support both Node and browser platforms?**

I understand that there are separate packages for the browser and Node (and Node+GPU). Currently, my package directly imports `@tensorflow/tfjs`, which causes issues when being called via a Node environment (issues including multiple backends and complaints about model loading). Additionally, it's not clear to me how to specify a valid peer dependency for the various TFJS packages out there.

Have other library authors run into this before? If there's a sample library that has solved this, I'd love to know.

**Comment by rthadur** [comment]
you can check this demo https://github.com/tensorflow/tfjs-models/tree/master/blazeface/demo as how different backends are loaded . Thank you

**Comment by thekevinscott** [comment]
Thanks for that reference @rthadur, that's very helpful. A few questions:

* These are all browser-specific, right? WebGL, WASM, and CPU?
* You're importing all three backends at script load; don't `@tensorflow/tfjs-backend-webgl` and `@tensorflow/tfjs-backend-wasm` fail to work for Node implementations?

**Comment by vladmandic** [comment]
create one-line wrapper for `tfjs` for each target  
for example:
`tfjs-browser.ts` would be `export * from '@tensorflow/tfjs` and
`tfjs-node.ts` would be `export * from '@tensorflow/tfjs-node`

then in your build script, just each of those builds to same destination, `tfjs.js` and that is what you import from your app
so sequentialize build script
1. build `tfjs-browser.ts` -> `tfjs.js`
2. build your app for browser
3. build `tfjs-node.ts` -> `tfjs.js` (same destination)
4. build your app for node

**Comment by thekevinscott** [comment]
Thank you @vladmandic, that's super helpful to see. So you're emitting a variety of builds - `cjs`, `esm`, `iife` - across the various platforms, and then you're shipping all the dist outputs in a single NPM package. So when a user installs the package, they then must request a specific built platform via something like `human.node.js`?

It looks like the package has no `peerDependencies`. I presume that's not been a source of any issues for you? (I'm not sure how I'd enable that and also allow for selecting amongst the TFJS platform variants.)

I appreciate the help from both of you!

**Comment by thekevinscott** [comment]
@vladmandic did you ever consider publishing separate version of the package to NPM (`human` for browser, `human-node` for Node, `human-node-gpu`) for each platform, to mirror TFJS's outputs? Curious to hear why you chose the single package route.

I imagine separate packages would keep package size down (and allow for the correct `peerDependencies` specification) but at the cost of a much more complicated build/publish step.

**Comment by vladmandic** [comment]
> did you ever consider publishing separate version of the package to NPM (human for browser, human-node for Node, human-node-gpu) for each platform, to mirror TFJS's outputs? Curious to hear why you chose the single package route.

it would be simpler to publish separate packages, but i just dont like that - besides, i like a challenge :)

> I imagine separate packages would keep package size down

size-wise, publishing single package for multi-target doesnt make a big difference as only `/dist` output is different and for node targets its dist is tiny (since tfjs-node cannot be embedded - dependency on node-gyph and actual tensorflow shared library means that it needs to be actually installed)

> So when a user installs the package, they then must request a specific built platform via something like human.node.js?

not really, only if you want to override what is auto-detected. having correct entries in `package.json` takes care of the 99% of scenarios so toolkits automatically pick correct file from dist.

for example:
```json
  "main": "dist/human.node.js",
  "module": "dist/human.esm.js",
  "browser": "dist/human.esm.js",
  "types": "types/human.d.ts",
```
> and allow for the correct peerDependencies specification

only peerDependency is `@tensorflow/tfjs-node` when using **human** in `nodejs`, but that is covered in docs.
for browser package, default version has `tfjs` bundled/embedded in the package itself (i also build my own `tfjs` for that so its cleaner than the default one, but thats besides the point) so there are 0 peer dependencies (there is also a non-bundled version for advanced use)

**Comment by thekevinscott** [comment]
Super helpful information, @vladmandic! I very much appreciate it.
