### ISSUE TITLE
How to create a 3D cube as shown in the blogpost

### ISSUE THREAD

**Issue by pc11000** [tensorflow/tfjs#6072]
How can one create a 3D representation in a cube as shown in the blogpost here (squatting man):
https://blog.tensorflow.org/2021/08/3d-pose-detection-with-mediapipe-blazepose-ghum-tfjs.html

**Comment by lina128** [comment]
Sorry this visualization is not open sourced at the moment, I will check with the team whether it can be open sourced.

**Comment by pc11000** [comment]
Ok thanks for your effort. Would be great, if possible.

**Comment by gaikwadrahul8** [comment]
Hi, @pc11000 

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFJs team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TFJs [version](https://github.com/tensorflow/tfjs/releases/tag/tfjs-v4.10.0) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tfjs/blob/master/README.md) to stay up to date with the latest developments which are happening in the Tensorflow.js space.

Thank you for your support and cooperation.
