### ISSUE TITLE
[RN] example not working properly on android.

### ISSUE THREAD

**Issue by GwangjoGong** [tensorflow/tfjs#6087]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Android
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Samsung Galaxy S10
- TensorFlow.js installed from (npm or script link): Cloned [tfjs-examples/react-native-pose-detection](https://github.com/tensorflow/tfjs-examples/tree/master/react-native/pose-detection)
- TensorFlow.js version (use command below): Cloned [tfjs-examples/react-native-pose-detection](https://github.com/tensorflow/tfjs-examples/tree/master/react-native/pose-detection)
- Browser version: -
- Tensorflow.js Converter Version: -

**Describe the current behavior**
I launched the pose detection example and take pose just like the image, but keypoints not detected like the image on [README.md](https://github.com/tensorflow/tfjs-examples/tree/master/react-native/pose-detection)

**Describe the expected behavior**
Keypoints should be detected just like the example image.

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/CodePen/any notebook.

**Test Process**
1. clone repo
2. `yarn` => Failed with ```error An unexpected error occurred: "https://registry.yarnpkg.com/colors/-/colors-1.4.2.tgz: Request failed \"404 Not Found\"".```
3. `rm yarn.lock`
4. `yarn && yarn start`
5. set camera to front and adjust position to show my face and shoulder. (just like image on `README.md`)

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by gaikwadrahul8** [comment]
Hi, @GwangjoGong 

Apologize for the delayed response and we're re-visiting our older issues and checking whether those issues got resolved or not as of now so May I know are you still looking for the solution or your issue got resolved ?

If issue still persists after trying package dependancies which is mentioned in this [official documentation](https://github.com/tensorflow/tfjs-examples/tree/master/react-native) please let us know with error log and code snippet to replicate the same issue from our end ?

Could you please confirm if this issue is resolved for you ? Please feel free to close the issue if it is resolved ? Thank you!
