### ISSUE TITLE
Performance tfjs vs TensorFlow Lite

### ISSUE THREAD

**Issue by 116050423** [tensorflow/tfjs#614]
Hi dear contributors,
recently I am trying to run some models on mobile phone and now I can do it by tfjs + mobile browsers(such as iOS safari).
I know tfjs is running in js engine and accelerated by WebGL.
Besides, TensorFlow Lite is designed for mobile and based on Apple Core ML accelerate lib (iOS) or Android Neural Network API(Android).
These two libs are designed for cpu/gpu acceleration and high performance.
So what's the performance difference between tfjs and tf lite for the same model?
Do you have quantized or empirical contrastive result？

**Comment by DavidGOrtega** [comment]
I haven't done meaurements yt since right now Im still in the process of using tfjs. However empirical work that I have done so far TF lite with model optimuzation and quantization is far superior than tfjs. Can't be compared. In example magenta pastiche takes a few seconds on lite for an HD image while in the browser under tfjs my laptop can't render completely a 256x256 image. Right now at least for me, they can not be compared

**Comment by rthadur** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
