### ISSUE TITLE
TF JS movenet blog not working in Safari or Chrome in iOS

### ISSUE THREAD

**Issue by adityarath302** [tensorflow/tfjs#6171]
I tried using the method stated in the blog: https://blog.tensorflow.org/2021/05/next-generation-pose-detection-with-movenet-and-tensorflowjs.html to deploy Movenet. It's working in android as expected but the frame freezes after asking for camera permission and not running on Safari or chrome. It works well in macOS but iPhone is an issue. My use case is to use tf js for webview on flutter.

**Comment by gaikwadrahul8** [comment]
Hi, @adityarath302 

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFJs team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TFJs [version](https://github.com/tensorflow/tfjs/releases/tag/tfjs-v4.10.0) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tfjs/blob/master/README.md) to stay up to date with the latest developments which are happening in the Tensorflow.js space.

Thank you for your support and cooperation.
