### ISSUE TITLE
BlazePose model: How to use poseDetection.calculator.keypointsToNormalizedKeypoints(keypoints, imageSize);

### ISSUE THREAD

**Issue by silvererudite** [tensorflow/tfjs#6176]
The [blazePose docs](https://github.com/tensorflow/tfjs-models/tree/master/pose-detection) say that we can get normalized values of `keypoints`  from image space using this function `poseDetection.calculator.keypointsToNormalizedKeypoints(keypoints, imageSize)`  ... I can't seem to get it to work though. 
```
let raf=0;
async function main(){
  let VIDEO = document.getElementById('webcam');
  const estimationConfig = {flipHorizontal: true};
  const timestamp = performance.now();
  const poses = await detector.estimatePoses(VIDEO, estimationConfig, timestamp);
  if(poses.length > 0){
           console.log(   poseDetection.calculator.keypointsToNormalizedKeypoints(poses[0].keypoints, VIDEO););
  }
 raf = requestAnimationFrame(main);
 
}
```
And I get this error 
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'keypointsToNormalizedKeypoints')
    at main 
```
I have also tried calling this method via `await` but got the same error. I don't quite understand why it's undefined.

**Comment by dio78** [comment]
Instead of "poses[0].keypoints", try passing just "poses" as the first argument, like this:

```
 if(poses.length > 0){
    console.log(poseDetection.calculator.keypointsToNormalizedKeypoints(poses, VIDEO));
  }
```
If that doesn't work, try changing "calculator" to "calculators" like this: 

```
 if(poses.length > 0){
    console.log(poseDetection.calculators.keypointsToNormalizedKeypoints(poses, VIDEO));
  }

```

I'm not sure what syntax it is looking for when you pass in the imageSize, but I'm working on that now and I'll let you know if I figure it out!

**Comment by lina128** [comment]
Hi @silvererudite , it is poseDetection.calculators.keypointsToNormalizedKeypoints(...). Can you try again? Thanks.

**Comment by gaikwadrahul8** [comment]
Hi, @silvererudite 

Apologize for the delayed response and Could you please refer above [comment](https://github.com/tensorflow/tfjs/issues/6176#issuecomment-1297768057) from @lina128 and it will help you to resolve your issue.

If issue still persists please let us know ? or Could you please confirm if this issue is resolved for you ? Please feel free to close the issue if it is resolved ? Thank you!
