### ISSUE TITLE
Video Timestamp for MediaPipeHands

### ISSUE THREAD

**Issue by DuKeM-CSGO** [tensorflow/tfjs#6215]
**System information**
- TensorFlow.js version : None but `tfjs-core` & `tfjs-backend-webgl` through the HTML <script> labels.
- Are you willing to contribute it (Yes/No): No:D

**Describe the feature and the current behavior/state.**
According to [BlazePoseMediaPipe](https://github.com/tensorflow/tfjs-models/tree/master/pose-detection/src/blazepose_mediapipe#run-inference), there's a third parameter of the `estimatePoses` function that can override my video's timestamp. Could the `estimatePoses` function of `MediaPipeHands` work like this? I don't find this param in its [readme](https://github.com/tensorflow/tfjs-models/tree/master/hand-pose-detection/src/mediapipe). Although my browser doesn't show any error, I find that 
MediaPipeHands only works when its `estimatePoses` method's third param is 0. Any other positive int would lead to a null result.
(Or another way to make `MediaPipeHands` could work on the video.)

**Will this change the current api? How?**
Maybe not, I think it only change the `estimatePoses` function's body.

**Comment by rthadur** [comment]
cc @lina128

**Comment by DuKeM-CSGO** [comment]
And I want to know how to analyze a video by `Blaze` and `MediaPipeHands` frame by frame, too.

**Comment by ahmedsabie** [comment]
@DuKeM-CSGO I think you are misunderstanding the timestamp parameter. The timestamp is part of the pose-detection API because it is used for their smoothing filters, however hands does not use such filters so it is not part of the API.

The timestamp is not used to select a frame in the video, our code simply uses the current frame of the video at the time of calling the estimatePoses or estimateHands functions. To analyze frame by frame you can use something like requestAnimationFrame to get a recurring callback, and in the callback body you can call our API with the video input.
