### ISSUE TITLE
Allow customGrad to take tensorlike objects

### ISSUE THREAD

**Issue by lina128** [tensorflow/tfjs#6219]
Feature request from forum: https://discuss.tensorflow.org/t/could-custom-ops-be-as-nice-as-core-ops/8236

"The args passed in customGrad(f)(x1, x2,…) must all be tensors. This means that custom ops are less user-friendly than the core ops which all use convertToTensor to allow them to take TensorLike objects.

I think it would be much nicer if custom ops were first class like the core ops, then library extensions could feel more natural. (I also noticed that convertToTensor seems to be private, I was expecting it in tf.util. Might that be exposed as well?)" - by [iislucas](https://discuss.tensorflow.org/u/iislucas)

**Comment by gaikwadrahul8** [comment]
Hi, @lina128 

Thank you for opening this issue for tracking purposes. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFJs team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TFJs [version](https://github.com/tensorflow/tfjs/releases/tag/tfjs-v4.12.0) with the latest compatible hardware configuration which could potentially resolve the issue. 

Based on our internal discussion, we are closing this issue at this time. If you still feel that this feature request is relevant, please feel free to create a new issue.

Thank you for your support and cooperation.
