### ISSUE TITLE
Please document GPUData texture format other than [1, height, width, 4] shape

### ISSUE THREAD

**Issue by huningxin** [tensorflow/tfjs#6238]
**Describe the current behavior**

[Optimization Topic - How to write a high performance GPU pipeline](https://github.com/tensorflow/tfjs/blob/master/docs/OPTIMIZATION_PURE_GPU_PIPELINE.md) only describes the texture format of

> So if a tensor's shape is [1, height, width, 4] or [height, width, 4], the way we store the data aligns with how image is stored, therefore if the downstream processing assumes the texture is an image, it doesn't need to do any additional coordination conversion. 

It only mentions 
> However, if the tensor has other shapes, downstream processing steps may need to reformat the data onto another texture. The texShape field has the [height, width] information of the texture, which can be used for transformation.

It is unclear to developer how to do the reformat. 

**Describe the expected behavior**

Document the format for other shapes. It would be very helpful if there are some shader code example or helpers.

/cc @lina128 @pyu10055

**Comment by gaikwadrahul8** [comment]
Hi, @huningxin 

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFJs team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TFJs [version](https://github.com/tensorflow/tfjs/releases/tag/tfjs-v4.10.0) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tfjs/blob/master/README.md) to stay up to date with the latest developments which are happening in the Tensorflow.js space.

Thank you for your support and cooperation.

**Comment by huningxin** [comment]
Thanks for the update. Closing this issue.
