### ISSUE TITLE
suppress unnecessary warnings for async execution

### ISSUE THREAD

**Issue by vladmandic** [tensorflow/tfjs#6249]
I cannot know ahead of time if model can be executed synchronously or not  
so only safe way is to execute all models asynchronously using  

```js
model.executeAsync()
```

but then there are warnings which cannot be suppressed:

> This model execution did not contain any nodes with control flow or dynamic output shapes. You can use `model.execute()` instead.

please either provide  
1. a way to determine ahead of time how a model should be executed or  
2. a way to suppress this message when async execution is a clear choice by user  
3. alternatively, remove the message altogether as there is no downside of running model inference asynchronously in all cases

**Comment by vladmandic** [comment]
any progress on this one? linked pr is open since apr.

**Comment by mattsoulanille** [comment]
Sorry @vladmandic. No updates so far, but I'll bring this up with Na and Ping, and maybe we can find a way to cache the graph in `executeAsync`, which should remove the performance difference and let us remove the warning. Alternatively, we can add a flag to disable the warning or have it self-disable after ~5 messages.

**Comment by vladmandic** [comment]
my biggest issue with this is that if i want to create a generic code, i cannot know in advance if model will require async execution or not, so only safe way is to execute all with `executeAsync`  

when in reality, only very few models actually require it (although more and more newer ones)

**Comment by gaikwadrahul8** [comment]
Hi, @vladmandic 

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFJs team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TFJs [version](https://github.com/tensorflow/tfjs/releases/tag/tfjs-v4.10.0) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tfjs/blob/master/README.md) to stay up to date with the latest developments which are happening in the Tensorflow.js space.

Thank you for your support and cooperation.

**Comment by govza** [comment]
The issue is still there though
