### ISSUE TITLE
[Codelab]: Making Predictions from 2D Data

### ISSUE THREAD

**Issue by MarchellStrydom** [tensorflow/tfjs#6289]
Access to script at 'file:///C:/Users/selli/OneDrive/Desktop/New%20folder%20(2)/data.js' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome-extension, edge, https, chrome-untrusted.
index.html:15 
        
      
        
        
      
        
      
       
        
       GET file:///C:/Users/selli/OneDrive/Desktop/New%20folder%20(2)/data.js net::ERR_FAILED

**Comment by rthadur** [comment]
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. As per the error message it shows that the your trying to load files from local folder which was blocked by CORS, I do not see a step in Codelab about the same step , please elaborate the steps . 
Thanks!
