### ISSUE TITLE
[Codelab]: TensorFlowJS Make a smart webcam in JavaScript with a pre-trained ML model

### ISSUE THREAD

**Issue by emilehickson** [tensorflow/tfjs#6331]
"This codelab **_is_** focuses on how to get started using TensorFlow.js pre-trained models."

=>

"This codelab focuses on how to get started using TensorFlow.js pre-trained models."

**Comment by rthadur** [comment]
It looks like you haven't used a template to create this issue. Please resubmit your issue using a template from [here](https://github.com/tensorflow/tfjs/issues/new/choose). We ask users to use the template because it reduces overall time to resolve a new issue by avoiding extra communication to get to the root of the issue. We will close this issue in lieu of the new one you will create from the template. Thank you for your cooperation.
