### ISSUE TITLE
Duplicated packages defined in multiple package.json files

### ISSUE THREAD

**Issue by gyagp** [tensorflow/tfjs#6334]
After the transition to Bazel, I think it's time to clean up all the unnecessary duplicated packages defined in all package.json files in subfolders. For example, tfjs-backend-webgl/package.json includes many duplications with the root folder. The clean up can at least help to:
* Make package versions consistent
* Save disk storage and ease the setup of dev env
* Save the effort to bump the package versions

**Comment by mattsoulanille** [comment]
This has been on my list of things to do for a while, and I think a good way to do this would be to have Bazel generate the package.json files for tfjs-core, tfjs-backend-cpu, etc. Dependencies from those packages' package.json files are not actually used during development since Bazel only uses the root package.json, as we've set it up. 

We should be able to find the transitive set of npm dependencies of a package by using Bazel Aspects ([example](https://docs.bazel.build/versions/main/skylark/aspects.html#simple-example)) and add them to a package.json template when we build the package for npm. We'd have to be careful not to cross package boundaries, though (e.g. the union package includes all the npm dependencies of tfjs-core, tfjs-backend-webgl, etc because it depends on them).

We should still keep each package's package.json file, since they have scripts for building and testing the packages, but we can remove the listed dependencies.

I'll give this a try.

**Comment by gyagp** [comment]
We're in the progress to manually remove the duplicated packages in WebGPU backend. As it's a general problem, we hope to eventually keep the solution consistent for all backends. 
Currently we met a problem and I will ping you in that PR for suggestion.
