### ISSUE TITLE
index.js:88 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'length')

### ISSUE THREAD

**Issue by sameermahajan** [tensorflow/tfjs#6358]
While trying to "Train" using this code I am getting an error:

DevTools failed to load source map: Could not load content for https://cdn.jsdelivr.net/npm/@tensorflow/tf.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
index.js:88 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'length')
    at flatten (index.js:88:26)
    at train (index.js:48:23)
    at HTMLButtonElement.onclick (index.html:14:42)

This is on latest chrome browser on Windows 10 machine.

**Comment by sameermahajan** [comment]
Attached is my code (inde.html and index.js just remove the .pdf suffix and you can execute them). It is based on your sample. I think it used to work about a month ago when I had got it. Nothing changed from my side but now I am getting this error.

Open index.html, click on button "Train" and the UI will grey out completely. You can see the exception, error and stack trace that I reported in developer tools.

[index.html.pdf](https://github.com/tensorflow/tfjs/files/8596233/index.html.pdf)
[index.js.pdf](https://github.com/tensorflow/tfjs/files/8596234/index.js.pdf)

**Comment by rthadur** [comment]
Could not open pdf , can you please paste here https://codepen.io/pen/ and share it.

**Comment by sameermahajan** [comment]
Here you go: https://codepen.io/sameermahajan/pen/YzezQej

**Comment by rthadur** [comment]
Initially I did not get which colab you were working on , by seeing the code I see you are [TensorFlow.js - Audio recognition using transfer learning](https://codelabs.developers.google.com/codelabs/tensorflowjs-audio-codelab). I was able to run the colab successfully here https://codepen.io/rthadur/pen/JjpoKbE . Codepen which you shared is also working fine for me , could you please let me know where you are seeing the issue ?

**Comment by juntaoxiang** [comment]
**Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'type')
    at eval (barPolar.js?120a:63:1)
    at GlobalModel.eval (Global.js?05a0:682:1)**

**Comment by sameermahajan** [comment]
I am getting error as reported at line 88 of index.js when clicked on button "Train". I get the error locally as well as in uploaded codepen. It is with latest chrome on windows 10 machine in case it matters.

**Comment by sameermahajan** [comment]
I get the same error with this from my machine / browser. Developer tools show the same error and stack.

**Comment by tempdeltavalue** [comment]
Also faced with this issue 

    <script type="text/javascript">
        function start_model() {
            // const modelJson = require('https://tempdeltavalue.github.io/model.json');
            // const modelWeights = require('https://tempdeltavalue.github.io/group1-shard1of1.bin');

            model = tf.loadGraphModel('https://tempdeltavalue.github.io/f_w2223_js_graph/model.json');

            states =[];
            next_char = ['Пр ']
            result = [next_char]


                    const prediction = res.executeAsync(
                        {"args_0" : next_char, "unknown" : next_char, "unknown_8" : next_char},

                        // [next_char, states]
                        );
                    console.log(prediction);
                }, function (err) {
                    console.log(err);
                });
            }


        }
        window.onload = start_model;
    </script>
    
    
    https://colab.research.google.com/drive/1zPeOgjKipPGyMJz-i99_LLFBYbr__JTr#scrollTo=DRKmCHi7vfSm

**Comment by shmishra99** [comment]
Hi @sameermahajan ,
I apologise for the delayed response. I have reviewed your code and encountered the same error you reported: `index.js:88 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'length’)` when attempting to train the model directly without any data. This error occurs due to passing an empty array to the `flatten(tensors)` function, resulting in a length error at the following line: `const size = tensors[0].length.`
To avoid this error, I suggest clicking on the left, right, or noise button first to fill the example array with some data using the following code: `let vals = normalize(data.subarray(-frameSize * NUM_FRAMES)); examples.push({vals, label});`. Once the example array has been populated with data, you can safely click on the train button without encountering any errors.
Output : 
<img width="1501" alt="image" src="https://github.com/tensorflow/tfjs/assets/124146945/89d32d46-b8d8-40e6-b2f0-0e270aabf1fc">

You could also refer to [tf.tensor](https://js.tensorflow.org/api/latest/#class:Tensor) documentation. Let me know if have I missed something here. Thank You !
