### ISSUE TITLE
tfjs-react-native got error [TypeError: undefined is not an object (evaluating 'env().platform.fetch')] with Apple M1 Pro

### ISSUE THREAD

**Issue by bergkamp** [tensorflow/tfjs#6418]
I run my code on my Apple M1 Pro(yarn ios) , got error 

> [TypeError: undefined is not an object (evaluating 'env().platform.fetch')]

```
{
  "name": "rntf",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "expo": "expo",
    "lint": "eslint ."
  },
  "dependencies": {
    "@react-native-async-storage/async-storage": "^1.17.4",
    "@tensorflow-models/mobilenet": "^2.1.0",
    "@tensorflow/tfjs": "^3.17.0",
    "@tensorflow/tfjs-react-native": "^0.8.0",
    "expo": "^45.0.0",
    "expo-camera": "~12.2.0",
    "expo-gl": "~11.3.0",
    "expo-gl-cpp": "~11.3.0",
    "react": "17.0.2",
    "react-native": "0.68.2",
    "react-native-fs": "^2.20.0"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@babel/runtime": "^7.12.5",
    "@react-native-community/eslint-config": "^2.0.0",
    "babel-jest": "^26.6.3",
    "eslint": "^7.32.0",
    "jest": "^26.6.3",
    "metro-react-native-babel-preset": "^0.67.0",
    "react-test-renderer": "17.0.2"
  },
  "jest": {
    "preset": "react-native"
  }
}
```

I had reade this https://github.com/tensorflow/tfjs/issues/3300 , could not fix

I try to run this https://github.com/tensorflow/tfjs-examples/tree/master/react-native/image-classification/react-native-cli but failed

Thanks

**Comment by bergkamp** [comment]
App.js

```
/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 *
 * @format
 * @flow strict-local
 */

 import React from 'react';
 import { Node, useEffect, useState,useRef } from 'react';
 import {
     SafeAreaView,
     ScrollView,
     StatusBar,
     StyleSheet,
     Text,
     useColorScheme,
     View,
     setState
 } from 'react-native';
 
 import {
     Colors,
     DebugInstructions,
     Header,
     LearnMoreLinks,
     ReloadInstructions,
 } from 'react-native/Libraries/NewAppScreen';
 
 // import * as mobilenet from '@tensorflow-models/mobilenet';
 // import { fetch, decodeJpeg } from '@tensorflow/tfjs-react-native';
 import * as tf from '@tensorflow/tfjs';
 import { fetch, decodeJpeg } from '@tensorflow/tfjs-react-native';
 import * as mobilenet from '@tensorflow-models/mobilenet';
 
 
 const Section = ({ children, title }): Node => {
     const isDarkMode = useColorScheme() === 'dark';
     return (
         <View style={styles.sectionContainer}>
             <Text
                 style={[
                     styles.sectionTitle,
                     {
                         color: isDarkMode ? Colors.white : Colors.black,
                     },
                 ]}>
                 {title}
             </Text>
             <Text
                 style={[
                     styles.sectionDescription,
                     {
                         color: isDarkMode ? Colors.light : Colors.dark,
                     },
                 ]}>
                 {children}
             </Text>
         </View>
     );
 };
 
 const App: () => Node = () => {
     const isDarkMode = useColorScheme() === 'dark';
 
     const backgroundStyle = {
         backgroundColor: isDarkMode ? Colors.darker : Colors.lighter,
     };
 
     const [isTfReady, setIsTfReady] = useState(false);
     const [result, setResult] = useState('');
     //const image = useRef(null);
 
     const load = async () => {
         try {
             // Load mobilenet.
             await tf.ready().then((data)=>{
                 console.log(data)
             });
             const model = await mobilenet.load();
             setIsTfReady(true);
 
             // Start inference and show result.
             const image = require('./assets/cat.jpeg');
             const imageAssetPath = Image.resolveAssetSource(image);
             const response = await fetch(imageAssetPath.uri, {}, { isBinary: true });
             const imageDataArrayBuffer = await response.arrayBuffer();
             const imageData = new Uint8Array(imageDataArrayBuffer);
             const imageTensor = decodeJpeg(imageData);
             const prediction = await model.classify(imageTensor);
             console.log(prediction);
             if (prediction && prediction.length > 0) {
                 setResult(
                     `${prediction[0].className} (${prediction[0].probability.toFixed(3)})`
                 );
                 console.log(result);
             }
         } catch (err) {
             console.log(err);
         }
     };
 
     useEffect(() => {
         load();
     }, []);
 
 
     return (
         <SafeAreaView style={backgroundStyle}>
             <StatusBar barStyle={isDarkMode ? 'light-content' : 'dark-content'} />
             <ScrollView
                 contentInsetAdjustmentBehavior="automatic"
                 style={backgroundStyle}>
                 <Header />
                 <View
                     style={{
                         backgroundColor: isDarkMode ? Colors.black : Colors.white,
                     }}>
                     <Section title="Step One">
                         Edit <Text style={styles.highlight}>App.js</Text> to change this
                         screen and then come back to see your edits.
                     </Section>
                     <Section title="See Your Changes">
                         <ReloadInstructions />
                     </Section>
                     <Section title="Debug">
                         <DebugInstructions />
                     </Section>
                     <Section title="Learn More">
                         Read the docs to discover what to do next:
                     </Section>
                     <LearnMoreLinks />
                 </View>
             </ScrollView>
         </SafeAreaView>
     );
 };
 
 const styles = StyleSheet.create({
     sectionContainer: {
         marginTop: 32,
         paddingHorizontal: 24,
     },
     sectionTitle: {
         fontSize: 24,
         fontWeight: '600',
     },
     sectionDescription: {
         marginTop: 8,
         fontSize: 18,
         fontWeight: '400',
     },
     highlight: {
         fontWeight: '700',
     },
 });
 
 export default App;
```

**Comment by darringrove** [comment]
I have this issues as well. Any update?

**Comment by poulou0** [comment]
I think it's because you're missing the
```js
import "@tensorflow/tfjs-react-native";
```
https://github.com/tensorflow/tfjs/tree/master/tfjs-react-native#step-4-test-that-it-is-working

_Note: Might need to restart the Metro Bundler_

**Comment by darringrove** [comment]
Thanks @poulou0. Here are more details on this issue. 

**System information**
Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js):
No. This issue is reproduced with a bare RN app + the tfjs RN pose detection [example](https://github.com/tensorflow/tfjs-examples/tree/master/react-native/pose-detection). I fixed some typescript issues in the example but did not fundamentally change it.

OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
macOS Monterey 12.4, Xcode 13.4.1

Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
iPhone 12 Pro, iOS 15.5

TensorFlow.js installed from (npm or script link):
TensorFlow.js version (use command below):
I was careful to use the same versions of all packages as the example
`
    "@mediapipe/pose": "~0.4.0",
    "@react-native-async-storage/async-storage": "~1.17.3",
    "@tensorflow-models/pose-detection": "2.0.0",
    "@tensorflow/tfjs": "3.18.0",
    "@tensorflow/tfjs-react-native": "0.8.0",
    "expo": "~45.0.6",
    "expo-camera": "^12.2.0",
    "expo-file-system": "^14.0.0",
    "expo-gl": "^11.3.0",
    "expo-gl-cpp": "^11.3.0",
    "expo-screen-orientation": "~4.2.0",
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "react-native": "0.68.2",
    "react-native-fs": "2.14.1",
    "react-native-gesture-handler": "~2.2.1",
    "react-native-svg": "12.3.0"
`

Browser version: n/a
Tensorflow.js Converter Version:

**Describe the current behavior**
on the call to createDetector
WARN  Possible Unhandled Promise Rejection (id: 0):
TypeError: undefined is not an object (evaluating 'env().platform.fetch')

_Note: call `await tf.ready()` is successful _

**Describe the expected behavior**
createDetector should return the model

Standalone code to reproduce the issue Provide a reproducible test case that is the bare minimum necessary to generate the problem.
[darringrove/posetest](https://github.com/darringrove/posetest)

1. `git clone` repo
2. `cd posetest`
3. `yarn`
4. `npx pod-install`
5. Run in Xcode on iPhone

**Other info / logs Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.**

I have verified that the [example](https://github.com/tensorflow/tfjs-examples/tree/master/react-native/pose-detection) using RN with pose detection works on my Apple M1 using Expo Go. This is not an M1 issue.

I believe this is an issue related to starting with a bare RN app.

1. I created a new RN project using the React Native CLI and the typescript template for RN 0.68.2.
2. I followed the [setup instructions](https://github.com/tensorflow/tfjs/tree/master/tfjs-react-native) in tfjs-react-native. There is a key difference to note (found by following dependent instructions):
   - react-native-unimodules is deprecated and replace by expo. I used the automatic installation for expo.
3. I added additional packages used by the RN pose detection example.
4. I copied the code from App.tsx from the example (and fixed some Typescript issues for a clean build).
5. The issue is recreated in [darringrove/posetest](https://github.com/darringrove/posetest)

Thanks in advance!

**Comment by darringrove** [comment]
@jinjingforever I noticed you only upgraded the expo examples. I would be interested to know if the image-classification/react-native-cli example would similarly break if it were upgraded to Expo 45.

**Comment by darringrove** [comment]
@bergkamp Are you starting with a bare RN app and did you resolve this with @rthadur ?

**Comment by darringrove** [comment]
@jinjingforever @rthadur Fwiw, my attempt to expo eject the example was unsuccessful (in the world of pods).

**Comment by bergkamp** [comment]
@darringrove I had installed EXPO as bare module, it works fine.

**Comment by darringrove** [comment]
@bergkamp How did you resolve this issue? Can you share the working package.json and App.js?

**Comment by fbotalla** [comment]
Does anyone have the answer on how to go past this?

**Comment by rbmdotdev** [comment]
same issue here

**Comment by rajaroni** [comment]
same issue

**Comment by alex-pominov** [comment]
same issue here

**Comment by AmitHBhagat** [comment]
friends, I am also getting the same issue, any solution?

**Comment by RachidZianne** [comment]
Same issue here

**Comment by onuraskinn** [comment]
same issue did you find any solution for this error ? 
 **ERROR  Error loading model: [TypeError: Cannot read property 'fetch' of undefined]**
