### ISSUE TITLE
How to use custom layer  tf.transpose with a layer?

### ISSUE THREAD

**Issue by whoisltd** [tensorflow/tfjs#6462]
I want to use a custom layer to transpose a conv2D layer.

The layers I want are some things like this:
```
    a = tf.layers.conv2d({filters: 2, kernelSize: 1, strides: 1, padding: 'same', name: 'conv4_1'}).apply(x)
    a = tf.layers.softmax().apply(a)
    
    a = tf.transpose(a, [0, 2, 1, 3])
    b = tf.layers.conv2d({filters: 4, kernelSize: 1, strides: 1, padding: 'same', name: 'conv4_2'}).apply(x)

    b = tf.transpose(b, [0, 2, 1, 3])
```

and this is TFOpLambda in my model.js was converted from python:
```
{
            "class_name": "TFOpLambda",
            "config": {
              "name": "tf.compat.v1.transpose",
              "trainable": true,
              "dtype": "float32",
              "function": "compat.v1.transpose"
            },
            "name": "tf.compat.v1.transpose",
            "inbound_nodes": [
              [
                "softmax_2",
                0,
                0,
                {
                  "perm": [0, 2, 1, 3],
                  "name": "transpose",
                  "conjugate": false
                }
              ]
            ]
          }
```
I was tried this with a custom layer:
```
class TFOpLambda extends tf.layers.Layer {
    
    constructor() {
        super({});
        this.supportsMasking = true;
    }

    call(inputs, kwargs) {
        let input = inputs;
        if (Array.isArray(input)) {
            input = input[0];
        }
        this.invokeCallHook(inputs, kwargs);

        const x = tf.transpose(input, [0, 2, 1, 3]);
        return x;
    }
    getClassName() {
        return 'TFOpLambda';
    }
}
TFOpLambda.className = 'TFOpLambda'; 
tf.serialization.SerializationMap.register(TFOpLambda);
```

When I load my model, the terminal does not return an error but it never finishes running.
Do you know how to fix this?

**Comment by francesco98** [comment]
Hello, I'm having the same issue!

Did you solve it?

**Comment by whoisltd** [comment]
> Hello, I'm having the same issue!
> 
> Did you solve it?

drop it :v

**Comment by gaikwadrahul8** [comment]
Hi, @whoisltd 

Apologize for the delayed response and we're re-visiting our older issues and checking whether those issues got resolved or not as of now so May I know are you still looking for the solution or your issue got resolved ?

If issue still persists after following the [official documentation](https://www.tensorflow.org/js/guide/models_and_layers#custom_layers) with latest version of TFJs please let us know with error log and code snippet to replicate the same issue from our end ?

Could you please confirm if this issue is resolved for you ? Please feel free to close the issue if it is resolved ? Thank you!
