### ISSUE TITLE
Three different form factors- a phone, watch, and tablet

### ISSUE THREAD

**Issue by JLeander85** [tensorflow/tfjs#6497]
https://www.reddit.com/r/BoostForReddit/comments/v56zav/three_different_form_factors_a_phone_watch_and/?utm_medium=android_app&utm_source=share

**Comment by JLeander85** [comment]
@JLeander85

**Comment by rthadur** [comment]
It looks like you haven't used a template to create this issue. Please resubmit your issue using a template from [here](https://github.com/tensorflow/tfjs/issues/new/choose). We ask users to use the template because it reduces overall time to resolve a new issue by avoiding extra communication to get to the root of the issue. We will close this issue in lieu of the new one you will create from the template. Thank you for your cooperation.
