### ISSUE TITLE
LSTMCell: different implementation compare with python tf package

### ISSUE THREAD

**Issue by p9gehka** [tensorflow/tfjs#6554]
```js
i.sigmoid().mul(j.tanh()).add($c.mul($forgetBias.add(f).sigmoid()))
```
it's not the same as
```python
c = f * c_tm1 + i * self.activation(z2)
```
you used the second part of `res` j.tanh(), but  z2 `self.activation(z2)` is third part

https://github.com/tensorflow/tensorflow/blob/705e1684593327dae7b1e71087d5c0f97f6e9b25/tensorflow/python/keras/layers/recurrent.py#L2414
```python
  def _compute_carry_and_output_fused(self, z, c_tm1):
    """Computes carry and output using fused kernels."""
    z0, z1, z2, z3 = z
    i = self.recurrent_activation(z0)
    f = self.recurrent_activation(z1)
    c = f * c_tm1 + i * self.activation(z2)
    o = self.recurrent_activation(z3)
    return c, o
```
https://github.com/tensorflow/tfjs/blob/38f8462fe642011ff1b7bcbb52e018f3451be58b/tfjs-core/src/ops/basic_lstm_cell.ts#L68
```js
const i = slice(res, [0, 0], sliceSize);
const j = slice(res, [0, sliceCols], sliceSize);
const f = slice(res, [0, sliceCols * 2], sliceSize);
const o = slice(res, [0, sliceCols * 3], sliceSize);
const newC: Tensor2D = add(mul(sigmoid(i), tanh(j)), mul($c, sigmoid(add($forgetBias, f)) as Tensor2D));
```

**Comment by gaikwadrahul8** [comment]
Hi, @p9gehka 

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFJs team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TFJs [version](https://github.com/tensorflow/tfjs/releases/tag/tfjs-v4.10.0) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tfjs/blob/master/README.md) to stay up to date with the latest developments which are happening in the Tensorflow.js space.

Thank you for your support and cooperation.
