### ISSUE TITLE
The undetected support of timestamp-query extension when using WebGPU backend

### ISSUE THREAD

**Issue by liborui** [tensorflow/tfjs#6691]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS 12.4
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow.js installed from (npm or script link): npm

## Description
Hi guys!

I am studying to use Tensorflow.js to run DNN in the Web browser with WebGPU feature.

### Example #1
So, I first use the `MobileNet` example ([Source](https://github.com/tensorflow/tfjs-examples/tree/master/mobilenet)) of Tensorflow.js as an initial point. However, the example does not use the WebGPU backend of Tensorflow.js. So I modified the first few lines of `index.js` to use the WebGPU backend, as shown below:
```javascript
import * as tf from '@tensorflow/tfjs';
import '@tensorflow/tfjs-backend-webgpu'
import { IMAGENET_CLASSES } from './imagenet_classes';
tf.setBackend('webgpu');
```
Then, following the `npm install` and `npm run watch`, the example indeed runs and could perform the DNN inference.

However, when I watch the terminal output of Chrome,  I see a warning that says

> This device doesn't support timestamp-query extension. Start Chrome browser with flag --disable-dawn-features=disallow_unsafe_apis then try again. Or zero will shown for the kernel time when profiling mode is enabled. Using performance.now is not workable for webgpu since it doesn't support synchronously to read data from GPU.

### Example #2
Another example I tried is the performance benchmark between WebGPU and WebGL backend of Tensorflow.js in the official repo of Tensorflow.js. [source](https://github.com/tensorflow/tfjs/tree/master/tfjs-backend-webgpu/perf)

I use `python3 -m http.server` to run a HTTP server in the `perf` folder, and run the benchmark.
However, the generated result shows that Tensorflow.js cannot get the execution time when running benchmarks on WebGPU. Moreover, the `support timestamp-query extension` warning is also appeared in the terminal of the browser.

## Execution environment of my experiments
I am using MacBook Pro M1 Max (with built-in GPU) + Google Chrome Canary (106.0.5205.0)

## Efforts I have tried
To make the `timestamp-query extension` work, following the instructions in the warning, I tried
```bash
./Google Chrome Canary --args --disable-dawn-features=disallow_unsafe_apis
```

However, this trick does not take any efforts.

So please you guys give me a hint that I can enable this feature?

**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by qjia7** [comment]
@liborui WebGPU should work with `./Google Chrome Canary --enable-unsafe-webgpu`. The warning message `This device doesn't support timestamp-query extension. ...` is only related with profiling mode. We shouldn't print it if `tf.profile` is not called. #6689 will resolve it. 
To run webgpu, you may need to setup a `https` server instead of `http` server. Otherwise `navigator.gpu` will be `null` if the url is like `http://ip-address:port/xxxx`. Or use `http://localhost:port/xxx` in your local machine.
Currently, on MacOS, profile is not well supported. So you may can't see the individual op execution time using gpu timestamp query API in benchmarks. But the avg model execution time using 'peformance.now' is still correct.
