### ISSUE TITLE
renders an error while loading the same code with all imports in chrome extension, i.e length Cannot read properties of undefined (reading 'length') 

### ISSUE THREAD

**Issue by amitmaliik** [tensorflow/tfjs#6697]
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'length')
at Module.inferFromImplicitShape (util_base.js:304:21)

i have been hitting my head in this issue since two weeks, can you please help with this for a side project of min
<img width="1206" alt="181682481-d9ef6610-f3db-4797-ace3-54331ea8e0a1" src="https://user-images.githubusercontent.com/42403708/181924785-e15fd337-bad9-460e-a0c7-3e3c9dd7963f.png">
e

link to my code repo https://github.com/amitmaliik/my-extension

this is the code which i am using below:
<img width="1079" alt="181682793-218d1de2-257a-4b84-a0ba-1d71ea6a24b5" src="https://user-images.githubusercontent.com/42403708/181924828-e135b40c-3fc7-42b5-ac9b-eb878c11101b.png">

**Comment by amitmaliik** [comment]
shows issuse in util_base.js file
<img width="1440" alt="Screenshot 2022-07-30 at 9 21 01 PM" src="https://user-images.githubusercontent.com/42403708/181924880-eda891a8-5e4a-4af1-b7f4-60b904a761fe.png">

**Comment by amitmaliik** [comment]
@rthadur can you please help with this issue, I have been blocked on my product due to this issue for almost a month.

**Comment by rthadur** [comment]
Thank you for the code , I was able to reproduce the same . Similar issue exists on windows for speech-commands here 
https://github.com/tensorflow/tfjs/issues/6358

**Comment by amitmaliik** [comment]
@jinjingforever can you please help resolve this issue, I have been stuck with my side project for more than a month. Much needed help @jinjingforever @rthadur

**Comment by jinjingforever** [comment]
Hi @amitmaliik 

Sorry for the delay.. I was busy with other projects..

I cloned your repo, but I couldn't reproduce the errors.. I can see the embedding being printed after I change the counter:

<img width="611" alt="Screen Shot 2022-08-09 at 3 36 49 PM" src="https://user-images.githubusercontent.com/8752427/183774072-43a72a2b-b059-4a81-a8c7-cbd3e4180fe6.png">

The commands I ran:

```bash
cd my-extension
yarn
yarn build
```

And I clicked the "Load unpacked" button and picked the "build" directory.

Any ideas?

**Comment by amitmaliik** [comment]
it worked for me for yarn but wasn't working with npm.
but really appreciate your help on this issue.

**Comment by shmishra99** [comment]
Hi @amitmaliik ,
I am able to clone and install the extension. It is working fine with the help of yarn. Here is a screenshot:
![image](https://github.com/tensorflow/tfjs/assets/124146945/59443eef-5c3b-41b2-8ef7-93aea65532cc)

However, when I try to run it with npm using the latest versions of the dependencies,  

``` 
"dependencies": {
    "@tensorflow-models/universal-sentence-encoder": "latest",
    "@tensorflow/tfjs": "latest",
    "@tensorflow/tfjs-backend-cpu": "latest",
    "@tensorflow/tfjs-core": "latest",
    "@tensorflow/tfjs-node": "latest"
  } 
```

I am getting the following error:
<img width="491" alt="image" src="https://github.com/tensorflow/tfjs/assets/124146945/488c925d-2f55-45a7-a2a2-eec5d39b78a9">
Could you please check from your side and let us know if you are getting the same error?
Thank You !!
CC: @jinjingforever

**Comment by gaikwadrahul8** [comment]
Hi, @amitmaliik 

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFJs team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TFJs [version](https://github.com/tensorflow/tfjs/releases/tag/tfjs-v4.10.0) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tfjs/blob/master/README.md) to stay up to date with the latest developments which are happening in the Tensorflow.js space.

Thank you for your support and cooperation.
