### ISSUE TITLE
Cannot load tflite over npm

### ISSUE THREAD

**Issue by avi12** [tensorflow/tfjs#6726]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code: No
- OS Platform and Distribution: Windows 10 x64 21H2
- TensorFlow.js installed from: npm
- TensorFlow.js version (use command below): 
   ```json
   {
     "@tensorflow/tfjs-backend-cpu": "^3.19.0",
     "@tensorflow/tfjs-core": "^3.19.0",
     "@tensorflow/tfjs-tflite": "0.0.1-alpha.8"
   }
   ```
- Browser version: Edge beta 104.0.1293.44

**Describe the current behavior**
Unable to load [@tensorflow/tfjs-tflite](https://github.com/tensorflow/tfjs/tree/master/tfjs-tflite) via npm:
```html
<script lang="ts">
  import "@tensorflow/tfjs-backend-cpu";
  import * as tf from "@tensorflow/tfjs-core";
  import * as tflite from "@tensorflow/tfjs-tflite";
  // ...
</script>
 
<!-- other Svelte code -->
```
![screenshot error](https://user-images.githubusercontent.com/6422804/183113279-655ef4c9-e324-46f9-8606-bedbeeaa9eaf.png)

**Describe the expected behavior**
Load it as usual

**Standalone code to reproduce the issue**
https://github.com/avi12/lego-ai.js

**Additional context**
For some reason, loading the libraries over CDN in the HTML (not in the `.svelte`) _does_ work

**Comment by rthadur** [comment]
@avi12 can you please try with latest `tflite` version `0.0.1-alpha.8` ? also could not run the code which you shared , please check. Thank you

**Comment by avi12** [comment]
Try to clone [this revision](https://github.com/avi12/lego-ai.js/tree/62eb1590c2c28a753748925090984a816029b2c2)

**Comment by haideratGitHub** [comment]
I am having same problem. Did you @avi12 find any fix ?

**Comment by avi12** [comment]
@haideratGitHub IIRC I had to downgrade some packages for it to work

**Comment by haideratGitHub** [comment]
@avi12 I am importing `@tensorflow-models/blazeface` and loading blazeface model. I am getting following error. Is it somehow relatable to this issue or I need to find some where else if you can help ?
<img width="476" alt="Screenshot 2022-09-06 at 8 26 40 PM" src="https://user-images.githubusercontent.com/53143024/188675480-04353b8a-900d-45e5-968f-9644ade1e92f.png">

This is the versions I am using
> {
		"@tensorflow-models/blazeface": "^0.0.7",
		"@tensorflow/tfjs": "^3.13.0",
		"react": "^17.0.2",
		"react-dom": "^17.0.2",
		"react-router": "^5.2.1",
		"react-router-dom": "^5.3.0",
		"react-scripts": "4.0.3",
		"react-webcam": "^6.0.0",
	}

**Comment by avi12** [comment]
I personally wouldn't use `@tensorflow/tflite` as the package is still in akpha

**Comment by gaikwadrahul8** [comment]
Hi, @avi12 

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFJs team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TFJs [version](https://github.com/tensorflow/tfjs/releases/tag/tfjs-v4.10.0) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tfjs/blob/master/README.md) to stay up to date with the latest developments which are happening in the Tensorflow.js space.

Thank you for your support and cooperation.
