### ISSUE TITLE
[Codelab]: Making Predictions from 2D Data

### ISSUE THREAD

**Issue by hjy1210** [tensorflow/tfjs#6779]
In the article [Handwritten digit recognition with CNNs](https://codelabs.developers.google.com/codelabs/tfjs-training-classfication/index.html) , accuracy is about 0.8 after training. But accuracy is about 0.9 in evaluate section. I seems there are some accuracy mismatch.

I implement the program following exact the steps described in this article in my local computer. What I got something like the following image.

<img width="807" alt="tensorflow-qa" src="https://user-images.githubusercontent.com/7498709/185899290-78263098-137f-47ed-afe4-836af0611d8d.png">

In training section, the accuracy is about 0.5.  In evaluate section, the accuracy is about 0.75, much more than 0.5.

So my question is : **How to explain the accuracy mismatch between two sections? Is there something wrong in the code?**

**Comment by jenperson** [comment]
The accuracy of the training and evaluation sections in the Codelab are quite similar. Looking at the graph, the training accuracy is closer to .9 than .8. I also ran through the Codelab myself and got similar results. Feel free to try out the [code on Glitch](https://glitch.com/edit/#!/forested-wind-find).

As for your project, I can't make much of a determination without the code. The testing graph has an unusual shape for sure.  Does that occur every time you run it? What happens if you increase `TRAIN_DATA_SIZE` and `TEST_DATA_SIZE`?

**Comment by hjy1210** [comment]
@jenperson  After trying your code on Glitch, I still got the same result as I mentioned before. Following are some image I got:
<img width="960" alt="training" src="https://user-images.githubusercontent.com/7498709/186289518-15ab76d9-e60d-4536-a0b3-c63865e4bd1a.png">
<img width="960" alt="evaluation" src="https://user-images.githubusercontent.com/7498709/186289533-f0705838-a8a9-45c3-b0dd-63aa58401f1e.png">

**Comment by hjy1210** [comment]
@jenperson  After trying your code on Glitch on different devices.
1. on my desktop computer,  the accuracy is about 0.53. This is not normal.
2. on my android mobile, the accuracy is about 0.91. This is normal.
I think there is something wrong in my desktop, can you figure out or guess how to fix my desktop.
nodejs tensorflow.js conflict? setting problem?

Thanks in advance

**Comment by jenperson** [comment]
Let's get some information about your system.
* What operating system do you use?
* What type of CPU/GPU does the computer have?
* What browser are you using? Are you able to try in a different browser and see if you get the same result?

**Comment by hjy1210** [comment]
Information of my desktop:
1. Operation system : Windows 10 64bit
2. CPU : Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz
3. Both Google Chrome and Microsoft Edge have the same result(Accuracy is
about 52% on training, more than 80% on evaluation).
4. On development console, execute tf.getBackend() got result :
'webgl'(same in Chrome and Edge)
5. Display card : Intel(R) HD Graphics 4600

**Comment by gaikwadrahul8** [comment]
Hi, @hjy1210 

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFJs team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TFJs [version](https://github.com/tensorflow/tfjs/releases/tag/tfjs-v4.10.0) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tfjs/blob/master/README.md) to stay up to date with the latest developments which are happening in the Tensorflow.js space.

Thank you for your support and cooperation.
