### ISSUE TITLE
failIfMajorPerformanceCaveat false by default on WebGL backend

### ISSUE THREAD

**Issue by Dorfdude8** [tensorflow/tfjs#6839]
This is an inquiry regarding https://github.com/tensorflow/tfjs/blob/52d30d65ec3dcc2ecb9cda2a72b461a1c5c7852d/tfjs-backend-webgl/src/canvas_util.ts#L29

We've recently had some automation tests fail on our platform with failed WebGL context creation from TFJS because failIfMajorPerformanceCaveat was set to true by default, rendering features on our app unusable. Wondering if this was intentional, and what the reason for setting this to true was.

**Comment by shanumantesc** [comment]
following

**Comment by Linchenn** [comment]
This is intentional for production environment, but not for testing.

From https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/getContext:
> failIfMajorPerformanceCaveat
> A boolean value that indicates if a context will be created if the system performance is low or if no hardware GPU is available.


For production, if WebGL performance is low or no hardware GPU is available, TFJS's other backends most likely perform better than WebGL backend. As a result, in this case, we hope TFJS automatically use other backend.

For testing, even though WebGL performance is not good or only software WebGL is available, you still want to set WebL backend and test on it, so you have to set the test flag before running the tests `tf.env().set('IS_TEST', true);`, then TFJS will set `failIfMajorPerformanceCaveat` as false.
