### ISSUE TITLE
Allow a (fixed value) alpha channel in decodeJpeg

### ISSUE THREAD

**Issue by bartbutenaers** [tensorflow/tfjs#6911]
**System information**
- TensorFlow.js version (you are using): 3.21.0
- Are you willing to contribute it (Yes/No): Yes (but I'm not familiar with the C++ part)

**Describe the feature and the current behavior/state.**
Currently [decodeJpeg](https://js.tensorflow.org/api_node/1.2.7/#node.decodeJpeg) does ***not*** support ´channels=4´ (i.e. no alpha channel), which is normal because jpeg does not support transparancy.  However it would be useful if we were allowed to specify value `4`, which would result in an alpha channel being added with fixed values (e.g. `0xff` which means fully opaque).  

That way, the [decodeImage](https://js.tensorflow.org/api_node/1.2.7/#node.decodeImage) could return a tensor containing an ***rgba*** image for all image types (png, bmp and jpeg), and not only for bmp and png (and ***rgb*** for jpeg).

This would be very convenient (and much faster) for example when the image needs to be drawn into a canvas, because the canvas always expects rgba as [data type](https://developer.mozilla.org/en-US/docs/Web/API/ImageData/data).  

**Will this change the current api? How?**
No, the only change is that value ´4´ would be allowed as input for the `channels` parameter of the `decodeJpeg` functions.

**Who will benefit with this feature?**
All people that need rgba.

**Any Other info.**
One of my use cases is that I need to draw bounding boxes in NodeJs on top of my images with [PureImage](https://www.npmjs.com/package/pureimage), which also expects rgba images for its canvas.  When I add the alpha channel via custom Js code, this consumes quite some cpu.  So it would be nice if this could be done with native code in tfjs...

Thanks !!!
Bart

**Comment by vladmandic** [comment]
its a valid feature request to make api more uniform, but in the meantime adding alpha is trivial and should not consume any cpu on your side:

```js
const rgb2rgba = (rgb) => {
  if (rgb.shape[2] === 4) return rgb;
  if (rgb.shape[2] === 3) return tf.tidy(() => {
    const alpha = tf.fill([rgb.shape[0], rgb.shape[1], 1], rgb.dtype === 'int32' ? 255 : 1, rgb.dtype);
    return tf.concat([rgb, alpha], 2);
  })
  throw new Error('invalid shape');
}
```

**Comment by bartbutenaers** [comment]
Hi @vladmandic,
My sincere apologies for not responding earlier!   Had some unplanned stuff that consumed almost all of my me-time...

Nice to hear that you like the idea to make the api more uniform.  

And thanks a lot for sharing your rgb2rgba function!!!  It works very well and is very fast.  I had written my own function, but I have replaced it by yours now.  If you should have also a _rgba2rgb_ function, I would appreciate a lot if you could also share it.

Kind regards,
Bart

**Comment by vladmandic** [comment]
> If you should have also a rgba2rgb function

i don't *have* it, i just wrote it :)

```js
const rgba2rgb = (rgba) => {
  if (rgba.shape[2] === 3) return rgba;
  if (rgba.shape[2] === 4) return tf.tidy(() => {
    const [r, g, b, a] = tf.unstack(rgba, 2);
    return tf.stack([r, g, b], 2);
  })
  throw new Error('invalid shape');
};
```

**Comment by bartbutenaers** [comment]
Faster than my shadow ;-)
Thanks again!!

**Comment by gaikwadrahul8** [comment]
Hi, @bartbutenaers 

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFJs team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TFJs [version](https://github.com/tensorflow/tfjs/releases/tag/tfjs-v4.10.0) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tfjs/blob/master/README.md) to stay up to date with the latest developments which are happening in the Tensorflow.js space.

Thank you for your support and cooperation.

**Comment by bartbutenaers** [comment]
@gaikwadrahul8,
For me the workaround is sufficient, so I will close this issue.
