### ISSUE TITLE
Tensor Flow tf.image.resizeBilinear() Running in react Native throwing Error

### ISSUE THREAD

**Issue by ekafe** [tensorflow/tfjs#6928]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**

- I have written the Code - For reproducing the bug - i have used the example - https://www.geeksforgeeks.org/tensorflow-js-tf-image-resizebilinear-function/:
- Windows 10 Pro:
- Tested on Android Device - Redmi, Samsung Galaxy:
- npm Installed TensorFlowJS - v3.20.0:
- Chrome-Version 105.0.5195.127, Edge-Version 105.0.1343.53:
- Tensorflow.js Converter Version: tensorflowjs 3.21.0
- "react": "18.1.0",
    "react-native": "0.70.2"

**Describe the current behavior**

While calling `tf.image.resizeBilinear(image, [3, 4])`, image is of type ts.tensor4D/tensor3D in the react native in native debugging, its throws an error - 
`Error: Argument 'images' passed to 'resizeBilinear' must be a Tensor or TensorLike, but got 'Tensor'`
While debugging the error, i found out its throwing error for the function 
In react native, there is option to debug in the browser, so when i running this in the browser, i am getting expected out and no error.
 
If i use expo build, which uses react native 0.69 - Above Error is solved,
But for 0.70 the error still exist.

**Describe the expected behavior**
It should return an tensor Array

**Standalone code to reproduce the issue**
Create a empty react native project
`npx react-native init MyApp --template react-native-template-typescript`

Install tensorflowjs
`npm install @tensorflow/tfjs`

Add the UseEffect and Error Will Come
`
  useEffect(()=>{
    const start = async() => {
        await tf.ready();
        const vals = tf.tensor4d([[
                      [[4, 7], [21, 9]],
                      [[8, 9], [1, 33]]
                      ]]);
        const res = tf.image.resizeBilinear(vals, [3, 4]);
        console.log({res});
    }
    start();
  },[])
`

**Other info / logs** Include any logs or source code that would be helpful to
`
Error: Argument 'images' passed to 'resizeBilinear' must be a Tensor or TensorLike, but got 'Tensor'
Error: Argument 'images' passed to 'resizeBilinear' must be a Tensor or TensorLike, but got 'Tensor'
    at convertToTensor (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.test4&modulesOnly=false&runModule=true:148859:22)
    at resizeBilinear_ (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.test4&modulesOnly=false&runModule=true:163780:34)
`

**Comment by Biki463** [comment]
same error i am aslo getting from the last 1 month and still i am not able to  solve it can i get some help

**Comment by gaikwadrahul8** [comment]
Hi, @ekafe 

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFJs team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TFJs [version](https://github.com/tensorflow/tfjs/releases/tag/tfjs-v4.10.0) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tfjs/blob/master/README.md) to stay up to date with the latest developments which are happening in the Tensorflow.js space.

Thank you for your support and cooperation.
