### ISSUE TITLE
Minor diffs between webgl and webgpu on FaceLandmarkDetection(attention_mesh)

### ISSUE THREAD

**Issue by axinging** [tensorflow/tfjs#6939]
After running FaceLandmarkDetection(attention_mesh) conformance in e2e, we got below results:

1. CPU-WebGPU: failed on Intel with vey small diffs (Error: Arrays differ: actual[0] = 124.50392150878906, expected[0] = 124.50059509277344.), passed on NV. Comparing epsilon: 0.001;
2. CPU-WebGL: pass on both Intel  and NV. Comparing epsilon: 0.001;
3. WebGL-WebGPU: there are small diffs on both Intel and NV. Comparing epsilon: 0.0;

After investigate the WebGL-WebGPU differences by dump tool(https://github.com/tensorflow/tfjs/pull/6850).  Errors are from below operators: 

| Op | Typical error | Workaround |
|----|---------------|------------|
| DepthwiseConv2dNative | "StatefulPartitionedCall/functional_1/depthwise_conv2d_3/depthwise", webgl: "9": 15.315400123596191, webgpu: "9": 15.315399169921875,              |  tf.env().set('WEBGL_PACK_DEPTHWISECONV', false)          |
| _FusedConv2D   |    "StatefulPartitionedCall/functional_1/conv_faceflag/BiasAdd", webgl: "0": -11.646951675415039,  webgpu:"0": -11.646952629089355           |    Use Conv2dNaive    instead   in WebGPU     |
|BatchMatMulV2    |  StatefulPartitionedCall/functional_1/landmarks_to_transform_matrix_v2/MatMul_5", webgl, "3": 14.921016693115234,webgpu:"3": 14.921015739440918,             |  Replace MatMulReduceProgram by MatMulPackedProgram in WebGPU         |

Dump tool e2e URL parameter:
```
task=conformance&benchmark=FaceLandmarkDetection&architecture=attention_mesh&inputType=image&inputSize=0.25&backend=webgpu&WEBGL_USE_SHAPES_UNIFORMS=true&CHECK_COMPUTATION_FOR_ERRORS=false&warmup=0&run=10&profile=0&localBuild=webgl,webgpu,core,converter&CANVAS2D_WILL_READ_FREQUENTLY=false&KEEP_INTERMEDIATE_TENSORS=true&dumpLevel=1&dumpLength=-1
```

Test platform:
```
Google Chrome	108.0.5358.0 (Official Build) canary (64-bit) (cohort: Clang-64) 
Revision	56db8a235e905de676b70dd896cdd8394053cca6-refs/branch-heads/5358@{#1}
OS	Windows 10 Version 21H2 (Build 19044.2130)
JavaScript	V8 10.8.166
User Agent	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
Command Line	"C:\Users\abc\AppData\Local\Google\Chrome SxS\Application\chrome.exe" --disable-dawn-features=disallow_unsafe_apis --disable-quic --enable-blink-features=UnexposedTaskIds --enable-unsafe-webgpu --restart --use-spdy=off --restart --flag-switches-begin --enable-experimental-web-platform-features --flag-switches-end

GL_VENDOR
Google Inc. (Intel)
GL_RENDERER
ANGLE (Intel, Intel(R) UHD Graphics 630 Direct3D11 vs_5_0 ps_5_0, D3D11-30.0.100.9684)
```

**Comment by gaikwadrahul8** [comment]
Hi, @axinging 

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFJs team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TFJs [version](https://github.com/tensorflow/tfjs/releases/tag/tfjs-v4.10.0) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tfjs/blob/master/README.md) to stay up to date with the latest developments which are happening in the Tensorflow.js space.

Thank you for your support and cooperation.
