### ISSUE TITLE
TensorFlow.js doesn't work with Keras models with named inputs (only positional inputs)

### ISSUE THREAD

**Issue by petersn** [tensorflow/tfjs#6986]
Observe these lines here:

https://github.com/tensorflow/tfjs/blob/38f8462fe642011ff1b7bcbb52e018f3451be58b/tfjs-layers/src/engine/container.ts#L1256-L1258

This typing of `config['inputLayers']` holds for a Keras model with positional inputs, but if the inputs are named, then `config['inputLayers']` is an object whose keys are the names of the inputs, and the for loop crashes as the object isn't iterable. This should dispatch on that possibility. I can try to write a PR to fix this, but I suspect I won't have time for at least a month or so, possibly you want to fix this before then.

To make a Keras model that exercises this issue:
```
inp_features = tf.keras.Input(shape=(10, 10), name="inp_features")
model = tf.keras.Model(inputs={"features": inp_features}, outputs={"trivial": inp_features})
# This next model would not trigger the issue, and works fine:
#model = tf.keras.Model(inputs=[inp_features], outputs=[inp_features])
```

Also thanks for making TensorFlow.js, I've found it to be a breeze to integrate with my app, and has dramatically improved the performance of my model in browser over what I could accomplish with WASM from Rust. So thanks!

**Comment by gaikwadrahul8** [comment]
Hi, @petersn 

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFJs team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TFJs [version](https://github.com/tensorflow/tfjs/releases/tag/tfjs-v4.10.0) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tfjs/blob/master/README.md) to stay up to date with the latest developments which are happening in the Tensorflow.js space.

Thank you for your support and cooperation.
