### ISSUE TITLE
[RN] Accessing additional keypoints in react-native for BlazePose

### ISSUE THREAD

**Issue by eledahl** [tensorflow/tfjs#7018]
Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js): Copied from [Here](https://github.com/tensorflow/tfjs-examples/tree/master/react-native/pose-detection) but changed to BlazePose
OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 22
Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: iPhone SE & iPhone 12. IOS 15
TensorFlow.js installed from (npm or script link): npm
TensorFlow.js version (use command below): "^0.8.0"
Tensorflow.js Converter Version: ^3.19.0

**Describe the current behavior**
Only able to access the normal 33 keypoints

**Describe the expected behavior**
I'm seeing an additional 6 keypoints here:
https://github.com/tensorflow/tfjs-models/blob/master/pose-detection/README.md

```
33: bodyCenter
34: forehead
35: leftThumb
36: leftHand
37: rightThumb
38: rightHand 
```

I am not seeing any updates to react-native packages that would allow me to access them

**Comment by gaikwadrahul8** [comment]
Hi, @eledahl 

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFJs team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TFJs [version](https://github.com/tensorflow/tfjs/releases/tag/tfjs-v4.10.0) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tfjs/blob/master/README.md) to stay up to date with the latest developments which are happening in the Tensorflow.js space.

Thank you for your support and cooperation.
