### ISSUE TITLE
React Native: 250mb efficientnet model + weights crashes app

### ISSUE THREAD

**Issue by d-kls** [tensorflow/tfjs#7024]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js): no
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Android Studio Emulator Pixel 6 
- TensorFlow.js installed from (npm or script link): npm
- TensorFlow.js version (use command below): @tensorflowjs/tfjs 4.0.0 /tfjs-react-native: 0.8.0
- Browser version: -
- Tensorflow.js Converter Version: ?

**Describe the current behavior**

App crashes when trying to call loadGraphModel on my efficientnet model. the model was converted with `tensorflowjs_converter` from `saved_model.pb` to `model.json` with 29 binary weight shards (1 = 9000kb).  

**Describe the expected behavior**
Locally stored files to be loaded and assembled to Graph model without crash 
OR 
Communicate clear limit of allowed models?

**Other info / logs** Include any logs or source code that would be helpful to
The project was setup with react-native init and all required dependencies of the tfjs react native adapter were installed. 
There are no error logs shown anywhere when the app crashes. Loading a smaller modell - a model using mobile net - works.

**Comment by gaikwadrahul8** [comment]
Hi, @d-kls 

Apologize for the delayed response and it is highly likely caused by incompatible package versions, specifically `expo-gl `and `react-native` and the following version combination should work. It is tested on iPhone 13 Pro Max with iOS 15.1.1 and Pixel 2 with Android 9 and please refer this [official documentation ](https://github.com/tensorflow/tfjs-examples/tree/master/react-native) and also refer this [comment](https://github.com/tensorflow/tfjs/issues/7454#issuecomment-1478743753). 

If issue still persists after following below version combination please let us know with error log to do further investigation to find out root cause for your issue ? Thank you!

```
"expo": "~44.0.2",
"expo-camera": "^12.1.0",
"expo-file-system": "^13.2.0",
"expo-gl": "^11.1.1",
"expo-gl-cpp": "^11.1.0",
"react": "17.0.1",
"react-native": "~0.64.3"
```
