### ISSUE TITLE
i have a error when running example in android

### ISSUE THREAD

**Issue by NgoVanDau** [tensorflow/tfjs#7060]
Dear tfjs team,
I do some request install and programming according your example. Compile has not error but when i run on physic android(galaxy 7-2018) it have a error:
TypeError: Cannot read property 'ExponentGLObjectManager' of undefined, js engine: hermes
 ERROR  Invariant Violation: Failed to call into JavaScript module method AppRegistry.runApplication(). Module has not been registered as callable. Registered callable JavaScript modules (n = 10): Systrace, JSTimers, HeapCapture, SamplingProfiler, RCTLog, RCTDeviceEventEmitter, RCTNativeAppEventEmitter, GlobalPerformanceLogger, JSDevSupportModule, HMRClient.
        A frequent cause of the error is that the application entry file path is incorrect. This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native., js engine: hermes

please tell me how to resolve it. Thanks.

**Comment by gaikwadrahul8** [comment]
Hi, @NgoVanDau 

Apologize for the delayed response and It looks like you haven't used a template to create this issue. Please resubmit your issue using a template from [here](https://github.com/tensorflow/tfjs/issues/new/choose). We ask users to use the template because it reduces overall time to resolve a new issue by avoiding extra communication to get to the root of the issue.

Meanwhile, May I know which tfjs-examples are you trying ? and  could you please try with package dependancies which are mentioned in this [official documentation](https://github.com/tensorflow/tfjs-examples/tree/master/react-native) ? 

If issue still persists please let us know ? Thank you!

```
"expo": "~44.0.2",
"expo-camera": "^12.1.0",
"expo-file-system": "^13.2.0",
"expo-gl": "^11.1.1",
"expo-gl-cpp": "^11.1.0",
"react": "17.0.1",
"react-native": "~0.64.3",
```
