### ISSUE TITLE
Add WebAssembly backend with threading but no SIMD

### ISSUE THREAD

**Issue by FranklinWhale** [tensorflow/tfjs#7134]
**System information**
- TensorFlow.js version (you are using): 4.1.0
- Are you willing to contribute it (Yes/No): Not sure

**Describe the feature and the current behavior/state.**
Safari and the Enhanced Security Mode of Microsoft Edge support multithreading but not SIMD. However, as the current threaded build of Wasm backend requires SIMD, the most basic Wasm build will be loaded, not bringing the optimal performance.

https://webassembly.org/roadmap/

**Will this change the current api? How?**

If custom Wasm paths are set, 1 more path (`tfjs-backend-wasm-threaded.wasm`) will be required.

**Who will benefit with this feature?**
Users of Safari and Microsoft Edge

**Comment by vladmandic** [comment]
@FranklinWhale difference between *single-threaded* and *multi-threaded* `wasm` are minimal for `tfjs`.  
`simd` is what matters, but if apple and microsoft don't allow `simd`, it should be raised with them.

**Comment by FranklinWhale** [comment]
According to [this blog post](https://blog.tensorflow.org/2020/09/supercharging-tensorflowjs-webassembly.htm),

> The performance gains from SIMD and multithreading are independent of each other.

And

> Since most runtimes that support multi-threading also support SIMD, we decided to omit the multi-threading-only runtime to keep our bundle size down.

As performance improvement brought by multithreading is not insignificant (1.8 - 2.9x) and "most runtimes that support multi-threading also support SIMD" is unfortunately not true, I think it's valuable to bundle a multithreading only runtime.

**Comment by vladmandic** [comment]
according to my experience and benchmarks, benefits of multi-threaded wasm are below 3% while benefits of simd are massive.  

and it makes sense to take advantage of simd, you can, but you often you dont have to code specifically for that - compiler will add a lot of optimizations.  

but for multithreading to have any effect, its really up to the caller. being multi-thread capable and actually actively taking advantage of it are two different things. some kernel ops would benefit tremendously from multithreading, but they would need to be written completely differently for single-thread and multi-threaded workflows - and that is not the case.

**Comment by gaikwadrahul8** [comment]
Hi, @FranklinWhale 

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFJs team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TFJs [version](https://github.com/tensorflow/tfjs/releases/tag/tfjs-v4.10.0) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tfjs/blob/master/README.md) to stay up to date with the latest developments which are happening in the Tensorflow.js space.

Thank you for your support and cooperation.
