### ISSUE TITLE
Investigate compute shaders

### ISSUE THREAD

**Issue by annxingyuan** [tensorflow/tfjs#716]
https://github.com/KhronosGroup/WebGL/pull/2707

**Comment by rumschuettel** [comment]
Any news on this? Even if compute shaders will only be part of WebGL 2.1, it would seem mature to move shaders over prior to that so that developers can use nightly builds of browsers to develop their models such that they're ready once it becomes officially part.

Here are some relevant links:
https://www.khronos.org/blog/webgl-2.0-arrives
https://news.ycombinator.com/item?id=8791056
https://bugzilla.mozilla.org/show_bug.cgi?id=664147#c30%3E
https://bugs.chromium.org/p/chromium/issues/detail?id=859249
https://groups.google.com/a/chromium.org/forum/#!topic/blink-dev/bPD47wqY-r8

Thinking even longer-run it might be worth to bet on WebGPU as well, there's already some traction:
https://groups.google.com/a/chromium.org/forum/#!msg/blink-dev/dxqWTSvyhDg/1UDaFD17AQAJ

**Comment by nkreeger** [comment]
This is a topic we're going to be looking at more in 2019. We can bootstrap Compute shaders using the [node-gles](https://github.com/google/node-gles) package (not yet published) today but we haven't had cycles for it yet.

**Comment by evdem** [comment]
TensorFlow Lite on GPU
https://www.tensorflow.org/lite/performance/gpu_advanced
supports some compute shader based functions on OpenGL ES 3.1.
Is it possible to include them into TFjs (e.g. as prototype)?
