### ISSUE TITLE
Better MedipipeSelfiSegmentation quality like google meet

### ISSUE THREAD

**Issue by Exlord** [tensorflow/tfjs#7163]
I have a question. Couple of month ago I checked out google meet when I was implementing our apps web cam background changer...
My implementation with tensorflowjs+bodypix had similer quality with google meets implementation of this functionality ...
But now google meets quality is way better than mine (using tensorflowjs+body-segmentation(mediapipe selfi-segmentation))

So, Is there anyway to make it better and close to google meet? Can I train the model to make it better ?

```
const model = bodySegmentation.SupportedModels.MediaPipeSelfieSegmentation;
const bodySegmenterConfig: MediaPipeSelfieSegmentationMediaPipeModelConfig = {
  runtime: 'mediapipe', //mediapipe or 'tfjs'
  modelType: 'general', // or 'landscape',
  solutionPath: '/node_modules/@mediapipe/selfie_segmentation',
};
bodySegmentation.createSegmenter(model, bodySegmenterConfig);
```

```
  protected foregroundThreshold = 0.5;

  protected edgeBlurAmount = 5;

    private async createPersonMask(segmentation: Segmentation | Segmentation[]): Promise<HTMLCanvasElement> {
    const backgroundMaskImage = await BodySegmentation.toBinaryMask(
      segmentation,
      {
        r: 0,
        g: 0,
        b: 0,
        a: 255,
      },
      { r: 0, g: 0, b: 0, a: 0 },
      false,
      this.foregroundThreshold,
    );
    const maskCanvas = renderImageDataToCanvas(backgroundMaskImage, this.ensureCanvas(Canvases.MASK));
    if (this.edgeBlurAmount === 0) return maskCanvas;
    return await drawAndBlurImageOnCanvas(this.ensureCanvas(Canvases.BLURRED_MASK), maskCanvas, this.edgeBlurAmount);
  }
```

**Comment by pyu10055** [comment]
@Exlord thank you for raising this concern, to understand your situation better, can you qualify the improvement you are seeing on Meet, is it faster, more accurate or both?

**Comment by Exlord** [comment]
@pyu10055 Its more accurate 
Recorded Samples : 
Google Meet : https://chat.skyroom.online/files/ujk6d3pouib9xpf3dichc3hqnh/public?h=l49LebKaAgWYvsr527lcYMEpw0qoGIqvrATqPuUfREM

Mine : https://chat.skyroom.online/files/pnf9xjnet3ysue5rkntd6xbonw/public?h=T1AMNtBEVR3krI114QrNEKN9Vut9sYT_WKzZlnkk06g

**Comment by pyu10055** [comment]
@Exlord Unfortunately, Google Meet uses a proprietary model that is not open sourced.
In your video I do see some lagging on the segmentation masks, I am not sure if it is related to recording, but there are ways to setup the GPU pipeline that will improve model inference / rendering performance.

**Comment by danrossi** [comment]
How do we setup GPU pipeline for desktop and mobile browser ? So mediapipe is now not using webgl ? I see it is setting up a context internally. I had a shader solution to render the mask with webgl with bodypix so attempting to migrate to that now. The mask rendering is rendering back to a canvas software render which increases cpu usage.

**Comment by Linchenn** [comment]
Currently TFJS is using WebGL to setup GPU pipeline. When you use TFJS's WebGL backend for inference, you typically have to input images and get output textures. As a result, if you use `tf.dataToGPU` or `tf.browser.fromPixels` API could improve the rendering performance.

**Comment by danrossi** [comment]
What about input to mediapipe directly ? It seems to be using wasm and mediapipe when setup from tfjs also with runtime: 'mediapipe'. Does it require a webgl rendered buffer first with mediapipe ? toPixels does a software draw from video element and creates a new canvas per frame so needs to be a webgl video texture canvas buffer. 

I'll stick with the webgl buffer. It seems I have alot of work to do in my shader to smooth the edges of the mask as its pixelated on the edges so trying to figure that one out. Im just confused why only canvas software mask rendering with video is still only provided as a helper like with bodypix. The cpu usage with the standard setup is 5-10% higher.

I found an amazing example I've been trying to find the whole time using the dataToGPU method. Getting the mask from tf webgl context directly to render and not download it. Can this be done from results from segmentPeople or is that data already downloaded ? It provides you a mask to use for rendering with the video. 

https://github.com/vladmandic/anime/blob/53805e82c00a3f9ee3fe95b8afe609c8d9c3de71/src/anime.ts#L60

**Comment by danrossi** [comment]
From inspection of media pipe, they are doing a video texture render with webgl so toPixels isn't needed anymore and an external webgl rendered buffer isn't needed. But there is no interface to get to the webgl context if not using tfjs, to be able to download and reuse the texture. trying to work out the best way still. Even the printed video texture could be reused for mixing the frame with the mask. 

Ive got a working solution for now mixing the returned mask r channel with video texture and background texture in webgl for now but it would be good to get the textures directly. It would be good to provide webgl rendering examples rather than keep directing people to do canvas software rendering. The cpu reduction just doing webgl rendering of the mask alone is significant I think.  

But I found there is calculators in mediapipe that could have been configured by default, to mix the video texture with the mask and a background directly, and do smoothing of the mask. And just returned the mixed texture output. So there isn't much needed to do externally. Its webgl shaders in the calculator, so maybe they arent for desktop but android because its cpu wasm for desktop ?  Custom building of the segmentation graph files and loading isn't supported with javascript I think.

**Comment by gaikwadrahul8** [comment]
Hi, @Exlord 

Apologize for the delayed response and It seems like @pyu10055 answered your question [here](https://github.com/tensorflow/tfjs/issues/7163#issuecomment-1358327689).

@danrossi, Yes mediapipe is using calculators to mix the video texture with the mask and a background directly with the help of Calculator options processing parameter, if I'm not wrong so May I know are you looking stiil help on this issue to get the textures directly or your issue got resolved ? Thank you!
