### ISSUE TITLE
SelfieSegmentation is not a constructor

### ISSUE THREAD

**Issue by Exlord** [tensorflow/tfjs#7165]
Hi,
Using vuejs3+vite+ts I am getting this error `Uncaught (in promise) TypeError: jle.SelfieSegmentation is not a constructor`

![Screenshot (230)](https://user-images.githubusercontent.com/3436565/206889116-c1603401-1692-4e3f-8508-336172717474.png)

There was a discussion here https://github.com/vitejs/vite/issues/4680

**Comment by MendyBerger** [comment]
Same issue

**Comment by wangyingjie123** [comment]
same issue. How to solve?

**Comment by gaikwadrahul8** [comment]
Hi, @Exlord 

Apologize for the delayed response and Could you please help us with your codepen-example or Github repo link to replicate same issue from our end ? 

If possible please help us with steps to reproduce the same issue from our end to dig more into your issue. Thank you!

**Comment by Limuyang1013** [comment]
Also meet this when i use `@mediapipe/selfie_segmentation` to segment image

`TypeError: (0 , $csb__tation.SelfieSegmentation) is not a constructor`

**Comment by Bersaelor** [comment]
The problem seems to be that `@mediapipe/*` packages are obfuscated and rollup (which vite uses) doesn't seem to be able to handle it.

In my case the error is:
```js
index-a9b38343.js:1 Uncaught (in promise) TypeError: Ik.FaceMesh is not a constructor
```
caused by `@mediapipe/face_mesh` not being built into the js properly.

I found [this thread](https://github.com/vitejs/vite/issues/4680) in the vite issues page:

> Rollup CommonJS plugin can't work with obfuscated packages because it relies on static analysis to determine its exports.

**Comment by Exlord** [comment]
I found the solution and I am putting it here just as a reference for any one who crosses path here.

```
function mediapipe_workaround() {
  return {
    name: 'mediapipe_workaround',
    load(id: string) {
      if (basename(id) === 'selfie_segmentation.js') {
        let code = fs.readFileSync(id, 'utf-8');
        code += 'exports.SelfieSegmentation = SelfieSegmentation;';
        return { code };
      } else {
        return null;
      }
    },
  };
}
```

vite.config

```
...
    build: {
      rollupOptions: {
        plugins: [mediapipe_workaround()],
      },
    }
```

**Comment by rohan-kumawat-ril** [comment]
@Exlord will building with webpack resolve this issue ?

**Comment by Exlord** [comment]
@rohan-kumawat-ril I don't know , haven't tried it with webpack

**Comment by rohan-kumawat-ril** [comment]
@Exlord  your workaround work for me  , can we use in production build

**Comment by Exlord** [comment]
Yes, this is a build time enchantment, its perfectly safe for production, I am using it in production.

**Comment by tarsusi** [comment]
Hey @Exlord ,

I have the same problem and I was trying your workaround. But what the `basename` stands for in the mediapipe_workaround function?

**Comment by obruchewilfred** [comment]
> I found the solution and I am putting it here just as a reference for any one who crosses path here.
> 
> ```
> function mediapipe_workaround() {
>   return {
>     name: 'mediapipe_workaround',
>     load(id: string) {
>       if (basename(id) === 'selfie_segmentation.js') {
>         let code = fs.readFileSync(id, 'utf-8');
>         code += 'exports.SelfieSegmentation = SelfieSegmentation;';
>         return { code };
>       } else {
>         return null;
>       }
>     },
>   };
> }
> ```
> 
> vite.config
> 
> ```
> ...
>     build: {
>       rollupOptions: {
>         plugins: [mediapipe_workaround()],
>       },
>     }
> ```

Thanks. this works for me

**Comment by liamross** [comment]
I fixed this by manually patching the `@mediapipe/selfie_segmentation` package.

Here's the fix until the `@mediapipe/selfie_segmentation` file is fixed.

1. `npm i patch-package postinstall-postinstall`
2. Go into `node_modules/@mediapipe/selfie_segmentation/selfie_segmentation.js`
3. Add `exports.SelfieSegmentation=nd;` to the last line of the file
   - `nd` is the obfuscated variable that `SelfieSegmentation` is assigned to. In previous fixes the solution was `exports.SelfieSegmentation=SelfieSegmentation;` but that no longer works, and there's a chance that the obfuscated variable changes with each release, so look at the same line for something that looks like `Aa("SelfieSegmentation",nd);` which is where `SelfieSegmentation` is assigned to `nd` (or replace `nd` with whatever the second argument is in your case)
4. Run `npx patch-package @mediapipe/selfie_segmentation` to generate a patch for the package
5. Add the line `"postinstall": "patch-package"` to your scripts so that every time you run `npm i` it will patch the package

**Comment by raviteja83** [comment]
```
import path from "path";
import { fileURLToPath } from "url";

/** Define `__dirname` manually for ESM */
const __dirname = path.dirname(fileURLToPath(import.meta.url));

export default {
  webpack: (config) => {
    config.module.rules.push({
      test: /selfie_segmentation\.js$/,
      use: [
        {
          loader: path.resolve(__dirname, "mediapipe-loader.js"),
        },
      ],
    });

    return config;
  },
};
```
mediapipe-loader.js

```
module.exports = function (source) {
  if (!source.includes('exports.SelfieSegmentation')) {
    source += '\nexports.SelfieSegmentation = SelfieSegmentation;';
  }
  return source;
};
```

The above has worked with `nextjs 15.2.1`

**Comment by EvilSpartans** [comment]
> I found the solution and I am putting it here just as a reference for any one who crosses path here.
> 
> ```
> function mediapipe_workaround() {
>   return {
>     name: 'mediapipe_workaround',
>     load(id: string) {
>       if (basename(id) === 'selfie_segmentation.js') {
>         let code = fs.readFileSync(id, 'utf-8');
>         code += 'exports.SelfieSegmentation = SelfieSegmentation;';
>         return { code };
>       } else {
>         return null;
>       }
>     },
>   };
> }
> ```
> 
> vite.config
> 
> ```
> ...
>     build: {
>       rollupOptions: {
>         plugins: [mediapipe_workaround()],
>       },
>     }
> ```

Thanks it worked for me too !

**Comment by PrajwalDhule** [comment]
Thanks a lot @Exlord and @raviteja83 it worked with Nextjs (15.3.4)!
