### ISSUE TITLE
Hand-pose-detection demos are failing to build/run

### ISSUE THREAD

**Issue by mikkamikka** [tensorflow/tfjs#7203]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow.js installed from (npm or script link): https://github.com/tensorflow/tfjs-models/tree/master/hand-pose-detection/demos
- TensorFlow.js version: 3.9.0

**Describe the problem**

Any attempt running hand-pose detection demos locally failed. I followed the instructions listed here https://github.com/tensorflow/tfjs-models/tree/master/hand-pose-detection/demos#how-to-run-a-demo

Step 2 ("Remove cache etc. rm -rf .cache dist node_modules") throws an error:
```
Remove-Item : A parameter cannot be found that matches parameter name 'rf'.
```

Step 3 ("Build dependency. yarn build-dep") throws a bunch of 27 errors, typical one of:

```
src/mediapipe/mediapipe_test.ts:25:65 - error TS2307: Cannot find module '../shared/test_util' or its corresponding type declarations.
```
etc.

Any suggestion for the correct demos build and run sequence?

Thanks!

**Comment by Linchenn** [comment]
> Step 2 ("Remove cache etc. rm -rf .cache dist node_modules") throws an error:
> 
> ```
> Remove-Item : A parameter cannot be found that matches parameter name 'rf'.
> ```

It looks like you are following the steps on your Windows machine. Actually, the instructions work on Mac or Linux machines, so you have to find out the corresponding commands for windows to run it.

For step2, you could manually delete `.cache dist node_modules` files or folders, if exists.
For step3, running `yarn build-dep` is same as running the following three commands:
```
cd ../../ 
yarn 
yarn build
```
If any of the commands does not work, you have to find corresponding commands for Windows.

**Comment by mikkamikka** [comment]
@Linchenn Thank you for your suggestions. I'm on a Windows machine, and I had no idea those commands are for Mac/Linux evironment.

**Comment by gaikwadrahul8** [comment]
Hi, @mikkamikka 

Apologize for the delayed response and please refer above comment from @Linchenn and if you're looking to clear cache and node modules folder on Windows system then I would suggest you to please follow below steps :

1. Install below NPM package

`npm install rimraf -g`

2. delete the node_modules folder easily with

`rimraf node_modules
`

For clearing the cache you can use `npm-cache` package also, you can refer this [official documentation](https://docs.npmjs.com/cli/v9/commands/npm-cache)

If have I missed something here, please let me know ? If issue still persists please let us know or Could you please confirm if this issue is resolved for you ? Please feel free to close the issue if it is resolved ? Thank you!
