### ISSUE TITLE
[PLEASE HELP] Pose estimation with react-native

### ISSUE THREAD

**Issue by KingOfTNT10** [tensorflow/tfjs#7205]
Hi guys!
not sure if this is the right place but I'm out of options (if there are any other places please recommend).
I'm trying to use react-native to do pose estimation (preferably using BlazePose), I've tried for about 40 hours in total with no success

I'm trying to find someone that can help me do this and guide me along the way.
Is it possible you help me?

So the first question: How do I even start? (What do I install, import etc.)

Thank you so much!! And sorry if it's the wrong place to ask for help

**Comment by Linchenn** [comment]
You may try this demo: https://github.com/tensorflow/tfjs-examples/tree/master/react-native/pose-detection. Then replace the model with your target model.

**Comment by gaikwadrahul8** [comment]
Hi, @KingOfTNT10 

Apologize for the delayed response and you can try below steps which may help you to use TFJs pose-detection model so please follow below steps :

1. Clone this `git clone https://github.com/tensorflow/tfjs-examples.git` in the terminal 
2. Go to pose-detection folder by using `cd /react-native/pose-detection` in the terminal 
3. Run `yarn` command in the terminal ( to install the package dependancies mentioned in the `package.json` file )
4. Run this `yarn start` command in the terminal ( pose-detection model will be up and running and you can test this by scanning QR code by downloading the Expo Go application from your Google play store on android device.

Please let us know if you face any issue while using `pose-detection` model from your end with error log to replicate same issue from our end ? 

Could you please confirm if this issue is resolved for you ? Please feel free to close the issue if it is resolved ? Thank you!

**Comment by wanfathurrahman** [comment]
It worked! But somehow it ask to update SDK project to the latest version (right now is 46). How we can achieve that?
