### ISSUE TITLE
model.predict() takes a lot of time . this causes physical lag in the tensor camera . how to fix ?

### ISSUE THREAD

**Issue by arpitKohli112** [tensorflow/tfjs#7216]
it takes 400ms or so to give a prediction this lags the tensor camera . how to make it fast ? im using webgl as backend as I think its the fastest one . other backends takes even more time . I created a model using teachable machine is this the problem ? pls help .

**Comment by gaikwadrahul8** [comment]
Hi, @arpitKohli112 

Apologize for the delayed response and Could you please help us with your codepen example or Github repo link in which `model.predict()` taking more time, at the moment without code snippet it's difficult to tell what's causing the issue in your code

If you're not using below api's in your code then it may cause the issue so please try to use below api's in your code to avoide memory leak or performance related issue, I hope it will help you to resolve your issue

If issue still persists please help us with code snippet to find out the root cause for your issue. Thank you!

1. [tf.tidy](https://js.tensorflow.org/api/latest/#tidy)
2. [tf.dispose](https://js.tensorflow.org/api/latest/#dispose)
3. [tf.keep](https://js.tensorflow.org/api/latest/#keep)
4. [tf.memory](https://js.tensorflow.org/api/latest/#memory)
