### ISSUE TITLE
Export tfjs symbols in tfjs-node and tfjs-node-gpu package.

### ISSUE THREAD

**Issue by nkreeger** [tensorflow/tfjs#732]
Should be as easy as: export * from '@tensorflow/tfjs' - let's consider doing this.

**Comment by caisq** [comment]
+1 That'll simplify users' import code from two lines to one line and reduce the chance of mistakes. Let's give it a try (and test it out thoroughly, needless to say).

**Comment by dsmilkov** [comment]
+1. This makes sense now that tfjs is a regular dependency of tfjs-node.

**Comment by caisq** [comment]
Related thought: when we make this change, we should probably switch the versioning scheme of tfjs-node so that it is in sync with tfjs. For example, minor version changes in tfjs should be reflected in the minor version of tfjs-node.

**Comment by dsmilkov** [comment]
That's a great point.

General point about this issue: Exposing the API would also reduce problems of [this nature](https://github.com/tensorflow/tfjs/issues/410#issuecomment-425902276) since people won't explicitly import `@tensorflow/tfjs`, thus they are less likely to run `npm install @tensorflow/tfjs` which is what results in having 2 separate versions of tfjs that are not compatible.

**Comment by dsmilkov** [comment]
This is done, right?

**Comment by caisq** [comment]
I think so.

**Comment by nsthorat** [comment]
This is done.
