### ISSUE TITLE
loading hands.js on web worker throws error missing files

### ISSUE THREAD

**Issue by ErickWendel** [tensorflow/tfjs#7380]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Firefox / Darwin M1
- TensorFlow.js installed from (npm or script link): [tfjs-core@4.2.0](https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-core@4.2.0/dist/tf-core.min.js)
- TensorFlow.js version (use command below): 4.2.0
- Browser version: Firefox 109.0.1 (64-bit)
- Tensorflow.js Converter Version: https://unpkg.com/@tensorflow/tfjs-converter@3.7.0/dist/tf-converter.js

**Describe the current behavior**
When try importing hands.js scripts from a web worker it throws the following error:
```
XHR GET http://localhost:8080/hands_solution_packed_assets.data
[HTTP/1.1 404 Not Found 4ms]
Error: Not Found : http://localhost:8080/hands_solution_packed_assets.data
```

**Describe the expected behavior**
it should work without any errors. If I removed it from the worker it instantly work. I'd also try using experimental esm web worker modules but had a different problem

**Standalone code to reproduce the issue**
Bug working: https://erickwendel.github.io/tfjs-hands-webworker-bug/

index.js
https://github.com/ErickWendel/tfjs-hands-webworker-bug/blob/main/index.js#L2-L8

index.worker.js
https://github.com/ErickWendel/tfjs-hands-webworker-bug/blob/main/index.worker.js#L3-L38

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by gaikwadrahul8** [comment]
Hi, @ErickWendel 

Apologize for the delayed response and this package `@mediapipe/hands` maintained and supported by `mediapipe` and looking at your error message from https://erickwendel.github.io/tfjs-hands-webworker-bug/, that error message is coming from this `@mediapipe/hands` package

If Am I missing something here, please let me know ?

If you're facing this issue due to `@mediapipe/hands` package then I would request you to close this issue from here because we're unable to help on this issue because we do not support `@mediapipe/hands` package and `mediapipe` team will help you further after posting this issue in [mediapipe](https://github.com/google/mediapipe/issues/new/choose) repo. Thank you!

**Comment by ErickWendel** [comment]
> Hi, @ErickWendel
> 
> Apologize for the delayed response and this package `@mediapipe/hands` maintained and supported by `mediapipe` and looking at your error message from https://erickwendel.github.io/tfjs-hands-webworker-bug/, that error message is coming from this `@mediapipe/hands` package
> 
> If Am I missing something here, please let me know ?
> 
> If you're facing this issue due to `@mediapipe/hands` package then I would request you to close this issue from here because we're unable to help on this issue because we do not support `@mediapipe/hands` package and `mediapipe` team will help you further after posting this issue in [mediapipe](https://github.com/google/mediapipe/issues/new/choose) repo. Thank you!

got it! gonna check it out! Thanks a lot!

**Comment by gaikwadrahul8** [comment]
Hi, @ErickWendel 

I wanted to follow up on the issue you reported here. Have you had a chance to check if the issue is related to the `MediaPipe `packages or `TensorFlow.js`? If the issue is related to `MediaPipe,` please submit it to the [MediaPipe repository](https://github.com/google/mediapipe/issues/new/choose) and feel free to close this issue.

Thank you for your patience and understanding.
