### ISSUE TITLE
Sudden craving for aws-sdk, nock, mock-aws-s3

### ISSUE THREAD

**Issue by jambudipa** [tensorflow/tfjs#7394]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS Ventura 13.2.1
- TensorFlow.js installed from (npm or script link): npm
- TensorFlow.js version: 4.2.0

**Describe the problem**

I had previously used the `@tensorflow/tfjs-node` library successfully with no issues. Now, however, I have changed environments and unfortunately I am running into issues. I don't have the original source code any more to compare to see what the difference is.

I am running under node v18.4.0, although I have tried v16.16.0 and v14.21.2 (using `nvm` on macOS).

The problem is now it seems the library wants all sorts of supporting modules, which are not installed:

- aws-sdk
- nock
- mock-aws-s3

It will not build without these, so I `npm i` them and then it builds happily.

So first question: why might my environment now be needing these where it didn't need them before? What might be different? As I say, sadly I don't have the last environment around any more.

Having built this, I now receive the error:
> Error: @package/learn package.json is not node-pre-gyp ready:
> package.json must declare these properties: 
> binary

Although I could configure all this, I think it is the wrong thing to do, since I had it up and running previously without any of this. Is where are these issues now coming from?

Can I run the  `@tensorflow/tfjs-node` without installing or needing those three dependencies? I can provide the other config if it is not apparent to someone who has had the same issue.

**Comment by gaikwadrahul8** [comment]
Hi, @jambudipa 

Apologize for the delayed response and I was able to replicate the issue and I tried latest version of `@tensorflow/tfjs-node` on my Mac M1 and it's getting installed as expected if I'm not wrong 

For Mac with M1 chip, `tfjs-node` only support `arm64` build. To install `tfjs-node`, you need to ensure rosetta has been turned off on your terminal app. Start your terminal and verify following command shows arm64 as response:

`uname -m`

Install your node version with arm64 binary. You can verify that with following command also shows arm64:

`node -e 'console.log(os.arch())'`

I have tried with latest version of `@tensorflow/tfjs-node": "^4.4.0` and `node version v18.15.0` also I tried sample code , it seems like working as expected so if have I missed something here please let me know ? Thank you!

For your reference I have added screenshot below:

![image](https://user-images.githubusercontent.com/115997457/232731300-eff78407-1e97-474e-a50c-8005a0928a0f.png)

**Comment by appocalypseltd** [comment]
Amazingly thorough response, thank you. I shall try it as soon as I can and let you know how I get on.

If I remember correctly, it was only an issue when bundling with esbuild. It was a while ago though, I do presently have it working as an unbundled app.

**Comment by jambudipa** [comment]
Amazingly thorough response, thank you. I shall try it as soon as I can and let you know how I get on.

If I remember correctly, it was only an issue when bundling with esbuild. It was a while ago though, I do presently have it working as an unbundled app.

**Comment by gaikwadrahul8** [comment]
Hi, @jambudipa 

Sure, please give it try from your end and let us know whether is it working as expected or not ? Thank you!

**Comment by ngquhuanbl** [comment]
After a few tries, the error was resolved (at least for my project and my environment).
I had debugged and notice that there's something wrong with how the path is resolved during the Webpack compilation.
In the @tensorflow/tfjs-node code, @mapbox/node-pre-gyp was called via a function named `find` and the corresponding argument is expected to the the path to the `package.json` of the @tensorflow/tfjs-node package but instead resolves to one of the main directory of my project, which caused `package.json is not node-pre-gyp ready` error.
**I add @tensorflow/tfjs-node to the `externals` config of Webpack and all the error were solved.**
However, before coming to a conclusion that Webpack was the cause, I had set up a simple Electron project with same versions for Node, Electron and Webpack. The Webpack config is simple that only includes `entry`, `output` and one plugin named `HTMLWebpackPlugins` to create the html for the renderer process. This simple project didn't encounter during compilation at all (i.e. it doesn't need the `externals` configuration).
I think the cause is 100% our Webpack configuration but maybe the library too since it logic might go wrong against some bundling configuration.
Please investigate more!
---
My environment:
Electron: 22.3.9
Node: 12.22.10
Webpack: 4.44.9
@tensorflow/tfjs-node: 4.12.0
![image](https://github.com/tensorflow/tfjs/assets/62880272/406435e0-899b-4ac6-9fef-41a76f3326b3)
