### ISSUE TITLE
Universal sentence encoder reports very different embeddings for upper and lower case text

### ISSUE THREAD

**Issue by ToonTalk** [tensorflow/tfjs#7418]
**Describe the current behavior**
Embeddings are different for same text depending upon case
**Describe the expected behavior**
They should be same - and are in Python colab - https://colab.research.google.com/github/tensorflow/hub/blob/master/examples/colab/semantic_similarity_with_tf_hub_universal_encoder.ipynb 
**Standalone code to reproduce the issue**
```
<script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs"></script>
<script src="https://cdn.jsdelivr.net/npm/@tensorflow-models/universal-sentence-encoder"></script>
<script>
use.load().then(model => {
  const sentences = [
    'This is a sentence',
    'THIS IS A SENTENCE'
  ];
  model.embed(sentences).then(embeddings => {
    console.log(embeddings.arraySync());
  });
});
</script>
```

**Comment by gaikwadrahul8** [comment]
Hi, @ToonTalk 

Apologize for the delay and I was able to replicate same issue which you're referring here is [gist-file](https://colab.research.google.com/gist/gaikwadrahul8/03bf484b039b48efb98702a3865460f6/copy-of-semantic-similarity-with-tf-hub-universal-encoder.ipynb) and It seems like Universal Sentence Encoder is case-sensitive pre-trained model due to which it's giving different embeddings for upper and lower case text and they're some pre-trained models which are case sensitive so you'll have to verify by giving same input in lower case and upper case to check whether are you getting same embeddings or not and in case of Universal Sentence Encoder it's giving different embedding, it means that model is case-sensitive.

For example, in BERT, you have `bert-base-uncased` and `bert-base-cased` so you'll have to choose pre-trained model upon your use case whether you want to go with case-sensitive model or not. I hope it will help you to resolve your issue.

Here is link `file:///Users/gaikwadrahul/Desktop/TFJS/%237418.html` just right click and inspect and see output in browser console.

If issue still persists please let us know or Could you please confirm if this issue is resolved for you ? Please feel free to close the issue if it is resolved ? Thank you!

**Comment by ToonTalk** [comment]
Thanks. That's helpful. At the minimum this should be documented. And I'm still unclear why this official USE Python Colab is case insensitive.

https://colab.research.google.com/github/tensorflow/hub/blob/master/examples/colab/semantic_similarity_with_tf_hub_universal_encoder.ipynb 

Once I understood that the JavaScript version of USE was case sensitive I fixed my app to lower case the text before passing it to USE so you can close this (but again the documentation really should discuss this).

**Comment by ToonTalk** [comment]
I replaced the line
`messages = [word, sentence, paragraph]`
with
`messages = ["this is a sentence", "THIS IS A SENTENCE"]`

Resulting in
```
Message: this is a sentence
Embedding size: 512
Embedding: [0.02881765551865101, -0.020200146362185478, 0.010696264915168285, ...]

Message: THIS IS A SENTENCE
Embedding size: 512
Embedding: [0.02881765365600586, -0.020200127735733986, 0.01069625373929739, ...]
```

And doing the same with the confusion matrix results in
![image](https://user-images.githubusercontent.com/2138696/223118210-35c9ea48-2c5b-4d87-9873-d6d5a570a796.png)

**Comment by gaikwadrahul8** [comment]
Hi, @ToonTalk 

Thank you for detailed sample example and it seems like in Python Google Colab we don't need to do `lowercase` operation but while using `USE` pre-trained model with TFJS we have to do `toLowerCase()` operation on the input and I found one [stack-overflow](https://stackoverflow.com/questions/75256833/tensorflowjs-universal-sentence-encoder-taking-8-seconds-to-encode-input) there also user did `toLowerCase()` operation on the input  so we'll update or add warning on our `TFJS` official documentation where we are using `USE` model and concerned team will take care of this. Thank you for noticing this issue, I really appreciate your efforts and time.

If you need any further assistance please let us know or Could you please confirm if this issue is resolved for you ? Please feel free to close the issue if it is resolved ? Thank you!

**Comment by ToonTalk** [comment]
Glad to hear the documentation will be updated.
