### ISSUE TITLE
tfjs-data with next.js - minifies to "(0++,e.done&&0++,e.value)", where 0++ which causes an error

### ISSUE THREAD

**Issue by dancherb** [tensorflow/tfjs#7446]
**System information**
- OS Platform and Distribution: Deployed with next.js and node.js on Heroku Stack 22 (Ubuntu 22.04)
- TensorFlow.js installed from (npm or script link): Installed via npm: "@tensorflow/tfjs-node": "3.7.0"

**Describe the problem**
When the project is built and deployed on Heroku, the following error appears:
`Uncaught SyntaxError: Invalid left-hand side expression in postfix operation`

This references the following minified code:
`async nextState(e){await e;let t=await wF(this.iterators,function(e){return e instanceof wJ?{value:e.next().then(e=>(0++,e.done&&0++,e.value)),recurse:!1}:{value:null,recurse:!0}});`

It seems that "0++" is causing the issue here. This appears to be minified from the following function in `@tensorflow\tfjs\node_modules\@tensorflow\tfjs-data\src\iterators\lazy_iterator.ts`. It appears that the variables numIterators and iteratorsDone are reduced to simply 0, thus giving the code 0++.

   ```
 let numIterators = 0;
    let iteratorsDone = 0;
    
    function getNext(container: IteratorContainer): DeepMapAsyncResult {
      if (container instanceof LazyIterator) {
        const result = container.next();
        return {
          value: result.then(x => {
            numIterators++;
            if (x.done) {
              iteratorsDone++;
            }
            return x.value;
          }),
          recurse: false
        };
      } else {
        return {value: null, recurse: true};
      }
    }
```

**Provide the exact sequence of commands / steps that you executed before running into the problem**

I'm attempting to perform face matching on Node.js using the package https://www.npmjs.com/package/@vladmandic/face-api.

**Comment by gaikwadrahul8** [comment]
Hi, @dancherb 

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFJs team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TFJs [version](https://github.com/tensorflow/tfjs/releases/tag/tfjs-v4.10.0) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tfjs/blob/master/README.md) to stay up to date with the latest developments which are happening in the Tensorflow.js space.

Thank you for your support and cooperation.
