### ISSUE TITLE
Uncaught Error: Cannot pass any input to an InputLayer's apply() method. InputLayer name: input1     at n.apply (tf.min.js:sourcemap:17:460091)

### ISSUE THREAD

**Issue by lebron8dong** [tensorflow/tfjs#7457]
I want to perform model inference at layer granularity，like
const model = await tf.loadLayersModel('./tfmodel.json');
var testData=data;
for(var i=0;i<model.layers.length;i++){
  testData=model.layers[i].apply(testdata);
  testData.print();
}
error:Uncaught Error: Cannot pass any input to an InputLayer's apply() method. InputLayer name: input1
    at n.apply (tf.min.js:sourcemap:17:460091)

How to solve it, or is there any other way to do model inference at layer granularity？

**Comment by gaikwadrahul8** [comment]
Hi, @lebron8dong 

Apologize for the delayed response and It seems like duplicate/similar issue [#7462](https://github.com/tensorflow/tfjs/issues/7462) and I have already assigned that issue to appropriate team to take action on it so if this is duplicate or similar issue could you please close this issue because we already being tracked in this issue  [#7462](https://github.com/tensorflow/tfjs/issues/7462), if not please let us know with more information or explanation ? Thank you!
