### ISSUE TITLE
Erratic .dataToGpu() behavior with webGL backend

### ISSUE THREAD

**Issue by paderevski** [tensorflow/tfjs#7463]
**System information**
- Have I written custom code: this is a slight modification of tfjs code
- OS Platform and Distribution : Macbook Pro i9 + AMD Radeon 5600M / OS 13.2
- TensorFlow.js installed from: script link
- TensorFlow.js version: 4.2.0
- Browser version: Chrome 110.0.5481.177 
- Tensorflow.js Converter Version: 4.2.0

**Describe the current behavior**
Using the benchmark at https://github.com/tensorflow/tfjs/tree/master/e2e/benchmarks, with a modification to replace `res.dataSync()` with `res.dataToGPU()` for WebGL backend, the inference time oscillates wildly, after approx 100 inferences. This occurs on DeepLab and similar segmentation models.

**Describe the expected behavior**
Consistent inference times, as exhibited with most other models.

**Standalone code to reproduce the issue**\
replace `dataSync` with `dataToGpu` in https://github.com/tensorflow/tfjs/blob/master/e2e/benchmarks/benchmark_util.js. Use DeepLabv3 with more than 100 iterations.

**Other info / logs** 
Screenshot shows example behavior.
<img width="1307" alt="Screenshot 2023-03-09 at 12 40 47 AM" src="https://user-images.githubusercontent.com/75690676/224036301-91ec19fb-0697-4c78-8258-f9792541dc25.png">

**Comment by Linchenn** [comment]
We could not replace dataSync with dataToGPU here. Actually we do not care the returned values from dataSync or dataToGPU; instead, we are using dataSync here because dataSync is a blocking call. In the other words, when dataSync returns, it means the GPU computation has completed, while dataToGPU is not a blocking call and it could not indicate if the GPU computation completes. 

Thank you for your interests and conducting experiments! @paderevski By the way, the picture you attached is using `dataToGPU` right? Does `dataSync` has oscillations? I am curious.

**Comment by gaikwadrahul8** [comment]
Hi, @paderevski 

Could you please check the above comment from @Linchenn and help us with above asked information to dig more into your  issue ? Thank you!
