### ISSUE TITLE
TFJS measure the execution time of each layer on tfjs when inferring. and get the flops of TensorFlow.js model.

### ISSUE THREAD

**Issue by lebron8dong** [tensorflow/tfjs#7471]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow.js version (you are using): 4.2
- Are you willing to contribute it (Yes/No): YES

**Describe the feature and the current behavior/state.**
-TensorFlow.js measures the execution time of each layer during model inference.
-I want to get the execution time and flops of each layer on tfjs when inferring, and make the results into a bar graph for analysis.

**Will this change the current api? How?**
-There is no straight forward API available in the TFJS

**Who will benefit with this feature?**
-Researchers can analyze model performance through this API and propose methods for model inference performance.

**Any Other info.**

**Comment by gaikwadrahul8** [comment]
Hi, @lebron8dong 

Apologize for the delayed response and it seems like this issue is duplicate issue, we have similar issues https://github.com/tensorflow/tfjs/issues/7425 and https://github.com/tensorflow/tfjs/issues/7425 if I'm not wrong and if this is duplicate feature request then I would request you to please close this issue because we already being tracked this feature request in other issues ? Thank you!
