### ISSUE TITLE
Uncaught TypeError: Cannot read properties of null (reading 'model_config')

### ISSUE THREAD

**Issue by lebron8dong** [tensorflow/tfjs#7486]
keras models are typically saved by , which results in an HDF5 (.h5) file that contains both the model topology and weights. To convert such a file to TF.js Layers format,：
tensorflowjs_converter \
    --input_format=keras \
    /tmp/my_keras_model.h5 \
    /tmp/my_tfjs_model

Then I load the tfjs model and report an error：models.js:295 Uncaught TypeError: Cannot read properties of null (reading 'model_config').
If there will be bugs when converting Keras to tfjs,  is there a way to convert from tfjs_graph_model to tfjs_layers_mode in tfhub？
Keras model source: https://github.com/fchollet/deep-learning-models/releases
AndI used mobilenet_1_0_224_tf.h5.

**Comment by gaikwadrahul8** [comment]
Hi, @lebron8dong 

I Apologize for the delayed response and I was able to replicate the same issue without any error on Google Colab with same model `mobilenet_1_0_224_tf.h5` and it's converting to model.json and also creating .bin files which are weight files of the model for your reference, I have added [gist-file](https://colab.research.google.com/gist/gaikwadrahul8/c87cf5ad44836cb23676f1efc2ae616a/-7486.ipynb) and I have also added screenshot below so please make sure that you're giving the correct model location path. 

If issue still persists please let us know or Could you please confirm if this issue is resolved for you ? Please feel free to close the issue if it is resolved ? Thank you!

![image](https://user-images.githubusercontent.com/115997457/226298247-6b853396-34fd-4691-9b39-d78f7e10a635.png)

**Comment by lebron8dong** [comment]
You can check the model.json file:"modelTopology": null.  I think  HDF5 files released by Keras are weights-only: I.e., they have only the weights, but not the model topology. Should I find files with model topology and weights？

**Comment by shinehs** [comment]
I also encountered this problem, I don't know if it is the problem of the .h5 model, or something else?
