### ISSUE TITLE
Provide a way to add custom GLSL functions in JS API.

### ISSUE THREAD

**Issue by nsthorat** [tensorflow/tfjs#75]
_From @znah on September 11, 2017 12:9_

One can also think of integration with [SaderGraph](https://github.com/unconed/shadergraph) to support users code to make queries to Tensors while abstracting away the data texture layout details. This way we can implement have [MathBox](https://github.com/unconed/mathbox)-like functionality that uses deeplearn.js under the hood.

_Copied from original issue: tensorflow/tfjs-core#121_

**Comment by dcunited001** [comment]
shadergraph doesn't support webgl2 and can't be easily modified to do that. does TFJS use webgl 2?

**Comment by dcunited001** [comment]
it looks like TFJS does pull a [webgl2 context](https://github.com/tensorflow/tfjs-core/blob/ace9e0c4e838b07139973c7f895ec0d6859d7225/src/kernels/webgl/webgl_util.ts#L36), if available. but there aren't any constants associated with webgl2-specific features in the shader metaprogramming in tfjs-core.

@nsthorat if you want to do this, i would recommend running TFJS while Webgl-Inspector is running, so you can ID the textures it creates. if it seems feasible, you can compile your own shaders and push them into storage outside TF on each frame or compute cycle. however, getting the metaprogramming from both Shadergraph and TF play well together will be tough.

however, since the TF textures represent tensors and bc TFJS doesn't really use WebGL, the data in those textures will be heavily deconstructed. WebGL 1.0's feature set has heavy design constraints for shader programming.

**Comment by nsthorat** [comment]
We are going to expose this after we release, relevant methods were exported in this PR (thanks @aman-tiwari) https://github.com/tensorflow/tfjs-core/pull/1202

We'll add a tutorial soon on how to do this.

**Comment by dsmilkov** [comment]
Should we close this issue, or keep to track the tutorial? @nsthorat @aman-tiwari

**Comment by nsthorat** [comment]
Let's keep it open for the tutorial then we can close it

**Comment by aman-tiwari** [comment]
Tutorial at https://github.com/tensorflow/tfjs-website/pull/186

**Comment by nsthorat** [comment]
This is done.
