### ISSUE TITLE
gyp ERR!

### ISSUE THREAD

**Issue by DevPhamPham** [tensorflow/tfjs#7510]
gyp ERR! find VS
gyp ERR! find VS msvs_version not set from command line or npm config
gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
gyp ERR! find VS could not use PowerShell to find Visual Studio 2017 or newer, try re-running with '--loglevel silly' for more details
gyp ERR! find VS looking for Visual Studio 2015
gyp ERR! find VS - not found
gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
gyp ERR! find VS
gyp ERR! find VS **************************************************************
gyp ERR! find VS You need to install the latest version of Visual Studio
gyp ERR! find VS including the "Desktop development with C++" workload.
gyp ERR! find VS For more information consult the documentation at:
gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
gyp ERR! find VS **************************************************************
gyp ERR! find VS
gyp ERR! configure error
gyp ERR! stack Error: Could not find any Visual Studio installation to use
gyp ERR! stack     at VisualStudioFinder.fail (C:\Users\Admin\AppData\Roaming\npm\node_modules\node-gyp\lib\find-visualstudio.js:122:47)
gyp ERR! stack     at C:\Users\Admin\AppData\Roaming\npm\node_modules\node-gyp\lib\find-visualstudio.js:75:16
gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\Users\Admin\AppData\Roaming\npm\node_modules\node-gyp\lib\find-visualstudio.js:369:14)
gyp ERR! stack     at C:\Users\Admin\AppData\Roaming\npm\node_modules\node-gyp\lib\find-visualstudio.js:71:14
gyp ERR! stack     at C:\Users\Admin\AppData\Roaming\npm\node_modules\node-gyp\lib\find-visualstudio.js:390:16
gyp ERR! stack     at C:\Users\Admin\AppData\Roaming\npm\node_modules\node-gyp\lib\util.js:54:7
gyp ERR! stack     at C:\Users\Admin\AppData\Roaming\npm\node_modules\node-gyp\lib\util.js:33:16
gyp ERR! stack     at ChildProcess.exithandler (node:child_process:404:5)
gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
gyp ERR! stack     at maybeClose (node:internal/child_process:1064:16)
gyp ERR! System Windows_NT 10.0.22000
gyp ERR! command "H:\\nodejs\\node.exe" "C:\\Users\\Admin\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--verbose"
gyp ERR! cwd H:\NCKH\Main\node_modules\@tensorflow\tfjs-node
gyp ERR! node -v v16.13.1
gyp ERR! node-gyp -v v9.3.1
gyp ERR! not ok

**Comment by DevPhamPham** [comment]
The issue is gyp ERR, i haven't download Visual Studio and include Desktop development with C++. Then I down load build tool for C++. The problem solved

**Comment by gaikwadrahul8** [comment]
Hi, @DevPhamPham 

Apologize for the delayed response and to use `node-gyp - Node.js native addon `build tool and You can install `node-gyp `using npm command `npm install -g node-gyp` Depending on your operating system, you will need to install and I see in your error log you're using windows system so you'll have to follow below instructions :

On Windows:

Install the current version of Python from the [Microsoft Store package](https://www.microsoft.com/en-us/p/python-310/9pjpw5ldxlz5).

Install tools and configuration manually:

Install Visual C++ Build Environment: [Visual Studio Build Tools](https://visualstudio.microsoft.com/thank-you-downloading-visual-studio/?sku=BuildTools) (using "Visual C++ build tools" workload) or [Visual Studio Community](https://visualstudio.microsoft.com/thank-you-downloading-visual-studio/?sku=Community) (using the "Desktop development with C++" workload)
Launch cmd, npm config set msvs_version 2017
If the above steps didn't work for you, please visit [Microsoft's Node.js Guidelines for Windows](https://github.com/Microsoft/nodejs-guidelines/blob/master/windows-environment.md#compiling-native-addon-modules) for additional tips. You can also refer our [official documentation](https://github.com/nodejs/node-gyp) for node-gyp - Node.js native addon build tool. I hope it will help you to resolve your issue.

If issue still persists in any other steps by following above documentation please let us know or Could you please confirm if this issue is resolved for you ? Please feel free to close the issue if it is resolved ? Thank you!
