### ISSUE TITLE
Unable to install @tensorflow/tfjs-node

### ISSUE THREAD

**Issue by MaxMady** [tensorflow/tfjs#7515]
**System information**
- OS: Windows 11 Pro
- Tensorflow version: @latest
- node-gyp version: @latest
- Visual Studio: 2017
- Python: 3.9

**Describe the problem**
I'm trying to install the latest version of `@tensorflow/tfjs-node` for the past couple of days, but everytime the installation fails stating that "Cannot find an installation of VS". I've tried installing the previous version of the package and I'm successful on doing so, but the latest version seems to be having a bug or so while installing.

On running the previous version, I'm getting an error message, "Error: A dynamic link library (DLL) initialization routine failed." while loading a custom model.

**Comment by gaikwadrahul8** [comment]
Hi, @MaxMady 

I would request you to please follow our [official documentation ](https://github.com/nodejs/node-gyp#on-windows) with all the instructions mentioned in that documentation and if Auto-detection fails for Visual C++ Build Tools 2017 then you can use this command `node-gyp configure --msvs_version=2017` so could please try it from your end and please let us know whether your issue is resolving or not ? 

If issue still persists please let us know ? Thank you!
