### ISSUE TITLE
How to navigate this error, cannot use tensorflow on nodejs 

### ISSUE THREAD

**Issue by amspsingh04** [tensorflow/tfjs#7545]
Downloading installers failed. Error: TypeError: 'process.env' only accepts a configurable, writable, and enumerable data descriptor
npm ERR!     at Function.defineProperty (<anonymous>)
npm ERR!     at Object.removePath (C:\Users\spsin\AppData\Roaming\npm\node_modules\windows-build-tools\dist\utils\remove-path.js:11:12)
npm ERR!     at Object.install (C:\Users\spsin\AppData\Roaming\npm\node_modules\windows-build-tools\dist\install\index.js:29:19)
npm ERR!     at C:\Users\spsin\AppData\Roaming\npm\node_modules\windows-build-tools\dist\start.js:17:19
npm ERR!     at Object.download (C:\Users\spsin\AppData\Roaming\npm\node_modules\windows-build-tools\dist\download.js:35:5)
npm ERR!     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
npm ERR!     at async Object.aquireInstallers (C:\Users\spsin\AppData\Roaming\npm\node_modules\windows-build-tools\dist\aquire-installers.js:32:13) {
npm ERR!   code: 'ERR_INVALID_OBJECT_DEFINE_PROPERTY'
npm ERR! }
npm ERR! windows-build-tools will now exit.

**Comment by gaikwadrahul8** [comment]
Hi, @amspsingh04 

Apologize for the delayed response and just to confirm are you following our this [official documentation](https://github.com/nodejs/node-gyp#on-windows) for Windows system ? If not could you please follow all the instructions mentioned in that official documentation and this [stackoverflow answer ](https://stackoverflow.com/questions/47030300/windows-build-tools-installation-failed) may help you to resolve your issue. if issue still exists please let us know with your error log to do further investigation to find out root cause for your issue ? Thank you!
