### ISSUE TITLE
predictAsync does not exist (React Native Expo)

### ISSUE THREAD

**Issue by sickopickle** [tensorflow/tfjs#7563]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js): I am merely trying to use predictAsync. 
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: iPad Air 5th gen (I think, maybe 4th)
- TensorFlow.js installed from (npm or script link): npm
- TensorFlow.js version (use command below): 3.11.0
- Browser version: 
- Tensorflow.js Converter Version: 3.18.0 (Dependency versions: keras 2.6.0 tensorflow 2.6.2)

**Describe the current behavior**

When I call model.predictAsync(input) in a React Native app, it says that model.predictAsync is not a function/undefined. Using execute, predict, and executeAsync work fine in place of predictAsync.

**Describe the expected behavior**

It should actually work because it is documented. I'm pretty sure I have the correct version required to use it >= 3.0.0

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/CodePen/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by gaikwadrahul8** [comment]
Hi, @sickopickle 

Apologize for the delayed response and I see in your issue template, you mentioned `tensorflow.js version 3.11` if possible could you please try to use latest version of `tensorflow.js 4.4.0` and it may be react native and expo versions issue so May I know which version of react-native and expo are you using currently ? Please check this [comment](https://github.com/tensorflow/tfjs/issues/7454#issuecomment-1478743753) and if you're using latest version of react-native and expo then could you please give it try to downgrade the version to previous stable version ?

If issue still persists please let us know with error log and if possible In order to expedite the trouble-shooting process, please provide a code snippet/codepen/Github repo link to reproduce the issue reported here. Thank you!
