### ISSUE TITLE
uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'shape')

### ISSUE THREAD

**Issue by patchBig** [tensorflow/tfjs#7569]
<img width="597" alt="image" src="https://user-images.githubusercontent.com/25219300/230923816-3215f38a-203b-47d5-b43d-ed6c91086138.png">

**Comment by gaikwadrahul8** [comment]
Hi, @patchBig 

It looks like you haven't used a template to create this issue. Please resubmit your issue using a template from [here](https://github.com/tensorflow/tfjs/issues/new/choose). We ask users to use the template because it reduces overall time to resolve a new issue by avoiding extra communication to get to the root of the issue. 

If possible please edit your issue template with all details mentioned in issue template or create new issue by following above issue template.Thank you for your cooperation.
