### ISSUE TITLE
apply out of core to tensorflowjs

### ISSUE THREAD

**Issue by dongyeoppp** [tensorflow/tfjs#7707]
When training a dataset with tensorflowjs, if the training dataset is very large, can we solve this problem by applying the out-of-core method?

**Comment by dongyeoppp** [comment]
Thank you for your answer. I'll try it

**Comment by gaikwadrahul8** [comment]
Hi, @dongyeoppp 

You're welcome and May I know did you try above workaround and Is it working as expected or not please ? 

If issue still persists please let us know ? or Could you please confirm if this issue is resolved for you ? Please feel free to close the issue if it is resolved ? Thank you!
