### ISSUE TITLE
React native app crashing on release version

### ISSUE THREAD

**Issue by nikolajevric** [tensorflow/tfjs#7753]
What could be the problem if the react native application is not working on the release version but works on the debug version when using TensorFlow? The environment being used is as follows:
"expo": "~47.0.12",
"expo-file-system": "^15.2.2",
"expo-gl": "~12.0.1",
"expo-camera": "~13.1.0",
"react-native": "0.70.8",
"react": "18.1.0",

**Comment by gaikwadrahul8** [comment]
Hi, @nikolajevric 

It seems like due to package compatibility issue between react-native and expo so I would suggest you to please try to use below package dependancies with mentioned version for your project, also refer this [official documentation](https://github.com/tensorflow/tfjs-examples/tree/master/react-native) and see whether is it resolving your issue or not ? I found one [article](https://medium.com/@devesu/react-native-android-release-build-crash-on-device-14f2c9eacf18) which may help you to solve your issue 

If issue still persists please let us know with error log so we'll do further investigation to find out the root cause for your issue  ? Thank you!

```
"expo": "~44.0.2",
"expo-camera": "^12.1.0",
"expo-file-system": "^13.2.0",
"expo-gl": "^11.1.1",
"expo-gl-cpp": "^11.1.0",
"react": "17.0.1",
"react-native": "~0.64.3",
```
