### ISSUE TITLE
Is there a more efficient way to convert VideoFrame to tf.tensor?

### ISSUE THREAD

**Issue by jhl13** [tensorflow/tfjs#7786]
More and more AI is being applied to videos, and video decoding usually results in VideoFrames. Currently, the only method I know of for converting a VideoFrame to a tf.tensor is to copy an array using VideoFrame.copyTo and then convert it to a tf.tensor. However, copyTo is very time-consuming. Is there any other way to complete this conversion more efficiently, or does tfjs plan to support the conversion from VideoFrame to tf.tensor？

**Comment by qjia7** [comment]
Currently, there is no directly way to do it. But for `webgpu` backend, you can do some preprocessing to convert a VideoFrame to a GPUBuffer, then call tfjs API. The whole process is like below:
1. Use [copyExternalImageToTexture](https://www.w3.org/TR/webgpu/#dom-gpuqueue-copyexternalimagetotexture) to copy VideoFrame to a texture.
2. Use [copyTextureToBuffer](https://www.w3.org/TR/webgpu/#dom-gpucommandencoder-copytexturetobuffer) to copy step 1's texture to a buffer.
3.  call [tf.tensor](https://js.tensorflow.org/api/latest/#tensor) to create tensor from a GPUBuffer.

To make the user experience better, I think another way to enhance the current API [tf.browser.fromPixels](https://js.tensorflow.org/api/latest/#browser.fromPixels). We can add a `VideoFrame` as one of the type of `pixels` for `webgpu` backend since underlying `fromPixels` calls [copyExternalImageToTexture](https://www.w3.org/TR/webgpu/#dom-gpuqueue-copyexternalimagetotexture). In  this way, all the complexity in first method is encapsulated in `fromPixels` and users don't need to do any preprocessing.

@chunnienc @pyu10055 How's your opinions?

**Comment by jhl13** [comment]
Additional information:

**Comment by jhl13** [comment]
Additional information:
While using VideoDecoder, I found that setting prefer-hardware causes copyTo to take longer. However, when set to prefer-software, the copying time is shorter. Assuming that the issue arises from setting prefer-hardware, which may cause the VideoFrame data decoded by VideoDecoder to be stored on the GPU (not yet accurately verified if it is indeed GPU data), the challenge now is to find a method to convert VideoFrame into GPUBuffer then into tf.tensor.

![1](https://github.com/tensorflow/tfjs/assets/31816229/05cda58b-3eb4-4b05-9f9c-8c8eafe14e51)
![2](https://github.com/tensorflow/tfjs/assets/31816229/a79b1ce2-8187-4848-a972-98cab29aef60)

Thank you for your suggestion @qjia7 . I will try it out.

**Comment by jhl13** [comment]
My final solution:
1. create image bitmap from VideoFrame using createImageBitmap
