### ISSUE TITLE
TypeError: Unknown op '_FusedMatMul'. I get this error ( : I'm trying to use qna tensorflow.js model

### ISSUE THREAD

**Issue by Axnjr** [tensorflow/tfjs#7795]

**Comment by gaikwadrahul8** [comment]
Hi, @Axnjr 

Thank you for bringing this issue to our attention and It looks like you haven't used a template to create this issue. Please resubmit your issue using a template from [here](https://github.com/tensorflow/tfjs/issues/new/choose). We ask users to use the template because it reduces overall time to resolve a new issue by avoiding extra communication to get to the root of the issue. 

At the moment, by looking at your error message `TypeError: Unknown op '_FusedMatMul'` may be you're trying to use custom model with an operation that is not supported by TensorFlow.js, I may be wrong here but unless until you provide more information about your issue and steps to re-produce the same issue from our end, we're unable to say about root cause for your issue.

Could you please help us with more information and steps which you're following to re-produce same issue from our end ? Thank you!
