### ISSUE TITLE
TypeError: Cannot convert "full" to double

### ISSUE THREAD

**Issue by akanshSirohi** [tensorflow/tfjs#7843]
Using the Handpose Pretrained Model in the browser, 0.1 version was working fine but when I am trying to elevate the version to 0.4 then this error is occuring.

![image](https://github.com/tensorflow/tfjs/assets/34837239/629bc191-1f88-4b79-9644-ec2912b56b69)

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 11
- TensorFlow.js installed from (npm or script link): Script Link

**Describe the current behavior**
Showing the error.

**Describe the expected behavior**
It should work properly.

**Standalone code to reproduce the issue**
```js
const hands = new Hands({
      locateFile: (file) => {
          return `https://cdn.jsdelivr.net/npm/@mediapipe/hands@0.4/${file}`;
      }
});
hands.setOptions({
    maxNumHands: 1,
    minDetectionConfidence: 0.8,
    minTrackingConfidence: 0.9,
    modelComplexity: 'full',
    selfieMode: false,
});
hands.onResults(onResultsHands);
```

Included with the following script tag:-
```html
<script src="https://cdn.jsdelivr.net/npm/@mediapipe/hands@0.4/hands.min.js" crossorigin="anonymous"></script>
```

**Comment by akanshSirohi** [comment]
@gaikwadrahul8 Do you have any quick fix for it...?

**Comment by gaikwadrahul8** [comment]
Hi, @akanshSirohi 

Could you please help us with complete codepen example or github repo where you're trying to use handpose pretrained model in the browser which will help us to find out the root cause for your issue ?

I see in `Tensorflow.js` there are 02 tfjs-models [handpose](https://github.com/tensorflow/tfjs-models/tree/master/handpose) and [hand-pose-detection](https://github.com/tensorflow/tfjs-models/tree/master/hand-pose-detection) so it seems like you're trying to use `hand-pose-detection` model and I checked `package.json `file for it and it's showing `"@mediapipe/hands": "~0.4.0"` [here](https://github.com/tensorflow/tfjs-models/blob/master/hand-pose-detection/demos/live_video/package.json. 

If have I missed something here please let me know or help me with the steps to reproduce the same issue from my end. Thank you!

**Comment by akanshSirohi** [comment]
@gaikwadrahul8 

Here is the simple code that you can try to regenerate the issue,

`index.html`
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Hand Pose - Tensorflow</title>
    <!-- Libraries -->
    <script src="https://cdn.jsdelivr.net/npm/@mediapipe/camera_utils@0.1/camera_utils.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@mediapipe/drawing_utils@0.2/drawing_utils.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@mediapipe/hands@0.4/hands.min.js" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.7.0.min.js"></script>
</head>
<body>
    <div class="text-center">
        <video autoplay="true" id="video" autoplay playsinline webkit-playsinline muted hidden></video>
        <canvas id="previewCanvas"></canvas>
    </div>
    <script src="script.js"></script>
</body>
</html>    
```

`script.js`
```js
const video = document.querySelector("#video");
const canvaselement = document.querySelector('#previewCanvas');
const ctx = canvaselement.getContext('2d');

let camera;

function onResultsHands(results) {
    console.log(results);
}

const loadModel = () => {
    modal_loading = true;
    hands = new Hands({
        locateFile: (file) => {
            return `https://cdn.jsdelivr.net/npm/@mediapipe/hands@0.4/${file}`;
        }
    });
    hands.setOptions({
        maxNumHands: 1,
        minDetectionConfidence: 0.8,
        minTrackingConfidence: 0.9,
        modelComplexity: 'full',
        selfieMode: false,
    });
    hands.onResults(onResultsHands);
    camera.start();
};

$(document).ready(function() {
    video.width = window.innerWidth;
    video.height = video.width * aspect_ratio;
    canvaselement.width = video.width;
    canvaselement.height = video.height;
    camera = new Camera(video, {
        onFrame: async () => {
          await hands.send({image: video});
        },
        facingMode: 'environment', // user
        width: canvaselement.width,
        height: canvaselement.height
    });
    loadModel();
});
```

Now simply run HTML in XAMPP or double-clicking it.

**Comment by gaikwadrahul8** [comment]
Hi, @akanshSirohi 

Apologize for the delayed response and this package `@mediapipe/hands` maintained and supported by mediapipe and there is no TFJs package dependancies in your code so I would request you to please report this issue [here](https://github.com/google/mediapipe/issues) and I hope mediapipe team will help you with your issue.

I would request you to close this issue from here because we're unable to help on this issue because we do not support `@mediapipe/hands` package and mediapipe team will help you further after posting this issue in mediapipe repo. Thank you!

**Comment by akanshSirohi** [comment]
Ok thanks for the information @gaikwadrahul8.
