### ISSUE TITLE
some errors in object detection when using tf.js in web worker

### ISSUE THREAD

**Issue by libofei2004** [tensorflow/tfjs#7869]
I use customvision-tfjs and tf.js to do object detection in web worker, but sometimes some errors  occurred like :

<img width="550" alt="log1" src="https://github.com/tensorflow/tfjs/assets/10001548/af8294b4-6ab3-48cc-a0fa-0423c2759d69">
<img width="440" alt="log2" src="https://github.com/tensorflow/tfjs/assets/10001548/0da936c7-d7a5-463f-bb1f-6f59eb1e76be">
<img width="550" alt="log3" src="https://github.com/tensorflow/tfjs/assets/10001548/672affb7-38cd-4aa5-8c8a-f9d351014206">
<img width="1620" alt="log4" src="https://github.com/tensorflow/tfjs/assets/10001548/47baeb35-9b2a-4e0e-8909-003d1a453d11">

I cannot find out the errors happened in what condition, sometimes it works fine.
my code is:
<img width="432" alt="code1" src="https://github.com/tensorflow/tfjs/assets/10001548/160c9391-54f4-42c1-b1f2-70afa6312943">

imagedata is ImageBitmap, index.umd.js is  customvision-tfjs,  a framework for using tf.js from microsoft , http://github.xiaoc.cn/microsoft/customvision-tfjs

**Comment by gaikwadrahul8** [comment]
Hi, @libofei2004 

Thank you for bringing this issue to our attention and I found similar issue from mediapipe repo [#1436 ](https://github.com/google/mediapipe/issues/1436) where user was getting the same error message and that error was coming from browser side so I'm not sure at the moment which browser you're using so could you please try to downgrade the browser version or changing the web browser and check whether your issue is resolving or not ?

If issue still persists please let us know ? Thank you!

**Comment by pyu10055** [comment]
This is a shader compilation error, and the error indicates that the shape array contains value NaN.
Can you share the full error stack trace, so we can see which op is causing this error?  Or if you can provide a codepen example that replicates this error would be great.

**Comment by libofei2004** [comment]
Thank you @pyu10055 @gaikwadrahul8 . I find  this error probably occured when models are not completely loaded. The models are loaded in web workers but sometimes the image data transfer to workers before some models are loaded completely  yet.

**Comment by gaikwadrahul8** [comment]
Hi, @libofei2004 

You're welcome, Thank you for your analysis so just to confirm, May I know your issue got resolved or not ? If yes, Please feel free to close the issue if it is resolved ? Thank you!
