### ISSUE TITLE
Failing to fetch various models

### ISSUE THREAD

**Issue by nickcalarco66** [tensorflow/tfjs#7874]
Hello,

Starting today, 3 models that we use are failing to fetch from tfhub.dev:

https://tfhub.dev/tensorflow/tfjs-model/blazeface/1/default/1/model.json?tfjs-format=file
https://tfhub.dev/mediapipe/tfjs-model/iris/1/default/2/model.json?tfjs-format=file
https://tfhub.dev/mediapipe/tfjs-model/facemesh/1/default/1/model.json?tfjs-format=file

![Screenshot 2023-07-26 at 9 38 10 AM](https://github.com/tensorflow/tfjs/assets/114501950/7c2e37cf-7833-40d3-a58b-e56c0418d9f4)

This was working yesterday, and is now failing both in localhost environment as well as our deployment environments. We have not changed anything in our application between yesterday and today.

Relevant libraries:

`"@tensorflow-models/face-landmarks-detection": "0.0.3"`
`"@tensorflow/tfjs": "^3.15.0"`

Any insight?

Thanks.

**Comment by gaikwadrahul8** [comment]
Hi, @nickcalarco66 

Thank you for bringing this issue to our attention and It seems like this issue is coming from browser side, The browser has blocked a request to a web resource because the resource does not allow cross-origin requests. 

This can happen for a variety of reasons, but the most common reason is that the server that hosts the resource has not been configured to allow cross-origin requests so could you please refer this stack-overflow [answer](https://stackoverflow.com/questions/67520114/access-to-fetch-at-from-origin-has-been-blocked-by-cors-policy-no-access) which may help you to solve your issue and also try to change `mode="no-cors"` for fetch and If the mode is set to `'no-cors'`, then CORS checks will be disabled.

Could you please give it try, let us know is it resolving your issue or not ? If issue still persists please let us know with error log to find out the root cause for your issue ? Thank you!

**Comment by nickcalarco66** [comment]
HI @gaikwadrahul8,

Thank you for your quick response!

We aren't directly using fetch to download the models, I believe that the tfjs-models packages are managing that.

If I use the `blazeface` tfjs-model package as an example (tensorflow/tfjs-models/blazeface/src/index.ts), it is using the `tfjs-converter` library to resolve the model, which, without digging all the way through that, I would assume is performing the fetch itself:

```
import * as tf from '@tensorflow/tfjs-core';
import * as tfconv from '@tensorflow/tfjs-converter';
import {BlazeFaceModel} from './face';

const BLAZEFACE_MODEL_URL =
  'https://tfhub.dev/tensorflow/tfjs-model/blazeface/1/default/1';

export async function load({
  maxFaces = 10,
  inputWidth = 128,
  inputHeight = 128,
  iouThreshold = 0.3,
  scoreThreshold = 0.75,
  modelUrl,
}: BlazeFaceConfig = {}): Promise<BlazeFaceModel> {
  let blazeface;
  if (modelUrl != null) {
    blazeface = await tfconv.loadGraphModel(modelUrl);
  } else {
    blazeface = await tfconv.loadGraphModel(BLAZEFACE_MODEL_URL, {
      fromTFHub: true,
    });
  }
}
```

I haven't dug through the the other face-landmark model yet, but I would assume the same type of logic is happening, as we've never tried to download the models directly from tfhub.dev before using fetch ourselves, it's simply worked by using the tfjs-models package.

Please advise.

Thanks.

**Comment by nickcalarco66** [comment]
The issue has resolved itself. We posted an issue to the tensorflow/hub repo and they reported an intermittent issue which has now been resolved. Thanks for your help.
