### ISSUE TITLE
It seems the OP Conv2DBackpropInput will use more time in the latest versoin of tfjs in the Intel devices 

### ISSUE THREAD

**Issue by zhiliang029** [tensorflow/tfjs#7929]
When we use tfjs to do VB, we find the version of tfjs 4.10.0 will use more time to get the result than the version of 3.11.0 on Intel i7-7700  HD630 graphics. The following is the result of the benchmark.

the version of tfjs 3.11.0
![image](https://github.com/tensorflow/tfjs/assets/122433353/b7f7212c-9500-4c51-a5be-dc26536f78af)

the version of tfjs 4.10.0
![image](https://github.com/tensorflow/tfjs/assets/122433353/db8adc1e-eebe-4953-9137-d31eacedd927)

the OP Conv2DBackpropInput will use more time on the version of tfjs 4.10.0

**Comment by qjia7** [comment]
@Linchenn  Some additional information:
1. backend: webgl
2. For tfjs 3.11.0, it sill uses `Conv2DDerInputProgram` instead of `Conv2DDerInputPackedProgram`.

So it seems `Conv2DBackpropInput`'s shape in user's model runs faster on the non-packed program than the packed one.

@zhiliang029 Can you share the `Conv2DBackpropInput`'s details information in `individual` mode? Just choose the `kernelTiming` in control panel to `individual` instead of `aggregate`. Then only copy `Conv2DBackpropInput`'s data here. It will be helpful to know the shape you used for `Conv2DBackpropInput`. Then we can adjust the condition to switch to `Conv2DDerInputProgram` or `Conv2DDerInputPackedProgram`.

**Comment by zhiliang029** [comment]
![image](https://github.com/tensorflow/tfjs/assets/122433353/e1775c58-a37b-4e0d-977b-f1c977dde08c)

**Comment by Linchenn** [comment]
It's weird that packed version is slower than unpacked one. I would guess it's from the changes of this file, https://github.com/tensorflow/tfjs/pull/7386/files#diff-985bc9b238aea25dd6e5f275d50d9bee56b105a584a005f14f8716288954f01a. 

Could you help me test whether it's improved on intel devices, if you revert the changes in this file?

**Comment by Linchenn** [comment]
Benchmark results:
After pack optimization - 2.3ms
Revert the [changes](https://github.com/tensorflow/tfjs/pull/7386/files#diff-985bc9b238aea25dd6e5f275d50d9bee56b105a584a005f14f8716288954f01a) - 1.6ms
Before pack optimization - 0.7ms

Considering the input and output shapes, this performance regression could be model-specific problem, so we could provide a flag  to allow users to disable pack optimization on this op. @zhiliang029
