### ISSUE TITLE
Mobile/Phone installation

### ISSUE THREAD

**Issue by Noelh34rts** [tensorflow/tfjs#8067]
I can't find a way to install it. So that means that I can't have anything that's finger tracking. If I could find away that be great, but I don't know how to.

**Comment by gaikwadrahul8** [comment]
Hi, @Noelh34rts 

It looks like you haven't used a template to create this issue. either please resubmit your issue using a template from [here](https://github.com/tensorflow/tfjs/issues/new/choose) or elaborate your issue with more context/description to help you further quickly. We ask users to use the template because it reduces overall time to resolve a new issue by avoiding extra communication to get to the root of the issue.

Thank you for your cooperation.
