### ISSUE TITLE
Using `loadLayersModel` in Capacitor.JS not working when running on Android 

### ISSUE THREAD

**Issue by paladinic** [tensorflow/tfjs#8077]
Hi, 

I've built a cross-platform app with Capacitor, written in Vanilla JS. It uses the following code to load a trained Tensorflow model, a simple classifier NN built in Python.

```
import * as tf from '@tensorflow/tfjs';

// ...other code

const model = await tf.loadLayersModel('./assets/models/model.json');
```

This works on the browser and I can use the model to make predictions. The model fails to load when deployed on Android. 

In the Android Studio logcat I see the following error:

```
E  Unable to open asset URL: http://localhost/assets/models/model.json
```

I also added these in the `AndroidManifest.xml`:
```
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
```

So far I've looked into using the `@capacitor/filesystem` package but I'm not sure how it can be used to replicate the model-loading behaviour of `loadLayersModel`.

I've tried many different versions of the file path without success.
The error is not too informative, although I appreciate it might be more of an Android/Capacitor issue than a Tensorflow issue.

Any help towards replicating the working behaviour of the app running on the browser, in Android would be very appreciated.

Thanks!

**Comment by gaikwadrahul8** [comment]
Hi, @paladinic 

Apologize for the delayed response and thank you for bringing this issue to our attention but as you mentioned it's working fine on the browser and  you can use the model to make predictions but the model fails to load when deployed on Android so  if I'm not wrong, it seems like this issue is coming from `Android/Capacitor`

I found some issue thread with some workaround which may help you to solve your issue [Ref-1](https://github.com/ionic-team/capacitor/issues/3339#issuecomment-664451656), [Ref-2](https://forum.ionicframework.com/t/solved-white-screen-when-debugging-building-from-android-studio/211624). Thank you.

**Comment by paladinic** [comment]
opened an issue with an executable example here:
https://github.com/ionic-team/capacitor/issues/7090

**Comment by gaikwadrahul8** [comment]
Hi, @paladinic 

Thank you for posting this issue to appropriate Github repo so that team will look into this issue and will take appropriate action from their end, To confirm do you want to keep this issue open ? if not please feel free to close this issue.

Thank you for your understanding and patience.
