### ISSUE TITLE
qna model can only answer a few questions.

### ISSUE THREAD

**Issue by ymrdf** [tensorflow/tfjs#8087]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js):no
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 22.04.3 LTS
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:no
- TensorFlow.js installed from (npm or script link):npm
- TensorFlow.js version (use command below):4.13.0
- Browser version: chrome 119.0.6045.159
- Tensorflow.js Converter Version:

**Describe the current behavior**
I run this [demo](https://github.com/tensorflow/tfjs-models/tree/master/qna/demo), but the model can only answer a few questions? And I tried the [demo](https://storage.googleapis.com/tfjs-models/demos/mobilebert-qna/index.html) which you provided. It have the same problem.For example, it can only answer these questions:   

- what  Nikola Tesla is famous for?
- what are  Nikola Tesla's contributions?
- where are  Nikola Tesla be born?
- What is the birthday of Nikola Tesla?
- what did Nikola Tesla studied?
- what is the inventions of Tesla?

It only return an empty array, when I ask these questions:
- who is Nikola Tesla?
-  Where did Nikola Tesla live?
- What did Nikola Tesla do?
- what is Nikola Tesla's major?
- what did Tesla invent?
- Do you know any inventions of Tesla?

**Describe the expected behavior**
It is expected to answer all questions.

**Standalone code to reproduce the issue**
https://storage.googleapis.com/tfjs-models/demos/mobilebert-qna/index.html

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by gaikwadrahul8** [comment]
Hi, @ymrdf 

Thank you for bringing this issue to our attention and I tried `qna` demo from my end and I have also observed same behavior from my end also it's returning an empty array for below mentioned questions so we'll have to dig more into this issue and will update you soon. Thank you.


```
who is Nikola Tesla?
Where did Nikola Tesla live?
What did Nikola Tesla do?
what is Nikola Tesla's major?
what did Tesla invent?
Do you know any inventions of Tesla?
```

**Comment by gaikwadrahul8** [comment]
Hi, @ymrdf 

I apologize for the delayed response and I tried below questions with `qna` model and it seems like giving the relavant answers for below questions but as far I know current qna model is not that much capable to answers all the questions from the given context if I'm not wrong so may be in future our relevant team will add robust `qna` model which will capable to answers all the questions from the given context 

At the moment with my current understanding `qna` model is not that much capable to answers all the questions from the given context due to which it's returning an empty array for some questions, our relavant team is aware of this and will update/upgrade `qna` model with robust model in near future possibly.

```
Where Nikola Tesla used to stay?
Who was Nikola Tesla ?
What were Nikola Tesla inventions?
What major did Nikola Tesla?
What is Nikola Tesla famous for?
```




Does this explanation address your concerns? If so, you'd like to consider this issue closed or please let me know if you have any further questions. Thank you for your understanding and patience.

**Comment by ymrdf** [comment]
HI, @gaikwadrahul8 
Thanks for your response. I am looking forward to your robust model. Hope it will come soon, for the qna model is unusable now. Thank you.
