### ISSUE TITLE
Initialization of backend webgpu failed 

### ISSUE THREAD

**Issue by September-9** [tensorflow/tfjs#8094]
when I use @tensorflow/tfjs-backend-webgpu in HUAWEI Mate 40 Pro,chrome 114.0.5735.60，I got an error，as the picture shows，`const adapter = navigator.gpu.requestAdapter(gpuDescriptor)`is null, so `adapter.features` cause an error.
![WechatIMG5549](https://github.com/tensorflow/tfjs/assets/11736415/3da0b605-9103-4bd6-930f-40a15caab494)

here is version Information:
```
"@tensorflow/tfjs": "^4.1.0",
"@tensorflow/tfjs-backend-wasm": "^4.1.0",
"@tensorflow/tfjs-backend-webgl":` "^4.1.0",
"@tensorflow/tfjs-backend-webgpu": "^4.15.0-rc.0",
```

**Comment by gaikwadrahul8** [comment]
Hi, @September-9 

I apologize for the delayed response and to confirm, have you tried with other mobile devices with latest Google chrome `Version 120.0.6099.109 ` ? if not could you please give it try once and see is it resolving your issue or not ?

I'm not sure at the moment whether is it happening due to browser compatibility issue so please give it try with version `113 (Released 2023-05-02)` Currently supported on `ChromeOS`, `macOS`, and `Windows` only. I see currently you're using `Google chrome 114.0.5735.60` so please give it try with Google chrome `113 (Released 2023-05-02)` and see is it solving your issue ? Please refer this [doc](https://developer.mozilla.org/en-US/docs/Web/API/GPU/requestAdapter#browser_compatibility)

I see currently you're using below package dependancies so could you please try with same package dependancies with same versions for all the package dependancies :

```
"@tensorflow/tfjs": "^4.1.0",
"@tensorflow/tfjs-backend-wasm": "^4.1.0",
"@tensorflow/tfjs-backend-webgl":` "^4.1.0",
"@tensorflow/tfjs-backend-webgpu": "^4.15.0-rc.0"
```

Like below ::

```
"@tensorflow/tfjs": "^4.1.0",
"@tensorflow/tfjs-backend-wasm": "^4.1.0",
"@tensorflow/tfjs-backend-webgl":` "^4.1.0",
"@tensorflow/tfjs-backend-webgpu": "^4.1.0"
```
Thank you for your understanding and patience.

**Comment by September-9** [comment]
I have tried the version "@tensorflow/tfjs-backend-webgpu": "^4.1.0," but it doesn't solve the problem. And I want to solve this promise in Google chrome 114.0.5735.60. I think this is a problem with GPU support detection. Is it possible to optimize it?

**Comment by gyagp** [comment]
WebGPU on Android will be supported in Chrome M121, which will be released on Jan 23, 2024. Before then, WebGPU detection code has problem as on Android, both navigator.gpu and navigator.gpu.requestAdapter are available, but "await navigator.gpu.requestAdapter()" returns null.
I'm not sure whether this deserves a fix. Can you just work around it in your code? Like:
const adapter = await navigator.gpu.requestAdapter();
if (!adapter) {
delete Navigator.prototype.gpu;
}

**Comment by gaikwadrahul8** [comment]
Hi, @September-9 

I apologize for the delayed response and please refer above [comment](https://github.com/tensorflow/tfjs/issues/8094#issuecomment-1869951564) from @gyagp about `WebGPU` on `Android` support with temporary workaround and please let us know is it solving your issue or not ?

Thank you for your understanding and patience.
