### ISSUE TITLE
Is it possible to preload the tf.tidy?

### ISSUE THREAD

**Issue by adriaciurana** [tensorflow/tfjs#817]
To get help from the community, check out our [Google group](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs).

#### TensorFlow.js version
0.12.7

#### Browser version
Chrome

#### Describe the problem or feature request

Hi, I know that this question may sound a bit confusing, but I am using tf.tidy to execute some operations prior to the entry of a neural network.

The problem is that the first iteration of tf.tidy takes approximately 1-2 seconds (I guess you must define everything necessary for gpu and cpu), and the others are very fast (20ms).

My question is if I can "compile" in some way tf.tidy so that the first iteration is already late.

This is the code I am using:

#### Code to reproduce the bug / link to feature request
```
function prediction(img){
	return tf.tidy(() => {
		let now = new Date();
		let pix = tf.fromPixels(img);
		pix = tf.image.resizeBilinear(pix, [128, 128])
					.toFloat()
					.div(tf.scalar(127.5))
					.sub(tf.scalar(1))
					.expandDims(0);
		const pred = network.predictOnBatch(pix);
		console.log('Time:', (+new Date()) - +now);
		return pred;
	});
}
```

The only solution I have found so far is to pre-run the prediction function with a totally black image only to load it all.
```
function load(){
	prediction(new ImageData(128, 128));
}

function run(img){
	return prediction(img);
}
```

**Comment by tafsiri** [comment]
What you are doing is the right approach. That first predict is often longer because it initializes a number bunch of textures on the gpu. Many of these can be re-used on subsequent calls which helps reduce that time. There isn't really a way around this initialization that the browser has to do that I can think of. 

In theory if you wanted to pre-warm the GPU in smaller chunks you could create tensors that correspond to the size and shape of the tensors created by your network and do some cheap operation on them to upload them to the GPU, but I doubt this would be worth it and can be error prone imo. 

You could separate the image resizing from the nextwork prediction and warm them up separately (giving the UI an opportunity to respond to events in between) as a first start if you want to go down that route.

**Comment by tafsiri** [comment]
Going to close this for now as it seems to have answered the question?
