### ISSUE TITLE
Is it useful if I add a simple example on tfjs-examples posenet with video feed and not webcam?

### ISSUE THREAD

**Issue by riccardogiorato** [tensorflow/tfjs#822]
Is it useful if I add a simple example on tfjs-examples posenet with video feed and not webcam?

It will enable anyone to get posenet estimation from a downloaded video easily by replacing a placeholder video.

**Comment by caisq** [comment]
I think it'll be useful! "help wanted" tag added. :)

**Comment by tafsiri** [comment]
Quick question, would the placeholder video be in the repository or hosted somewhere? Is this something that could potentially be added to the existing posenet demo?

cc @nsthorat @oveddan

**Comment by Giorat** [comment]
@tafsiri it could be both for the video, hosted outside or a really lightweight one in the folder in the repository. What would be better?

**Comment by tafsiri** [comment]
I have a preference towards something that can fit in the existing posenet demo folder (e.g. maybe a video.js to complement the camera.js), just so that it is easy to find and we can point people to one thing (as opposed to a separate folder in a different repo). As for video location having it hosted means that the demo can just work being served off a static host like we do now so that is also good, if there is something suitable we can find that is a few hundred kilobytes or something that would be good.

However I'll let others chime in who have done more work on that model.

**Comment by nsthorat** [comment]
cc @oveddan

**Comment by oveddan** [comment]
@Giorat @tafsiri I think a demo like this would be great.  Hosting a couple videos on a cdn would work.
It would also be great if the image demo would support drag & drop of an image (but thats for a separate issue).

**Comment by kenlupo** [comment]
I could really use a demo with a video file. I'm working on a project using tfjs posenet and am struggling with how to process a video, image is easy but a full video is a challenge.

**Comment by carrycooldude** [comment]
I want to solve this issue but I am a begineer in open source so pls anyone guide me in this

**Comment by mdaj06** [comment]
@tafsiri is this issue still open?

**Comment by pree-T** [comment]
May I work on this? Can someone help me?

**Comment by rthadur** [comment]
This feature has been already implemented here https://github.com/tensorflow/tfjs-models/tree/master/pose-detection/demos , please check. Closing this issue. Thank you
