### ISSUE TITLE
tidy function erase tensor before it can be used

### ISSUE THREAD

**Issue by jmpedrosa** [tensorflow/tfjs#8223]
**System information**

I'm using tfjs 4.17.0 on a webapp with the hand-pose-detection library and the mediapipe models

**Describe the current behavior**

The tidy function disposes the tensor before it can be consumed by the 'estimateHands' function which is executed inside the function wrapped by tidy.

**Describe the expected behavior**

The tidy function should dispose the tensor after the completion of the wrapped function.

**Standalone code to reproduce the issue**

```

const model = handPoseDetection.SupportedModels.MediaPipeHands;
const detectorConfig = {
        runtime: "tfjs", 
        modelType: "full",
      };
const detector = await handPoseDetection.createDetector(
        model,
        detectorConfig
      );

//later on the code there's a loop that calls to this function

new Promise((resolve) => {
    tf.tidy(() => {
           const imageTensor = tf.browser.fromPixels(canvasContext.getImageData(0,0,width,height));
           detector.estimateHands(imageTensor).then((hands)=>{  
                if (hands.length > 0) {
                    //do something
                    resolve(true);
                } else {
                    resolve(false);
                }
        });
    }
```

This is the exception:

```
Uncaught (in promise) Error: Tensor is disposed.
    at e.value (tf.min.js:17:210260)
    at e.<anonymous> (tf.min.js:17:208705)
    at h (tf.min.js:17:2100)
    at Generator.<anonymous> (tf.min.js:17:3441)
    at Generator.next (tf.min.js:17:2463)
    at u (tf.min.js:17:8324)
    at o (tf.min.js:17:8527)
    at tf.min.js:17:8586
    at new Promise (<anonymous>)
    at e.<anonymous> (tf.min.js:17:8467)
```

**Comment by gaikwadrahul8** [comment]
Hi, @jmpedrosa 

We sincerely apologize for the delayed response.

To expedite our investigation into the error you encountered, we would be grateful if you could share the following details, at your convenience:
1. GitHub Repository Link (if applicable): If the issue is related to a specific project, a link to the relevant GitHub repository would be immensely helpful.
2. Complete Code Snippet: Please provide the exact code portion where the error occurred.
3. Steps to Reproduce: A detailed breakdown of the actions you took leading up to the error message would be highly beneficial for our replication efforts.

By gathering this information, we can attempt to reproduce the error on our end and conduct a more thorough root cause analysis.

Thank you for your cooperation and patience.
