### ISSUE TITLE
[Codelab]: Making Predictions from 2D Data

### ISSUE THREAD

**Issue by kawaii-kitsune** [tensorflow/tfjs#8245]
await train(model, data);
Data is not defined
so i did this
const data = new MnistData();
await data.load();
await train(model, data);
which I am not that proud of

**Comment by gaikwadrahul8** [comment]
Hi, @kawaii-kitsune 

I apologize for the delayed response and I believe you're following this [codelab example](https://codelabs.developers.google.com/codelabs/tfjs-training-regression?hl=en#0) with all instructions mentioned in the codelab example in that we are loading the `"cars"` dataset from a JSON file that we have hosted for you [here](https://storage.googleapis.com/tfjs-tutorials/carsData.json) but I see you're trying to load MNIST dataset so for that please refer [3. Load the data](https://codelabs.developers.google.com/codelabs/tfjs-training-classfication?hl=en#2) section from this [codelab example ](https://codelabs.developers.google.com/codelabs/tfjs-training-classfication?hl=en#0)

We have provided code to load these images from a special [sprite file](https://storage.googleapis.com/learnjs-data/model-builder/mnist_images.png) (~10MB) that we have created for you so that we can focus on the training portion.

Feel free to study the [data.js](https://raw.githubusercontent.com/tensorflow/tfjs-examples/master/mnist-core/data.js) file to understand how the data is loaded. Or once you are done with this tutorial, create your own approach to loading the data.

The provided code contains a class MnistData that has two public methods:

```
nextTrainBatch(batchSize): returns a random batch of images and their labels from the training set.
nextTestBatch(batchSize): returns a batch of images and their labels from the test set

```
I hope it will help you to resolve your issue, if issue still persists please help us with your Github repo/Codepen example to investigate this issue further. 

Thank you for your cooperation and patience.
