### ISSUE TITLE
Issue running python's tensorflowjs_converter

### ISSUE THREAD

**Issue by xbdrcx** [tensorflow/tfjs#8327]
**System information**
Windows 11
Python 3.12.4
tensorflow 2.16.2
tensorflowjs 3.18.0

Hi everyone

I recently trained a model using python/tensorflow. I wanted to use it on javascript/tensorflowjs so, as instructed here (https://www.tensorflow.org/js/tutorials/conversion/import_keras), I installed the python/tensorflowjs module and proceeded to execute the following on the command line: **tensorflowjs_converter --input_format=keras ./project/model.h5 ./project/model**

Executing that line gives me the following error on file read_weights.py:28 :

AttributeError: module 'numpy' has no attribute 'object'.
`np.object` was a deprecated alias for the builtin `object`. To avoid this error in existing code, use `object` by itself. Doing this will not modify any behavior and is safe.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations. Did you mean: 'object_'?

I tried to change all instances of np.object for np.object_ in both read_weights.py and write_weights.py but that ends up giving other error. (AttributeError: module 'tensorflow.compat.v1' has no attribute 'estimator')

Am I missing something?

**Comment by somkamarius** [comment]
To add - had the same issue with MacOS 14.5 and python 3.12. Switching to 3.10 fixed the issue and tensorflowjs_converter runs properly.

**Comment by gaikwadrahul8** [comment]
Hi, @xbdrcx 

To confirm, have you got chance to try with Python version between `3.7.x and 3.11.x` instead of Python version `3.12.x`  and it should work, if you're using TensorFlow version `2.16.2` then starting with TensorFlow 2.16, doing `pip install tensorflow` will install `Keras 3`. When you have `TensorFlow >= 2.16` and `Keras 3`, then by default `from tensorflow import keras` ([tf.keras](https://www.tensorflow.org/api_docs/python/tf/keras)) will be `Keras 3`.

If you install latest version of `tensorflowjs` then by default it will install `Tensorflow 2.16.2` and` Keras Version: 3.4.1` (Keras 3) which does not support with tensorflowjs_converter so you'll have to downgrade `TensorFlow version to 2.15.0 `where it will use` Keras Version: 2.15.0`

Meanwhile, the legacy `Keras 2` package is still being released regularly and is available on PyPI as `tf_keras` (or equivalently `tf-keras` – note that - and _ are equivalent in PyPI package names). To use it, you can install it via pip install `tf_keras` then import it via `import tf_keras as keras`.

Should you want [tf.keras](https://www.tensorflow.org/api_docs/python/tf/keras) to stay on Keras 2 after upgrading to TensorFlow 2.16+, you can configure your TensorFlow installation so that [tf.keras](https://www.tensorflow.org/api_docs/python/tf/keras) points to `tf_keras`. To achieve this:

Make sure to install `tf_keras`. Note that TensorFlow does not install it by default.
Export the environment variable `TF_USE_LEGACY_KERAS=1`.

There are several ways to export the environment variable:

- You can simply run the shell command export TF_USE_LEGACY_KERAS=1 before launching the Python interpreter.
- You can add export `TF_USE_LEGACY_KERAS=1 `to your `.bashrc` file. That way the variable will still be exported when you restart your shell.
- You can start your Python script with:

```
import os
os.environ["TF_USE_LEGACY_KERAS"] = "1"
```

These lines would need to be before any import tensorflow statement.

Thank you for your cooperation and patience.

**Comment by xbdrcx** [comment]
Hi, @gaikwadrahul8 

As suggested, I downgraded the current Python version and tried with 3.10.11, 3.9.13 and 3.8.6, installed the required modules and ran the line: **tensorflowjs_converter --input_format=keras ./project/model.h5 ./project/model** but it still gives an error: 

Exception has occurred: NotFoundError
c:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow_decision_forests\tensorflow\ops\inference\inference.so not found

In the meanwhile, I discovered WSL. Using it ended up fixing the situation. I installed and configure WSL, installed Python3, both Tensorflow and Tensorflowjs and it worked from there.

Thanks @gaikwadrahul8 and @somkamarius for your responses, appreciate

**Comment by gaikwadrahul8** [comment]
Hi, @xbdrcx 

You're welcome and good to hear that your issue has been resolved with WSL, if your issue got resolved then please feel free to close this issue from your end, if you need any further assistance with TensorFlow.js then please feel free to create [new issue ](https://github.com/tensorflow/tfjs/issues/new/choose) and we'll be happy to help you further.

Thank you for your cooperation and patience.

**Comment by doiko** [comment]
Hi there,
I am a bit confused...
If my training envirnment is:
`python=3.11.x`
`keras >= 3.4 `
`tensorflow >= 2.16`

Is it possible to save a model and convert it to tensoflowjs using 
`tensorflowjs >= 4.20`

So far I have not managed. Even if model.json is created then javascript fails to load the model. 
Solution like the one provide in #8328 cannot go to production.
Everything was fine with `tensorFlow < 2.16`
