### ISSUE TITLE
Error dumping weight ssd_bboxes_select/add/y, dtype int64 not supported.

### ISSUE THREAD

**Issue by allenwangcheng** [tensorflow/tfjs#833]
TensorFlow.js version 0.6.4

**Comment by rthadur** [comment]
It looks like you haven't used a template to create this issue. Please resubmit your issue using a template from [here](https://github.com/tensorflow/tensorflow/issues/new/choose). We ask users to use the template because it reduces overall time to resolve a new issue by avoiding extra communication to get to the root of the issue. We will close this issue in lieu of the new one you will create from the template. Thank you for your cooperation.
