### ISSUE TITLE
Predict is aborted with a .tflite model

### ISSUE THREAD

**Issue by lhofinger** [tensorflow/tfjs#8426]
Hello,

**System information**
- I have written custom code
- OS: Windows 11 23H2
- TensorFlow.js installed from script link https://cdn.jsdelivr.net/npm/@tensorflow/tfjs@latest/dist/tf.js
- TensorFlow.js version: latest
- Browser version: Chrome 130.0
- Tensorflow.js Converter Version: /

**Describe the current behavior**
Trying to use BirdNET model https://github.com/rdz-oss/BattyBirdNET-Analyzer/raw/refs/heads/main/checkpoints/V2.4/BirdNET_GLOBAL_6K_V2.4_Model_FP32.tflite

But I get this error:
classif.js:22 Error: RuntimeError: Aborted(). Build with -sASSERTIONS for more info.
    at abort (tflite_web_api_cc_simd.js:9:6515)
    at _abort (tflite_web_api_cc_simd.js:9:60528)
    at tflite_web_api_cc_simd.wasm:0x1baad
    at tflite_web_api_cc_simd.wasm:0x2e1f87
    at tflite_web_api_cc_simd.wasm:0x2f907
    at tflite_web_api_cc_simd.wasm:0x522f0
    at tflite_web_api_cc_simd.wasm:0x32b150
    at tflite_web_api_cc_simd.wasm:0x17e14
    at TFLiteWebModelRunner.TFLiteWebModelRunner$Infer [as Infer] (eval at new_ (tflite_web_api_cc_simd.js:9:33059), <anonymous>:8:10)
    at module$exports$google3$third_party$tensorflow_lite_support$web$tflite_web_api_client.TFLiteWebModelRunner.infer (tflite_web_api_client.js:2714:188)

The same code, with a simple model is not aborting.

**Standalone code to reproduce the issue**
Simple code with issue: https://www.paludour.net/bats/classification.html

**Comment by shmishra99** [comment]
Hi @lhofinger , 

I am able to reproduce the issue you're facing. I created a dummy dataset of 144,000 points and encountered the same error.

<img width="907" alt="image" src="https://github.com/user-attachments/assets/4774352d-6edf-4f84-bbc8-e9d8ef0051d6">

I've noticed that the model sometimes halts for a while before throwing the error. Additionally, models with fewer tensors seem to work without problems.
While the model is running, I've observed that browser memory consumption becomes very high. I suspect this could be an `'out-of-memory' `issue due to the execution of large tensors.

Thank You!!

**Comment by shmishra99** [comment]
Hi @lhofinger , 

I apologize for the late response. Memory management differs between `browsers` and the main `os`. The model, which runs on Keras, may not be directly compatible with TensorFlow.js. I've observed that the code is spiking system memory. Therefore, I believe this error is due to memory issues. Could you please confirm if your system is also displaying the memory spike? 

Thank You!!
