### ISSUE TITLE
Improve the boken effect on the BodyPix (Person-Segmentation) model

### ISSUE THREAD

**Issue by dsmilkov** [tensorflow/tfjs#891]
cc @oveddan @tylerzhu-github

**Comment by tylerzhu-github** [comment]
Thanks Daniel for creating this issue. I quoted the potential approach described in the original PR:
> For person segmentation bokeh effect, we can treat the floating value of the person segmentation after sigmoid as the alpha mask for blurring effect. More specifically we only set the value below threshold to 0, retain the float value above the threshold for determine how much blur we want to apply. This will make the boundary of the Bokeh blend more softly between main subject and background.

**Comment by oveddan** [comment]
This was fixed with PR https://github.com/tensorflow/tfjs-models/pull/124.

I didn't see the above recommended solution when doing the fix...but my fix achieves a similar result by applying a gaussian blur to the segmentation output before applying it to crop the background in the bokeh effect.  

The above would certainly be good but would just require changing the API and having it return float values.

**Comment by tylerzhu-github** [comment]
> The above would certainly be good but would just require changing the API and having it return float values.
Yes i think we can add a flag in the BodyPix function call to let a user determine what output type we want to return. e.g. use_float_segmentation=True (default False). This way it can be a bit more flexible. What do you think? I have a feeling that combining soft alpha mask and edge blur you have implemented would give us the optimal bokeh effect.

**Comment by oveddan** [comment]
@tylerzhu-github I want to avoid having a flag that changes the return type because that will may add confusion for people and it adds more to document.   I'm wondering if just returning the float values from the API makes sense - and not doing the segmentation threshold in the api.  Since users are going to be calling methods that convert the output to a mask, using the method `toMaskImageData` (see the documentation [here](https://github.com/tensorflow/tfjs-models/blob/a045fd58a464c1bb89e645e7b2ecc17b27d7916f/body-pix/src/output_rendering_util.ts#L145)), and that already iterates through all the pixels, we could actually just apply the threshold there.  

So the high level suggestion is:
* for `estimatePersonSegmentation` - the api returns float values for each pixel.
* in `toMaskImageData` - add an argument for `segmentationThreshold` - when this converts it to a binary mask image it uses that threshold.

Some downsides to this:
*  it is inconsistent with the `estimateBodyPartSegmentation` return because that returns integer values in the array, as there the segmentation threshold is applied to the output to crop the body parts.  
* Threshold is performed on CPU, but performance hit is negligent as the user would be using `toMaskImageData` anyways.

What do you think @dsmilkov @nsthorat ?

**Comment by tylerzhu-github** [comment]
Thanks for the explanations Dan! Will let Daniel and Nikhil make the final call.
Your suggested API changes (returning float type instance mask and moving binary thresholding to `toMaskImageData` function) makes sense. 
In terms of the inconsistency between instance mask and body part masks after this change, we could  leave it as is or return each body part mask as a separate instance mask (array of 24 masks with float type).

**Comment by rthadur** [comment]
Will be closing this issue as `bodypix` is is deprecated , please check out this demo https://github.com/tensorflow/tfjs-models/tree/master/pose-detection here , thank you
