### ISSUE TITLE
The path to load from must be a file. Loading from a directory is not supported.

### ISSUE THREAD

**Issue by neilljordan** [tensorflow/tfjs#937]
To get help from the community, check out our [Google group](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs).

#### TensorFlow.js version

@tensorflow/tfjs: 0.13.5
@tensorflow/tfjs-node-gpu: ^0.1.21

#### Browser version

node v8.11.1

#### Describe the problem or feature request

I'm unable to load a model just saved to the file system. It seems to save successfully, but I receive the following error when I call _loadModel_:

> Error: The path to load from must be a file. Loading from a directory is not supported.
 
Am I doing something wrong or it this not yet supported?

#### Code to reproduce the bug / link to feature request

```js
  const tf = require('@tensorflow/tfjs')
  require('@tensorflow/tfjs-node-gpu')

  let model = tf.sequential();

  const fileurl = 'file://./test.model'
  
  await model.save(fileurl)

  // # ls ./test.model
  // model.json  weights.bin

  try {
    model = await tf.loadModel(fileurl)
  } catch (error) {
    // (node:62270) UnhandledPromiseRejectionWarning: Error: The path to load from must be a file. 
    // Loading from a directory is not supported.
    console.log(error)    
  }
```

**Comment by neilljordan** [comment]
I tried that before, but since that gives me another error, I figured I'd ask for help. The error when I point it directly to the model.json is:

> TypeError: Cannot read property 'className' of undefined
>    at Sequential.fromConfig (node_modules/@tensorflow/tfjs-layers/dist/models.js:404:29)
>    at Object.deserializeKerasObject (node_modules/@tensorflow/tfjs-layers/dist/utils/generic_utils.js:174:29)

It seems like it's saving in one format and then trying to load in another, but the examples in the API docs don't demonstrate specifying a format when saving/loading. Any suggestions?

**Comment by adwellj** [comment]
I believe it's because the model doesn't have any layers.

I was able to reproduce your error, but then resolved it by adding a layer (and specifying "model.json" during load).

<pre><code class="hljs js">model.add(tf.layers.conv2d({
  <span class="hljs-attr">inputShape</span>: [<span class="hljs-number">28</span>, <span class="hljs-number">28</span>, <span class="hljs-number">1</span>],
  <span class="hljs-attr">kernelSize</span>: <span class="hljs-number">5</span>,
  <span class="hljs-attr">filters</span>: <span class="hljs-number">8</span>,
  <span class="hljs-attr">strides</span>: <span class="hljs-number">1</span>,
  <span class="hljs-attr">activation</span>: <span class="hljs-string">'relu'</span>,
  <span class="hljs-attr">kernelInitializer</span>: <span class="hljs-string">'VarianceScaling'</span>
}));</code></pre>

**Comment by neilljordan** [comment]
Yep, that was it. Thanks for the help @adwellj !
