### ISSUE TITLE
support dtype int64 in the savedmodel python converter

### ISSUE THREAD

**Issue by pyu10055** [tensorflow/tfjs#970]
To get help from the community, check out our [Google group](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs).

#### TensorFlow.js version
0.14.0
#### Describe the problem or feature request
When supporting https://tfhub.dev/google/universal-sentence-encoder-lite/2, there are constants of type int64, currently write_weight method will error out by saying 'int64 are not supported'

**Comment by ToonTalk** [comment]
We have a project that would strongly prefer to use the sentence encoder in TFJS and so we would love an estimate as to when this (and any other problem) is likely to be resolved. Since our project must be web-based the alternative we hope to avoid is needing a server to run the sentence encoding model.

**Comment by rthadur** [comment]
related changes have been merged , closing this issue.
