### ISSUE TITLE
register className for logSoftmax

### ISSUE THREAD

**Issue by rumschuettel** [tensorflow/tfjs#998]
Hi,

`tf.logSoftmax` is now supported in 14.1, but I cannot do the following:
```
const classifier = tf.layers.dense({
                trainable: false,
                name: "classifier",
                units: num_labels,
                activation: "logSoftmax"
            });
```

I can use a separate layer explicitly I assume, but then why support giving the activation function in first place - so I guess this is just an omission? It'd be great if it could be added for the recently-included activation functions.

Merci!
 - J

**Comment by Derek-Wds** [comment]
Hi, @caisq. First time to the community and I would like to help with this feature. Since tfjs-core has already included a logSoftmax function in it, I registered it in the activation.ts. [Here](https://github.com/Derek-Wds/tfjs-layers/blob/master/src/activations.ts) is the code. I wonder if you could help to review it and gives me some comment.

Thanks,
Derek

**Comment by rthadur** [comment]
Thank you @Derek-Wds , closing this issue as the PR is merged.
